### ISSUE TITLE
Add an additional parameter to the make command to build a specific DPI version

### ISSUE THREAD

**Issue by DJAlik** [opengapps/opengapps#100]
Not really an issue but an enhancement request

To further reduce the size of the opengapps package is it possible to add a parameter to the make command to build a specific dpi version? for example make arm-22-stock-320. If a specific dpi is not available for the package the logic would include the next best match up or down (not sure how it's done now). Thoughts?

**Comment by mfonville** [comment]
I will look into this, since this is also a partial requirement for #64 and can help with #97

**Comment by mfonville** [comment]
I thought about this. We need to also be able to specify two kinds of behaviour:
*Bundle last version of that specific DPI, even if newer versions of other DPI are available
*Bundle last version, preferably of the given DPI, but otherwise fallback to other.

**Comment by MatthewBooth** [comment]
I was just coming to add a issue/request for this very thing. It would help me immensely to bring down the zip size.

**Comment by mfonville** [comment]
@MatthewBooth 
Actually it would barely reduce the zip file nowadays, because with the strong XZ compression each extra APK of an already bundled app is relatively small. But we will implement it nonetheless, I just need a bit more time to implement it :)

**Comment by MatthewBooth** [comment]
I'm including it in my ROM zip (the whole installer, untouched by me, credits should be intact) so every little helps :P

**Comment by MatthewBooth** [comment]
Did this get any further towards being used?

I also realised that the zip will flash quicker if we are not using the multiple DPI's, or at least so I assume

**Comment by mfonville** [comment]
@MatthewBooth it is still on my agenda.
Honestly it is one of the lowest priorities at the moment. Also it is dependend on some other issues I need to resolve first, because it would touch the same code.

**Comment by mfonville** [comment]
This issues is now been covered in the aosp_build project that is better suited for these use cases. (DPI-specific builds that integrate directly with the ROM). Benefits for the regular packages would not have any real beneficial effects in combination with our current compression.
