### ISSUE TITLE
.odex remains after a Universal Application Removals

### ISSUE THREAD

**Issue by Tobyskernel** [opengapps/opengapps#101]
.odex remains after a Universal Application Removals. Is there any possibility to get .odex removed as well?

**Comment by mfonville** [comment]
I will look into it when back from holiday.
Could you attach the debug log, then I can see the paths of the odex files.

**Comment by mfonville** [comment]
@Tobyskernel could you please still add the debug logs or some file paths of the odex files?

**Comment by mfonville** [comment]
Note to ourselves: the universal remover removes .odex files, if .apk is present.
The normal/default removal scripts still don't remove any .odex. We could implement that when rewriting the generation of install.data
