### ISSUE TITLE
New GMS variant: -200

### ISSUE THREAD

**Issue by bgiesing** [opengapps/opengapps#102]
http://www.apkmirror.com/apk/google-inc/google-play-services/google-play-services-8-1-02-2204618-238-android-apk-download/

Need to add support?

**Comment by bgiesing** [comment]
@mfonville

**Comment by bgiesing** [comment]
@mfonville Looks like -2XX replaces -4XX for Lollipop and Marshmallow now uses -4XX

**Comment by mfonville** [comment]
This goes automatically ok for us, since we don't process those numbers in the versioncode anymore, we look at sdk level that it supports, cpu architecture and DPI specification, with those 3 factors APKs are already sorted correctly.
