### ISSUE TITLE
Allow ForceDPI to set 'universal' DPI

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#103]
We currently already allow one to set the ForceDPI keyword to force a certain DPI setting, but it does not allow (explicitly) setting the universal DPI. It would be nice if we could allow for this.
I don't know yet what whould be the best way to handle this and what the best keyword variation would be, but problaby something like ForceDPInodpi since 'nodpi' is already the name used for the folder containing the universal version.

**Comment by rapperskull** [comment]
Yes, it's probably the correct way to handle it, plus we just have to change 2 lines to make it work, since the current code is probably ready.

**Comment by rapperskull** [comment]
Just re-thought about that: the code is not completely ready, it will fail if there's no *nodpi* package. In that case we can install the package with higher DPI.

**Comment by mfonville** [comment]
I assume you mean the 'highest' DPI, right?
So preference order would become: nodpi, then from high to low.

**Comment by rapperskull** [comment]
Yes "highest", sorry. Exactly, that would be the order.
