### ISSUE TITLE
Issue with leanback import for add_sourceapp.sh

### ISSUE THREAD

**Issue by NicholasBuse** [opengapps/opengapps#104]
I was trying to import APKMirror's [PlayGames](http://www.apkmirror.com/apk/google-inc/google-play-games/google-play-games-3-2-21-2197783-846-arm64-android-apk-download/) and add_sourceapp.sh does not recognize it as leanback and tries to upgraded the "old" API of 9 to 21.

**Comment by mfonville** [comment]
I tried it here and it detects it correctly. Are you sure the APK you downloaded is not damaged and that your script is up to date?

**Comment by mfonville** [comment]
For some reason your aapt dump line includes 'name=' that is not in my version.
I think I will rewrite the line to be less dependent on the specific output

**Comment by NicholasBuse** [comment]
which version of aapt are you using?

**Comment by mfonville** [comment]
Mine is from the Ubuntu vivid repositories, ```aapt v``` gives: Android Asset Packaging Tool, v0.2

**Comment by mfonville** [comment]
Fixed it. Please test though :-P

**Comment by NicholasBuse** [comment]
I reverted the PlayGames apk in question and the updated add_sourceapp.sh imported it as expected in my setup
