### ISSUE TITLE
Java signing errors on 9/3 build

### ISSUE THREAD

**Issue by DJAlik** [opengapps/opengapps#105]
This is new....

Packaging and signing /home/djalik/opengapps/out/open_gapps-arm-5.1-stock-20150903.zip...
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at java.util.zip.ZipOutputStream.write(ZipOutputStream.java:339)
	at orig.SignApk.copyFiles(SignApk.java:455)
	at orig.SignApk.main(SignApk.java:504)
ERROR: Creating Flashable ZIP-file failed, unsigned file can be found at /home/djalik/opengapps/build/arm/22/stock.zip

**Comment by DJAlik** [comment]
Here are my defaults:

djalik@djalik-VirtualBox:~/opengapps$ java -XX:+PrintFlagsFinal -version | grep Heap
Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
    uintx ErgoHeapSizeLimit                         = 0                                   {product}
    uintx G1HeapRegionSize                          = 0                                   {product}
    uintx G1HeapWastePercent                        = 5                                   {product}
    uintx GCHeapFreeLimit                           = 2                                   {product}
    uintx HeapBaseMinAddress                        = 2147483648                          {pd product}
     bool HeapDumpAfterFullGC                       = false                               {manageable}
     bool HeapDumpBeforeFullGC                      = false                               {manageable}
     bool HeapDumpOnOutOfMemoryError                = false                               {manageable}
    ccstr HeapDumpPath                              =                                     {manageable}
    uintx HeapFirstMaximumCompactionCount           = 3                                   {product}
    uintx HeapMaximumCompactionInterval             = 20                                  {product}
    uintx HeapSizePerGCThread                       = 87241520                            {product}
    uintx InitialHeapSize                          := 132120576                           {product}
    uintx InitiatingHeapOccupancyPercent            = 45                                  {product}
    uintx LargePageHeapSizeThreshold                = 134217728                           {product}
    uintx MaxHeapFreeRatio                          = 100                                 {manageable}
    uintx MaxHeapSize                              := 2095054848                          {product}
    uintx MinHeapDeltaBytes                        := 524288                              {product}
    uintx MinHeapFreeRatio                          = 0                                   {manageable}
     bool PrintHeapAtGC                             = false                               {product rw}
     bool PrintHeapAtGCExtended                     = false                               {product rw}
     bool PrintHeapAtSIGBREAK                       = true                                {product}
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

**Comment by mfonville** [comment]
The package singing in Java needs a lot of memory. Make sure you have enough RAM and/or swap and pass otherwise even more memory to java in the inc.packagetarget.sh

Unfortunately we cannot fix it, our best bet is to get the signing using our own shellscript correctly working, but that still needs some more debugging and work.

**Comment by DJAlik** [comment]
Why all of a sudden though. Is the package getting too big... Another point to address #100

**Comment by mfonville** [comment]
A bigger package makes the problem indeed worse, but maybe you had (at that given time) also less RAM available/free on your computer than normal? The script currently asks for 2GiB of RAM for java to sign, which is enough for the java 1.7 and 1.8 that I use on 64 bit Ubuntu to build the packages.

**Comment by DJAlik** [comment]
I just upped my RAM for the VM from 8gigs to 12gigs and I am getting the exact same results.  Anything else you can suggest?

**Comment by mfonville** [comment]
In inc.packagetarget.sh line 110 you;ll find the java command that also passes the amount of RAM that can be used, currently it is 2048m, try increasing that number and see if it resolves your issue.
If it does not work, I am afraid you'd be out of options...

**Comment by DJAlik** [comment]
Why is nobody else having this issue? What settings are @opengapps/packagers
<https://github.com/orgs/opengapps/teams/packagers> using? I am running an
ubuntu 15.03 with 12gigs of ram in VM mode. Java 8u60

On Thu, Sep 3, 2015 at 11:56 AM, mfonville <notifications@github.com> wrote:

> In inc.packagetarget.sh line 110 you;ll find the java command that also
> passes the amount of RAM that can be used, currently it is 2048m, try
> increasing that number and see if it resolves your issue.
> If it does not work, I am afraid you'd be out of options...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opengapps/opengapps/issues/105#issuecomment-137510865>
> .
>



-- 
<http://www.facebook.com/djalik>  <http://twitter.com/#!/DJAlik>
<http://www.linkedin.com/in/alexrusinov>
<http://plus.google.com/114580313768137070684>
<http://www.mixcloud.com/djalik/>
<http://psnprofiles.com/DJAlik>

**Comment by NicholasBuse** [comment]
VBox, (headless) Ubuntu 14.04, 1G Ram. Java: java-7-openjdk-amd64.

**Comment by DJAlik** [comment]
Then it doesn't make sense at all why all of a sudden I started getting
this error.

On Thu, Sep 3, 2015 at 12:26 PM, Nicholas Buse <notifications@github.com>
wrote:

> VBox, (headless) Ubuntu 14.04, 1G Ram. Java: java-7-openjdk-amd64.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opengapps/opengapps/issues/105#issuecomment-137520386>
> .
>



-- 
<http://www.facebook.com/djalik>  <http://twitter.com/#!/DJAlik>
<http://www.linkedin.com/in/alexrusinov>
<http://plus.google.com/114580313768137070684>
<http://www.mixcloud.com/djalik/>
<http://psnprofiles.com/DJAlik>

**Comment by mfonville** [comment]
You could try running the java command manually on the commandline, and keep an eye on the process manager to see how much RAM is being consumed the java process.

**Comment by DJAlik** [comment]
I updated In inc.packagetarget.sh line 110 to 4096 and everything worked
perfectly. Should we change this globally?

On Thu, Sep 3, 2015 at 12:36 PM, Alex Rusinov <djalik@gmail.com> wrote:

> Then it doesn't make sense at all why all of a sudden I started getting
> this error.
>
> On Thu, Sep 3, 2015 at 12:26 PM, Nicholas Buse <notifications@github.com>
> wrote:
>
>> VBox, (headless) Ubuntu 14.04, 1G Ram. Java: java-7-openjdk-amd64.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/opengapps/opengapps/issues/105#issuecomment-137520386>
>> .
>>
>
>
>
> --
> <http://www.facebook.com/djalik>  <http://twitter.com/#!/DJAlik>
> <http://www.linkedin.com/in/alexrusinov>
> <http://plus.google.com/114580313768137070684>
> <http://www.mixcloud.com/djalik/>
> <http://psnprofiles.com/DJAlik>
>



-- 
<http://www.facebook.com/djalik>  <http://twitter.com/#!/DJAlik>
<http://www.linkedin.com/in/alexrusinov>
<http://plus.google.com/114580313768137070684>
<http://www.mixcloud.com/djalik/>
<http://psnprofiles.com/DJAlik>

**Comment by mfonville** [comment]
We can't because the buildbot does not have that much RAM/swap.
Also it is still weird that you have the issue at all, while the largest package is around 550MiB, so I would expect that 1650MiB heap memory should be enough. Very probably there is a memory leak in Java.
Anyhow, if for more people this issue arises we do have to change it until we fixed signapk.sh

**Comment by mfonville** [comment]
Building AROMA today failed, because of the same error:
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:2271)
        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:113)
        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:140)
        at java.util.zip.ZipOutputStream.write(ZipOutputStream.java:322)
        at orig.SignApk.copyFiles(SignApk.java:455)
        at orig.SignApk.main(SignApk.java:504)
ERROR: Creating Flashable ZIP-file failed, unsigned file can be found at /home/maarten/opengapps/build/arm/22/aroma.zip

So we *will* have to fix this.
