### ISSUE TITLE
android.database.sqlite.SQLiteException after upgrade

### ISSUE THREAD

**Issue by thorstent** [opengapps/opengapps#106]
I just upgraded the openapps from 20150803 to 20150904. I also upgraded Cyanogenmod to 20150901 on my Nexus 9. The OS boots, but I constantly get the error "Unfortunately,  Google Play services has stopped."

I see the following exception in logcat:
E/DatabaseUtils( 2308): Writing exception to parcel
E/DatabaseUtils( 2308): android.database.sqlite.SQLiteException: Can't downgrade database from version 65 to 64
E/DatabaseUtils( 2308):         at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:360)
E/DatabaseUtils( 2308):         at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:254)
E/DatabaseUtils( 2308):         at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
E/DatabaseUtils( 2308):         at com.android.providers.telephony.SmsProvider.query(SmsProvider.java:276)
E/DatabaseUtils( 2308):         at android.content.ContentProvider.query(ContentProvider.java:1000)
E/DatabaseUtils( 2308):         at android.content.ContentProvider$Transport.query(ContentProvider.java:214)
E/DatabaseUtils( 2308):         at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
E/DatabaseUtils( 2308):         at android.os.Binder.execTransact(Binder.java:446)
E/AndroidRuntime( 5748): FATAL EXCEPTION: Proxy Executor
E/AndroidRuntime( 5748): Process: com.google.android.gms, PID: 5748
E/AndroidRuntime( 5748): android.database.sqlite.SQLiteException: Can't downgrade database from version 65 to 64
E/AndroidRuntime( 5748):        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:181)
E/AndroidRuntime( 5748):        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
E/AndroidRuntime( 5748):        at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
E/AndroidRuntime( 5748):        at android.content.ContentResolver.query(ContentResolver.java:478)
E/AndroidRuntime( 5748):        at android.content.ContentResolver.query(ContentResolver.java:422)
E/AndroidRuntime( 5748):        at com.google.android.gms.icing.proxy.o.a(SourceFile:384)
E/AndroidRuntime( 5748):        at com.google.android.gms.icing.proxy.o.a(SourceFile:49)
E/AndroidRuntime( 5748):        at com.google.android.gms.icing.proxy.p.run(SourceFile:177)
E/AndroidRuntime( 5748):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 5748):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 5748):        at java.lang.Thread.run(Thread.java:818)

I delete all the /data directories that have anything to do with gms and rebooted. The error persists and in addition google play store does no longer work. I'm wondering if there is a fix other than wiping entire /data.

**Comment by mfonville** [comment]
Did you also try to 'clear data' from the settings->app->all screen?
Also I wonder, did you ever manually upgraded your GMS with a seperate APK e.g. from apkmirror?

As for a fix, if 'clear data' doesn't work I fear that wiping /data would be the only straightforward solution :-/

**Comment by mfonville** [comment]
@thorstent could you still please reply?

**Comment by thorstent** [comment]
Hi, I wiped /data and the issue disappeared.

**Comment by mfonville** [comment]
OK, I will close the bug than. I hope it was an incident, but if the future such a thing happens again we can maybe investigate further.

PS: Did you remember whether you ever installed a Google Play Services APK yourself, eg from apk mirror? It would help to know, since 'downgrading' of this service should never happen when upgrading to a newer package.

**Comment by thorstent** [comment]
The installation was in the following order: Cyanogenmod 12 and their gapps release -> Cyanogenmod 12.1 nightly and their gapps release (was buggy), therefore -> Cyanogenmod 12.1 nigthly and opengapps pico -> Cyanogenmod 12.1 snapshot and opengapps pico updated on that day -> above mentioned bug.

I never installed apks manually, but i did update any gapps offered by the Play Store.

**Comment by mfonville** [comment]
Ok, thank you for the detailed information :-)
