### ISSUE TITLE
Moving Streetview from Mini to Full?

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#107]
I spotted that TK GApps has moved Streetview from Mini to Full, because the app has become so much larger (before it was only a few KiBs, now it is MiBs).
I had not thought about that before, but it does make sense, from size-perspective. But moving it out of mini would mean that we are moving functionality out of an existing package, which might be unexpected for some users.

I'd like to get the opinion of @opengapps/general whether we should follow suit and move Streetview to Full, or to keep the existing situation.

**Comment by rapperskull** [comment]
I think that we should move Street View to Full, making sure that the users know the change. We can put a message on opengapps.org when the Mini package is selected to download, and obviously post in the XDA thread about the change.

An important question: does the latest version of Google Maps work without the Street View app installed?

**Comment by mfonville** [comment]
Yes, Maps works without Streetview.

**Comment by bgiesing** [comment]
The new Street View app is a "social network" for Photospheres, not needed for Google Maps. I think it should be moved to Full. @mfonville @rapperskull

**Comment by mfonville** [comment]
OK, I moved it. One important thing to notice btw, is that for streetview we only have the updated package for 'arm' at the moment. So we need the 'x86' of that one soon, so that we can remove the old package from 'all'.

**Comment by mc1100** [comment]
Unfortunately, my x86_64 tablet died and I do not have ID for the APK
downloader. :(

2015-09-07 10:09 GMT+02:00 mfonville <notifications@github.com>:

**Comment by mfonville** [comment]
I approached @deadman96385 about the x86 GApps, since he currently maintains his own Deadman's/Zenfone x86 GApps, but did not get any response of him the last days. So I guess he's very busy. We could really benefit from a x86 maintainer/developer, because x86 is presence is growing, but the availability of public APKs on e.g. apkmirror is really low.

**Comment by deadman96385** [comment]
Yeah i got busy, i plan on working on it now, going through each package to make sure it all works as we speak. (A month ago they didn't)
