### ISSUE TITLE
[Aroma] Back button reloads selections file

### ISSUE THREAD

**Issue by MarkJeronimus** [opengapps/opengapps#109]
When you load an existing selection file at the beginning of the walk through the options, change stuff, then at some point (be it at the review page, and you want to go back and make a little change), at the press of the back button it reloads the selections file and every change is gone.

With Aroma 5.1 20150913

**Comment by mfonville** [comment]
@raulx222 Do you think we would be able to fix/improve on this?

**Comment by raulx222** [comment]
This can be fixed. Since is not a major bug I will fix it after I get a new device.
