### ISSUE TITLE
Trying to exit freezes

### ISSUE THREAD

**Issue by MarkJeronimus** [opengapps/opengapps#110]
When I try to exit early, whether via the circle button at the bottom or with the exit option on the first screen, my Nexus 5 freezes so hard I have to 'pull the battery' (10 seconds power button press).

Exiting at the end of the installation procedure works fine.

With Aroma 5.1 20150913
If it matters, I'm using TWRP 2.8.7.1.

**Comment by mfonville** [comment]
@raulx222 is this a libAroma issue?

**Comment by raulx222** [comment]
I think this is a AROMA Installer bug and I can't do anything about it.

**Comment by mfonville** [comment]
We will have to wait for the new libaroma unfortunately. We can't fix it, so I close the issue.
