### ISSUE TITLE
Tar gives problems on (old) Philz recovery

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#111]
Somebody tried to flash the package, and even though it succesfully did pass our tar-detection mechanism, it still gave errors.

Output appeared like:
```
Non used options while in non create mode!
Usage: tar [OPTION...] [FILE]...
Examples:
   tar -cf archive.tar foo bar  # Create archive.tar from files foo and bar.
   tar -tvf archive.tar         # List all files in archive.tar verbosely.
   tar -xf archive.tar          # Extract all files from archive.tar.

Main operation mode:
   -c, --create     create a new archive
   -x, --extract    extract files from an archive
   -t, --list       list the contents of an archive

Valid Options:
   -V, --version
   -C, --directory
   -v, --verbose
   -H, --format [ustar][gnu](default)
   -T, --files-from
   -f, --file
   -z, --gzip
   -p, --preserve-permissions (include selinux context)
   -X, --exclude
   -n, --numeric-owner
```

I think that the problem is that TAR is not able to understand/process the hyphen '-' as file input selector, OR that it does not understand the extra argument we pass as filepath that has to be extracted.

Relevant XDA post: http://forum.xda-developers.com/android/software/pa-gapps-continuation-t3098071/post62866927#post62866927

**Comment by mfonville** [comment]
Thank you for fixing this @rapperskull (and that you found the time to do so :-) )

**Comment by rapperskull** [comment]
This is just a check and not a real fix. We could include a new binary, like we do with the xz one to support older recoveries.

**Comment by mfonville** [comment]
Nah, all major recoveries available do have support for it. Upgrading recoveries should be enough to resolve it, even on CWM/PhilZ.

Also PhilZ did apparently also stop all development, so over (a long) time TWRP and CM-Recovery will be the only ones around that we'll have to deal with. Thus maybe we should ask the CM-Recovery guys to also include the XZ decompression filter.
