### ISSUE TITLE
Aroma

### ISSUE THREAD

**Issue by nick37332001** [opengapps/opengapps#115]
Aroma package freezes while flashing on TWRP 2.8.6.1

**Comment by mfonville** [comment]
@raulx222 Can you help out?
@nick37332001 I think you'll have to attach more information about your device.

**Comment by nick37332001** [comment]
@mfonville I use a msm8916 device [Xiaomi Redmi 2] running cyanogenmod 12.1

**Comment by raulx222** [comment]
@nick37332001 If it's available and older TWRP version for your device you can try it, it might work on other TWRP versions. AROMA Installer is old and we are all waiting for the next update but amarullz didn't announced any ETA.
I'm sorry for any problems related to the AROMA variant of Open GApps, but we can't do anything about it until amarullz will release a new update.
