### ISSUE TITLE
Online upload service

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#117]
We should try to make a drag-drop possibility for packagers to upload new APKs to a private website.
The server then processes the certificate checks, adding and upload to GitHub. At first still with some manual intervention/checks to prevent possible errors.

This will allow more contributions from packagers not running their own Linux installations.

It will also be useful for the future, when we want more automatic collection of recent APKs.

**Comment by mfonville** [comment]
Idea: use GitHub auth to control access to the site. And maybe even use that too to commit with proper credentials (if possible).

**Comment by osm0sis** [comment]
Presumably abandoned, since GitHub isn't super cooperative anymore and reinventing APKMirror sounds labor intensive. 🙂
