### ISSUE TITLE
Libhoudini support for x86

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#118]
Libhoudini is available in practically every x86 ROM, allowing arm apps to run on x86 too.
Proposal is to specify 'arm' as fallback architecture for 'x86'

Best would be to rewrite the fallback architecture mechanism to use a recursion mechanism, so that it only would have to know its next fallback architecture.
x86_64 -> x86
x86 -> arm
arm64 -> arm
arm -> all

We do have to take into account that this only works for applications and their libs, and not for systemwide libs, that can only stay within their own architecture and 32 bit equivalents for 64 bit archs (with lib64 and lib).

**Comment by deadman96385** [comment]
I will have a build that tests this later today!

**Comment by deadman96385** [comment]
I can confirm including the missing apps that do not have x86 as arm works used these 2 commits.  To do exactly what this issue says will need some changes on top of what i did

https://github.com/deadman96385/opengapps/commit/cc6490a42a74d48e9a433fab8cbcd1f167eb7c1f
https://github.com/deadman96385/opengapps/commit/c90ef388b44f0d78bf95c072338bbaeae3aceeac

**Comment by mfonville** [comment]
@deadman96385 Could you please check out whether the branch https://github.com/opengapps/opengapps/tree/fallbackarch works good for you?

Also @opengapps/general does anyone have an arm64 device that they could test this branch on?
If it works, I will push it to master and update the wiki accordingly.

**Comment by mfonville** [comment]
I would really like to merge this, before we are going to work on the "super" package and merging my "tv/leanback" branch, so please still test if possible, otherwise I will just merge at some point :-/

**Comment by rapperskull** [comment]
I would like to help, but I don't have any other device beside my Nexus 5.
Maybe we can put an announcement on opengapps.org to find arm64 and x86 volunteers.

**Comment by mfonville** [comment]
@mc1100 did test the arm64 version, and all was right. And of @deadman96385 I know that his temporary hack worked, so I will now just merge it.
