### ISSUE TITLE
Reconsider some of the automatic deleted apps list

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#121]
This article got my attention: http://en.miui.com/thread-167227-1-1.html

And I was wondering if we maybe can drop those 2 lines from the default removal list, or are they still in known conflict with existing GApps?

@opengapps/general does anybody have experience with the apps thare by default installed in those folders?

**Comment by rapperskull** [comment]
Well, /system/app/QuickSearchBox is an old location for the Google Search app.
I'm not sure about /system/app/BrowserProviderProxy, but it's probably another old location.

**Comment by mfonville** [comment]
But is /system/app/QuickSearchBox still used on any ROM? E.g. do 4.4 ROMs still use this location, or do they not (anymore)?

**Comment by mfonville** [comment]
BrowserProviderProxy's aapt details:

package: name='com.android.browser.provider' versionCode='21' versionName='5.0.1-1602158'
sdkVersion:'21'
targetSdkVersion:'21'
uses-permission:'com.android.browser.permission.READ_HISTORY_BOOKMARKS'
uses-permission:'com.android.browser.permission.WRITE_HISTORY_BOOKMARKS'
application: label='' icon=''
uses-feature:'android.hardware.touchscreen'
uses-implied-feature:'android.hardware.touchscreen','assumed you require a touch screen unless explicitly made optional'
other-activities
supports-screens: 'small' 'normal' 'large' 'xlarge'
supports-any-density: 'true'
locales: '--_--' 'en_XA' 'ar_XB'
densities: '160' '240' '320'

**Comment by mfonville** [comment]
I downloaded all recent Miui ROMs, but in none of them I could find the /system/app/QuickSearchBox so I think they alread dropped that one.

But about the BrowserProviderProxy, should we maybe make it part of the browser_list removal?

**Comment by rapperskull** [comment]
Some Googling revealed that BrowserProviderProxy is part of the AOSP browser and I have no idea why we always remove it. Does the AOSP browser work without it too?

**Comment by mfonville** [comment]
Apparently. But then you agree with putting it in browser_list removal?

**Comment by rapperskull** [comment]
Unless there's a proven incompatibility, I think it's safe to move it to browser_list.
