### ISSUE TITLE
Google Cloud Messaging (GCM) not working?

### ISSUE THREAD

**Issue by r-arias** [opengapps/opengapps#122]
Hi, I was wondering which package (http://opengapps.org) I need to install to get GCM working on Android 5.1 on a Samsung Galaxy S4 LTE Intl. (I9505).
I installed the pico package today and seem to have problems with GCM. Messages in TextSecure and Whatsapp do not arrive for a long time, sometimes only once I open the app.

I was under the impression that GCM is included with Google Play Services, but I am not sure.

I would like to know whether I am simply using a wrong package or if there is a bug somewhere in the package, my ROM or anywhere else.

Thanks!

**Comment by mfonville** [comment]
GCM is indeed part of the Google Play Services, I believe.
I had no other report of the issues you are experiencing, neither do I experience them myself. Unless Google had some (temporary) issues I would expect that it is a problem with your ROM or your connection (maybe WiFi and mobile data get disabled?).

I am at least 100% certain it is not an issue within the GApps package itself, so I'll close this issue. (PS: such kind of problems/issues can also be posted on XDA Forum, you'll get probably a faster response).

**Comment by r-arias** [comment]
Thanks for the answer! That's what i thought.
