### ISSUE TITLE
Installation fails on Nexus 10 (manta)

### ISSUE THREAD

**Issue by oGkgN** [opengapps/opengapps#127]
Today I tried to install the opengapps after a fresh system upgrade of cyanogenmod 12.0 (http://download.cyanogenmod.org/get/jenkins/124088/cm-12-20150901-SNAPSHOT-YNG4NAO254-manta.zip). I choosed to install arm 5.0 nano 3 October 2015, and after failing also arm 5.0 pico 3 October 2015. I used ClockworkMod recovery to install zip from sdcard.
This is the error message I get:
-- Installing: /sdcard/open_gapps-arm-5.0-pico-20151003.zip
Finding update package...
Opening update package...
Verifying update package...
Installing update...
E:Error in /data/media/open_gapps-arm-5.0-pico-20151003.zip
(Status 6)
Installation aborted.

**Comment by mfonville** [comment]
Don't use (outdated) CWM, this issue is described in the FAQ: https://github.com/opengapps/opengapps/wiki/FAQ#3-im-getting-a-status-error-6-when-i-try-and-install-these-gapps-with-cwm-what-can-i-do-to-fix-it
