### ISSUE TITLE
Creation of a "super" package

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#132]
Since Google did drop some apps from the Nexus stock images, but we do have official names for them, and people installing and depending on them e.g. Google Earth, we can make a "super" package that contains these apps, and keep "stock" equal the latest offical Google stock experience.
We can also include the less used packages, like international keyboards, Google Fi, Android for Work etc in this package. And less/in-compatible apps, that people might want to experiment with, like Android Pay (see #116) and maybe even Google Dialer.
I did discuss this idea with @rapperskull and it seems at the moment more easy to implement such a big package than creating seperate add-ons, which would require much more changes to our code, build and website infrastructure.

- [x] Collect APKs of all apps we want to bundle in super
- [x] Update path and lib definitions for these APKs in inc.buildtarget.sh
- [x] Let gapps-remove.txt be generated based on this "super" pakage instead of "stock"
- [x] Update package set definitions in inc.buildtarget.sh
- [x] Update the website to allow downloading of this "super" package
- [x] Update the wiki for contents op both "super" and "stock"
- [x] Post on XDA what has changed and update OP and and the hotlinks
- [x] Possibility of a better name than "super" (any suggestions can be posted in the comments)

**Comment by rapperskull** [comment]
I just made a list of apps contained in the Nexus 6 factory image and filtered only the ones with the package name containing "google". We should now filter only the ones we don't already include and select the ones worth adding.

File path | Package name
--------- | ------------
/system/app/Books/Books.apk | com.google.android.apps.books
/system/app/CalculatorGoogle/CalculatorGoogle.apk | com.google.android.calculator
/system/app/CalendarGooglePrebuilt/CalendarGooglePrebuilt.apk | com.google.android.calendar
/system/app/CloudPrint2/CloudPrint2.apk | com.google.android.apps.cloudprint
/system/app/DMAgent/DMAgent.apk | com.google.android.apps.enterprise.dmagent
/system/app/Drive/Drive.apk | com.google.android.apps.docs
/system/app/EditorsDocs/EditorsDocs.apk | com.google.android.apps.docs.editors.docs
/system/app/EditorsSheets/EditorsSheets.apk | com.google.android.apps.docs.editors.sheets
/system/app/EditorsSlides/EditorsSlides.apk | com.google.android.apps.docs.editors.slides
/system/app/FitnessPrebuilt/FitnessPrebuilt.apk | com.google.android.apps.fitness
/system/app/GoogleCamera/GoogleCamera.apk | com.google.android.googlecamera
/system/app/GoogleContactsSyncAdapter/GoogleContactsSyncAdapter.apk | com.google.android.syncadapters.contacts
/system/app/GoogleEars/GoogleEars.apk | com.google.android.ears
/system/app/GoogleHindiIME/GoogleHindiIME.apk | com.google.android.apps.inputmethod.hindi
/system/app/GoogleHome/GoogleHome.apk | com.google.android.launcher
/system/app/GoogleJapaneseInput/GoogleJapaneseInput.apk | com.google.android.inputmethod.japanese
/system/app/GooglePinyinIME/GooglePinyinIME.apk | com.google.android.inputmethod.pinyin
/system/app/GoogleTTS/GoogleTTS.apk | com.google.android.tts
/system/app/Hangouts/Hangouts.apk | com.google.android.talk
/system/app/KoreanIME/KoreanIME.apk | com.google.android.inputmethod.korean
/system/app/LatinImeGoogle/LatinImeGoogle.apk | com.google.android.inputmethod.latin
/system/app/Maps/Maps.apk | com.google.android.apps.maps
/system/app/Music2/Music2.apk | com.google.android.music
/system/app/Newsstand/Newsstand.apk | com.google.android.apps.magazines
/system/app/Photos/Photos.apk | com.google.android.apps.photos
/system/app/PlayAutoInstallConfig/PlayAutoInstallConfig.apk | android.autoinstalls.config.google.nexus
/system/app/PlayGames/PlayGames.apk | com.google.android.play.games
/system/app/PlusOne/PlusOne.apk | com.google.android.apps.plus
/system/app/PrebuiltBugle/PrebuiltBugle.apk | com.google.android.apps.messaging
/system/app/PrebuiltDeskClockGoogle/PrebuiltDeskClockGoogle.apk | com.google.android.deskclock
/system/app/PrebuiltExchange3Google/PrebuiltExchange3Google.apk | com.google.android.gm.exchange
/system/app/PrebuiltGmail/PrebuiltGmail.apk | com.google.android.gm
/system/app/PrebuiltKeep/PrebuiltKeep.apk | com.google.android.keep
/system/app/PrebuiltNewsWeather/PrebuiltNewsWeather.apk | com.google.android.apps.genie.geniewidget
/system/app/ShamuLayout/ShamuLayout.apk | com.google.android.launcher.layouts.shamu
/system/app/talkback/talkback.apk | com.google.android.marvin.talkback
/system/app/Tycho/Tycho.apk | com.google.android.apps.tycho
/system/app/Videos/Videos.apk | com.google.android.videos
/system/app/Wallet/Wallet.apk | com.google.android.apps.walletnfcrel
/system/app/WebViewGoogle/WebViewGoogle.apk | com.google.android.webview
/system/app/YouTube/YouTube.apk | com.google.android.youtube
/system/priv-app/AndroidForWork/AndroidForWork.apk | com.google.android.androidforwork
/system/priv-app/ConfigUpdater/ConfigUpdater.apk | com.google.android.configupdater
/system/priv-app/GCS/GCS.apk | com.google.android.apps.gcs
/system/priv-app/GoogleBackupTransport/GoogleBackupTransport.apk | com.google.android.backuptransport
/system/priv-app/GoogleContacts/GoogleContacts.apk | com.google.android.contacts
/system/priv-app/GoogleDialer/GoogleDialer.apk | com.google.android.dialer
/system/priv-app/GoogleFeedback/GoogleFeedback.apk | com.google.android.feedback
/system/priv-app/GoogleLoginService/GoogleLoginService.apk | com.google.android.gsf.login
/system/priv-app/GoogleOneTimeInitializer/GoogleOneTimeInitializer.apk | com.google.android.onetimeinitializer
/system/priv-app/GooglePackageInstaller/GooglePackageInstaller.apk | com.google.android.packageinstaller
/system/priv-app/GooglePartnerSetup/GooglePartnerSetup.apk | com.google.android.partnersetup
/system/priv-app/GoogleServicesFramework/GoogleServicesFramework.apk | com.google.android.gsf
/system/priv-app/PrebuiltGmsCore/PrebuiltGmsCore.apk | com.google.android.gms
/system/priv-app/SetupWizard/SetupWizard.apk | com.google.android.setupwizard
/system/priv-app/TagGoogle/TagGoogle.apk | com.google.android.tag
/system/priv-app/Velvet/Velvet.apk | com.google.android.googlequicksearchbox

**Comment by mfonville** [comment]
imho to be added to the super apps (if they don't give issues):
File path | Package name
--------- | ------------
/system/app/DMAgent/DMAgent.apk | com.google.android.apps.enterprise.dmagent
/system/app/GoogleHindiIME/GoogleHindiIME.apk | com.google.android.apps.inputmethod.hindi
/system/app/GoogleJapaneseInput/GoogleJapaneseInput.apk | com.google.android.inputmethod.japanese
/system/app/GooglePinyinIME/GooglePinyinIME.apk | com.google.android.inputmethod.pinyin
/system/app/KoreanIME/KoreanIME.apk | com.google.android.inputmethod.korean
/system/priv-app/AndroidForWork/AndroidForWork.apk | com.google.android.androidforwork
/system/priv-app/GCS/GCS.apk | com.google.android.apps.gcs
/system/app/GoogleEarth | com.google.earth
/system/app/Street | com.google.android.street

imho to be added to the stock apps (if they don't give issues):
File path | Package name | Why/what
--------- | ------------ | ---
/system/app/CalculatorGoogle/CalculatorGoogle.apk | com.google.android.calculator
/system/priv-app/GoogleContacts/GoogleContacts.apk | com.google.android.contacts | replaces AOSP contacts
/system/priv-app/GoogleDialer/GoogleDialer.apk | com.google.android.dialer | replaces AOSP dialer (note: also needs framework and etc)
/system/priv-app/GooglePackageInstaller/GooglePackageInstaller.apk | com.google.android.packageinstaller | replaces AOSP packageinstaller

imho to be added to the core apps (if they don't give issues):
File path | Package name | Why/what
--------- | ------------ | ---
/system/priv-app/ConfigUpdater/ConfigUpdater.apk | com.google.android.configupdater | Updates certificates and shit

Apps that I don't know what they do and what we should do with them:
File path | Package name | Why/what
--------- | ------------ | ---
/system/app/PlayAutoInstallConfig/PlayAutoInstallConfig.apk | android.autoinstalls.config.google.nexus
/system/app/ShamuLayout/ShamuLayout.apk | com.google.android.launcher.layouts.shamu
/system/app/Tycho/Tycho.apk | com.google.android.apps.tycho

**Comment by rapperskull** [comment]
I completely agree on the "Super" list, while we should be cautious with the new "Stock" apps.
Google Contacs and Google Dialer gave many problems in the past, and that's why they're not included in standard GApps (also because they're not on the Play Store).
The same applies to Calculator and PackageInstaller, that are new in Marshmallow, since the 5.1 factory images ship with the AOSP ones. We have to check if it's safe to install them on Lollipop and KitKat (if they're not dependent on the API level).
ConfigUpdater is also new in Marshmallow.
The other three apps are probably device-specific:
I was not able to find anything about PlayAutoInstallConfig, but it's probably used to automatically install "Nexus stuff".
ShamuLayout simply sets the default position of the home screen apps on first start (I thought it was done by the Google (Search) App), as hinted by the source code: https://android.googlesource.com/device/moto/shamu/+/marshmallow-release/ShamuLayout
Tycho is simply the Project Fi app (not to be confused with GCS, that provides the background).

**Comment by mfonville** [comment]
I am btw thinking, maybe GoogleCalculator (if it works) should even go in 'mini' just like the deskclock and nfctag.

Google Contacts and Dialer will require indeed a lot of testing, to see if they are compatible with AOSP ROMs. And we should also research whether these two can only be installed together, or whether having just 1 installed works too.

Calculator requires SDK 23, so that one will only be for 6.0+ builds.

Google's packageinstaller already appeared on Android TV for 5.1 already. (there the codename is com.google.android.pano.packageinstaller ).

Based on your info, I think we should NOT bundle ShamuLayout.

Tycho should be in the "super" package if it is part of Project Fi.

**Comment by rapperskull** [comment]
I also made a table with the minimum SDK required, but it's not very accurate, since many packages were found in previous factory images too.

Name | Package name | MinSDK
---- | ------------ | ------
Calculator | com.google.android.calculator | 23
Device Policy | com.google.android.apps.enterprise.dmagent | 1
Google Hindi Input | com.google.android.apps.inputmethod.hindi | 14
Google Japanese Input | com.google.android.inputmethod.japanese | 14
Google Pinyin Input | com.google.android.inputmethod.pinyin | 14
Google Korean Input | com.google.android.inputmethod.korean | 14
Device configuration | android.autoinstalls.config.google.nexus | 21
Nexus 6 Home Screen | com.google.android.launcher.layouts.shamu | 23
Project Fi | com.google.android.apps.tycho | 22
Android Work Assistant | com.google.android.androidforwork | 23
ConfigUpdater | com.google.android.configupdater | 23
Google Connectivity Services | com.google.android.apps.gcs | 22
Contacts | com.google.android.contacts | 23
Phone | com.google.android.dialer | 23
Package installer | com.google.android.packageinstaller | 23

**Comment by mfonville** [comment]
I propose to make the "super" package only 5.1+ since 4.4. is for sure incompatible with some of the extra stuff and usage is dropping, and 5.0 is already a small user base and will shrink probably very quickly coming months.
Also I would only do Contacts+Phone on 6.0+, since we *know* of the issues on Lollipop, and only with 6.0 they introduced their own contacts app.
Calculator, Packageinstaller & Configupdater are not available for <6.0 (with exception of android TV), so those also become 6.0+ only.
So, as far as I can see, we should only get Android Work Assistant from a 5.1 image.

**Comment by rapperskull** [comment]
It does make sense to have a 5.1+ only "super" package if it doesn't create problems with aroma being based on it, since the other keyboards are available starting from API 14.
As for as the Google Contacts app, I have it on my 5.1.1 Nexus 5, so it's not new in 6.0. We're also not sure that Phone and Contacts will work on 6.0 AOSP ROMs and we need testers.

**Comment by mfonville** [comment]
We can make the aroma config generation more dynamic per android version. That is no problem.

I thought that the folder of the contacts app was new compared to the nexus 5? Or was that also the same? Anyhow, we will need indeed testers for 6.0 GApps, especially for that Contacts+Phone, but I am sure we can find those on XDA. Let's just assume for now that they would work on 6.0. We can always choose to exclude them later on.

I'll have other obligations this evening, so I cannot start working on the code, but if you feel like coding, you can start a branch and then I'll later join in :-)

**Comment by rapperskull** [comment]
I've already coded a large portion of the new logic, and I'm going to commit later.
I found out that ConfigUpdater has been included since Android 4.2, so I added it to the Core base.

**Comment by mfonville** [comment]
I did now create 'superpackage' branches for the source repos that contain the new APKs that we do need to build the new packages.

**Comment by bgiesing** [comment]
@mfonville Just to add to the super list, we should have Inbox as I know a lot of people would love to have that in system replacing Gmail.

**Comment by mfonville** [comment]
@bgiesing We will start conservative and start with the apps that we have "official" paths for, as they are on Nexus devices. Other popular apps can be added later, but we should make some ground rules for which&how, to maintain consistency.

**Comment by mfonville** [comment]
We now have to wait for @raulx222 to update the Aroma config.
And I have to wait 1 day for the packages to be built, and then I can update the OP.

**Comment by bgiesing** [comment]
@mfonville I was one of the first people to make an AROMA GApps, maybe I can help? I just need to add the new apps and their keywords, right?

**Comment by mfonville** [comment]
@bgiesing It seems @raulx222 more busy than expected, so if you could pick this up that would be very nice. Indeed just adding the new apps and their keywords, and if necessary move/update the indication of what is included in Stock and Full.

**Comment by bgiesing** [comment]
@mfonville Sorry for the delay, I updated it and cleaned some things up in PR #145

**Comment by mfonville** [comment]
@bgiesing Thanks!
OP also updated, so this is fixed/done.
