### ISSUE TITLE
Stock WebViewGoogle is always removed

### ISSUE THREAD

**Issue by Asvel** [opengapps/opengapps#134]
[Line 711-715 in inc.updatebinary.sh](https://github.com/opengapps/opengapps/blob/a2928a0687323daaa0d6d216789004d33aeff57c/scripts/inc.updatebinary.sh#L711) will always remove WebViewGoogle, even if the installed package doesn't include WebViewGoogle.
And, that stock WebViewGoogle maybe the only WebView, so there won't be any WebView in system after installing.

**Comment by rapperskull** [comment]
I don't see anything at lines 711-715. Is it a mistake or you indicated the wrong lines?

**Comment by Asvel** [comment]
Sorry, it's merely a log. The real lines are:
```sh
Line   36: gapps_removal_list=/tmp/gapps-remove.txt;
Line  968: full_removal_list="$(cat $gapps_removal_list)"$'\n'"${obsolete_libs_list}";
Line   79: complete_gapps_list() {cat << EOF $full_removal_list EOF }
Line 1138: rm -rf $(complete_gapps_list);
```

**Comment by rapperskull** [comment]
WebViewGoogle is treated like any other package, that is removed if it's not going to be installed.
Maybe a good compromise is not include it in the removal list of packages that does not contain it.
In this way users of the stock+ packages will not experience changes to the behavior.
I already developed a change, and it's scheduled to go live alongside the new "super" package, that will bring BTW other packages changes.

**Comment by mfonville** [comment]
I am fixing this in a different manner on the device-scripting side in issue #166
Because users using aroma or one of the stock+ packages don't expect their ROM's Google webview to be removed if it is not selected.
Neither do we want ROMs to become in a state where both the AOSP and the Google Webview are removed.
