### ISSUE TITLE
Not possible to flash on Genymotion, just copies to /sdcard/Download instead.

### ISSUE THREAD

**Issue by zeorin** [opengapps/opengapps#135]
When I try to flash any of the x86 Gapps packages to a Genymotion AVD, the zip file is copied only, instead of copied and flashed.

Genymotion tries to ascertain whether a dragged & dropped zip file is a flashable archive by running a script: `check-archive.sh`. If it looks like a flashable archive, it'll run ask if you want to flash it and run `flash-archive.sh`.

When I run these commands from the command line, I have the following results:

```
$ adb shell check-archive.sh /sdcard/Download/open_gapps-x86-5.1-pico-20151008.zip 
uid=0(root) gid=0(root) groups=1003(graphics),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats)
File to check: /sdcard/Download/open_gapps-x86-5.1-pico-20151008.zip
/sdcard/Download: content of directory:
total 116584
-rw-rw---- root     sdcard_r 75205930 2015-10-09 10:05 gapps-5.1-2015-04-20-15-56-24.zip
-rw-rw---- root     sdcard_r 44173728 2015-10-09 07:50 open_gapps-x86-5.1-pico-20151008.zip
/sdcard/Download/open_gapps-x86-5.1-pico-20151008.zip: this file seems to be a zip archive
[check-archive.sh] system/ NOT found in /sdcard/Download/open_gapps-x86-5.1-pico-20151008.zip; return 1
{Result:KO};
```

```
$ adb shell flash-archive.sh /sdcard/Download/open_gapps-x86-5.1-pico-20151008.zip
uid=0(root) gid=0(root) groups=1003(graphics),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats)
/sdcard/Download/open_gapps-x86-5.1-pico-20151008.zip seems to be a zip archive
[flash_archive] Creating tmp dir
rm: /data/local/tmp/flash-tmp-dir: No such file or directory
[flash_archive] Unzip archive
Archive:  /sdcard/Download/open_gapps-x86-5.1-pico-20151008.zip
  inflating: Core/framework.tar.xz
  inflating: Core/gmscore.tar.xz
  inflating: Core/googlebackuptransport.tar.xz
  inflating: Core/googlecontactssync.tar.xz
  inflating: Core/googlefeedback.tar.xz
  inflating: Core/googleonetimeinitializer.tar.xz
  inflating: Core/googlepartnersetup.tar.xz
  inflating: Core/gsfcore.tar.xz
  inflating: Core/gsflogin.tar.xz
  inflating: Core/setupwizard.tar.xz
  inflating: Core/vending.tar.xz
  inflating: GApps/calsync.tar.xz
  inflating: META-INF/com/google/android/update-binary
  inflating: META-INF/com/google/android/updater-script
  inflating: app_densities.txt
  inflating: app_sizes.txt
  inflating: bkup_tail.sh
  inflating: g.prop
  inflating: gapps-remove.txt
  inflating: installer.data
  inflating: META-INF/com/android/otacert
  inflating: META-INF/MANIFEST.MF
  inflating: META-INF/CERT.SF
  inflating: META-INF/CERT.RSA
[flash_archive] Remount /system/ in rw
[flash_archive] Start file install
find: system/: No such file or directory
[flash_archive] Remount /system/ in ro
[flash_archive] Delete tmp directory
[flash_archive] Done successfully !
{Result:OK};
```

I don't know whether it's part of the project goals, but supporting Genymotion would be A+ in my book.

**Comment by rapperskull** [comment]
Our package is not a standard flashable package that simply unpacks on top of /system. It has very advanced logic that requires the ash shell, as found in TWRP.
Many other recoveries miss some indispensable commands, and are not compatible with our package.
What I understood at first sight is that your emulator does not have a real "modern" custom recovery, and simply tries to unpack the ZIP file, therefore it will never be compatible.
One solution is to ask to the developers if they plan to implement a complete shell with all the commands found in TWRP and the support for "modern" flashable ZIPs (read support for update-binary).

**Comment by zeorin** [comment]
OK, thanks for your feedback. I thought it might be a long shot. I'll contact Genymotion and see whether they'd be willing to support this.

**Comment by scana** [comment]
@zeorin so, did you manage to get a response from guys from Genymotion?

**Comment by zeorin** [comment]
Support for modern flashable zips is on their roadmap, but I rabbit say when it will be implemented:

> We are actively working on support for modern flashable ZIP. We understand how it can be useful for users, and we'll do our best to provide it as soon as possible.
> The first Genymotion virtual devices that will support this feature will be the final release of Android Marshmallow (6.0). Other virtual device version will support it later.

**Comment by f03lipe** [comment]
Any updates on this?

**Comment by mfonville** [comment]
@f03lipe Genymotion is doing their best to be compatible, but I can't disclose any details.

**Comment by f03lipe** [comment]
Thank you, @mfonville. I got it working by following this: https://gist.github.com/wbroek/9321145.

**Comment by kolenj** [comment]
hi,zeorin, I have this problem now ,do u haved find some ways to solve this problem?

**Comment by Bnaya** [comment]
I've just managed to flash opengapps on genymotion android 6
![screen shot 2017-03-04 at 23 19 13](https://cloud.githubusercontent.com/assets/1304862/23582367/2bc1f426-0131-11e7-803f-f8006f2a91a2.png)

**Comment by alejandroiglesias** [comment]
@Bnaya how did you do it?

**Comment by Bnaya** [comment]
just dragged the zip into the emulator window and it offered to flash the zip.
i hit yes, and it worked

**Comment by alejandroiglesias** [comment]
@Bnaya what package did you use? I tried to do it on an Android 7.1.0 device but it just fails with this message:

![image](https://cloud.githubusercontent.com/assets/480640/25434455/c46a3102-2a62-11e7-9e3c-28aa2f3b504d.png)

**Comment by NikitaZhevnitskiy** [comment]
Solved this by 
https://stackoverflow.com/questions/26469299/genymotion-is-not-flashing-my-zip/26543279#26543279

**Comment by Bnaya** [comment]
@alejandroiglesias as i was saying, it worked for me on GM android 6, I don't remember what with A7. i think it was failing also for me
