### ISSUE TITLE
prompt to force install 

### ISSUE THREAD

**Issue by Tom-Neverwinter** [opengapps/opengapps#137]
This is a really annoying issue with cm and aosp; http://pastebin.com/tWnuaT9D
 I formatted and this still comes up. I want to force install normally.

"Force clean install Setting

Open GApps normally detects if it's a clean install or an upgrade. This affects how Camera and Keyboard apps are treated, it won't install those unless this is a clean install to avoid problems during upgrades. User might may add forceclean to ignore that detection. Note: this setting is untested widely and may cause problems." 

This does not work.

**Comment by mfonville** [comment]
I think you misinterpret what was written in the Wiki.
Force a "clean install" is that the script will treat the device as if the /data/ partition was clean, not that other conflicts, like other GApps installations, are ignored.
You should first wipe your /system/ and reflash your ROM when switching GApps. This will not lose you any data.

CC @eugenesan
