### ISSUE TITLE
SecurityException with Google Partner Setup

### ISSUE THREAD

**Issue by robinharmsen** [opengapps/opengapps#138]
This issue was first reported to Cyanogen, but they refferd to you for this issue.

After PowerUp  the message "Google Partner Setup is terminated" is shown. After "close" it doesn't appear again until the next PowerUp. 

It is a java.lang.SecurityException with the following description: "Neither user 10023 nor current process has android.permission.READ_PHONE_STATE."

Hope you will be able to resolve.
In case you want to discuss with cyanogen, please use the jira ticket at https://jira.cyanogenmod.org/browse/NIGHTLIES-1903

**Comment by mfonville** [comment]
Could you give us a full logcat of the error and the debug log of your open gapps installation?

**Comment by robinharmsen** [comment]
Logcat:
https://www.dropbox.com/s/gqh2y2ul7yxwtt2/logcat.txt?dl=0

Debug log
https://www.dropbox.com/s/z0bcxz5btr2hsys/open_gapps_debug_logs.tar.gz?dl=0

**Comment by mfonville** [comment]
Could you try the build of Oct 4th? It can be found at https://github.com/opengapps/arm/releases/tag/20151004

I have a suspicion what the cause could be, and it was introduced shortly after that date.

**Comment by mfonville** [comment]
I got now related input from XDA forum that confirms my suspicion. I will fix it right away.

**Comment by mfonville** [comment]
This fixes it: https://github.com/opengapps/all/commit/ebe0e317622053276a7b7e67be977d682d153ba0

**Comment by mfonville** [comment]
Still it something that should may need a fix on the ROM side, that the application does crash on a non-existing permission, and it does state that it should be compatible with lower SDK versions, is very weird.
