### ISSUE TITLE
com.google.android.maps.jar Bad checksum

### ISSUE THREAD

**Issue by demokritos** [opengapps/opengapps#140]
Some app crashes immediately after launch.
Logcat message:
```
E/AndroidRuntime(16977): 	Suppressed: java.io.IOException: Failure to verify dex file '/system/framework/com.google.android.maps.jar': Bad checksum (50b0c1bb, expected d4887843)
```
Replacing /system/framework/com.google.android.maps.jar with old one resolves this issue.

I am using CM 12.1 Nightly on Nexus 5 hammerheadcaf.

**Comment by mfonville** [comment]
Today I have pdated the framework with some original non-deoxed JARs from Android One, maybe that will resolve your problem. Please report back when Oct 13th builds are available and you can test those.

**Comment by demokritos** [comment]
I built a flashable zip file and flashed it. This issue is fixed.

Thank you.

**Comment by mfonville** [comment]
Awesome :-)
Happy that someone knows how to build from source!
