### ISSUE TITLE
Allow keyboard swype libs to be installed as optional extra

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#141]
Since keyboard swipe libs break stuff for most users, but some still do want it, we could bundle them as an optional (non-default extra).

**Comment by foresto** [comment]
For the record, gesture typing works fine for me with recent cyanogenmod 12.1 nightly builds + cgapps.

**Comment by mfonville** [comment]
Could you test if gesture typing did work in the build of 13 October 2015? We used the Marshmallow libs in that version, and I would like to know if those do not pose issues with CM 12.1

**Comment by foresto** [comment]
Where can I find old builds?

**Comment by mfonville** [comment]
In the architecture-sources are all the releases published.

But could you please try if this (pico) package works right for you: https://www.androidfilehost.com/?fid=24052804347837879

You should make a gapps-config file and add 'swypelibs' as keyword to it.
Also it should detect any former install of the swypelibs, and then automatically reinstall them (by checking if libjni_latinime.so is a symlink instead of a file)

**Comment by foresto** [comment]
I'll try to find some more time for testing soon.

In the mean time, are you sure you want to use the word "swype" as the keyword? As far as I know, the library does not come from Swype, Inc. and has nothing to do with the Swype keyboard.

**Comment by mfonville** [comment]
I see your point, but people tend to refer to gesture-typing as 'swype'-support. It is indeed technically wrong, but I don't see any (legal) issue with using their name as a config keyword. If you have a better 1-word description for these libs that would be very welcome.

**Comment by foresto** [comment]
Okay, I just tried the package you linked above (open_gapps-arm-5.1-pico-20151015.zip) and the one you posted on xda yesterday (open_gapps-arm-5.1-pico-20151015+v2.zip). Neither one worked.

Before I started, I was running cm-12.1-20151014-NIGHTLY-amami with cgapps, and gesture typing worked.

For the first test, I took these steps:
- copy cm-12.1-20151014-NIGHTLY-amami.zip to sdcard1
- copy open_gapps-arm-5.1-pico-20151015+v2.zip to sdcard1
- enter fastboot mode
- fastboot erase system
- fastboot erase cache
- fastboot reboot
- enter recovery mode
- wipe cache partition
- apply update from sdcard1: cm-12.1-20151014-NIGHTLY-amami.zip
- apply update from sdcard1: open_gapps-arm-5.1-pico-20151015+v2.zip
- reboot
- enter my android encryption passphrase and wait for android boot to complete
- verify that gesture typing is enabled in the AOSP keyboard settings

Result: AOSP keyboard works, but gesture typing does not.

I then repeated those steps with a file named `.gapps-config` on sdcard1, containing one line:

    swypelibs

Result: Gesture typing still does not work.

Finally, I tried again with the earlier build that you linked in your comment above: open_gapps-arm-5.1-pico-20151015.zip

Result: Gesture typing still does not work.

**Comment by foresto** [comment]
I don't see an open_gapps log file anyplace obvious. Do I have to do something special for it to be created?

**Comment by mfonville** [comment]
It should be created at the location where the zip file is located. Do you flash using TWRP? And is there write access on sdcard1 in recovery?

**Comment by foresto** [comment]
I flash using Cyanogen Recovery, which is the standard way to install CyanogenMod 12.1. I don't know how to determine whether it has write access to sdcard1.

**Comment by mfonville** [comment]
Would you be willing to try flash using TWRP? In general it gives better control and gives more feedback/possibilities to gather debug info and troubleshoot.

**Comment by foresto** [comment]
TWRP doesn't offer a build for the Xperia Z1 Compact.

**Comment by mfonville** [comment]
Hmm, that is irritating. Then I don't know how/why to help you with collecting the debug file. It *should* try to write it where the zip is located. Other things are beyond my control.
But we do need that debug file to see what goes wrong.

PS: the code that was in those test versions is also in today's daily, so you can flash also any 16 October package.

**Comment by foresto** [comment]
A couple more interesting things:

In an attempt to return to a fully-working state, I wiped the system and cache partitions again, then re-installed my cm-12.1 build and cgapps. When I rebooted, gesture typing worked again, but pop-up messages kept appearing, telling me that Google Services had stopped. I guess that means there's no clean way to return from open_gapps.

While gesture typing was working, I thought I'd take a look at the libraries that were on my system:

    $ ls -l /system/lib/libjni_la*
    -rw-r--r-- root     root       636480 2015-10-13 17:03 libjni_latinime.so
    -rw-r--r-- root     root       677372 2008-08-01 05:00 libjni_latinimegoogle.so

That libjni_latinime.so is the same size as the one that was there when I used open_gapps, but libjni_latinimegoogle.so was not present when I used open_gapps. I then tried an experiment:

- make a backup of /system/lib/libjni_latinimegoogle.so
- fastboot erase system and cache
- installed cm-12.1 and open_gapps
- reboot
- manually copy my backup of libjni_latinimegoogle.so to /system/lib
- reboot again

After this, gesture typing worked. Is it possible that open_gapps just needs to install libjni_latinimegoogle.so along with libjni_latinime.so to make this all work?

**Comment by mfonville** [comment]
CGApps has an outdated Google Play Services, but your the data on your /data/ partition can't be downgraded to match that lower version. That causes the FCs.

OpenGApps installs those files (actually it is 1 file and 1 symlink to the other) too for the gesture typing. I just have the feeling that your config-file is not processed, because it uses the same mechanism/location as the debug file.

Maybe you can try storing the config-file with the keyword as /sdcard/Open-GApps/.gapps-config ?

**Comment by foresto** [comment]
I created /sdcard/Open-GApps/.gapps-config with `swypelibs` inside, and tried again. Still no libjni_latinimegoogle.so, gesture typing, or log file.

**Comment by foresto** [comment]
I don't understand why the config file should be necessary at all. Isn't the latest version of opengapps supposed to install libjni_latinimegoogle.so if libjni_latinime.so is already present?

**Comment by mfonville** [comment]
Does the recovery itself produce any kind of log? We currently have literally no clue what is happening inside that black box :-(

**Comment by mfonville** [comment]
The current package checks if libjni_latinime.so is a symlink instead of a file, then it knows the original lib is not in place, and will then automatically activate the keyword.

**Comment by foresto** [comment]
While the recovery is installing the open_gapps zip file, it shows some text output that runs off the bottom of the screen. It looks like the word "open" drawn in ASCII graphic block letters (possibly created by figlet).

After it has finished, the recovery allows me to display two log files: /cache/recovery/last_kmsg and /cache/recovery/last_log. The latter contains this:

    - Fixing permissions & contexts

    - Copying Log to /sideload

    - Installation complete!

    - Unmounting /system, /data, /cache, /persist


    Installation complete.

It looks like that text comes from open_gapps, yes?

**Comment by mfonville** [comment]
Yes, that is Open GApps user-interface output.
But I am interested in the output of the recovery, that what is happening "behind the scenes".

**Comment by foresto** [comment]
Unfortunately, the log files in /cache/recovery are overwritten by the time I reboot and get a shell to read them.

Perhaps we could learn more if opengapps didn't log that huge banner (which seems to push further output off the bottom of the screen) or if it wrote its log to someplace under the /cache directory?

**Comment by mfonville** [comment]
It writes its debugs logs to /tmp/ you could attach adb debugger over USB from your computer (I hope that CM recovery supports that) and fetch those?

**Comment by foresto** [comment]
I've been trying to get adb to work with CM recovery, but haven't had any luck yet. So far, adb just reports the device as "offline".

**Comment by mfonville** [comment]
Ok. I just found another error, using the debug logs from someone on XDA.
So if we wait for next nightly build (should be a few hours) you can try it again: https://github.com/opengapps/opengapps/commit/cf04e76e927fb58d46f544f9922c51fc1091565a

**Comment by foresto** [comment]
Okay, will do. Where is that "architecture-sources" place containing all releases published? I'd like to bookmark it.

**Comment by foresto** [comment]
I just tried open_gapps-arm-5.1-pico-20151017 with a gapps-config.txt file. It still doesn't work.

**Comment by mfonville** [comment]
https://github.com/opengapps/arm/releases

**Comment by mfonville** [comment]
The libs included were broken, because of a silly mistake. It should now work and I have received a lot of feedback that it does, so I consider it fixed :-)

**Comment by mfonville** [comment]
I will re-add the code for excluding AOSP libs.

**Comment by mfonville** [comment]
Done in https://github.com/opengapps/opengapps/commit/f429c999999509236aa6dcdd1ef2263d0fbeaa33
