### ISSUE TITLE
Wrong Google Play Services in GMSCore 0 folder. -438 instead of -430.

### ISSUE THREAD

**Issue by SiRMez** [opengapps/opengapps#15]
I noticed that in the gmscore folder, folder 0 it has the wrong google play services. It has google play services -438 instead of the universal -430 version. I have also checked to see what's installed in my system and it says -438 after installing open gapps. I'm on a Nexus 6 which would require/install -430 on its own.

**Comment by mfonville** [comment]
Should be fixed in commit 7404d0ce9da9e201209c8c8312205711db0c59ac
Could you try to check out and build this version?

**Comment by SiRMez** [comment]
At work can't build, sorry.

**Comment by mfonville** [comment]
Ok, then please wait for the uploads that will be coming soon.
I implemented the building of the different package variations :)

**Comment by SiRMez** [comment]
I will definitely test as soon as I see it and let you know how it goes. Glad to see everything is going smoothly.
