### ISSUE TITLE
bkup_tail.sh fails to calculate storage needed

### ISSUE THREAD

**Issue by jezzaaa** [opengapps/opengapps#151]
My ROM upgrades have been failing due to a bug in bkup_tail.sh.

This line requires the double quotes to be removed:

    installed_gapps_size_kb=$(cd /system; du -ak "$(list_files)" | awk '{ i+=$1 } END { print i }')

Otherwise the list of files to backup are treated as one huge filename, which doesn't exist, and hence contains zero bytes.

More details in my comment against commit https://github.com/opengapps/opengapps/commit/f2e620b2be0ef811d9093cab6e622caa0a4c3309.

**Comment by mfonville** [comment]
Thank you for finding the error, debugging and handing the solution to us :-)
I will fix it ASAP
