### ISSUE TITLE
Google dropped some apps from Nexus 6P

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#153]
Google+, Docs, Sheets, Slides, Fitness, Keep, News & Weather, Books, Newsstand, Ears
are not on Nexus 6P Stock.

We could bring our mini-package in line with this new 'small stock' set, and e.g. drop G+.

Any opinions?

**Comment by NicholasBuse** [comment]
Not even as stubs huh?

**Comment by mfonville** [comment]
Nope, not even stubs. They really slimmed it down.

**Comment by mfonville** [comment]
Google+ is dropped from Mini.
The other apps that Google actually *did* bundle with the Nexus 6P, like Play Movies and Play Games are imho not popular enough to be considered for mini.
