### ISSUE TITLE
Don't delete AOSP usr srec when not installing speech

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#154]
Currently we always delete /usr/srec/ during installation, but if not installing Google's speech files, we maybe should leave the AOSP files that *can* be there intact.

**Comment by kabouin** [comment]
Hello,

I'm the one that reported this issue by email. Thanks for opening this issue.
I don't know exactly how do you plan to fix this, but it would be great to prevent the removal of `/usr/srec` when Speech package is excluded in `.gapps-config` file.

Thanks!

**Comment by mfonville** [comment]
I think we will change the general specified path of 'speech' to /usr/srec/en-US/ instead, since that is the only speech files we bundle.
From the debug logs I received the AOSP files are in /usr/srec/config/en.us/

In that case the files should not be removed anymore. Expect a patch in the coming minutes :)

**Comment by mfonville** [comment]
The fix is live, in tomorrow's build it should be fine.
If you want, you can already check the code and build it yourself with the patch :-)

I'll close the bug, because for 100% certain this fixes the behaviour. If you still find (any other) issues you'll know where to contact us :-)

**Comment by kabouin** [comment]
Many thanks for your reactivity. I will check that in the next builds =)
