### ISSUE TITLE
Gesture typing does not work with AOSP keyboard

### ISSUE THREAD

**Issue by Ghent** [opengapps/opengapps#156]
Using AOSP keyboard doesn't work.  According to various articles on the Internet, this may be caused by a missing libjni_latinime.so in the system\lib directory.  I've been unable to confirm this.

**Comment by innir** [comment]
Did you actually tell the installer to install the swype libs? See the [wiki](https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options#swype-libs) for instructions.

**Comment by Ghent** [comment]
I tried this and I believe it worked.  Thank you!
