### ISSUE TITLE
Rename Hindi to Indic

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#157]
Hindi Inputmethod has been renamed to Google Indic Keyboard and now supports more languages
We could consider changing the keyword from hindi to indic.

Any thoughts?

**Comment by NicholasBuse** [comment]
https://github.com/opengapps/apkcrawler/commit/1f8b40bd0111bad18852f018e5015028890e6674

I can update the keyword when we decide :)

**Comment by rapperskull** [comment]
It's probably the best thing to do.

**Comment by mfonville** [comment]
Keyword has been changed!
