### ISSUE TITLE
PackageManager

### ISSUE THREAD

**Issue by Mr-MEX** [opengapps/opengapps#159]
Boot loop, not working!

Please fix!

**Comment by bgiesing** [comment]
We Can't do anything without logs and what ROM you are using. 

But assuming that you are using Marshmallow, the GApps won't work unless the person who made your ROM has added a patch.

**Comment by rapperskull** [comment]
Commit 6101d8d49a246083ca11b40f1219c825238b3560 should fix this issue, if the problem is the stock PackageInstaller not being removed.

**Comment by mfonville** [comment]
I actually got feedback now that it does solve the problem, so I will mark the bug as solved.

**Comment by airend** [comment]
@bgiesing, is the frameworks change needed anymore? Based on @deadman96385's [comment](https://github.com/opengapps/opengapps/issues/93#issuecomment-154180359), it sounded like all is included in AOSP, but I may be misreading it. I'm having the soft/boot loop issue as well, hopefully due to the PackageInstaller bug.

**Comment by mfonville** [comment]
You do need that patch, otherwise you will get FCs during boot if the permissions are not granted.

**Comment by invisiblek** [comment]
@mfonville Sean implied the patch wasn't needed on CM gerrit: http://review.cyanogenmod.org/#/c/116418/

**Comment by invisiblek** [comment]
https://github.com/opengapps/opengapps/pull/161

**Comment by deadman96385** [comment]
@mfonville The patch is not needed for CM and CM based roms, aosp based roms still need the permissions patch

**Comment by mfonville** [comment]
@deadman96385 that clarifies :-)
I will update it in the wiki too.
