### ISSUE TITLE
Various GApps have multiple DPI versions

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#16]
@rapperskull has found out that many more GApps have various DPI variants, he compiled a list at http://pastebin.com/cJQcBm9g

We should think about if and how we should maybe package these variations.
aapt dump badging xxxx.apk gives output like:
`compatible-screens:'200/400','300/400','400/400','500/400','200/480','300/480','400/480','500/480','200/560','300/560','400/560','500/560','200/640','300/640','400/640','500/640'`

The first number says something about the screensize (a classification with 200=small, 300=normal, 400=large, 500=xlarge ???)
And the second number is the dpi.

Docs/Drives/Sheets/Slides uses the most coherent naming scheme:
30: Universal
31: ldpi (120) (Never seen)
32: mdpi (160) (Never seen)
33: hdpi (240)
34: xhdpi (320)
35: xxhdpi (480)
36: xxxhdpi (640)
37: xxxxhdpi (Doesn't exist yet)

Current tasks:
- [x] Study what is going on and what has to be done
- [x] Rewrite the apk-sources add and report tools to support multidpi
- [x] Restructure the format of the produced ZIP archive
- [x] Rewrite the buildtarget tools to support multidpi
- [x] Rewrite the buildtarget tools to build the new ZIP archive structure
- [x] Rewrite the installscripts to handle the new ZIP archive structure
- [x] Rewrite the installscripts to handle multidpi
- [x] Add all the packages to the new source-repository structure
- [x] Add all dpi variants of the packages to the new source-repository structure

**Comment by mfonville** [comment]
Current thought:

*if* a package has different paths defined in its 'application-icon-XXX:' lines -> it is a universal package

*if* a package has fully equal paths defined in its 'application-icon-XXX:' lines -> look at the path (that looks like 'res/drawable-hdpi-v4/...' get ldpi/mdpi/hdpi/xhdpi/xxhdpi/ definition.

**Comment by mfonville** [comment]
More information for the docs related apps:

30 (All DPI) ** Missing for latest release **
32 (160 DPI)
33 (240 DPI)
34 (320 DPI)
35 (480 DPI)
36 (640 DPI)

**Comment by mfonville** [comment]
The rule for installation of DPI version on the Android device should become:
*Is there an APK for my exact DPI -> install that one
*Is there otherwise a universal APK available? -> install that one
*No universal and no exact DPI available? Then look for the APK's DPI version that is as close as possible *above* the device's own DPI.

**Comment by NicholasBuse** [comment]
Another interesting case is do we favor "correct" DPI for the most recent version (as outlined above) or an older version with a matching DPI.

Also, I think @rapperskull 's pastebin post needs Photos too (or did that go away with the latest version?)

**Comment by mfonville** [comment]
Photos was not yet in existince during his pastebin, I believe. Trick will be to set up many accounts (or have many contributors) that can download all these different APK versions directly from the Play Store directly. So we would need a lot of GSF ids for the various device variants (arm,arm64,x86,x86_64, 240dpi, 320dpi, 480dpi, 560dpi, 640dpi). Maybe we can generate these using virtual android machines?

**Comment by rapperskull** [comment]
3. No universal and no exact DPI available? Then look for the APK's DPI version that is as close as possible <s><i>above</i></s> <i>below</i> the device's own DPI.

In this way the app will be updated by the Play Store. Remember that apps with higher DPIs have higher version numbers.
BTW I'm updating the pastebin and the 33 variant for Docs (that was marked as never seen) is now a thing.

**Comment by mfonville** [comment]
Yeah, the Hangouts change I noticed earlier today, really weird, but should not impact the handling when following my dpi-detection approach.

About the above/below discussion: choosing below indeed will allow the play store to silently update the app, if it is available, but above gives the 'best' and most compatible user experience, because having a higher-DPI version is always compatible with a lower dpi, but not per se the other way around.

**Comment by rapperskull** [comment]
It's not really a big deal, but maybe downscaling resources instead of upscaling them is better.
As for as the problem of obtaining all the APKs, I tried some time ago to install Google Play Store in the Google AVD (that should include the Core base or something similar), but I failed.

**Comment by rapperskull** [comment]
New pastebin: http://pastebin.com/c0J75JsH

It will be updated in the future to provide useful informations to all.

**Comment by DJAlik** [comment]
In cases where universal version is older than specific dpi versions it appears the builder picks the older universal version. For example for device Samsung Galaxy S3 Google Play Games 3.1.11 is available but the make file put 3.0.11 into the zip. Is there a way to make an extra parameter for the make file to build a specific dpi version and then if a particular dpi is not available it would revert to the universal version? Something like make arm-22-stock-320?

**Comment by DJAlik** [comment]
New APK added
djalik@djalik-VirtualBox:~/opengapps$ ./add_sourceapp.sh /home/djalik/Downloads/com.google.android.play.games.apk 
Importing Google Play Games
Package com.google.android.play.games | VersionName 3.1.11 | VersionCode 31110036 | API level 9
Package supports DPIs: 320
Native code for architecture(s): armeabi-v7a 
Existing version /home/djalik/opengapps/sources/arm/app/com.google.android.play.games.6/9/31100036.apk
Replaced with /home/djalik/opengapps/sources/arm/app/com.google.android.play.games.6/9/31110036.apk


Build log
Built com.google.android.play.games with extra DPI variants: 2 of universal version 30110030

**Comment by mfonville** [comment]
@DJAlik this is because currently the 'universal' one it our benchmark for the versioning scheme. In the code I am still writing a different approach will be used.

**Comment by DJAlik** [comment]
Just to confirm that my assumptions were correct that the correct DPI
version is not installed. I just installed the latest build which I built
early this morning and the Play Store is offering me to update Youtube to
10.24.57 and Google Play Games to 3.0.11 (1917563-036). The versions I have
installed based on this morning's build are Youtube 10.24.57 (probably the
universal dpi version) and Google Play Games is 3.0.11 (1917563-030)

On Fri, Jun 26, 2015 at 5:16 AM, mfonville <notifications@github.com> wrote:

> @DJAlik <https://github.com/DJAlik> this is because currently the
> 'universal' one it our benchmark for the versioning scheme. In the code I
> am still writing a different approach will be used.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opengapps/opengapps/issues/16#issuecomment-115629153>.
>



-- 
<http://www.facebook.com/djalik>  <http://twitter.com/#!/DJAlik>
<http://www.linkedin.com/in/alexrusinov>
<http://plus.google.com/114580313768137070684>
<http://www.mixcloud.com/djalik/>
<http://psnprofiles.com/DJAlik>

**Comment by mfonville** [comment]
Working on multi-dpi support in the new branch https://github.com/opengapps/opengapps/tree/multidpi

**Comment by mfonville** [comment]
I urge all @opengapps/packagers to download the new toolset, and to look with ./report_sources.sh which DPI versions of packages we are still missing, and trying to download those from apkmirror or directly from the play store :-)

Yay! So happy we were able to implement this huge change. It will also increase the size of the package, but install sizes will be even smaller (no DPI upgrades more in /data/) and the compatability will be much better.

**Comment by mfonville** [comment]
I wonder btw if TWRP supports the usage a zip-algorithm that would allow for delta-compression, like 7zip, for the flashable file. That would reduce the size from 900 to around 450 megabytes...

**Comment by mfonville** [comment]
Apparently TWRP does *not* support 7zip. But I am thinking, we could include 7za for Android (around 1.5MB) in the zip package, and then 7zip all the packages' folders in 7zip format within the ZIP. These 7zips files can then get extracted to /tmp/ when a package is being chosen for installation, and get processed further from there.

An obstacle: we need a 7za application for each (fallback) architecture, so at least an x86 and an arm version.

**Comment by rapperskull** [comment]
We must check if compressing every single folder gives approximately the same compression ratio of compressing the entire package. I thought about compressing the whole package, but it would be a problem to extract it to /tmp.
Or we could use tar, that should be included in busybox, with xz compression. It seems that it's as efficient as LZMA (not 2 though) and should provide both compression and compatibility.
For comparison: http://catchchallenger.first-world.info//wiki/Quick_Benchmark:_Gzip_vs_Bzip2_vs_LZMA_vs_XZ_vs_LZ4_vs_LZO

BTW running tar on android (haven't tried in recovery) lists in the options:
a (De)compress using lzma
so probably we can extract 7zip archives directly with tar.

**Comment by rapperskull** [comment]
Apparently xz implements the LZMA/LZMA2 compression algorithm (https://en.wikipedia.org/wiki/Xz) and is preferred to 7zip in \*nix environments.
Also, even if I don't see that in the help on Android, tar *should* support permission and ownership preserving (https://www.gnu.org/software/tar/manual/html_section/tar_70.html). In this way we can store the files with the correct owner and permissions. Maybe.

**Comment by mfonville** [comment]
Hmm, I was already trying to compile 7zr for x86 and arm (but failed :-P).
So if tar.xz is supported by default, and that also would have the same delta-compression techiques to reduce the size when packaging almost similar APKs, that would be preferred.
I will do some testing with .xz to see how it performs.

**Comment by mfonville** [comment]
.xz doesn't seem to do any delta compression, so I think we are still 'convicted' to using 7z to achieve any real size reduction :-/

**Comment by rapperskull** [comment]
Comparison test: compressing Core, GApps and Optional folders in a single archive using 7-zip 9.38 on Windows.
Uncompressed: 1372 MB
ZIP compressed: 860 MB (Compression ratio: 62,7%)
LZMA compressed: 446 MB (Compression ratio: 32,5%)
LZMA2 compressed: 469 MB (Compression ratio: 34,2%) (why?)

On Ubuntu using the following command: *XZ_OPT=-9 tar -cvf test.tar.xz --xz Core GApps Optional*
468 MB (Compression ratio: 34,1%)

At first I also noticed low compression, then I found out you have to set the compression level with the XZ_OPT parameter.

**Comment by mfonville** [comment]
You can even use -9e for compression (I am testing that one now)

**Comment by rapperskull** [comment]
I tested it too and I got 468 MB again, better avoid the extreme parameter to speed up the compression a little bit. BTW LZMA compression (7-zip one) is also supported by tar, I'm testing it now.

**Comment by mfonville** [comment]
It is actually not tar that does the compression. Tar just puts multiple files into a single file, and then the compression tool (xz) does a 'filter' over it. That also explains the double file extension: .tar.xz -> a tar wrapped within a xz.

You can read the details and options about xz if you type in: man xz

**Comment by rapperskull** [comment]
Yes, I know that, for supported I mean that you can compress/decompress it using a single command instead of two. Also supported means available through busybox, but it seems that basically all common compression algorithms are supported: zip, gzip, bzip2, lzma and xz.

**Comment by mfonville** [comment]
Ok. Well, I have to go to sleep now, but if you want, you can start a new branch and work on those nice future filepaths like GApps/youtube.tar.xz ;-)

**Comment by rapperskull** [comment]
I have to sleep too, I'm just testing the lzma compression on Ubuntu. Tomorrow we'll decide what compression algorithm to use and start the work.

**Comment by bgiesing** [comment]
Even though it might take more work, could we get recovery developers to
update with support for other compression techniques? This is becoming a
problem for more than just these GApps and I think that it could benefit
more than just us.



To unsubscribe click: <http://email.giesing.cf/u/eJwljrtOw0AQAL_GLqO7vb1dX3FFiAVFMBIUGOj2Xn4QK1GUgPL3RGaKKUeTPJFEqCe_2-6vR_7u-_Fnv-tcO9-eK9PGj5d-Apx_8fHr1dDpc5jfn_Rb7tp5qeChGypUi0yHzbA6Hpd69OQKo2IVQKwkSwWxEGbKwCaWouuzP-fT4XYPKMUNO2GxDKEoTI1ia1FMINaQJTOISTElZCYqwUEs6h-ttSQmDQ5Ek4tZYSkpqOa-tOY3w3QZr2GduvgKtn_w_UW9>

**Comment by rapperskull** [comment]
@bgiesing TWRP already includes tar and support to many compression algorithms. They're however not supported in the zip update because also the AOSP recovery does not support them.

@mfonville Created a new branch and started working on it. Pushed the first commit(s) and now apps are stored in tar.xz format. Later today I'll update inc.updatebinary.sh if you're not faster then me.

**Comment by bgiesing** [comment]
@rapperskull /startrant Just because AOSP doesn't support it, doesn't mean they can't add it. That's the whole purpose of TWRP. They add stuff that AOSP won't support! /endrant

In all seriousness, it would be difficult to get them to support it but not impossible. While this while work in the meantime (or if they never change), it would still be nice to at least ask.

@Dees-Troy

**Comment by mfonville** [comment]
@bgiesing but one of the problems is that it isn't supported in the OTA format that Google uses for its zipfiles. So even if they would add it, I would *really* never get verification of the zip to work :-P

I think the current approach that we now take in issue #40 is really the long-term way to go for maximum compatibility and great compression results.

**Comment by mfonville** [comment]
So we have a new bug on the forum: http://forum.xda-developers.com/showpost.php?p=61745648&postcount=458

On a device with DPI of 560 we can see that the APKs of Google+, Earth and YouTube don't get installed. The libs are correctly in place. So the selection mechanism to 'select a lower dpi if the same dpi or a higher one is not available' does not work.

@rapperskull any ideas how to fix this?

**Comment by mfonville** [comment]
@rapperskull should line 306 in inc.updatebinary.sh not be changed from:
```
				if [ "$d" -ge "$density" ]; then
```
to
```
				if [ "$d" -le "$density" ]; then
```
?

**Comment by rapperskull** [comment]
Yes, but we also have to reverse sort the list, otherwise we install the lowest one.
Today I was very busy and all the day away from home. Had no time to work on opengapps.

**Comment by mfonville** [comment]
Can we embed a check within the shell script that can check whether tar supports the XZ decompression? If it would fail to pass that test, we could just give an error-code and a message to use TWRP, instead of leaving the device in a broken state.

**Comment by rapperskull** [comment]
Sure, I'll make this change in the evening.

**Comment by mfonville** [comment]
ok, great. I think we could use a line like:
```
tar --help | grep -e "-J"
```

**Comment by rapperskull** [comment]
Or we can just use command -v xz like we already do in our scripts.





On Wed, Jul 8, 2015 at 1:53 AM -0700, "mfonville" <notifications@github.com> wrote:
ok, great. I think we could use a line like:
```
tar --help | grep -e "-J"
```

---

**Comment by mfonville** [comment]
But having xz does not imply that tar understands the -J argument. So I think we should then use both.

**Comment by mfonville** [comment]
I think we can conclude that this bug is done, multidpi is implemented, and most packages have now the most common dpi variants.
