### ISSUE TITLE
[AROMA] New Aroma Installer (dependent on external)

### ISSUE THREAD

**Issue by bgiesing** [opengapps/opengapps#160]
Looks like the theme got updated for the first time in a while. 

I am away from my computer but anybody willing to look into updating it? 

http://forum.xda-developers.com/attachment.php?attachmentid=3361463&d=1434244797

@mfonville

**Comment by bgiesing** [comment]
@raulx222

**Comment by raulx222** [comment]
I'll have a look.

**Comment by raulx222** [comment]
Our theme is based on that latest theme by Daniiiik49 but with some changes which I made (dark layout, lollipop navigation buttons, and maybe some more minimal changes).

**Comment by bgiesing** [comment]
Well, it's from the same xda thread, but this user took it and fixed some
bugs as well as updating it for Aroma 3.0

On Fri, Nov 6, 2015, 11:41 PM raulx222 <notifications@github.com> wrote:

> Our theme is based on that latest theme by Daniiiik49 but with some
> changes which I made (dark layout, lollipop navigation buttons, and maybe
> some more minimal changes).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opengapps/opengapps/issues/160#issuecomment-154628662>
> .
>



To unsubscribe click: <http://email.giesing.cf/u/eJwljktPwlAQRn9NuyQzc-c-ZtEFKpL4CBEjhBW5z9IAogRK9Nfb1G9x8q1OTmqM8ZHqrrmfPl9Pdr_-uH1-_87el7F_7fsZVHRn0T9uu-G0i8Xm6W21YV-ph3a1fdFztbxVDEffHSbtyHg61ruGi3NAYhAwpiwBTQrKA1FhR6xMfW7O-evwM0gBrLPibcmghVI0SRCYvXbOFmsgCUsoFl2KmiMEoVjgf4iktUZkIY9GYgaTVUE2Q9Kon7TdZXcNY9SlqWj6BwdgRKI>

**Comment by raulx222** [comment]
Hmm..
>- Fixed errors in Material Gray Theme
>- Updated the AROMA Installer binary to 3.00b1
>- Removed unneeded files from Themes folders
>- Added Material Gray to Theme preview

He made some fixes for the Gray theme, also cleared some unneeded files from themes folder. And added the 3.0 AROMA binary to the demo package `Material_Aroma_Theme_v1.02_FIXED-djb77.zip` so our theme is still 'up-to-date' since he didn't touched the Material Green Theme (except the deletion of some unneeded files).

**Comment by mfonville** [comment]
Maybe we could let some people test with the new binary?

**Comment by raulx222** [comment]
I'm pretty sure that it's more unstable compared with 2.70RC2, but we could let some people test it with the new binary and see the results.

**Comment by mfonville** [comment]
Maybe especially those that experience issues with the current release...

**Comment by mfonville** [comment]
@raulx222 it is your call if and how to handle this further.

**Comment by raulx222** [comment]
@mfonville Okay! But since I can't run AROMA Installer on my device, let me know if you need some changes to the theme.
And about the 3.0 Beta version, I will try it on my device (maybe it will work, *magic*).

**Comment by mfonville** [comment]
LibAroma got a big update this Christmas:
https://github.com/amarullz/libaroma/commits/master

**Comment by mfonville** [comment]
There is zero development on AROMA since the beginning of this year.

Probably best to accept that AROMA will die at some point, and focus on creating other gapps-config creating tools instead.
