### ISSUE TITLE
Can't seem to clone repo 

### ISSUE THREAD

**Issue by Nikki1993** [opengapps/opengapps#162]
While cloning repo on Arch I get this

Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Any ideas why it denies permission? any other repo seems to work just fine.

**Comment by Nikki1993** [comment]
Solved... it was my ssh key!

**Comment by mfonville** [comment]
:-)

**Comment by Nikki1993** [comment]
Can I capture your attention for just a little longer (so I don't have to open another issue)

I synced arm gapps and now I want to build them, using arch 64bit. Got android-sdk platform tools etc. 

When running make arm-23-stock terminal gives
Android SDK is required for aapt and zipalign utilities but not installed.

Weird thing is, I have sdk installed and working, for instance typing in android in terminal opens sdk. What's the catch here? have been sitting for 2 hours on this one.

**Comment by mfonville** [comment]
Make sure the SDK tools like aapt are in your path (the environment variable)

**Comment by Nikki1993** [comment]
Roger that, will copy it there as I can't seem to fix it anyway, path is right, or so it seems.

**Comment by mfonville** [comment]
If you run 'which aapt' you can check with one it finds.  Maybe you have an outdated from the os in the primary path?
