### ISSUE TITLE
6.0 Not Booting

### ISSUE THREAD

**Issue by AnimbusDev** [opengapps/opengapps#163]
Will not boot in 6.0, all of the other 6.0 Gapps are horrid, and my 5.1.1 backup failed 80% into restoring /data. Basically, my phone will be messed up until you fix this, then I will be able to use it properly again. Please fix this quickly

Device: Victara
Version: CM13

**Comment by bgiesing** [comment]
If you used the November 7th or 8th releases, they were broke. Try the
November 9th ones

On Sun, Nov 8, 2015, 9:44 PM AnimbusDev <notifications@github.com> wrote:

> Will not boot in 6.0, all of the other 6.0 Gapps are horrid, and my 5.1.1
> backup failed 80% into restoring /data. Basically, my phone will be messed
> up until you fix this, then I will be able to use it properly again. Please
> fix this quickly
>
> Device: Victara
> Version: CM13
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opengapps/opengapps/issues/163>.
>



To unsubscribe click: <http://email.giesing.cf/u/eJwljrtOw0AQRb_GLqPd8e6Mp9jCSYNEAQjhQBXNvhzjmCDHBuXvscwtTnV1dKJDlABl7w7N43Klob2_64_59DT2-5fXRPQz9Obrs26753a50e14ao4s00MBexjefgujRukvu25juI7l2dkgqmJMOftojZANPnv0XhGCYMZyclP6vtxXhVJUEwsZXdkI6485JbGQVRZvk45sIKZKkLJnxIohZPU_rcFSrIUYRCOHpDBhUNauSZt-1_XzefFb1OwKaP4As3JG8Q>

**Comment by AnimbusDev** [comment]
@bgiesing when will that be available?

**Comment by bgiesing** [comment]
It already is

On Mon, Nov 9, 2015, 3:15 AM AnimbusDev <notifications@github.com> wrote:

> @bgiesing <https://github.com/bgiesing> when will that be available?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opengapps/opengapps/issues/163#issuecomment-155003671>
> .
>



To unsubscribe click: <http://email.giesing.cf/u/eJwljstqwzAQAL_GPob1ytqVDjo4oVAScqhLml6llWQL54WJafv3Le4c5jhMdEResC5u1x2WO0-f532fbu9vL9207b_2p3Qqcz-Vs8SwjEdv4LUfpXzMx-_HULVw9eWyGVbL_VqPzgMpm3LLwaikgxaM1jBCtt4H1qqe3Zwel58KtwBs2HoWEOIs0XKE7Kkx3oTQJkRhIBIh1WhrWmVRMvzTNKgNksoWfUNWElAiAa3_ltb8ZijPcQnr1NNV2P0CI2FFrA>

**Comment by AnimbusDev** [comment]
@bgiesing https://goo.gl/photos/cxqDzVnwpKPPJaSc7
Where?

**Comment by AnimbusDev** [comment]
@bgiesing That comment came off pretty harsh, I apologize.

Is there an alternative downloads site I don't know about or is it just not pushed to the site yet?

**Comment by mfonville** [comment]
November 9 is only build for arm64, because there were no packages updated for arm and x86.
I can make a manual build for arm and x86 pico.

**Comment by mfonville** [comment]
Check out: https://www.androidfilehost.com/?w=files&flid=41081

**Comment by AnimbusDev** [comment]
@mfonville Can you release Auroma, super, or stock? I like opengapps because of the options

**Comment by AnimbusDev** [comment]
@mfonville
I figured out what file needs to be deleted to fix the system. So no need to build the more intense packages if you don't want to

**Comment by mfonville** [comment]
@AnimbusDev No, you'll have to wait for the buildbot for those. I don't have the upload capacity from my own computer to make those available.

I did get btw already the feedback that the last patch works for CM, so we close this bug.

Also, please for such 'support' request instead use XDA, that is more appropiate than directly filing an issue. Also, if you are dependent on your phone I'd also suggest you to stay clear of Marshmallow for some time. Also Stock & Super are 'broken' at the moment, since we included Google Dialer, but it doesn't work yet.

**Comment by AnimbusDev** [comment]
@mfonville I use the aroma package so I just excluded Google Dialer
