### ISSUE TITLE
Advanced app usage wiki clarification

### ISSUE THREAD

**Issue by jawz101** [opengapps/opengapps#164]
At the bottom of the Advanced Options page the wiki says that new lines don't matter.
Earlier it mentions #comments are ignored.

You can't have it both ways.
If I comment out a package name on a line that tells me the script comments

**Comment by jawz101** [comment]
I meant to say that ignores comments are still processed if you use the name of a package inside a comment

**Comment by mfonville** [comment]
I think you did not understand what the writer meant with "seperate lines", it does not state that the newline character is ignored. I will make it more clear that it does mean empty lines.
