### ISSUE TITLE
Setup Wizard FC

### ISSUE THREAD

**Issue by USBhost** [opengapps/opengapps#165]
arm64
Pico Package
nexus 9
android 6

http://pastebin.com/yzUJdsFb

11-14 23:58:06.340   168   623 D audio_hw_primary: out_set_parameters: enter: usecase(0: playback) kvpairs: routing=2 out->devices(2) adev->mode(0)
11-14 23:58:06.342  2586  2586 I Process : Sending signal. PID: 2586 SIG: 9
--------- beginning of system
11-14 23:58:06.392   652  1659 I StatusBarManagerService: binder died for pkg=com.google.android.setupwizard
11-14 23:58:06.393  1266  1266 D PhoneStatusBar: disable: < expand* icons alerts* system_info back home* recent* clock* search* quick_settings >
11-14 23:58:06.397   652  1157 I ActivityManager: Process com.google.android.setupwizard (pid 2586) has died
11-14 23:58:06.410   652  1157 I ActivityManager: Start proc 2621:com.google.android.setupwizard/u0a11 for activity com.google.android.setupwizard/.SetupWizardActivity
11-14 23:58:06.412  1266  1266 D PhoneStatusBar: heads up is enabled
11-14 23:58:06.455   652   681 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
11-14 23:58:06.462  2621  2621 W System  : ClassLoader referenced unknown path: /system/priv-app/SetupWizard/lib/arm64
11-14 23:58:06.515  2621  2621 I SetupWizard.SetupWizardActivity: DEVICE_PROVISIONED=false USER_SETUP_COMPLETE=false
11-14 23:58:06.519  1266  1266 D PhoneStatusBar: disable: < EXPAND* icons ALERTS* system_info back HOME* RECENT* CLOCK* SEARCH* quick_settings >
11-14 23:58:06.521  1266  1266 D PhoneStatusBar: heads up is disabled
11-14 23:58:06.521  1266  1266 D PhoneStatusBar: dismissing any existing heads up notification on disable event
11-14 23:58:06.527   652  1230 I ActivityManager: START u0 {act=com.android.wizard.LOAD flg=0x10000000 cmp=com.google.android.setupwizard/.WizardManager (has extras)} from uid 10011 on display 0
11-14 23:58:06.541  2621  2621 I SetupWizard.LoggingHelper: Connected to Google Play Services.
11-14 23:58:06.548   652   672 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
11-14 23:58:06.548  2621  2621 I SetupWizard.WizardManager: sendAction action=WizardAction (id=welcome uri=intent:#Intent;action=com.android.setupwizard.WELCOME;end transitions={} default: carrier_setup)
11-14 23:58:06.549   652  1234 I ActivityManager: START u0 {act=com.android.setupwizard.WELCOME flg=0x4000000 cmp=com.google.android.setupwizard/.Welcome (has extras)} from uid 10011 on display 0
11-14 23:58:06.559  1609  1630 I FactoryReset: [FactoryResetProtectionManager] No Factory Reset Protection challenges are present.
11-14 23:58:06.605  2621  2621 D AndroidRuntime: Shutting down VM
--------- beginning of crash
11-14 23:58:06.605  2621  2621 E AndroidRuntime: FATAL EXCEPTION: main
11-14 23:58:06.605  2621  2621 E AndroidRuntime: Process: com.google.android.setupwizard, PID: 2621
11-14 23:58:06.605  2621  2621 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.setupwizard/com.google.android.setupwizard.user.WelcomeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.android.setupwizard.accessibility.AccessibilityGestureHelper.isAccessibilityEnabled()' on a null object reference
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.android.setupwizard.accessibility.AccessibilityGestureHelper.isAccessibilityEnabled()' on a null object reference
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at com.google.android.setupwizard.user.WelcomeActivity.updateAvailableLocales(WelcomeActivity.java:604)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at com.google.android.setupwizard.user.WelcomeActivity.-wrap4(WelcomeActivity.java)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at com.google.android.setupwizard.user.WelcomeActivity$6.onInit(WelcomeActivity.java:220)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at com.google.android.setupwizard.accessibility.AccessibilityGestureHelper$2.onInit(AccessibilityGestureHelper.java:401)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:814)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at android.speech.tts.TextToSpeech.initTts(TextToSpeech.java:792)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:723)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:702)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:686)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at com.google.android.setupwizard.accessibility.AccessibilityGestureHelper.<init>(AccessibilityGestureHelper.java:93)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at com.google.android.setupwizard.user.WelcomeActivity.onCreate(WelcomeActivity.java:257)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6237)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
11-14 23:58:06.605  2621  2621 E AndroidRuntime: 	... 9 more
11-14 23:58:06.607   652   673 W ActivityManager:   Force finishing activity com.google.android.setupwizard/.Welcome
11-14 23:58:06.636   652   922 I OpenGLRenderer: Initialized EGL, version 1.4
11-14 23:58:07.110   652   675 W ActivityManager: Activity pause timeout for ActivityRecord{b869295 u0 com.google.android.setupwizard/.Welcome t21 f}

**Comment by mfonville** [comment]
Marshmallow ROMs needs the permission patc described in the wiki. Without the patch setupwizard will FC.

**Comment by USBhost** [comment]
I could've sworn pure nexus has that patch

**Comment by mfonville** [comment]
Could you then try with a larger package that also contains googleTTS (and report back)?

**Comment by USBhost** [comment]
Will do
Which one has it?

**Comment by mfonville** [comment]
Micro and up

**Comment by USBhost** [comment]
going to test now

**Comment by USBhost** [comment]
@mfonville 
update Micro worked!!! googleTTS is needed for Setup Wizard now

**Comment by mfonville** [comment]
We had before no feedback of structural problems for flashing it without GoogleTTS, though there were some indications that for some reasons some ROMs did seem to demand it.

To prevent any trouble I now added it to the core set of apps on 6.0.

**Comment by skychan** [comment]
@mfonville 
Have seen the _Notes for Android 6.0_, I just wonder how to patch the ROM (for me, I use CM13 Nightly), could you please add it on the Note? After flash CM ROM, then Open Gapps (6.0 arm pico) without boot, my cellphone crushed, the toast says the Setup Wizard Stopped.

**Comment by mfonville** [comment]
@skychan 
The ROM dev needs to apply the patch. For some reason latest CM13 nightlies *always* give the setupwizard problems (where before they didn't). We are still figuring out why. Temporary workaround is to remove SetupWizard from the Core folder in the opengapps package, or to remove thet SetupWizard from /system/priv-app after installation using the TWRP file manager.

**Comment by mfonville** [comment]
@skychan you did remove the wiki page (!)
I restored it now, but you hit a wrong button there...

**Comment by skychan** [comment]
@mfonville sorry for that, it might be an accidentally click, very very sorry

**Comment by klausenbusk** [comment]
Pretty annoying
```
02-06 20:44:33.470 31658 31658 E AndroidRuntime: FATAL EXCEPTION: main
02-06 20:44:33.470 31658 31658 E AndroidRuntime: Process: com.google.android.setupwizard, PID: 31658
02-06 20:44:33.470 31658 31658 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.google.android.setupwizard.SetupWizardApplication: java.lang.SecurityException: addOnSubscriptionsChangedListener: Neither user 10008 nor current process has android.permission.READ_PHONE_STATE.
02-06 20:44:33.470 31658 31658 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4759)
02-06 20:44:33.470 31658 31658 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
02-06 20:44:33.470 31658 31658 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
02-06 20:44:33.470 31658 31658 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-06 20:44:33.470 31658 31658 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
02-06 20:44:33.470 31658 31658 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5466)
02-06 20:44:33.470 31658 31658 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-06 20:44:33.470 31658 31658 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-06 20:44:33.470 31658 31658 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-06 20:44:33.470 31658 31658 E AndroidRuntime: Caused by: java.lang.SecurityException: addOnSubscriptionsChangedListener: Neither user 10008 nor current process has android.permission.READ_PHONE_STATE.
02-06 20:44:33.470 31658 31658 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1620)
02-06 20:44:33.470 31658 31658 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1573)
02-06 20:44:33.470 31658 31658 E AndroidRuntime: 	at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.addOnSubscriptionsChangedListener(ITelephonyRegistry.java:500)
02-06 20:44:33.470 31658 31658 E AndroidRuntime: 	at android.telephony.SubscriptionManager.addOnSubscriptionsChangedListener(SubscriptionManager.java:465)
02-06 20:44:33.470 31658 31658 E AndroidRuntime: 	at com.google.android.setupwizard.carrier.PhoneMonitor.<init>(PhoneMonitor.java:509)
02-06 20:44:33.470 31658 31658 E AndroidRuntime: 	at com.google.android.setupwizard.carrier.PhoneMonitor.initInstance(PhoneMonitor.java:70)
02-06 20:44:33.470 31658 31658 E AndroidRuntime: 	at com.google.android.setupwizard.SetupWizardApplication.onCreate(SetupWizardApplication.java:27)
02-06 20:44:33.470 31658 31658 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
02-06 20:44:33.470 31658 31658 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4756)
02-06 20:44:33.470 31658 31658 E AndroidRuntime: 	... 8 more
```

**Comment by mfonville** [comment]
@klausenbusk CM currently refuses to accept the patch to grant setupwizard the proper rights;
I am still looking into a fix that can be deployed from recovery instead of patching the ROM, but it is hard and needs time.

**Comment by klausenbusk** [comment]
> @klausenbusk CM currently refuses to accept the patch to grant setupwizard the proper rights;

link?



> I am still looking into a fix that can be deployed from recovery instead of patching the ROM, but it is hard and needs time.

Can't we just add a script to /system/etc/init.d/ like:
```
#!/system/bin/sh
pm grant com.google.android.setupwizard android.permission.READ_PHONE_STATE

mount -o rw, remount /system
rm /system/etc/init.d/100-permission-something
mount -o ro,remount /system
```
or wouldn't that work?

**Comment by mfonville** [comment]
@klausenbusk For the CM patch refused see:
http://review.cyanogenmod.org/#/c/116418/

Nope, init.d wasn't a solution, though I did not experiment myself with it.  @rapperskull did and I believe he concluded the init script did not have the proper permissions. (But I am not sure).

**Comment by USBhost** [comment]
@mfonville why does other gapps work without this patch?

**Comment by mfonville** [comment]
@USBhost they also need the patch; or they choose not to bundle Google's setupwizard.

**Comment by 4311021x** [comment]
Just for reference because this issue lead me into a blind alley searching for a solution. If the reason in the crash report of the force close is a SecurityException like this: 

```
com.google.android.setupwizard threw java.lang.SecurityException

java.lang.RuntimeException: Unable to create application com.google.android.setupwizard.SetupWizardApplication: java.lang.SecurityException: addOnSubscriptionsChangedListener: Neither user nor current process has android.permission.READ_PHONE_STATE.
```

Try a fresh install of CM13 (wipe cache and data) and directly install Open GApps without booting CM in between. Pico Open GApps are sufficient.
https://github.com/opengapps/opengapps/wiki/Notes-for-Android-6.0

**Comment by KreAch3R** [comment]
I think I found out why GoogleTTS seems to be necessary for some ROMs on marshmallow. It affects this issue here and this commit: https://github.com/opengapps/opengapps/commit/6b7ade0150b40c4298d3aa92a0943fa492f3ab1c

I think it's because of the **removal of AOSP TTS** from most ROMs. When I reverted it: https://github.com/krexus/build/commit/20ca963619afcb830fad2b2dbd100b59cc6b426b

Setupwizard worked correctly, and this is the obligatory gapps log: http://pastebin.com/6maunZ4a
It shows GoogleTTS as **not** installed.
I even used it on an earlier version of my ROM (where AOSP TTS was not included), and the FC came back,  so it confirms my hypothesis.

I thought you would like to know, and/or inform users and developers about it in the Wiki - even change default behavior? (that's a stretch for obvious reasons, N is around the corner).

**Comment by mfonville** [comment]
@KreAch3R thanks for your investigation. Based on your info I think our current defaults are sane/OK if many AOSP ROMs come without any TTS. Also GoogleTTS is clearly an improvement over PicoTTS, so if people choose to use GApps, using Google as TTS-provider should be ok (and can still be disabled using gapps-config). I will check where we would need to update the wiki.

**Comment by KreAch3R** [comment]
I agree @mfonville. What I think you should do is inform the users that if they choose to exclude GoogleTTS and they get SetupWizard FCs, it's a ROM problem and you (the OpenGApps) are not responsible for it. :smiley:
