### ISSUE TITLE
x86_64 builds not in daily build

### ISSUE THREAD

**Issue by l2dy** [opengapps/opengapps#167]
Website says x86_64 builds will be provided the very moment a compatible device will be released. What does it mean?

**Comment by mfonville** [comment]
There are no ROMs that are compiled for x86_64
As soon as there are, we will provide GApps packages for it.

(If you have spotted one, you can let us know here)

**Comment by l2dy** [comment]
Zenfone 2 has a x86_64 kernel. What does ROM mean?

**Comment by mfonville** [comment]
The whole ecosystem of the ROM needs to be x86_64, so kernel+(lower level) libraries.

Afaik the Zenfone 2 has an x86_64 CPU, but the ROM and kernel are x86. If you do find an x86_64 ROM (so the whole set described above) please let me know. I'd just have to pull a switch to start those builds (all the code is already there) :-)
