### ISSUE TITLE
Create automagic changelog/version report

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#17]
Since all package revisions are known to the script anyhow, we could automatically generate a log of which packages+versions where used for a build. This would be useful for tagging on GitHub and the OP on XDA.

**Comment by bgiesing** [comment]
Here's what I got so far... Doesn't pull in Submodule changes which is the hard part I may need help with. Any ideas @opengapps/general?

## Script
```shell
#!/bin/sh
lastdate=$(git show -s --format=%ad `git rev-list --tags --max-count=1`)
git log --pretty=format:"- %s%n%b" --since="$lastdate"
```

## Example Output from 2015-06-27
- Always install Google WebView with the fornexus package.

- More advanced features for report_sources including a small usage instruction

- small aesthetic changes to report_sources

- A new script introduced: report_sources.sh, that can print an overview of all current packages available in the sources-directories

- fix typo

- Move Webview to Stock-only

- Allow the building of a Stock package on x86 platforms

- Clarify structure of the buildtarget.sh a bit

- Prevented error on arm devices when finding Chrome libs

- Remove Chrome libs also from /system/lib64
(I don't see them in Nexus 9 factory image though).
- Allow to build (for now) x86 with mini as largest package (is the only one with complete set of packages)

```markdown
- Always install Google WebView with the fornexus package.

- More advanced features for report_sources including a small usage instruction

- small aesthetic changes to report_sources

- A new script introduced: report_sources.sh, that can print an overview of all current packages available in the sources-directories

- fix typo

- Move Webview to Stock-only

- Allow the building of a Stock package on x86 platforms

- Clarify structure of the buildtarget.sh a bit

- Prevented error on arm devices when finding Chrome libs

- Remove Chrome libs also from /system/lib64
(I don't see them in Nexus 9 factory image though).
- Allow to build (for now) x86 with mini as largest package (is the only one with complete set of packages)
```

**Comment by mfonville** [comment]
I was thinking less about the Git log, but more in the direction of e.g. the reports that are now created with https://github.com/opengapps/opengapps/blob/master/report_sources.sh

**Comment by bgiesing** [comment]
@mfonville Maybe combine the two? The reasoning for that is there is a lot more than just updated GApps as seen by my log above. So `end-users` could see what apps got updated and the more `tech-minded` people could see that + a log with the changes that may impact development like that very `report-sources.sh` script being introduced!

**Comment by mfonville** [comment]
Yes, we could do more technical reports too, just wondering how much it provides compared to the basic GitHub tools that most tech-savvy people already know about.
I just want to make the information that 'the system' already knows more easily available and readable.

Btw, I attached Twitter to our GitHub: https://twitter.com/opengapps

**Comment by mfonville** [comment]
In future stable releases I want to publish package-logs with the builds that use the output of e.g.:
```
./report_sources.sh arm-22 nohelp
```

**Comment by mfonville** [comment]
I have this done and staged for the next buildbot version.
