### ISSUE TITLE
opengapps arm-6.0 series error

### ISSUE THREAD

**Issue by akar1nchan** [opengapps/opengapps#172]
![](http://ww3.sinaimg.cn/mw1024/6d9bd6a5jw1eydim5xx3cj21jk1jkh7j.jpg)

ERROR Status 6
Installation aborted.

**Comment by mfonville** [comment]
https://github.com/opengapps/opengapps/wiki/FAQ#3-im-getting-a-status-error-6-when-i-try-and-install-these-gapps-with-cwm-what-can-i-do-to-fix-it

**PLEASE READ THE FAQ OR ASK ON Q&A ON XDA** instead of directly opening an issue...
