### ISSUE TITLE
Why remove calculatorgoogle, contactsgoogle and facedetect but can not select to install on aroma package (arm64 6.0)?

### ISSUE THREAD

**Issue by jat001** [opengapps/opengapps#174]

**Comment by mfonville** [comment]
I have no clue what you mean, neither does @raulx222 .

Could you try to rephrase your issue?

**Comment by jat001** [comment]
Sorry for my bad english.
I flashed opengapps on my nexus for upgrade stock apps and found google contacts missed after reboot.
So I found ```/system/app/CalculatorGoogle```, ```/system/priv-app/GoogleContacts```, ```/system/lib/libfilterpack_facedetect.so``` and ```/system/lib64/libfilterpack_facedetect.so``` were removed by ```gapps-remove.txt```. But the packages which are provide these files (```GApps/calculatorgoogle.tar.xz```, ```GApps/contactsgoogle.tar.xz``` and ```GApps/facedetect.tar.xz```) can not be selected to install because they are not in ```META-INF/com/google/android/aroma-config```.

**Comment by mfonville** [comment]
Ok, I understand now.

We will add contactsgoogle and calculatorgoogle to the aroma-config. They were indeed missing.

Facedetect is a Core-app though, and should have been installed automatically. Do you still have the debug log of this install?

**Comment by mfonville** [comment]
This should fix the issue: https://github.com/opengapps/opengapps/commit/2592b38e866cbf1194ec01092370db150a33359a
