### ISSUE TITLE
git clone issue 

### ISSUE THREAD

**Issue by c3ph3us** [opengapps/opengapps#176]
should be: 
git clone https://git@github.com/opengapps/opengapps.git

instead: 
git clone git@github.com:opengapps/opengapps.git

when u dont have ssh keys :) for repo

**Comment by mfonville** [comment]
The scripts and instructions are focused on users (and automated scripts) that also need to upload contribution to the repos, and therefore use ssh instead of https.

Also opengapps only runs on posix-environment, where people tend to have their ssh setup ;-)
