### ISSUE TITLE
More information about the packages

### ISSUE THREAD

**Issue by leoheck** [opengapps/opengapps#177]
Hi, you are making a very good work. Could you add this image or an information like in the image in the 
[opengapps.org](http://opengapps.org) page and in the README.md here in github? By the way, I found the image here in [XDA Forum](http://forum.xda-developers.com/paranoid-android/general/5-1-x-5-0-x-4-4-x-pa-gapps-mirror-t3069879)

![fsytjqq](https://cloud.githubusercontent.com/assets/1277920/11500693/df21db84-9815-11e5-921a-80c9184b7929.png)

**Comment by mfonville** [comment]
This image does not apply to Open GApps, it was for PA GApps, but our package contents differ.

We have a text-based version here: https://github.com/opengapps/opengapps/wiki/Package-Comparison
Also clicking each package on opengapps.org links to a wiki page with the contents of the package.

The README.md is focused on how to build Open GApps packages, not about the content of the prebuilt versions.

So AFAIK all information is available to users. I do not have the skills neither the resources to make a picture of it; especially as we do change the contents of the packages regularly.
So I'll close the bug. If you do want to make an updated image, to be distributed, you are welcome to do so and can upload it here ;-)

**Comment by leoheck** [comment]
Ok, thank you for the answer :) I will send you an image with the info you have in wiki!

**Comment by mfonville** [comment]
:-D looking forward to it!
