### ISSUE TITLE
libwebviewchromium.so should not be removed on lollipop

### ISSUE THREAD

**Issue by HardLight** [opengapps/opengapps#179]
CM and probably most custom roms include libwebviewchromium.so and WebView.apk. So removing lib breaks functionality of rom . Problem starts from https://github.com/opengapps/opengapps/commit/fec2ee4ae8a6569d1a16c7a24a0e8309b8f3e0f4 .

**Comment by mfonville** [comment]
Isn't it automatically excluded from removal by the installation script? Because that should be the case, if not there is a bug.
Could you attach your debug log?

**Comment by HardLight** [comment]
No it isn't excluded. I don't have that logs because they are overwritten. But in gapps-remove.txt from open_gapps-arm-5.1-pico-X.zip there are lines:
/system/lib/libwebviewchromium.so
/system/lib64/libwebviewchromium.so
and it's not supposed to be there, I think..?

I fixed it by:
diff --git a/scripts/inc.compatibility.sh b/scripts/inc.compatibility.sh
index 3385396..726bde7 100755
--- a/scripts/inc.compatibility.sh
+++ b/scripts/inc.compatibility.sh
@@ -235,7 +235,5 @@ lib64/$WebView_lib_filename
     gappsmicro="$gappsmicro
 googletts"
     webviewlibs="" # on non-Marshmallow the WebViewlibs should not be considered part of the Stock/AOSP WebView, since they are shared with the Google WebView
-    webviewgappsremove="lib/libwebviewchromium.so
-lib64/libwebviewchromium.so" #on non-Marshmallow the WebViewlibs are to be explictly included as a Google WebView file in gapps-remove.txt
   fi
 }

**Comment by mfonville** [comment]
The lines are supposed to be there, but are then removed/ignored during execution of the script.

**Comment by mfonville** [comment]
The lines are supposed to be there, but are then removed/ignored during execution of the script.

**Comment by HardLight** [comment]
Logs says:
  Remove Stock/AOSP WebView | false[default]
  ...
  Ignore Google WebView | true[NoRemove]

But see system files before and after: /system/lib/libwebviewchromium.so is missing..
[logs.zip](https://github.com/opengapps/opengapps/files/52165/logs.zip)

**Comment by mfonville** [comment]
You are completely right.

I hope that this will resolve the issue: https://github.com/opengapps/opengapps/commit/461106fb2527745de3c6178ff251794891932c28

Could you try again tomorrow on a clean ROM install when the new daily build would be up?

**Comment by mfonville** [comment]
And https://github.com/opengapps/opengapps/commit/2a025e7156e37a3cc629f786a8a7163edb76415a covers another scenario.

**Comment by HardLight** [comment]
Hi, tested with 20151205 - same issue..

**Comment by mfonville** [comment]
Did you test on a fully clean ROM? And could you please supply the full debug logs this time? I'd really want to have a look at e.g. the installer output.

**Comment by HardLight** [comment]
Yes clean install. Here are logs:
[open_gapps_debug_logs.tar.gz .txt](https://github.com/opengapps/opengapps/files/53106/open_gapps_debug_logs.tar.gz.txt)

**Comment by mfonville** [comment]
Thanks for the logs. For some reason Recovery_tmp.log seems to be missing from the logs, so I do not see the installer's script output.
The problem is still there indeed, because we can indeed see from the file lists that it does get removed.
I will have a look at it later again (at this very moment I have less time available, see xda) and will post any updates here.

I have an extra question to you @HardLight though, I see your device is 160dpi, and those are quite rare and is sometimes hard to get the APKs for those. Would you be interested in helping the Packagers team, that try to collect all these (rare versions of) APKs?

**Comment by davepwsmith** [comment]
Would that be the cause of this then? I'm getting force closes and reboots on CM12.1 (WileyfoxStorm/kipper) with arm64-pico 20151206

http://pastebin.com/HkgMyE5f

**Comment by HardLight** [comment]
@mfonville there is no Recovery_tmp.log in my *logs.tar.gz, should it be located elsewhere?
About APK's, yes I could assist. Contact me on xda or email for details.
Also good luck :)
@davepwsmith Yes it same issue, temporary workaround is to remove
/system/lib/libwebviewchromium.so
/system/lib64/libwebviewchromium.so
from gapps-remove.txt.

**Comment by davepwsmith** [comment]
OK, well for those who don't want to muck about with the zips, a temporary work-around is to use the aroma installer (I know, a much, much bigger file, but whatever) and select Android Webview as the only component to install. Not quite the same as Pico, but at least you can get past the setup wizard!

**Comment by mikhaelkh** [comment]
After I installed latest CyanogenMod 12.1 hammerheadcaf (Nexus 5 CAF) with OpenGApps nano-20151206, some app started to crash (for example, HTML5 Viewer), then I installed Google WebView and crashes  disappear.

**Comment by mfonville** [comment]
@HardLight could you try this new build with the latest fix: https://www.dropbox.com/s/iqpn8hdgfwgnxad/open_gapps-arm-5.1-pico-20151208.zip?dl=0

Also, very happy you want to be a packager. Is your XDA nick the same as on GitHub?

**Comment by HardLight** [comment]
Ok I'll try it when have some free time.
Yes it's same.

**Comment by mfonville** [comment]
I got confirmation that the bug is solved now, so I close the bugreport. Please let me know if problems appear.
