### ISSUE TITLE
device dpi processing of build.prop (and other prop files) should be limited to 1 line only

### ISSUE THREAD

**Issue by Schischu** [opengapps/opengapps#182]
Hi,

I am providing a clean AOSP Marshmallow build for the Samsung Tab S and Samsung Note 10.1 (2014).

My 6.0 ROMs had always problems with the SetupWizard after installing OpenGapps, 
so yesterday I dug a little around to find the cause of the issue.

The cause is that the OpenGApps installer tries to determine the dpi value by asking recovery about it.
However our twrp recovery builds have not set the "ro.sf.lcd_density" value so PrebuildCoreGms was not installed at all which caused the issue.

Does it really make sense to ask recovery about the dpi?
Shouldn't it be by reading /system/build.prop instead of using getprop?

**Comment by Schischu** [comment]
Hm, the update-binary script already checks build.prop if getprop does not return anything.
I think I will have to add a little debug about why this does not work for me.

**Comment by mfonville** [comment]
To prevent SetupWizard FCs you need the patch mentioned here: https://github.com/opengapps/opengapps/wiki/Notes-for-Android-6.0

The SetupWizard OpenGApps install does not differ per dpi. If PrebuiltCoreGMS was not installed we would need the debug logs to investigate.

**Comment by Schischu** [comment]
Patch is applied. I've just tried again and uploaded you the logs

[open_gapps_log.txt](https://github.com/opengapps/opengapps/files/53195/open_gapps_log.txt)
[open_gapps_debug_logs.zip](https://github.com/opengapps/opengapps/files/53196/open_gapps_debug_logs.zip)

**Comment by Schischu** [comment]
Pfff, found the issue. 
ro.sf.lcd_density was defined two times in build.prop, so file_getprop returned
"320
320"
Which did not match the allowed densities.

So I can fix this issue on the ROM side be removing the second ro.sf.lcd_density entry.

-> Issue can be closed.

**Comment by mfonville** [comment]
Did you manually changed the build.prop that it was like that, or was it defined twice by the ROM?

**Comment by Schischu** [comment]
Twice by the ROM, it was listed in system.prop and also in device.mk.  :-(

**Comment by mfonville** [comment]
I will add some robustness to the processing then.

**Comment by mfonville** [comment]
After reviewing the .prop specifications and getprop function I have re-considered this.
Clearly the uniqueness of lines in the prop-file is a responsibility of the prop editing tool and the fetching of a correct value is getprop's responsibility.
So I won't implement this feature.
