### ISSUE TITLE
Stock 5.1 ARM zip does not open

### ISSUE THREAD

**Issue by fossum** [opengapps/opengapps#183]
I tried to install the stock ARM 5.1 gapps today and noticed they failed. I then tried to open them in Windows and Linux and neither worked.

**Comment by mfonville** [comment]
You really have to describe your problem better, because I have no clue what you try to do and what your error is.
If the ZIP in general fails to open, you probably have to check if your download isn't corrupted.

**Comment by devurandom** [comment]
I downloaded the nano version for arm from 2015-12-13 and tried to flash it. The CyanogenMod recovery refuses to do so, stating a signature verification error as the reason.
However, the file can be opened with ZArchiver on my phone. So either the file itself is healthy, the zip-internal CRC sums are correct (and just the recovery checksum is wrong), or ZArchiver does no checks at all.

**Comment by mfonville** [comment]
We introduced a custom signature with the 13 Dec build. I am aware of the problem it posed on some recoveries and have already a fix ready. So the next build will be OK again.

I'd suggest to use the 12 dec build for now.

**Comment by devurandom** [comment]
> We introduced a custom signature with the 13 Dec build. I am aware of the problem it posed on some recoveries and have already a fix ready. So the next build will be OK again.

I confirm: The 2015-12-18 build works.

**Comment by mfonville** [comment]
Thanks for the feedback.
