### ISSUE TITLE
Aroma installer freezes

### ISSUE THREAD

**Issue by xingrz** [opengapps/opengapps#186]
Device: OnePlus 1 (bacon)

It stops at the copyright line.

Tested freezes at these version of TWRP: 2.8.7.0, 2.8.6.1
Tested works at this version of TWRP: 2.8.4.0

I know aroma installer doesn't work for any version of TWRP, so I wrote this issue to provide information to who finding a working version of TWRP.

**Comment by mfonville** [comment]
I added it to the wiki, that is a better place than again so the many-th bug report about AROMA that we cannot unfortunately not fix ourselves.
See: https://github.com/opengapps/opengapps/wiki/Aroma-Package
If you want, you can extend/improve the page with more findings.
