### ISSUE TITLE
BlackHole live wallpaper is not removed via gapps-config

### ISSUE THREAD

**Issue by GermanKiwi** [opengapps/opengapps#188]
I"m using a gapps-config.txt file to remove apps that I don't want to have. I've included the `LiveWallpapers` keyword, which does successfully remove all of my live wallpapers, with the exception of the BlackHole live wallpaper (which I believe is included with CyanogenMod).

The path to this wallpaper app is:
/system/app/Galaxy4/Galaxy4.apk

Could you please include it in the `LiveWallpapers` keyword, or alternatively create a new keyword for removing it?

**Comment by mfonville** [comment]
It is already there with the ``Galaxy`` keyword. I will update the wiki to also describe it is also known as BlackHole.

**Comment by GermanKiwi** [comment]
Thanks for that!
