### ISSUE TITLE
Google Keyboard (AOSP) is not removed via gapps-config

### ISSUE THREAD

**Issue by GermanKiwi** [opengapps/opengapps#189]
I"m using a gapps-config.txt file to remove apps that I don't want to have. I've included the `KeyboardStock` keyword, but it does not remove the stock Google Keyboard app which is included with CM12.1 on my phone.

The path to this keyboard app on my phone is:
/system/app/LatinIME/LatinIME.apk

Could you please include it in the `KeyboardStock` keyword, so that it gets correctly removed?

**Comment by mfonville** [comment]
If you use ``KeyboardStock`` app/LatinIME/ is correctly removed.
The installer just won't let you have not NO keyboard installed, unless you specify ``override`` too.
Please check the documentation for details, and use XDA for questions like this instead of directly filing an issue.
