### ISSUE TITLE
Random Reboots on arm64 pico

### ISSUE THREAD

**Issue by davepwsmith** [opengapps/opengapps#194]
I don't get them without gapps installed (but then that doesn't mean that gapps causes them). Very difficult to pull any info, logcat below but shows no fatal error:
[reboot.txt](https://github.com/opengapps/opengapps/files/58577/reboot.txt)

**Comment by davepwsmith** [comment]
Sorry: 

Wileyfox Storm
Cyanogenmod 12.1

**Comment by devurandom** [comment]
I have the same issue. Open GApps nano version for arm from 2015-11-29. CyanogenMod 12.1 20151117-snapshot-yog7dao1k3-serranoltexx.

**Comment by mfonville** [comment]
@davepwsmith this is hard one to debug and unfortunately the log doesn't give us any useful information, but personally I would expect some kind of conflict between one of the core gapps and the ROM.

Could you try to clean flash your ROM (so wipe /data/ too) and then OpenGApps pico, so that we start with a minimal set of applications to see if those trigger the reboots?

**Comment by davepwsmith** [comment]
I have already tried the recommended full wipe procedures - including fastboot format system && fastboot format userdata. Any installation with CM12.1 and OpenGapps Pico crashes randomly at any point. With a few apps installed, Maps/Navigation of any kind (including Nokia Here) but Google Maps in particular seems to be the thing which most upsets everything, but there really is no repeatable case. It will often reboot in my pocket, when sitting on the table with the screen off, etc. etc. 

To be honest, this has been such a pain that I've gone back to the stock CyanogenOS rom which comes with Gapps bundled, and just disabled all of the bits I don't want, but I would much prefer to not have this footprint on my phone at all.

Many thanks,

D

**Comment by mfonville** [comment]
@davepwsmith ok, pity that you experience these issues.
Still my strong suspicion is that something within the ROM is probably broken, and the apps and google services installed trigget it somehow.
At least I suspect it is not something we are able to fix from our side.

**Comment by davepwsmith** [comment]
If I have a little time over Christmas I wil attempt to get on top of this. I suspect that the way to get started will be to install gradually increasing packages (pico, nano, micro, mini, full, stock) until the crashes stop. I know that there are people with this phone who have no issues whatsoever, so I suspect that it has to do with some google *xyz* which something is expecting to be there but not finding. Problem is that it's very hard to test that hypothesis without the play store and services installed, which is where all the problems start!

I'll return to this thread when I have more news.

Many thanks for your efforts, and I hope I can be of more help in the next few weeks.

**Comment by mfonville** [comment]
OK great. Instead of play store you could sideload maybe those APKs, but indeed they might expect the play services to be available.
