### ISSUE TITLE
Add Google Dialer to stock and super package

### ISSUE THREAD

**Issue by kasei-wang** [opengapps/opengapps#197]
Those apps have been added to play store.

**Comment by mfonville** [comment]
Contacts is already in the package. Dialer is still under review, because it does not work for everyone.

**Comment by kasei-wang** [comment]
OK, Thank you :)

**Comment by JRoot3D** [comment]
Add Dialer to AROMA package for user choice

**Comment by mfonville** [comment]
I will look into whether this would be possible.
It will need some adjustments of the scripts (e.g. at the moment when adding an app to a package, it is selected by default for installation).
Also I would to like to add some "protection from stupidity" mechanism to it, that will only allow installation on Nexus devices.

I will work on it after the holidays.

**Comment by TeMochkiN** [comment]
How long will the dialer is under review?

**Comment by mfonville** [comment]
Dialer still has known problems on many devices; I have a lot of more higher priority bugs to work on atm, so please have patience. It will come in the future.

**Comment by nvenasquez** [comment]
Hope that Google Dialer will be added in the future and work properly on Oppo Find 7a --> Nameless ROM 3.0/6.0.1

**Comment by LorneCash** [comment]
I'm running CM13 on an LG G3 VS985.  I downloaded the Dialer app from the Play Store and it seems to work fine.  I have a VS985 as my daily driver and also another one as a test device so if you want me to do some testing on this lmk.

**Comment by mfonville** [comment]
I added GoogleDialer for future builds, but it is configured as an optional "extra". So not with the normal Include/Exclude behaviour, but only as an "Include".

**Comment by shashankshirke** [comment]
Hi, I installed the latest Stock version but still tyhe AOSP dialer shows up instead of the stock Google dialer. I checked the Stock wiki page and it says "Google Dialer (replaces stock/AOSP Dialer)".

Please let me know how to get this working.

**Comment by mfonville** [comment]
@shashankshirke Currently the dialer is experimental only, and as such needs a keyword to be activated with the gapps-config keyword `DialerGoogle` (see https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options#include-and-exclude-google-applications )
