### ISSUE TITLE
Installation on marshmallow CM Recovery will always fail

### ISSUE THREAD

**Issue by AdFad666** [opengapps/opengapps#199]
Error: Status 255 is caused by toybox; `/sbin/ash` does not exist - the updater script cannot execute!

**Comment by mfonville** [comment]
Hmm, we *do* use (d)ash functionality and note pure sh.
Could you check if replacing ```/sbin/ash``` with ```/sbin/sh``` whether the install script still works? Because I suspect it silently uses mksh as interpreter instead.
