### ISSUE TITLE
Script solution for Marshmallow permissions

### ISSUE THREAD

**Issue by dim0x69** [opengapps/opengapps#200]
This problem came up as is updated my LG G3 (d855) to the latest Cyanogenmod 13 Nightly( 20151222) (from 12.1).

"play services" (and "system") crashed with the following exception:

12-22 20:23:41.267  5619  5860 E AndroidRuntime: Process: com.google.android.gms.persistent, PID: 5619
12-22 20:23:41.267  5619  5860 E AndroidRuntime: java.lang.SecurityException: "passive" location provider requires ACCESS_FINE_LOCATION permission.
[stack trace]

after i granted the needed permission to GMS "pm grant com.google.android.gms android.permission.ACCESS_FINE_LOCATION" everything worked as expected.

I hope this is the right place to address this issue.

Thank you!

**Comment by mfonville** [comment]
@TheCrazyLex could you check what is the situation here? Is there a new permission from either ROM or GMS's side?

**Comment by TheCrazyLex** [comment]
@mfonville this permission is required, this is normal and was always like that. However as Cm doesn't include my patch, things like that may happen on CM. 

This won't happen on ROMs including the patch. 


Alex

**Comment by mfonville** [comment]
Thanks for the explanation. I thought cm had the patch included, maybe we can request to upstream it somehow?

Also we are still looking into possible scripting solutions to handle the permissions for roms without the patch. But such a solution is not available yet for the near future.

**Comment by TheCrazyLex** [comment]
@mfonville I don't think upstreaming will work.

A script solution would be very nice..

Alex

**Comment by nixar** [comment]
@TheCrazyLex can you point to that patch? is there a clutch way to fix this at least temporarily with a root shell?

**Comment by polyzen** [comment]
This appears to also happen on [CopperheadOS](https://copperhead.co/android/) which is forked off of AOSP.

**Comment by maximu** [comment]
@TheCrazyLex  How run script with root access in init first time? because you patch not working for me user can't access grant.runtime.permissions .

**Comment by klausenbusk** [comment]
Not sure if this is related, but I get:
```
02-13 11:39:01.383 31298 31355 W ctxmgr  : [AclManager]checkPermissionTypeStatus: no inject permission for { uid=10061, packageName=com.google.android.gms }. Returned permission was: PACKAGE_NOT_WHITELISTED for context name=POWER_CONNECTION, account=account#-51794xxxx#
```
When trying to start Endomondo on CM nightly

**Comment by cunha17** [comment]
The issue still persists on last CM 13 Nightly (20160313) for i9300. The proposed procedure along with "pm grant com.google.android.gms android.permission.ACCESS_COARSE_LOCATION" fixed the issue.

**Comment by jkdf2** [comment]
Cyanogenmod now has a bug report for it: https://jira.cyanogenmod.org/browse/NIGHTLIES-2706

There is also a discussion of this on the XDA Q&A page for opengapps: http://forum.xda-developers.com/android/help/qa-gapps-android-5-1-5-0-4-4-t3124506/post66054618

**Comment by nezorflame** [comment]
@mfonville this should be closed now.
