### ISSUE TITLE
Installation wipes /tmp

### ISSUE THREAD

**Issue by polyzen** [opengapps/opengapps#201]
Apparently part of the installation wipes /tmp. This affects TWRP functionality, and requires one to reboot into TWRP eg. before flashing something else.

**Comment by mfonville** [comment]
I will look into this after the holidays
Could you maybe provide me (I might need it when solving this) which file(name)s are stored by TWRP in /tmp/ and should *not* be removed?

**Comment by polyzen** [comment]
Thank you. Will do.

**Comment by polyzen** [comment]
@mfonville, TWRP apparently only keeps its recovery.log there -- aside from whatever installers leave over.

Did a bit of testing with the installers I use. Aside from logging not working properly (though recovery.log does get recreated):
* superuser.zip from [seSuperuser](https://github.com/seSuperuser/Superuser)
  * no trouble installing
* ota update for https://copperhead.co/android/
  * gives [this error](https://ptpb.pw/5LUi.png)

Simply deleting the log doesn't cause the flashing issue.

**Comment by mfonville** [comment]
(Especially the larger packages of) OpenGApps manipulates the contents on /system/, are you sure that the OTA is not just failing because of the unexpected changes on /system/?

**Comment by polyzen** [comment]
If you reboot into TWRP after installing OpenGApps, the OTA doesn't give you any problem.

**Comment by mfonville** [comment]
Can it maybe be related to the mounting of unmounting of the partitions?

I am wondering if we somehow could compare a "before" and an "after" state within TWRP to find the exact cause :-/

**Comment by mfonville** [comment]
@polyzen could you check if this (6.0 pico) version succesfully skips the deletion of the recovery.log and whether it resolves the OTA problem? https://www.dropbox.com/s/rvnjhdoackwb44y/open_gapps-arm-6.0-pico-20160107.zip?dl=0

**Comment by polyzen** [comment]
> Can it maybe be related to the mounting of unmounting of the partitions?

> I am wondering if we somehow could compare a "before" and an "after" state within TWRP to find the exact cause :-/

/cache is mounted prior to the GApps install. Mounting it again allows me to flash the OTA. Not sure what else needs /cache; flashing OTA after GApps isn't a normal thing :p.

Should a separate issue be opened for this?

> @polyzen could you check if this (6.0 pico) version succesfully skips the deletion of the recovery.log and whether it resolves the OTA problem? https://www.dropbox.com/s/rvnjhdoackwb44y/open_gapps-arm-6.0-pico-20160107.zip?dl=0

The logfile remains and logging works properly. :)

**Comment by mfonville** [comment]
Thanks for testing it. Then I will integrate at least the patch for the recovery file.
Meanwhile I will also look into a fix to not unmount partititions that were already mounted when starting the install.
