### ISSUE TITLE
Option for removal of AOSP Music App

### ISSUE THREAD

**Issue by legendtang** [opengapps/opengapps#203]
![image](https://cloud.githubusercontent.com/assets/1352729/12005286/f4cc38a0-abd7-11e5-9226-00a6a36f7680.png)

The AOSP Music App hasn't updated since Gingerbread, but the compilation of AOSP ROMs still brings back this App, which should be considered generally useless and be removed as default behavior as Nexus devices do not have this App too.

New option should be also implemented in the `gapps-config.txt`.

**Comment by mfonville** [comment]
Could you give me filesystem paths where this app resides?

**Comment by legendtang** [comment]
@mfonville Located at `/system/app/Music/Music.apk`
