### ISSUE TITLE
20151225-mini build - Hangouts works but no push/background notifications

### ISSUE THREAD

**Issue by jpgnz** [opengapps/opengapps#204]
Installed the following:

* cm-13.0-20151225-NIGHTLY-m8.zip
* open_gapps-arm-6.0-mini-20151225.zip

And separately (Because I thought it was a CM13 issue):

* cm-12.1-20151117-SNAPSHOT-YOG7DAO1K1-m8.zip
* open_gapps-arm-5.1-mini-20151225.zip

Both have the exact same issue. Hangouts will not sync while in the background. Works perfectly fine while open/in foreground, but no notifications are delivered when in background.

**Comment by jpgnz** [comment]
Ended up with Hangout notifications working by doing the following:

* cm-12.1-20151117-SNAPSHOT-YOG7DAO1K1-m8.zip
* [gapps-5.1-arm-2015-07-17-13-29.zip](https://github.com/cgapps/vendor_google/blob/builds/arm/gapps-5.1-arm-2015-07-17-13-29.zip)
* Immediately had to update the Google App (com.google.android.googlequicksearchbox 5.7.14.19.arm)
* Installed Hangouts from Play Store (com.google.android.talk 6.1.109448852)
* Had to update Google Play services for Hangouts to work (com.google.android.gms 8.4.89 (2428711-238))

Now works as previously/expected.

**Comment by mfonville** [comment]
I received news that notifications/sync issues are apparent in 6.0, probably because of Doze.
But it does not really explain why it then *does* work if installed from the Play Store, with the exact same versions.

Could you verify that the app permissions were correctly set after installation?
And try to get some logcats of the issue, that could point us in a direction.

**Comment by Jonatino** [comment]
Only happens in the mini build. Flashing stock hangouts works fine.

**Comment by jpgnz** [comment]
@Jonatino so open_gapps-arm-5.1-stock-YYYYMMDD.zip? I couldn't flash that at the time because it failed the storage checks.

@mfonville apologies for lack of updates, I no longer have the M8 in working order (dropped it one too many times) and replaced it with an N6, so can't replicate/provide more information.

**Comment by Jonatino** [comment]
@jpgnz I'm talking about the 6.0 marshmallow build. Sorry if I was unclear. open_gapps-arm-6.0-mini-20160122.zip specifically.

**Comment by jpgnz** [comment]
No that's my bad, I copy/pasted the wrong build zip. Thanks.

**Comment by Jonatino** [comment]
@jpgnz no problem, thanks for doing this for the android community, it's really awesome!

**Comment by jpgnz** [comment]
@mfonville is the one who deserves the credit, I'm just a user! :)

**Comment by mfonville** [comment]
More people are reporting this issue on XDA. Since it can't be a difference in the app itself, but probably how the ROM handles apps on /system/ and /data/ it something they should figure out and resolve. We can't do anything about it unfortunately.
