### ISSUE TITLE
Major Issue

### ISSUE THREAD

**Issue by AnimbusDev** [opengapps/opengapps#205]
So, Open-Gapps is broken.

I do not have a log because, well, the folder well the log is deposited is broken.

Very broken.

Here is my issue:
I cannot delete or write to /sdcard/Open-Gapps. Nothing can, even twrp cannot. I tried using chmod to make it 777, still doesn't work. rm -rf doesn't work, it says that the directory is empty. If I run ls -al it gives me this:

total 40
drwxrwx--x 2 root sdcard_rw 4096 2015-12-05 .
drwxrwx--x 27 root sdcard_rw 4096 2015-12-08 ..

That's it. I cannot delete those files. I cannot rename the folder, I cannot do anything. When I try to flash the gapps a "Please Wait" pop-up shows up and doesn't go away.

That's all. It just loads and loads and loads. Then it freezes and doesn't do anything. (Using aroma)

So please, either A) give us a backup secondary location just in case or B) Please help me fix this.

**Comment by mfonville** [comment]
Sounds like your filesystem/partition is broken, you probably will have to format it.
This is not an issue related to OpenGApps, for any support I refer you to the XDA forums, which are the appropiate place to find help before filing an issue in the bugtracker.

**Comment by AnimbusDev** [comment]
@mfonville I ended up wiping everything afterwards, but it only happened to the one folder

Guess cm was acting up again...
