### ISSUE TITLE
after start: <gapps app name> has ended [ok]

### ISSUE THREAD

**Issue by axaluss** [opengapps/opengapps#207]
Whenever i try to install gapps 5.1 with CM 12.1 or gapps 5 with cm 12  ARM on my LG d802 the gapps hangup all together with "<gapps app name> has stopped [OK]".
There is just a stack of those "OK" dialog windows and they reopen within seconds. 
The system is not usable.

**Comment by mfonville** [comment]
Please use XDA forum thread to get support for your issues. Also look at the intructions of the 1post there, a debug log + logcat of your errors are necessary for investigating your problem.
