### ISSUE TITLE
"Zip file is Corrupt" error when installing Gapps in Galaxy S3 (Cyanogenmod 13, Android 6.0)

### ISSUE THREAD

**Issue by brpaz** [opengapps/opengapps#209]
Hi.
I cant seem to be able to flash gapps in my Galaxy S3 (Cyanogen 13 Android 6.0 ROM). It allays say "Zip file is corrupt".

I trad re downloading gaaps multiple times and different versions (stock, mini etc) but I allays got the same error. If I try to extract the zip file on my PC it works fine.

Any Ideas what I am doing wrong?

**Comment by brpaz** [comment]
After formatting my SD card and try to download the gapps zip like 10 times, now it worked. Can close this issue.

**Comment by mfonville** [comment]
Happy it got resolved, but a hint for the feature: for support please first try XDA before directly filing an issue please.
