### ISSUE TITLE
Toybox: mount failed

### ISSUE THREAD

**Issue by dianlujitao** [opengapps/opengapps#210]
If we use toybox in TWRP instead of busybox, partitions such as /system won't get mounted.
If I run "mount /system" manually, it says:
mount: '/system' not in fstab
But busybox's mount works

busybox will be removed soon, so this should be something important

**Comment by mfonville** [comment]
I see toybox has not implemented yet the remount feature, which we used as a workaround for RastaROM that gave otherwise issues. Since RastaROM does not get updates anymore, we will return to normal mount behaviour, which should solve this.

**Comment by mfonville** [comment]
I references this issue by mistake from another commit.
But anyhow it *should* be fixed.

@dianlujitao could you check whether you still get an error from the (re)mount statements?

**Comment by dianlujitao** [comment]
Both works after https://gerrit.omnirom.org/#/c/16258/

**Comment by mfonville** [comment]
Thanks!
