### ISSUE TITLE
KitKat /data hack fixes

### ISSUE THREAD

**Issue by osm0sis** [opengapps/opengapps#212]
Just wanted to give a couple notes from a recent KitKat install I did.

1) The compatibility script needs ownership fixes for the files pushed to /data for lib compatibility issues on KitKat. The APKs (at least) should be system:system instead of root.root.

2) It could also use a rework to account for smart numbering. It should check /data/app/ for anything like e.g. com.google.android.package.name-*.apk and if it exists, replace it, if not, default to -1.apk so the Play Store is happy.

Thanks guys!

**Comment by mfonville** [comment]
Thanks for the feedback!

KitKat support was always a bit hackish, since I did do the primary development from the 5.1 codebase and only later was presented with the app-specific library conflicts on 4.4.

1. will be easy to implement.

2. Are you sure that the play store always adds -# to the end by default? I did only do a few tests on 4.4 (but quite some time ago and can't exactly remember) but I was not sure if a number was always added.

**Comment by mfonville** [comment]
PS: the -# scheming, which effect does it have on the app-lib folder? Does that also need the # in the pathname?

**Comment by osm0sis** [comment]
Yup, /data/app/com.google.android.package.name-#.apk and /data/app-lib/com.google.android.package.name-# match.

/data/app/com.google.android.package.name-#.apk are system:system ownership and 644 perms.

The libs are directly in /data/app-lib/com.google.android.package.name-#/ and are all system:system ownership and 755 perms.

Otherwise, hackish or not, the KitKat installation seems to have gone well. Only issue is a caveat regarding the newer Google Play services that creates a 100% wakelock if the ROM hasn't been updated to accommodate it (hard to say how many KitKat ROMs are still seeing updates). There is a workaround though, which involves force-starting the SystemUpdateService intent while leaving its receivers disabled..

**Comment by osm0sis** [comment]
Oh, and the Play Store definitely adds -# by default, so to be totally correct with a data install you should mirror that.

**Comment by mfonville** [comment]
@osm0sis I added some ugly greps that should now handle these paths. Would you be able to check whether it works correctly with a future build?

**Comment by osm0sis** [comment]
Sure! Instead of 
number="$(find /data/app/com.google.android.talk-*.apk | head -n1 | grep -o "\-[0-9]\+\.apk\$" | grep -o "[0-9]\+")"

Maybe
number="$(basename /data/app/com.google.android.talk-* .apk | rev | cut -d- -f1)"

would be simpler. basename used as shown removes the .apk and everything, and rev to get at the end of the line is a handy trick. :+1: 

Thanks!

**Comment by mfonville** [comment]
Good thinking :-)
I will use that instead!

**Comment by osm0sis** [comment]
- Installing updated GApps

Archive:  /data/media/open_gapps-arm-4.4-stock-20160108.zip
  inflating: Core/framework.tar.xz
unzip: zip flags 1 and 8 are not supported
tar: youtube/320: not found in archive
find: /tmp/youtube/320/: No such file or directory
cp: can't stat '/tmp/youtube/320/.': No such file or directory
Archive:  /data/media/open_gapps-arm-4.4-stock-20160108.zip
  inflating: Core/googlebackuptransport.tar.xz
unzip: zip flags 1 and 8 are not supported
tar: googlebackuptransport/common: not found in archive
find: /tmp/googlebackuptransport/common/: No such file or directory
cp: can't stat '/tmp/googlebackuptransport/common/.': No such file or directory
Archive:  /data/media/open_gapps-arm-4.4-stock-20160108.zip
  inflating: Core/googlecontactssync.tar.xz
unzip: zip flags 1 and 8 are not supported
tar: googlecontactssync/common: not found in archive
find: /tmp/googlecontactssync/common/: No such file or directory
cp: can't stat '/tmp/googlecontactssync/common/.': No such file or directory
Archive:  /data/media/open_gapps-arm-4.4-stock-20160108.zip
  inflating: Core/googlefeedback.tar.xz
unzip: zip flags 1 and 8 are not supported
tar: googlefeedback/common: not found in archive
find: /tmp/googlefeedback/common/: No such file or directory
cp: can't stat '/tmp/googlefeedback/common/.': No such file or directory
Archive:  /data/media/open_gapps-arm-4.4-stock-20160108.zip
  inflating: Core/googleonetimeinitializer.tar.xz
unzip: zip flags 1 and 8 are not supported
tar: googleonetimeinitializer/common: not found in archive
find: /tmp/googleonetimeinitializer/common/: No such file or directory
cp: can't stat '/tmp/googleonetimeinitializer/common/.': No such file or directory
Archive:  /data/media/open_gapps-arm-4.4-stock-20160108.zip
  inflating: Core/googlepartnersetup.tar.xz
unzip: zip flags 1 and 8 are not supported
tar: googlepartnersetup/common: not found in archive
find: /tmp/googlepartnersetup/common/: No such file or directory
cp: can't stat '/tmp/googlepartnersetup/common/.': No such file or directory
Archive:  /data/media/open_gapps-arm-4.4-stock-20160108.zip
  inflating: Core/gmscore.tar.xz
unzip: zip flags 1 and 8 are not supported
Archive:  /data/media/open_gapps-arm-4.4-stock-20160108.zip
  inflating: Core/gsfcore.tar.xz
unzip: zip flags 1 and 8 are not supported
tar: gsfcore/common: not found in archive
find: /tmp/gsfcore/common/: No such file or directory
cp: can't stat '/tmp/gsfcore/common/.': No such file or directory
Archive:  /data/media/open_gapps-arm-4.4-stock-20160108.zip
  inflating: Core/gsflogin.tar.xz
unzip: zip flags 1 and 8 are not supported
tar: gsflogin/common: not found in archive
find: /tmp/gsflogin/common/: No such file or directory
cp: can't stat '/tmp/gsflogin/common/.': No such file or directory
Archive:  /data/media/open_gapps-arm-4.4-stock-20160108.zip
  inflating: Core/setupwizard.tar.xz
unzip: zip flags 1 and 8 are not supported
tar: setupwizard/common: not found in archive
find: /tmp/setupwizard/common/: No such file or directory
cp: can't stat '/tmp/setupwizard/common/.': No such file or directory
Archive:  /data/media/open_gapps-arm-4.4-stock-20160108.zip
  inflating: Core/vending.tar.xz
unzip: zip flags 1 and 8 are not supported
tar: vending/common: not found in archive
find: /tmp/vending/common/: No such file or directory
cp: can't stat '/tmp/vending/common/.': No such file or directory
/tmp/updater: line 1295: syntax error: unexpected "fi" (expecting ")")
I:Legacy property environment disabled.
E:Error executing updater binary in zip '/data/media/open_gapps-arm-4.4-stock-20160108.zip'
Error flashing zip '/data/media/open_gapps-arm-4.4-stock-20160108.zip'

**Comment by mfonville** [comment]
I spotted the typo, I hope that it was the one that caused it and that it will be resolved with it.

**Comment by osm0sis** [comment]
Hmm. Still not fixed:

-rw-r--r-- system   system   17303106 2016-01-11 13:43 com.google.android.apps.photos-*.apk
-rw-r--r-- system   system   12235796 2016-01-11 13:43 com.google.android.youtube-*.apk

And it doesn't look like anything is getting copied to app-lib for either of those anymore.

**Comment by osm0sis** [comment]
Totally my mistake since basename doesn't care whether the file exists or not.

**Comment by osm0sis** [comment]
`number=$(basename `find /data/app/com.google.android.apps.photos-* | h
ead -n1` .apk | rev | cut -d- -f1)`
