### ISSUE TITLE
Improve usability of "OS" column in downloader menu

### ISSUE THREAD

**Issue by bnvk** [opengapps/opengapps#214]
I just made a n00b, mistake and ended up downloading the OpenGApps for Android 5.1 and then it wouldn't install on my freshly installed CyanogenMod 13 phone. Reason being CM13 is based on Android 6. Given that many users interested in OpenGApps are Cyanogenmod users and not Android users, it might make sense to do one of the following:

- Make the "Android" header in download menu toggleable between Android / Cyanogenmod 
- Show CyanogenMod version instead of Android versions

I think this would help with the usability of helping users download the correct zip file!

**Comment by Peshyy** [comment]
I don't understand? CyanogenMod is still Android. People that install CyanogenMod do have to know which version they're installing and which version of GApps they should install as well. The OpenGApps website is very well made and lists the download options in a very user-friendly way. Only those who are in a hurry or don't read/think that much might download the wrong GApps, but that has happened to me as well. Just download the proper ones and flash them.

**Comment by bnvk** [comment]
> I don't understand? CyanogenMod is still Android. 

Yes, it is, but the versioning is quite different. CM ? - 12 is Android 5.1 and CM 13 is Android 6. Users who are downloading GApps are using CM, yet the website says "Android Version #"

**Comment by Peshyy** [comment]
Well, yes. Because CyanogenMod is Android, but built for dozens of different devices and with added mods and stuff. It's still Android, CyanogenMod is not something standalone built from scratch.
CM 12 is Android 5.0, CM 13 is Android 6.0. That's how it is.

**Comment by bnvk** [comment]
@Peshyy yes, I understand that this is the case, *now* that I spent a few hours downloading incompatible ISOs. My point of this issue is to minimize that confusion for others who don't dig in an read / understand this relatively technical thing

**Comment by Peshyy** [comment]
Well if you don't read and understand what you're doing, you shouldn't be doing it in the first place. I don't want to judge or be rude, but this is very sensitive stuff and if someone flashes the wrong thing, and in the worst case it's something essential, they can break their device. That's why there's so much information and guides on rooting, flashing, etc.
Again, no need to rename anything.

**Comment by mfonville** [comment]
Hi,

thanks for your suggestion. CM users are only a minority of the public we serve, and in general CM communicates the Android versions their release has been based on quite well. Also the new users are via wiki.cyanogenmod.org/w/Google_Apps directly linked to the pre-selected Android version for each CM release.

Adding an mechanism to toggle e.g. dynamically CM vs Android is first of all not easily possible in the GetMDL toolkit we use for the website, and as such not trivial to implement, also imho it would probably confuse (a majority of) our users more than help them.

We could e.g. add something on the wiki page of each Android version to indicate which CM version does correspond. But in general people first find and download their ROM and only afterwards their GApps, so imho most effective policy would be to notify ROM developers on the possibilities of hotlinking and preselecting the preferred GApps version for their users using https://github.com/opengapps/opengapps/wiki/Hotlinking-to-OpenGApps.org

I hope you understand my reasons and point of view.
