### ISSUE TITLE
Support MicroG Apps

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#215]
http://forum.xda-developers.com/android/apps-games/app-microg-gmscore-floss-play-services-t3217616
https://github.com/microg/android_packages_apps_GmsCore
- Base a package around the MicroG services from the thread
- Install GsfProxy as core
- By default install/bundle the BlankStore
- If user chooses not to install BlankStore the FakeStore should be installed instead
- Only provide a Pico package by default
- Needs to include the proper license file for MicroG

**Comment by ibleedbinari** [comment]
Since this project is still alpha grade, the nightly builds are currently the most functional, and often times the only working  builds. Maybe they should be used rather than what is on the thread or add an option to install the nightly package instead.

Nightlies are auto-built after each commit (with a "Latest" download URL), so it shouldn't be hard to keep it up to date. They are hosted here: http://files.brnmod.rocks/apps/

**Comment by ibleedbinari** [comment]
Also, a common use case is to use microG to support the Google Play Store rather than using BlankStore as it supports IAP and many other features. There should probably be an option to choose between the BlankStore, Play Store, or no store (FakeStore)

**Comment by polyzen** [comment]
If I understand correctly, https://github.com/microg/JGooglePlay deprecates BlankStore. I've only just learned of these; very interesting.

**Comment by ibleedbinari** [comment]
@polyzen AFAIK neither project is being worked on right now. The first part of an open source Play Store was working Play Services, which is why GmsCore is being developed first. Regardless, BlankStore is the supported and working one of the two as JGooglePlay was never advanced to a working state.

**Comment by polyzen** [comment]
Ahha.. Thank you, @ibleedbinari. Eager to try BlankStore now.

**Comment by Nutomic** [comment]
Is there any new information on this? It would be great if we could install microG just by flashing a zip!

**Comment by mfonville** [comment]
This is a stretch goal, so it will take a while. But that is positive too, because microG is getting more mature in the meanwhile and fixing their issues with the more expert userbase.

**Comment by ale5000-git** [comment]
If someone need a flashable ZIP to easily install microG, it is [here](https://forum.xda-developers.com/showthread.php?t=3432360).

**Comment by zeorin** [comment]
In the short term, a non-stretch goal could be to add a way to individually exclude/include

* Google System Base,
* Google Play Store, and
* Google Android Shared Services

using `gapps-config`, like any of the other packages.

This would allow installation of e.g. just the Play Store, as MicroG users don't need the rest.

Another use case are MicroG users that don't want to even install the Play Store, but do want to install some libraries (e.g. swiping library).

IMO there's no need to bundle MicroG with OpenGAPPS, but to be compatible with it by providing these options would be nice.

**Comment by ale5000-git** [comment]
@zeorin: In my installer you can choose (live) between Google Play Store and FakeStore.
There will also be settings from file similar to gapps-config in the future.

**Comment by Zireael07** [comment]
@ale5000-git what installer is that?

**Comment by osm0sis** [comment]
Seems abandoned.
