### ISSUE TITLE
Google services crashing on Nexus 9 with CM13.

### ISSUE THREAD

**Issue by xelra** [opengapps/opengapps#218]
Hi, I installed OpenGApps on a completely wiped Nexus 9 with cm-13.0-20160109-NIGHTLY-flounder.

Unfortunately the Google Play services crash all the time.

I tried open_gapps-arm64-6.0-nano-20160109, open_gapps-arm64-6.0-pico-20160109 and open_gapps-arm64-6.0-stock-20160109.

**Comment by mfonville** [comment]
Please post your support request first to XDA Forum as instructed in https://github.com/opengapps/opengapps/wiki/FAQ#2-im-having-a-problem-with-my-open-gapps-install-what-information-do-you-need-to-help-me including your installation debug log(s) and a logcat of the force closures.

There we can investigate and help you with your problem.
