### ISSUE TITLE
Trusted Face has stopped

### ISSUE THREAD

**Issue by DJAlik** [opengapps/opengapps#22]
Just updated to the latest files and I am getting Unfortunately Trusted Face has stopped.

Samsung Galaxy S3 T-Mobile
CM12.1 nightly 6/11
OpenGapps 6/11 Stock personal built.

**Comment by mfonville** [comment]
This is a problem of the S3, which I also happen to own. I did use ADB today again, to verify, and it is the exact same bug as was reported in https://github.com/ArchiDroid/android_device_samsung_i9300/issues/109
