### ISSUE TITLE
Hangouts not getting installed to data (or at all) in KitKat install

### ISSUE THREAD

**Issue by osm0sis** [opengapps/opengapps#220]
/data/media/open_gapps-arm-4.4-stock-20160109.zip;
/data/media/.gapps-config:
```
NoDebug
SmallBuffer

# Exclusions
Books
Docs
Ears
Earth
Fitness
GooglePlus
Movies
NewsWidget
PlayGames
Sheets
Slides
Talkback
Wallet

# Stock Removals
CMFileManager
Galaxy
HoloSpiral
LiveWallpapers
NoiseField
Phasebeam
PhotoTable
PhotoPhase
Studio
VisualizationWallpapers

# Extra Removals
(MagicSmokeWallpapers)
(Music)
(Wallpapers)
```

But /data/app and /data/app-lib only contain Photos and YouTube.

**Comment by mfonville** [comment]
Could you check with the fix of https://github.com/opengapps/opengapps/commit/251d53827751938ac757a3e1534c21f5f685f7fc ?

**Comment by osm0sis** [comment]
Talk gets installed now. Good eye on the fix. I was worried it might be something more broad like Talk vs. Talkback. :+1:
