### ISSUE TITLE
Gapps for ARM / Android_6.0  with  cm-13.0-**-jfltexx.zip 

### ISSUE THREAD

**Issue by Tolmino** [opengapps/opengapps#222]
After wipe, i have mada a fresh installation of last (and i have tryied the last 3 version) of cm-13.0-**-jfltexx.zip 
after that installation i can start phone and use it .
but if i install gapps in different version (i have test with mini, micro and nano)
restarting phone i have a white windows that say that an error occured during starting of configuration program.

can i help you to debug in any way?

**Comment by Tolmino** [comment]
the device is a samsung GT-I9505

**Comment by Tolmino** [comment]
Same thing that morning with Gapps arm 6.0 mini 13 January 2016
and  cm-13.0-20160113-NIGHTLY-jfltexx.zip

always same error

**Comment by booldik** [comment]
Exactly the same thing is happening to me in a GT-I9300
As of now, I'm only using the phone, because I can't get any version of GAPPS to work with cm-13.0-20160116-NIGHTLY-i9300.zip
Any advice will be helpful.

**Comment by mfonville** [comment]
Could you please use the xda forum for support requests as described in the FAQ? There it will be more easy to provide support since the whole community can help.
Specific to your issue, please include a logcat so that the exact error can be seen.

**Comment by Tolmino** [comment]
booldik, now i know, after different flashing, that is surely a cyanogenmod issue, because for have a vorking image i have used crdroid. that image is based on cyanogenmod, but work perfectly. I'm non a xda forum user, and mfonville is in right.
So booldik, can you open a thread on xda forum for we all ? thanks in advance

**Comment by mfonville** [comment]
Don't open a thread, but just post to the OpenGApps thread :-)
There I will see it and follow up if necessary. But in general the community there can also help out and it helps in creating a common knowledge pool :-)
