### ISSUE TITLE
Should we drop "micro" as a package?

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#224]
Since 6.0-era, GoogleTTS has been added to the smaller packages, GMail has become a bit less popular because of Inbox.  System partitions are considerably larger and every device should be able fit Mini on their system if they would want to.

I would like to receive some opinions (and reasons) why we should or should not drop the "micro" package.

**Comment by Portaleus** [comment]
Google apps like Maps and Hangouts are not easy on battery, it is better to keep them as user app and use greenify to sleep them.

**Comment by mfonville** [comment]
@Portaleus I have no experience with greenify. But greenify can't sleep apps that are on /system/ I understand from your comment?

**Comment by Portaleus** [comment]
Yes, you cannot grenufy system app (there is a rooted experimental feature, but google apps are too deeply implemented in the system to be silenced).
I think this package is the best fit if you want minimal Google ecosystem.

**Comment by mfonville** [comment]
@Portaleus thanks for your feedback and insights!

**Comment by lapism** [comment]
Hi, I hope you are going to keep it. But I have a problem with those Micro/Pico/Nano packages. On my Nexus 4 it is showing STATUS 70. I did full wipe and still I have that error. Any solution?

**Comment by mfonville** [comment]
Based on the feedback, decision is not to drop the package at this moment.

**Comment by lapism** [comment]
Thanks. I am using it right now in my Nexus.
