### ISSUE TITLE
Cannot install pico on i93100 + CM13

### ISSUE THREAD

**Issue by EvaSDK** [opengapps/opengapps#225]
Hello,

I installed CM13 on my i9300 today using CM recovery. For some reason, I cannot install any of the opengapps packages from pico to stock even though I should have enough space for it according to FAQ:

```
$ adb shell df -h
Filesystem            Size  Used Avail Use% Mounted on
tmpfs                 414M   80K  414M   1% /dev
none                  414M  8.0K  414M   1% /sys/fs/cgroup
tmpfs                 414M     0  414M   0% /mnt
/dev/block/mmcblk0p9  1.4G  470M  1.0G  32% /system
/dev/block/mmcblk0p8  0.9G   18M  990M   2% /cache
/dev/block/mmcblk0p12  11G  695M   11G   6% /data
tmpfs                 414M     0  414M   0% /storage
/dev/fuse              11G  695M   11G   6% /storage/emulated
/dev/fuse              29G   16G   14G  54% /storage/8991-1F0C
```

I am loosing my head over this and it is 2AM, thanks for any help.

**Comment by mfonville** [comment]
Please post to the OpenGApps support thread at [XDA Forum](http://forum.xda-developers.com/showthread.php?t=3124506) and include your installation debug log. There the community can help out.

**Comment by EvaSDK** [comment]
Actually, I installed latest stable (CM11) recovery and it installed the stock package just fine, I guess it's a CM recovery bug then.

**Comment by mfonville** [comment]
CM Recovery still a problem yes, there is a beta version which you can try on the CM13 recovery: https://www.dropbox.com/s/ttw5f551gj15g0v/open_gapps-arm-6.0-pico-20160113.zip?dl=0
(I would really like to get feedback on it, so that it could be included in the normal packages too)

**Comment by acidicX** [comment]
@mfonville I've tried it right now on a Nexus 5 with a fresh CM13 flash as described in the FAQ for 6.0 on CM Recovery. Still "Insufficient storage space available in System partition". System is at 51% usage.

**Comment by mfonville** [comment]
@acidicX thanks for testing. Then I know I will have to find another solution for CM13
