### ISSUE TITLE
CMMusic vs CMEleven

### ISSUE THREAD

**Issue by jawz101** [opengapps/opengapps#226]
on the wiki both say they uninstall CyanogenMod Music player.

**Comment by mfonville** [comment]
Thank you for spotting that. I will merge them than into a single CMMusic keyword.

**Comment by jawz101** [comment]
Thanks.  It confused me for a sec.  I use that wiki page all the time :)
I'm thinking of just posting a sample config file that's all commented so it easier to reference.
