### ISSUE TITLE
Integrate @RapperSkull 's zip-calculations for GApps sizes

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#23]
Import the improvements @RapperSkull had in his PA GApps package e.g. the size calculations using zip list/info.

This because the script is becoming more dynamic/advanced anyhow, so it makes sense to also make this information now more dynamic.

**Comment by rapperskull** [comment]
Merged changes with the latest two commits. It should work.

**Comment by mfonville** [comment]
Great work :-)
