### ISSUE TITLE
Please don't remove GooglePinyinIME and QuickSearchBox in pico

### ISSUE THREAD

**Issue by wudimenghuan** [opengapps/opengapps#231]
Please don't remove GooglePinyinIME and QuickSearchBox.

pico don't have them. It made ota fail. (miui version android 6.0)

**Comment by wudimenghuan** [comment]
app/Provision is removed. But I don't know whether it's removed by opengapps

**Comment by mfonville** [comment]
See #213 for a comparable situation, and we will have to do in the future to solve it.
Concerning GooglePinyinIME: that *is* always a Google-app path, you need to make sure to download at least the super-package if you need that.

**Comment by wudimenghuan** [comment]
@mfonville How can I do? How to write the gapps-config file to prevent remove GooglePinyinIME?
I try to write "Pinyin" but not solve it.

**Comment by wudimenghuan** [comment]
@mfonville I download the super package and write a gapps-config

```
CalSync
PackageInstallerGoogle
DialerFramework
GoogleTTS
Pinyin
```

But it said "insufficient space". But why?

And I think this should working
```
PicoGApps 
Pinyin
```
I am trying.

**Comment by wudimenghuan** [comment]
@mfonville I added Include keyword and it's correct

```
Include
CalSync
PackageInstallerGoogle
DialerFramework
GoogleTTS
Pinyin
```

But why use this is wrong?
```
+Pinyin
```

**Comment by mfonville** [comment]
@wudimenghuan please use XDA Forum for support and issues with the pre-built packages.

Your config from https://github.com/opengapps/opengapps/issues/231#issuecomment-213789141 looks alright.

The + is only for a few select skips, it is not a generic option.

If you need more support, please use the XDA forum and don't forget to attach your debug logs.
