### ISSUE TITLE
Installation error in /sideload/package.zip (status 255)

### ISSUE THREAD

**Issue by abhay44** [opengapps/opengapps#236]
I installed cyangogenmod on my motorola moto g xt1033.When i try to install gapps through cm-recovery,I get the above error and 'Installation aborted'.what's wrong with this error.Can somebody help me?

**Comment by championswimmer** [comment]
It is an issue with toybox. 
(CM moved from busybox to toybox)

Should be merged with https://github.com/opengapps/opengapps/issues/211
