### ISSUE TITLE
Bypass stock camera

### ISSUE THREAD

**Issue by gericom-hummer** [opengapps/opengapps#237]
Will it be possible to make a choice for bypassing the stock camera, e.g. aosp, CM Snap, moto cam... like you already did with the browser, gallery... Thanks in advance.

**Comment by bgiesing** [comment]
You can't as there can't be two camera apps installed in the `/system` partition at the same time (unlike Browser/Gallery)

**Comment by gericom-hummer** [comment]
Why? For nearly 1 month it was possible, without any problems.

**Comment by bgiesing** [comment]
It hasn't since before we even existed (when PA GApps existed)

**Comment by mfonville** [comment]
@bgiesing there is a new situation since https://github.com/opengapps/opengapps/pull/233
Snap camera is now also treated as one of the stock camera apps.
I will look into a +CameraStock keyword

**Comment by gericom-hummer** [comment]
They can coexists, because they were, untill adding Snap in the list of stock cams. Since then i excluded google camera from installation and i have copy-pasted and changed the name of the google camera's folder so that the installer won't delete it and will think it is uninstalled.
So probably +CameraStock keyword will be greatly appreciated.

**Comment by gericom-hummer** [comment]
Thanx a lot!

**Comment by gericom-hummer** [comment]
I have opened new issue.
In Aroma when Google Camera is selected to be installed and +CameraStock is being selected too Google camera is not being installed, in fact if i copy google camera folder to /system/app and then start the installer again with checked to be installed and Google and the Stock camera, the installer is deleting Google camera's folder. So again with +CameraStock selected it is not possible to install google camera with aroma.
Thanx
