### ISSUE TITLE
wrong missing space error with cm13

### ISSUE THREAD

**Issue by krodelabestiole** [opengapps/opengapps#239]
hi, i've been trying to install the nano package on cyanogenmod13 (ARM64 android 6.0) and got an error 70 about missing available space on the system partition.

but as you can see 

    root@crackling:/system/bin # df -h
    Filesystem            Size  Used Avail Use% Mounted on
    tmpfs                 934M   36K  934M   1% /dev
    tmpfs                 934M   52K  934M   1% /tmp
    tmpfs                 934M     0  934M   0% /storage
    /dev/block/mmcblk0p25 1.4G  738M  749M  50% /system
    root@crackling:/system/bin #

i have 749M left on /system - which should be more than enough for the nano package.
i tried with the pico package and had the same issue.
i tried to remove the abortion in case of $E_NOSPACE but i can't because that would change the zip signature.
when i `mount /system` manually i can read and write on it.

the phone is a wileyfox swift if that's of any use

**Comment by krodelabestiole** [comment]
this issue was related to the latest cm recovery.
i found a workaround using TWRP and it just worked

**Comment by mfonville** [comment]
This is a result of current ToyBox issues. Indeed stick to TWRP for now.
