### ISSUE TITLE
Cannot install gapps on 4.4 since version 20150618

### ISSUE THREAD

**Issue by laolangcool** [opengapps/opengapps#24]
When flash, it says doesn't support the phone, versions before 20150618 works fine. My phone is xiaomi 2s (aries), omni rom 4.4.

**Comment by mfonville** [comment]
Can you give the exact error output and attach the debug logs?

**Comment by laolangcool** [comment]
Here it is. Please rename the attachment to zip.
![opengapps_log zip](https://cloud.githubusercontent.com/assets/12975042/8266582/955ea500-1768-11e5-9211-7f811a236c69.jpg)

**Comment by laolangcool** [comment]
oh sorry, how to give the log to you?

**Comment by mfonville** [comment]
Ok, thank you for the logs. I see what the issue is, apparently your ROM is only a (long time) deprecated field for the ABI specification. I will put in a fix, which you can try with tomorrow's (21 jun) build.
