### ISSUE TITLE
+CameraStock

### ISSUE THREAD

**Issue by gericom-hummer** [opengapps/opengapps#242]
In Aroma when Google Camera is selected to be installed and +CameraStock is being selected too Google camera is not being installed, in fact if i copy google camera folder to /system/app and then start the installer again with checked to be installed and Google and the Stock camera, the installer is deleting Google camera's folder. So again with +CameraStock selected it is not possible to install google camera with aroma.
Thanx

**Comment by mfonville** [comment]
Could you please attach or link your debug logs?

**Comment by gericom-hummer** [comment]
Here they are

**Comment by gericom-hummer** [comment]
[open_gapps_log.txt](https://github.com/opengapps/opengapps/files/108443/open_gapps_log.txt)



[Device_Space_After.txt](https://github.com/opengapps/opengapps/files/108446/Device_Space_After.txt)
[Device_Space_Before.txt](https://github.com/opengapps/opengapps/files/108447/Device_Space_Before.txt)
[gapps-config_original.txt](https://github.com/opengapps/opengapps/files/108448/gapps-config_original.txt)
[gapps-config_processed.txt](https://github.com/opengapps/opengapps/files/108449/gapps-config_processed.txt)
[gapps-remove_revised.txt](https://github.com/opengapps/opengapps/files/108444/gapps-remove_revised.txt)
[open_gapps_log.txt](https://github.com/opengapps/opengapps/files/108445/open_gapps_log.txt)


[System_Files_After.txt](https://github.com/opengapps/opengapps/files/108450/System_Files_After.txt)
[System_Files_Before.txt](https://github.com/opengapps/opengapps/files/108451/System_Files_Before.txt)

**Comment by gericom-hummer** [comment]
by mistake i closed the issue, sorry.

**Comment by mfonville** [comment]
np

I just don't understand how github can indicate that "mfonville closed this issue" directly after your re-opened it, if I didn't. Seems like github has some bugs :-/

**Comment by gericom-hummer** [comment]
Me either. OK check the logs and if it is possible to fix. Thanks a lot.

**Comment by mfonville** [comment]
Thanks for the logs. I did find some errors in my code and are now testing the fixes.

**Comment by gericom-hummer** [comment]
Welcome. Tomorrow when we have new package, I'll test it too 😁

**Comment by mfonville** [comment]
:)
If any problems arise (also for the future), just comment on the existing bug about the topic. If necessary I can always reopen.

**Comment by gericom-hummer** [comment]
Ok, no problems.

**Comment by gericom-hummer** [comment]
Nope, today's build - 20160129 is acting the same way.
here are the logs.
Thanx
[open_gapps_log.txt](https://github.com/opengapps/opengapps/files/109417/open_gapps_log.txt)


[Device_Space_After.txt](https://github.com/opengapps/opengapps/files/109418/Device_Space_After.txt)
[Device_Space_Before.txt](https://github.com/opengapps/opengapps/files/109419/Device_Space_Before.txt)
[gapps-config_original.txt](https://github.com/opengapps/opengapps/files/109421/gapps-config_original.txt)
[gapps-config_processed.txt](https://github.com/opengapps/opengapps/files/109420/gapps-config_processed.txt)
[gapps-remove_revised.txt](https://github.com/opengapps/opengapps/files/109422/gapps-remove_revised.txt)
[open_gapps_log.txt](https://github.com/opengapps/opengapps/files/109423/open_gapps_log.txt)


[System_Files_After.txt](https://github.com/opengapps/opengapps/files/109424/System_Files_After.txt)
[System_Files_Before.txt](https://github.com/opengapps/opengapps/files/109425/System_Files_Before.txt)

**Comment by mfonville** [comment]
@gericom-hummer I don't see any wrong behaviour in the logs actually. Snap camera seems to be succesfully retained.

And that you don't get GoogleCamera installed is because it is a "dirty" install: https://github.com/opengapps/opengapps/wiki/FAQ#5-i-read-that-google-camera-can-only-be-installed-during-a-clean-install-or-as-an-update-to-an-existing-open-gapps-installation-what-does-this-mean

Try adding `forceclean` as in https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options#force-clean-install-setting to enforce Google Camera installation on "dirty" installs.

**Comment by gericom-hummer** [comment]
OK i will try it in few minutes and will write down the result.

**Comment by gericom-hummer** [comment]
Now, with force clean i think it is OK. Installed camera google legacy. I think, because it is not a nexus device or it doesn't support camera3 api.
Thanx.

**Comment by mfonville** [comment]
Happy to hear that :+1:
