### ISSUE TITLE
#87

### ISSUE THREAD

**Issue by suzydellgmail** [opengapps/opengapps#245]

**Comment by polyzen** [comment]
This appears to be missing something.

**Comment by suzydellgmail** [comment]
No mic volume, earpiece volume really low have to hit speaker to hear caller barely. Speakers compromised after update to lollipop. Running Android 5.1 on moto E xt1023.. Please I'm going bananas for a week now..
Forever grateful
Suzydell@gmail.com

**Comment by polyzen** [comment]
Did you close this accidentally? If hitting it makes a difference, then it seems like a hardware issue. Have you tried downgrading to see if it works again? Perhaps you can try Marshmellow (6)?

**Comment by suzydellgmail** [comment]
Thanks Daniel I shall give it a try, ( Marshmallow)
that is.  Thanks, Amy remedy's you can thiñk of lime the SDK package disappeard after recovery mode on reboot.
Regards I'll let ya know how Marshmallow turns out..

**Comment by mfonville** [comment]
@suzydellgmail What makes you think this is is an issue related to Open GApps? It looks more like a hardware fail and otherwise something with the ROM, not with the GApps.

**Comment by polyzen** [comment]
> Thanks, Amy remedy's you can thiñk of lime the SDK package disappeard after recovery mode on reboot.

Autocorrect <3

**Comment by suzydellgmail** [comment]
Do you any protocol default to troubleshoot

**Comment by polyzen** [comment]
Have you tried Marshmallow or another rom yet? That should probably be your first step.
