### ISSUE TITLE
20160201 - Aroma installs packages, even marked to be excluded and removes bypassed ones

### ISSUE THREAD

**Issue by gericom-hummer** [opengapps/opengapps#247]
Installs: KoreanIME GoogleZhuyinIME GooglePinyinIME AndroidForWork
Removes: Snap Camera

[open_gapps_log.txt](https://github.com/opengapps/opengapps/files/111989/open_gapps_log.txt)

[Device_Space_After.txt](https://github.com/opengapps/opengapps/files/111991/Device_Space_After.txt)
[Device_Space_Before.txt](https://github.com/opengapps/opengapps/files/111990/Device_Space_Before.txt)
[gapps-config_original.txt](https://github.com/opengapps/opengapps/files/111992/gapps-config_original.txt)
[gapps-config_processed.txt](https://github.com/opengapps/opengapps/files/111995/gapps-config_processed.txt)
[gapps-remove_revised.txt](https://github.com/opengapps/opengapps/files/111994/gapps-remove_revised.txt)
[open_gapps_log.txt](https://github.com/opengapps/opengapps/files/111993/open_gapps_log.txt)

[System_Files_After.txt](https://github.com/opengapps/opengapps/files/111996/System_Files_After.txt)
[System_Files_Before.txt](https://github.com/opengapps/opengapps/files/111997/System_Files_Before.txt)

[70-gapps.sh.txt](https://github.com/opengapps/opengapps/files/112002/70-gapps.sh.txt)

**Comment by mfonville** [comment]
Check out https://github.com/opengapps/opengapps/issues/246 and the forum.

I took that 1st of February build offline because of this issue. In tomorrow's it will be resolved.

**Comment by gericom-hummer** [comment]
Thanks.
