### ISSUE TITLE
AOSP Keyboard constant FC on CM 13 with Open GApps ARM Nano 6.0

### ISSUE THREAD

**Issue by aidas957** [opengapps/opengapps#249]
Please fix this

**Comment by mfonville** [comment]
Please use XDA forums for support requests and to troubleshoot the exact cause before opening an issue directly; you'll need attach at least a debug log and a logcat of the FCs to get any support.

**Comment by mfonville** [comment]
The libs are updated in the newest build; I assume this would fix your problem, if you still find any issues please visit our XDA forum thread.

**Comment by aidas957** [comment]
Fixed
