### ISSUE TITLE
Architecture detection

### ISSUE THREAD

**Issue by high1** [opengapps/opengapps#25]
In a2a00c3e47fb0ed79e42dcc050f26e4dd532b487, device architecture detection changed to
device_architecture=$(file_getprop $b_prop ro.product.cpu.abilist)
from
devarch=$(file_getprop $b_prop ro.product.cpu.abi).
This change results in Incompatible Device Detected on devices that were compatible before.
I do think that ro.product.cpu.abi is much more common, or that additional check for empty value should be added, something like:
device_architecture="${device_architecture:-$((file_getprop $b_prop ro.product.cpu.abi)}:"

**Comment by mfonville** [comment]
Didn't commit https://github.com/opengapps/opengapps/commit/dae5cba5d5b6fc603a230d8808fd3c5933b51465 fix this issues for you?

**Comment by high1** [comment]
That fixes it, thanks. 4.4 ROMs mostly do not implement this, so this is a needed backward compatibility fix.
