### ISSUE TITLE
On a clean flash, first time init fails due to Playservices FC

### ISSUE THREAD

**Issue by mammenj** [opengapps/opengapps#250]
Please see the screenshot in the below thread.
http://forum.xda-developers.com/oneplus-one/development/rom-orion-os-2-0-t3294632/post65091440#post65091440

Unable to get past the inital setup of the newly flashed ROM, Stock Gapps. This issue happened in OrionOS and Darkobas rom.
Please review if its an gapps issue, already reported in ROM threads.

**Comment by mammenj** [comment]
BTW, the permission patch is included in the ROM, please see below commit:
https://github.com/TeamOrion/frameworks_base/blob/6.0.1/services/core/java/com/android/server/pm/DefaultPermissionGrantPolicy.java

**Comment by mfonville** [comment]
Do you have a logcat? Than we could see what exactly causes the FC

**Comment by mammenj** [comment]
I will try to get it next time as I could not complete the setup.

**Comment by maximu** [comment]
Under Android-x86_64 rom with patch permission some crash  in the first boot but
![screenshot_20160207-130624](https://cloud.githubusercontent.com/assets/1274014/12872256/9d223cb0-cd9e-11e5-8cbe-bd6bf22b1ac1.png)
 Anyway i can finish wizard process .

**Comment by mfonville** [comment]
I am putting out a patch that should not remove Provision by default on 6.0 anymore;
Apparently CM made some changes that instead of having SetupWizard conflict with Provision it now actually *needs* provision.
After the fix goes live (for arm coming night, other architectures will get a new build later because there are no new packages) please report back in this issue whether it is fixed or not, and whether the issue should be re-opened.

**Comment by mammenj** [comment]
Feb 8 build still fc on Orion os

**Comment by mfonville** [comment]
@mammenj could you upload the debug log and a logcat of the feb 8 try?

**Comment by mammenj** [comment]
@mfonville bro, can't get past the setup, so can't get to the logs.
Let me know if there is a way, I will get it.

**Comment by mfonville** [comment]
@mammenj you can get the debug logs using the file manager in TWRP recovery (or adb from your computer while booted in your recovery).
The setupwizard is more hard. But you can first flash without setupwizard, set-up your phone and grant adb permissions. Than reflash gapps with setupwizard, after boot do:
`adb shell am start -n com.google.android.setupwizard/.SetupWizardActivity` to start the setupwizard and get a logcat with adb.

**Comment by mammenj** [comment]
@mfonville OK thanks, I will get the logs a suggested. I will do it tomorrow and update here.

**Comment by mammenj** [comment]
OK tried to get the logcat but this is the error I got:
CANNOT LINK EXECUTABLE: cannot locate symbol "stderr" referenced by "logcat"...
page record for 0xb6ed102c was not found (block_size=32)

not sure whats going on...any idea where the actual log files are kept in the device, that way I can go directly to the file from recovery and get it.

**Comment by mfonville** [comment]
It looks like your logcat command is missing the libraries it needs. Are you sure you set up the Android SDK correctly?

The debug logs of opengapps install itself can be found in the same folder as where the opengapps ZIP is located.
