### ISSUE TITLE
Android 6 on Nexus4 mako error #70 - Insufficient Space Available in System Partition

### ISSUE THREAD

**Issue by larsx2000** [opengapps/opengapps#251]
I formated /system on my Nexus 4 installed CyanogenMod 13 (Android 6) so /system has 329MB free:
df -h
/dev/block/mmcblk0p21 828M  499M  329M  61% /system

Trying to install opengapps pico gives error #70 - Insufficient Space Available in System Partition. Is this really not enough space? How much space is required for the pico edition?

**Comment by mfonville** [comment]
Please use XDA Forum for support requests. You are probably using CM13 recovery which is not supported. Use TWRP recovery instead.

**Comment by gericom-hummer** [comment]
In TWRP go to Wipe=>Advanced wipe=>select System=>click on Repair/Change File system=>then click Resize. After that you can proceed installing opengapps. Do it every time when flash/dirtu/update your rom.

It is known bug when flashing CM or CM-based roms.

**Comment by larsx2000** [comment]
Thank you for the advice!
resizefs did the trick:
/dev/block/mmcblk0p21  827.8M    609.2M    218.6M  74% /system

**Comment by mfonville** [comment]
@gericom-hummer thanks for helping out!

**Comment by gericom-hummer** [comment]
You are welcome.
