### ISSUE TITLE
Google Camera not being flashed with Aroma

### ISSUE THREAD

**Issue by allard1997** [opengapps/opengapps#254]
When I select to flash the Google Camera with the Aroma installer it doesn't flash it.
Also in the log that you see on screen it doesn't say it is installing it.
This is on the Nexus 5X with TWRP 3.0.0. Also happened on 2.8.7.2.

**Comment by mfonville** [comment]
Please use xda forum for support requests and attach your debug log.

**Comment by allard1997** [comment]
Sorry for using the wrong method of reporting the problem. I did include my debug log now.

[logs.zip](https://github.com/opengapps/opengapps/files/121297/logs.zip)
