### ISSUE TITLE
Ability to do in-tree builds with gapps

### ISSUE THREAD

**Issue by Fuzion24** [opengapps/opengapps#256]
In order to take advantage of features like OTA updates, dm-verity, etc, it would nice to do in-tree overlays of Google apps.

**Comment by mfonville** [comment]
Would @opengapps/aosp-build be able to offer this functionality?

**Comment by Blystad** [comment]
Yes the AOSP build system should be able to handle this.

On the flipside, if there is a second, sufficiently large partition (e.g. a vendor partition) then that could be used. Doubt you'll see that on a normal off the self phone thought, but worth mentioning.

**Comment by mfonville** [comment]
@Fuzion24 I hope this answers your question, if not please file (if appropiate) a bug against the aosp_build repository instead. If it would have to apply to the pre-built packages you can commend here and we can re-open.

**Comment by Fuzion24** [comment]
thanks for this info.  i'll check it out!
