### ISSUE TITLE
Download md5 checksum fails for all packages with unknown error

### ISSUE THREAD

**Issue by tinydynamite00** [opengapps/opengapps#257]
Issue #257

Tap to download md5 results in "<untitled>" document/unknown error. Check first for mini package. Corroborate for all packages for date 20160210 is true
![screenshot_20160210-145214](https://cloud.githubusercontent.com/assets/6479505/12963341/345da9ba-d007-11e5-8302-bbe98045a237.png)

**Comment by mfonville** [comment]
Thanks! I did change some things today so probably I made a typo and will fix it asap

**Comment by mfonville** [comment]
Should be fixed now!

**Comment by tinydynamite00** [comment]
Thank you!
