### ISSUE TITLE
Using getprop instead of file_getprop in updatebinary

### ISSUE THREAD

**Issue by kabouin** [opengapps/opengapps#258]
Hello,

I am wondering why `file_getprop` (which basically greps properties from a given `*.prop` file) is used in the `updatebinary` script instead of the `getprop` command?

This makes the opengapps installation to fail on the recovery I'm working on, since we set some properties like the android version elsewhere than in the `build.prop` or `default.prop` file.

For reference:
* https://github.com/opengapps/opengapps/blob/master/scripts/inc.updatebinary.sh#L479
* https://github.com/opengapps/opengapps/blob/master/scripts/inc.updatebinary.sh#L140

Thanks

**Comment by mfonville** [comment]
@kabouin this is a very good idea and I heard via @deadman96385 why it would be necessary for a certain environment.
I will need to get some feedback from various devices (especially the Amazon Fire Tablet) if they are all compatible with using this method. If yes I can implement it very fast, if not it will take a little bit more time to implement a fallback-method.

**Comment by mfonville** [comment]
@kabouin can you test with tomorrow's build (Thu 18 Feb) if it works?

**Comment by mfonville** [comment]
Ok, with this out in the wild we got some first real bug reports:
Recoveries tend to report their own getprop values, which do not have to reflect those of the ROM :-/
I will re-implement this that it first will try to scan those prop files manually, and only if those return empty-handed it will run getprop.

**Comment by kabouin** [comment]
Ok, that should be fine for me. Thanks!

2016-02-18 9:00 GMT+01:00 Maarten Fonville <notifications@github.com>:
