### ISSUE TITLE
[opengapps.org] Buttons not working

### ISSUE THREAD

**Issue by easyaspi314** [opengapps/opengapps#259]
There is no apparent bug tracker on [opengapps/opengapps.github.io](https://github.com/opengapps/opengapps.github.io) so I am posting it here.

On stock browser (CM13) with AOSP WebView 44, the download/version info/etc buttons don't work. They just show feedback. I will try updating to Google WebView.

**Comment by easyaspi314** [comment]
Update: Latest Google WebView works. However, many users (esp. on custom ROMs would not be able to install it.

**Comment by mfonville** [comment]
Could you enable debugging in your browser by going to `about:debug` and use adb logcat while trying to download? I would be very interested in the exact error AOSP webview gives and what I could do to workaround it.

**Comment by mfonville** [comment]
@easyaspi314 
Could you try if this trick helps at all? https://github.com/opengapps/opengapps.github.io/commit/2e49dd88b12a08260ad8ed4a313554cef0a88332

**Comment by mfonville** [comment]
I dropped the nice method and made it AOSP-webview compatible again.
https://github.com/opengapps/opengapps.github.io/commit/bc34d34a886a60760b91ca19d3ca1c60b33b62f9

**Comment by easyaspi314** [comment]
Thanks, it worked! :)
