### ISSUE TITLE
Insufficient storage error on one plus one

### ISSUE THREAD

**Issue by tusharmath** [opengapps/opengapps#262]
I have been trying to install `open_gapps-arm-6.0-pico-20160215.zip` but I keep getting the same error as described [here][0]. I tried to also get the logs as per the error message @ `/sideload/open_gapps_log.txt` but there is not file there.

Can someone please explain what is the problem and how can I get around it. 

[0]: https://github.com/opengapps/opengapps/wiki/FAQ#6-open-gapps-install-failed-with-the-message-insufficient-storage-space-available-in-system-partition-my-device-has-16gb-or-more-of-storage-available-how-can-this-be

**Comment by mfonville** [comment]
Please use the XDA Forum for support requests instead of directly opening an issue.
I suspect you might be using CM recovery, which is unsupported at the moment can cause this error, please use TWRP.

**Comment by tusharmath** [comment]
Yup that was the issue. I think FAQ can be updated saying that this issue could be because you are using cm recovery

**Comment by mfonville** [comment]
Well, the FAQ does state that in general only TWRP is supported.
CM Recovery is in a horrible state at the moment, that is why decided to bundle our own busybox environment in future builds. Than the weird failures should not happen anymore.

**Comment by tusharmath** [comment]
Thanks!
