### ISSUE TITLE
Utilize issue and pull request templates

### ISSUE THREAD

**Issue by polyzen** [opengapps/opengapps#266]
@mfonville, if you haven't heard of this yet, you'll probably be very pleased: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by mfonville** [comment]
Thanks @polyzen I will certainly check that out

**Comment by mfonville** [comment]
We still have to do a pull request template ;-)

**Comment by polyzen** [comment]
Woops :p

**Comment by artityod** [comment]
https://github.com/opengapps/opengapps/commit/d296f096ab74b0c6f919d43d943ea596bcbab599
