### ISSUE TITLE
Actuality of the published versions on opengapps.org

### ISSUE THREAD

**Issue by weberhofer** [opengapps/opengapps#267]
I'm not sure wether this is the right place to ask; While searching for a new version of gapps includeable in CM I found that you have fixed #211 and related bugs.
No matter which package I download, all files contained in the zip package are from December 13th 2015. I think the packages date on the page should reflect this date or the packages should be rebuild everyday.

**Comment by mfonville** [comment]
The date on the files in the zip are set manually to give consistent signature and hashing. Best place to ask is XDA Forum and not directly filing GitHub issues
