### ISSUE TITLE
Incompatible Android ROM Detected

### ISSUE THREAD

**Issue by PartTimeLegend** [opengapps/opengapps#268]
I'm running [cm-13.0-20160217-NIGHTLY-klte.zip ](https://download.cyanogenmod.org/get/jenkins/149352/cm-13.0-20160217-NIGHTLY-klte.zip), which is 6.0.1. From the website I grab 6.0 Stock.

Upon installation I get failure as my ROM is not compatible, apparently the install package is just for 6.0.x ONLY. Which I am running.

Checks show ARM23 as my SDK level.

**Comment by mfonville** [comment]
Known bug with today's built. Build has been pulled, please read the FAQ and do no directly file GitHub issues.
