### ISSUE TITLE
busybox's tar+xz decompression filter gives problems with aroma

### ISSUE THREAD

**Issue by gericom-hummer** [opengapps/opengapps#269]
It is impossible to install latest opengapps - 20160218 and 20160217 due failure saying This GApps package can only be installed on a 6.0.x ROM. But i am using latest nightly AICP 11, which is CM13 6.0.1
With version 20160215 everything is OK
I am attaching the logs.
Thanks.

[build.prop.txt](https://github.com/opengapps/opengapps/files/135954/build.prop.txt)
[default.prop.txt](https://github.com/opengapps/opengapps/files/135953/default.prop.txt)
[Device_Space_After.txt](https://github.com/opengapps/opengapps/files/135955/Device_Space_After.txt)
[Device_Space_Before.txt](https://github.com/opengapps/opengapps/files/135957/Device_Space_Before.txt)
[gapps-config_original.txt](https://github.com/opengapps/opengapps/files/135956/gapps-config_original.txt)
[gapps-config_processed.txt](https://github.com/opengapps/opengapps/files/135958/gapps-config_processed.txt)
[gapps-remove_revised.txt](https://github.com/opengapps/opengapps/files/135959/gapps-remove_revised.txt)
[open_gapps_log.txt](https://github.com/opengapps/opengapps/files/135961/open_gapps_log.txt)
[Recovery_cache.log.txt](https://github.com/opengapps/opengapps/files/135960/Recovery_cache.log.txt)
[Recovery_tmp.log.txt](https://github.com/opengapps/opengapps/files/135963/Recovery_tmp.log.txt)
[System_Files_After.txt](https://github.com/opengapps/opengapps/files/135962/System_Files_After.txt)
[System_Files_Before.txt](https://github.com/opengapps/opengapps/files/135964/System_Files_Before.txt)

**Comment by mfonville** [comment]
Known bug with today's built, we assume getprop would return the ROMs properties, but it gives those of the recovery instead. Build has been pulled, please see the XDA Forum for details.

**Comment by gericom-hummer** [comment]
Thanx, FYI, the same happened with 20160217 build ;)

**Comment by mfonville** [comment]
You sure that it was with 20160217 too? that shouldn't be...

**Comment by gericom-hummer** [comment]
Yes, but I deleted the logs, and installed again 20160215. Thought it could some bug that will be fixed with next release.

**Comment by mfonville** [comment]
If you could try again with 20160217 I would appreciate that; because if you have an issue with **that one** there is a bug that I am not aware of...

**Comment by gericom-hummer** [comment]
I just tried, but there are no logs, because after 50 times of trying to install it, it keeps rebooting the recovery - twrp 3.0.0.0 and I gave up. Still 20160215 is working perfectly.

**Comment by mfonville** [comment]
Hmm, the difference between 0215 and 0217 is the addition of busybox.
Could you extract the busybox binary from the zip to somewhere (and set permissions to executable `chmod +x` ) and if you can run that executable in the recovery terminal successfully?

**Comment by gericom-hummer** [comment]
yes, i can run the executable in terminal
![p2183597](https://cloud.githubusercontent.com/assets/11374740/13143379/1a46d560-d64c-11e5-85da-040f3f40fd0c.JPG)

**Comment by mfonville** [comment]
hmm, so that is ok. How weird that it just "reboots" the recovery during the installation :-/
Are there any clues in /cache/recovery/log (or last_log) after such a failed install?

**Comment by gericom-hummer** [comment]
i don't know how to explain it, it reaches the phase for gathering system info, clearing old packages and just reboots. I will try it again now and will check the logs.

**Comment by gericom-hummer** [comment]
Here are the logs,  respectively 20160215 and 20160217



[20160215.log.txt](https://github.com/opengapps/opengapps/files/136256/20160215.log.txt)
[20160217.log.txt](https://github.com/opengapps/opengapps/files/136257/20160217.log.txt)

**Comment by gericom-hummer** [comment]
Check this video i've made to see what i have in mind

[http://download.tuxfamily.org/hummer/P2183600.MP4](url)
it will be uploaded shortly...

**Comment by gericom-hummer** [comment]
@mfonville The same is happening and with today's build 20160219 - This GApps package can only be installed on a 6.0.x ROM. I won't say again, that i am using AICP 11 nightly again.
Here you are the logs.
Thanx.
[70-gapps.sh.txt](https://github.com/opengapps/opengapps/files/137603/70-gapps.sh.txt)
[build.prop.txt](https://github.com/opengapps/opengapps/files/137604/build.prop.txt)
[default.prop.txt](https://github.com/opengapps/opengapps/files/137606/default.prop.txt)
[Device_Space_After.txt.txt](https://github.com/opengapps/opengapps/files/137605/Device_Space_After.txt.txt)
[Device_Space_Before.txt.txt](https://github.com/opengapps/opengapps/files/137615/Device_Space_Before.txt.txt)
[g.prop.txt](https://github.com/opengapps/opengapps/files/137616/g.prop.txt)
[gapps-config_original.txt.txt](https://github.com/opengapps/opengapps/files/137607/gapps-config_original.txt.txt)
[gapps-config_processed.txt.txt](https://github.com/opengapps/opengapps/files/137609/gapps-config_processed.txt.txt)
[gapps-remove_revised.txt.txt](https://github.com/opengapps/opengapps/files/137608/gapps-remove_revised.txt.txt)
[open_gapps_log.txt.txt](https://github.com/opengapps/opengapps/files/137610/open_gapps_log.txt.txt)
[Recovery_cache.log.txt](https://github.com/opengapps/opengapps/files/137611/Recovery_cache.log.txt)
[Recovery_tmp.log.txt](https://github.com/opengapps/opengapps/files/137612/Recovery_tmp.log.txt)
[System_Files_After.txt.txt](https://github.com/opengapps/opengapps/files/137613/System_Files_After.txt.txt)
[System_Files_Before.txt.txt](https://github.com/opengapps/opengapps/files/137614/System_Files_Before.txt.txt)

**Comment by mfonville** [comment]
@gericom-hummer could you check if this test build (it is pico!) does run work? https://www.dropbox.com/s/yr4uusv6zo9omy6/open_gapps-arm-6.0-pico-20160219_experiment.zip?dl=0

**Comment by gericom-hummer** [comment]
In few minutes i will tell you the result. I am backing up and will install it.

**Comment by mfonville** [comment]
@gericom-hummer I already got confirmed that in the end that one didn't work. But I had another iteration and it should be ok now :)
The buildbot is making the builds and they should be available soon.

**Comment by gericom-hummer** [comment]
Nope, the same result - INSTALLATION FAILURE: This GApps package can only be installed on a 6.0.x ROM.
[70-gapps.sh.txt](https://github.com/opengapps/opengapps/files/137944/70-gapps.sh.txt)
[build.prop.txt](https://github.com/opengapps/opengapps/files/137943/build.prop.txt)
[Uploading default.prop.txt…]()
[Device_Space_After.txt](https://github.com/opengapps/opengapps/files/137945/Device_Space_After.txt)
[Uploading Device_Space_Before.txt…]()
[Uploading g.prop.txt…]()

[gapps-remove_revised.txt](https://github.com/opengapps/opengapps/files/137946/gapps-remove_revised.txt)
[open_gapps_log.txt](https://github.com/opengapps/opengapps/files/137947/open_gapps_log.txt)
[Recovery_cache.log.txt](https://github.com/opengapps/opengapps/files/137948/Recovery_cache.log.txt)
[Recovery_tmp.log.txt](https://github.com/opengapps/opengapps/files/137949/Recovery_tmp.log.txt)

[Uploading System_Files_Before.txt…]()

**Comment by mfonville** [comment]
@gericom-hummer haha, we just cross-posted one another.
Could I invite you btw to our Gitter at: https://gitter.im/opengapps/general
It is not publicly announced yet, and first I would like to invite some of the power-users like you :)

**Comment by gericom-hummer** [comment]
yup, i'm there :) Thanx

**Comment by gericom-hummer** [comment]
this is the recovery log of 0219 build
[recovery.log.txt](https://github.com/opengapps/opengapps/files/138015/recovery.log.txt)

**Comment by gericom-hummer** [comment]
"Super" package installed successfully. Here are the logs.
@mfonville can you tag it "Help Wanted" for somebody who is good with C to find the error in busybox's source code and knowledge to scan the XZ sources, since we found that it is error in the aroma+busybox package.
[70-gapps.sh.txt](https://github.com/opengapps/opengapps/files/138101/70-gapps.sh.txt)
[build.prop.txt](https://github.com/opengapps/opengapps/files/138106/build.prop.txt)
[default.prop.txt](https://github.com/opengapps/opengapps/files/138107/default.prop.txt)
[Device_Space_After.txt](https://github.com/opengapps/opengapps/files/138103/Device_Space_After.txt)
[Device_Space_Before.txt](https://github.com/opengapps/opengapps/files/138109/Device_Space_Before.txt)
[g.prop.txt](https://github.com/opengapps/opengapps/files/138108/g.prop.txt)
[gapps-config_original.txt](https://github.com/opengapps/opengapps/files/138102/gapps-config_original.txt)
[gapps-config_processed.txt](https://github.com/opengapps/opengapps/files/138104/gapps-config_processed.txt)
[gapps-remove_revised.txt](https://github.com/opengapps/opengapps/files/138114/gapps-remove_revised.txt)
[open_gapps_log.txt](https://github.com/opengapps/opengapps/files/138105/open_gapps_log.txt)
[Recovery_cache.log.txt](https://github.com/opengapps/opengapps/files/138110/Recovery_cache.log.txt)
[Recovery_tmp.log.txt](https://github.com/opengapps/opengapps/files/138111/Recovery_tmp.log.txt)
[System_Files_After.txt](https://github.com/opengapps/opengapps/files/138112/System_Files_After.txt)
[System_Files_Before.txt](https://github.com/opengapps/opengapps/files/138113/System_Files_Before.txt)

**Comment by mfonville** [comment]
This should now be fixed: https://github.com/opengapps/opengapps/commit/1b1a989fb67271e0a59e3ce371d0010d6d5540ba
