### ISSUE TITLE
Move WebViewGoogle from /system/app/Webview to /system/app/WebViewGoogle

### ISSUE THREAD

**Issue by rapperskull** [opengapps/opengapps#27]
On Nexus devices Google WebView is installed in /system/app/WebViewGoogle, while /system/app/Webview is the AOSP one. Is there a reason for which Google WebView is installed in /system/app/Webview or it's an error?

**Comment by mfonville** [comment]
When I checked some time ago the Nexus 7 tablet of my wife Google's Webview was installed in /system/app/webview (without a capital).
I will look into it, if you are right, we will have to move it.

**Comment by mfonville** [comment]
You are right, we will move it.
