### ISSUE TITLE
Stock Package 6.0/ Google Camera Marshmallow build

### ISSUE THREAD

**Issue by nvenasquez** [opengapps/opengapps#270]
The Google Camera included in the package is not working properly on Oppo Find 7a --> Nameless ROM 3.0/6.0.1 especially when I use the video mode it stops and hang up then it crash..

**Comment by mfonville** [comment]
Please use XDA for support; use the template provided and at least provide the installation debug logs.

**Comment by nvenasquez** [comment]
You mean the the files that were automatically saved in internal storage name as open_gapps_debug_logs.tar.gz and open_gapps_logs.txt??

**Comment by nvenasquez** [comment]
When I install the Google Camera app via Play Store the one being installed is the Google Camera Lollipop Build not the new Google Camera Marshmallow build same with Nexus Devices on M builds and the one in the Stock package you've had included.

**Comment by gericom-hummer** [comment]
Oppo Find 7a has support for camera api2, but not api3, only the new nexus devices, for now, has support for camera api 3, thats why you have an error when trying to take a video, and that's why when you install it from the play store, it gives you the old build.

**Comment by nvenasquez** [comment]
I knew it that's why it gives error when I used video mode.. But I just want some clarification from others, hope it'll be supported in the future updates.. So Google is the one responsible for the support and no longer the opengapps developer correct me if I'm wrong..

**Comment by gericom-hummer** [comment]
opengapps can detect does your system support or not api3 and then will install the new google camera or the old legacy one.

**Comment by nvenasquez** [comment]
It didn't detect whether my phone's system is API3 or not, still when I use Stock Gapps 6.0 it'll install the new Google Camera and not the old legacy one..

**Comment by nvenasquez** [comment]
Now the 0222 stock gapps 6.0 installed the old legacy camera instead of the new google camera 3.1

**Comment by mfonville** [comment]
Yes, that is on purpose because your device/ROM is not compatible with the new google camera v3.
If you do want compatibility your ROM developer does need to include drivers that are compatible with the new camera API; but a very big chance he doesn't have those because they have to be supplied by the vendor of the phone (and they are dependent on their camera supplier again).

I close this since this is clearly no *bug* in Open GApps in any way.
