### ISSUE TITLE
Add mediatek touch support in the aroma installer

### ISSUE THREAD

**Issue by wazeeahmed** [opengapps/opengapps#271]
I had no other problems using your aroma installer except the touch sensitivity . There are calibration issues . If I use touch function then installer freezes . or if activate an option using touch , the touch stops working . I had to use volume and power keys all these days . My device is sprout4 or symphony roar a50 , an androidone device .

**Comment by mfonville** [comment]
@wazeeahmed we don't develop the AROMA-installer itself (we only include a config and the binary).
You should open a bug here: https://github.com/amarullz/libaroma/
