### ISSUE TITLE
The gapps-config file excluding doesn't work.

### ISSUE THREAD

**Issue by destiriser** [opengapps/opengapps#273]
I tried putting this:
Exclude CalSync
Exclude PackageInstallerGoogle
and this:
Exclude CalSync PackageInstallerGoogle

to both the gapps-config.txt and .gapps-config files in the same directory as the gapps zip package and it still installs CalSync (Google Calendar Sync) and PackageInstallerGoogle (Package Installer). I use GApps ARM 6.0 Pico version.

**Comment by mfonville** [comment]
As described in the FAQ please use XDA Forum for support and problems with the pre-built packages: http://forum.xda-developers.com/android/software/pa-gapps-continuation-t3098071
You *need* to include your debug logs

PS: you format your exclude wrong; You need only need to exclude once on its own line, after that each line is interpreted as an exclude statement.

**Comment by destiriser** [comment]
Yes, but this is the script, not packages.

Thanks for the help. I think the wiki should be edited to include this since it tells the exact opposite at the moment: "Case, order, spaces, or using empty lines does not matter when using gapps-config."

**Comment by bgiesing** [comment]
@destiriser No it's not the script. The script is what the packages are made with while the `gapps-config` is a feature of the packages.

Also, the wiki says it clearly and that line is correct. You might be getting confused by empty lines part:

## With Empty Lines
```
Exclude

CalSync
PackageInstallerGoogle
```

## Without Empty Lines
```
Exclude
CalSync
PackageInstallerGoogle
```

Either way, Exclude/Include only needs to be used once and every keyword is on it's own line.

**Comment by mfonville** [comment]
@bgiesing thanks for the addendum.

@destiriser if you see possibility to improve the text on the wiki to make it more readable, more comprehensible and less ambiguous, you are invited to update the article. Documentating isn't my strongest skill and I am not a native English speaker.

Also, I am still interested in your debug logs, so that we could see what happened in the script exactly and if we can make it more robust.
