### ISSUE TITLE
video cam Crash I9100

### ISSUE THREAD

**Issue by ColdShadowXX** [opengapps/opengapps#275]
[2016-02-26-12-03-36.txt](https://github.com/opengapps/opengapps/files/149900/2016-02-26-12-03-36.txt)

there is a log i try some versions pico mini stock and have every time same problem with video cam frosen now i have custom gapps and it work maybe you can fix the bug!

**Comment by mfonville** [comment]
Please read the FAQ and the issue-opening statement and use XDA for support requests instead of direcly opening an issue here.
