### ISSUE TITLE
Allow to symlink libjni_latinime.so to libjni_latinimegoogle.so

### ISSUE THREAD

**Issue by F-i-f** [opengapps/opengapps#276]
**Only issues related to the code of The Open GApps Project scripts themselves**
If you have found an issue with a pre-built OpenGApps.org package please use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [X] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [X] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [ ] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aopen+is%3Aissue) and has not been discussed before in the list of [closed issues](https://github.com/opengapps/opengapps/issues?q=is%3Aissue+is%3Aclosed)

*If Open GApps installation fails:*
- [ ] Is the issue reproducible using the latest version of your recovery?
- [ ] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

*If receiving force closures after Open GApps installation:*
- [ ] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [ ] The issue is reproducible on clean (=wiped /data/ partition) installation
- [ ] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [ ] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**
When installing any opengapps package that would install the swypelibs, (in my instance opengapps-arm-20150229-pico on a CM13 or OmniROM 6.x snapshot), opengapps installs /system/lib/libjni_latinimegoogle.so then symlinks into /system/app/LatinIME/lib/arm/.
The symlink is created at /system/app/LatinIME/lib/arm/libjni_latinimegoogle.so.
However the LatinIME app will look the library as /system/app/LatinIME/lib/arm/libjni_latinime.so, and the swype library is never loaded.

**Reproduction Steps:**

1. Install a MarshMallow ROM.
2. Install Opengapps-arm-20150229 (for example)
3. Check the contents of  /system/app/LatinIME/lib/arm

**Expected behavior:**

# ls -l /system/app/LatinIME/lib/arm/
lrwxrwxrwx    1 root     root            36 Feb 29 22:38 libjni_latinime.so -> /system/lib/libjni_latinimegoogle.so

**Observed behavior:**

# ls -l /system/app/LatinIME/lib/arm/
lrwxrwxrwx    1 root     root            30 Feb 29 23:01 libjni_latinime.so -> /system/lib/libjni_latinime.so
lrwxrwxrwx    1 root     root            36 Feb 29 23:02 libjni_latinimegoogle.so -> /system/lib/libjni_latinimegoogle.so

**Installation debug log and logcat of FC:**

N/A

**Comment by F-i-f** [comment]
Patch attached.
[opengapps-swypelibs.patch.txt](https://github.com/opengapps/opengapps/files/151901/opengapps-swypelibs.patch.txt)

**Comment by mfonville** [comment]
Hi, thanks for your bugreport and even the already included patch.

We do have a conflict of some ROM behaviours in this situation though, some don't place nice at all if libjni_latinime.so is redirected to a libjni_latinime.so. As such I cannot directly apply the patch, which actually was our legacy behaviour and triggered quite a lof of error reports from users.

Most ROMs do however look up automatically if libjni_latinimegoogle.so exists, and if so, they prefer to load that lib over the aosp libjni_latinime.so.

I think the best way forward here would to be add an extra keyword for the config, comparable to https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options#skip-googles-swype-library-setting, that would enforce the behaviour you desire. A possible keyword idea could be `substituteswypelibs`

**Comment by F-i-f** [comment]
Odd, I've tried both cm-13.0-20160224-NIGHTLY-mako.zip and omni-6.0.1-20160229-mako-NIGHTLY.zip.
Neither CM13 nor OmniROM seem to be including the patch at all and both seem to attempy to load libjno_latinime.so.

WIth either ROM, upon boot without any gapps installed, attempting to Swype crashes.
After installing opengapps pico, which does install the Swype libs, with either ROM, attempting to Swype still crashes (because both ROM load libjni_latinime.so).

Users of both of these ROMs won't have a working Swype keyboard.
I assume most users will use the Google Keyboard anyways, but it still feels wrong.

**Comment by mfonville** [comment]
I have the feeling those ROMs are doing *something* different than in the past, e.g. skipping the installation the swypelibs was also no necessity in the past, but on certain devices for CM ROMs it is obligatory nowadays to have a working keyboard at all :-/

**Comment by F-i-f** [comment]
Will you include a patch that implements the substituteswypelibs flag?
I'm happy to work on it, but only if it's going to be included.

**Comment by F-i-f** [comment]
Well I couldn't resist.
Here's a patch that implements substituteswypelibs as you described...

[opengapps-swypelibs2.patch.txt](https://github.com/opengapps/opengapps/files/152393/opengapps-swypelibs2.patch.txt)

**Comment by mfonville** [comment]
Thank you for the patch, I could not respond to your inclusion question, because I was asleep at the time ;-)

It is added to the scripts, so future builds will include the feature. I documented it here: https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options#substitute-aosp-library-with-googles-swype-library-setting

**Comment by F-i-f** [comment]
Thanks for including my patch.
Do you have idea as to when this will propagate to the official builds?

**Comment by mfonville** [comment]
all architectures received new APKs today so it should be live tomorrow (daily builds are triggered if APKs are updated)

**Comment by F-i-f** [comment]
As a follow-up to that issue, I recently experienced a bad TWRP build where SELinux was busted.
This led me to find out that the SELinux context for the  /system/app/LatinIME/lib/arm/libjni_latinime.so may be incorrect if the option substituteswypelibs is on.

The code responsible for setting the SELinux contexts is:
<pre>
ch_con() {
  LD_LIBRARY_PATH=/system/lib /system/lib64 /system/toolbox chcon u:object_r:system_file:s0 "$1";
  LD_LIBRARY_PATH=/system/lib /system/lib64 /system/bin/toolbox chcon u:object_r:system_file:s0 "$1";
  chcon u:object_r:system_file:s0 "$1";
}

ch_con_recursive() {
  dirs=$(echo "$@" | awk '{ print substr($0, index($0,$1)) }');
  for i in $dirs; do
    find "$i" -exec LD_LIBRARY_PATH=/system/lib /system/lib64 /system/toolbox chcon u:object_r:system_file:s0 {} +;
    find "$i" -exec LD_LIBRARY_PATH=/system/lib /system/lib64 /system/bin/toolbox chcon u:object_r:system_file:s0 {} +;
    find "$i" -exec chcon u:object_r:system_file:s0 {} +;
  done;
}
</pre>

However chcon on a symlink will change the symlink target.
It seems that add -h to chcon should make it work.

**Comment by mfonville** [comment]
@F-i-f thanks for your thorough investigation and finding this issue and a directly offering a solution! I will add the `-h` to the ch_con*()-functions
