### ISSUE TITLE
open_gapps-arm-6.0-pico-20160301 cause cm camera FC

### ISSUE THREAD

**Issue by 523860169** [opengapps/opengapps#277]
rt...
my nexus4 is based on cm-13.0-20160301-NIGHTLY-mako

**Comment by mfonville** [comment]
Please read the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ#2-im-having-a-problem-with-my-open-gapps-install-what-information-do-you-need-to-help-me) and the support instructions mentioned. You need to use XDA Forum for support requests, directly opening GitHub issues is *not* appreciated.

PS: Please remember to at least include your installation debug log and (if applicable) a logcat when requesting support.
