### ISSUE TITLE
busybox illegal instructions

### ISSUE THREAD

**Issue by justmwa** [opengapps/opengapps#278]
Hello,

on a Galaxy TAB 10.1 (p4tmo) I tried either TWRP 2.8.7 or TWRP 3.0, I installed AOSP6 without issues, but can't get gapps (tried both 0212 and 0302) to install with error 70. Logs show that the installer can't detect free space and there's a lot of 'illegal instructions', has it something to do with the Tegra2 cpu of the platform?

[open_gapps_debug_logs.zip](https://github.com/opengapps/opengapps/files/155318/open_gapps_debug_logs.zip)

thanks for your help!

**Comment by mfonville** [comment]
could you take the busybox binary from the zip and put it in your recovery and try its various commands from the recovery shell?

**Comment by justmwa** [comment]
I will try. In the meantime, downgrading to pico build from 0215 (no busybox included) works. I thought I had the same issue because of space issue but mini was really too big.

**Comment by justmwa** [comment]
I no longer have the device to test on, however given the XDA thread there's definately an issue with busybox on it, because it stopped working the moment busybox got included.

**Comment by mfonville** [comment]
@yashdsaraf do you have any clue why busybox gives these fails on Tegra2?

**Comment by mfonville** [comment]
@justmwa could you link us to the XDA thread you referred to? Than @yashdsaraf can investigate and hopefully fix the issue.

**Comment by yashdsaraf** [comment]
@justmwa I faced a similar issue on older api arm devices. Can you get me the output of
 `cat /proc/cpuinfo`
 from the device on which your facing these problems.

**Comment by justmwa** [comment]
The thread is http://forum.xda-developers.com/galaxy-tab-10-1/development/rom-android-6-0-marshmallow-t3266663/page22
I asked the owner for /proc/cpuinfo, waiting for its feedback. I own a Nexus7 myself, I will try it since it is also Tegra2 based.

**Comment by mfonville** [comment]
Nexus 7 should be Tegra 3.

**Comment by justmwa** [comment]
Whoops, you're right. Its storage is so slow that I thought it was older overall... what a waste. I wil try it nonetheless, just to make sure :)

**Comment by mfonville** [comment]
@yashdsaraf we have another illegal instructions report: http://forum.xda-developers.com/showpost.php?p=65855782&postcount=2275

**Comment by Decatf** [comment]
I am the maintainer for the Galaxy Tab 10.1 TWRP and the ROM mentioned by the OP.

It appears that the illegal instruction is coming from calls to awk. I replaced all the awk calls in installer.sh with "busybox awk" and it works with any problems. No illegal instructions.

My TWRP is built with busybox. There hasn't been any problems with open gapps until some recent version of open gapps. I am unsure which exactly.

Here is a log from an unmodified open gapps package (open_gapps-arm-6.0-pico-20160316):
 [http://pastebin.com/duQhXVYB](http://pastebin.com/duQhXVYB)
Here is a log with the script modified with explicit calls to busybox awk:
[http://pastebin.com/i2RRZqNs](http://pastebin.com/i2RRZqNs)

awk works just fine from the command line.

>~# awk
>BusyBox v1.22.1 bionic (2016-02-07 13:18 -0500) multi-call binary.

>Usage: awk [OPTIONS] [AWK_PROGRAM] [FILE]...

>	-v VAR=VAL	Set variable
>	-F SEP		Use SEP as field separator
>	-f FILE		Read program from FILE
>	-e AWK_PROGRAM

It's calling the right binary from command line.

> ~ # which awk
>/sbin/awk

>~ # ls -al /sbin/awk
>lrwxrwxrwx    1 root     root             7 Jan  1  1970 /sbin/awk -> busybox


A command line test of the space check done in the install script works.
>~# df -k /system | tail -n 1 | awk '{ print substr($0, index($0,$2)) }'`
>582548    472072    110476  81% /system

**Comment by mfonville** [comment]
@Decatf The cause of the problem has been found by @yashdsaraf and he will provide an updated busybox soon  to solve the issue.
Unfortunately we cannot "trust" the awk (and many other commands) in the recoveries anymore since toybox (and all kind of hybrids) are floating around (background story here: https://plus.google.com/+OpengappsOrg/posts/FJ2v1kNxzHV )

**Comment by Decatf** [comment]
I have read that post now and I see that this change has already been implemented. It is probably cause of this particular problem with Tegra2 devices.  

Previously open gapps was using the busybox from recovery itself which was fully compatible with open gapps. Now it is using a bundled busybox binary. The bundled binary is not compatible with the Tegra2. It is likely because it was compiled with the NEON instruction set which the Tegra2 does not support.  

Is there any chance it could be built with vfp3 only?

> To build for VFPv3 only, with no NEON instructions, specify -mfpu=vfpv3.

[http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dht0004a/CHDHJDIE.html](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dht0004a/CHDHJDIE.html)

**Comment by klausenbusk** [comment]
```
1|root@serranoltexx:/tmp # ./busybox-arm ls                                    
./busybox-arm[1]: syntax error: '<' unexpected
```
With the newest busybox-arm from this repo, https://busybox.net/downloads/binaries/latest/busybox-armv6l works fine through. On Samsung S4 mini with newest nightly recovery. (cm-13.0-20160402-NIGHTLY-serranoltexx-recovery.img)

**Comment by klausenbusk** [comment]
Same problem with busybox-arm from e994e418441b1f84b0c8513b842c4a23819ef415

**Comment by mfonville** [comment]
@klausenbusk could you post your `cat /proc/cpuinfo` ?
@yashdsaraf would you be able to investigate?

**Comment by klausenbusk** [comment]
> @klausenbusk could you post your cat /proc/cpuinfo ?

http://sprunge.us/VYQS

**Comment by klausenbusk** [comment]
@mfonville I tried replacing the busybox-arm in the file with the working busybox binary, but then verification fail. Do you know of any hack, I can use to install it?

**Comment by mfonville** [comment]
@klausenbusk if you use TWRP you can choose to skip verification.

**Comment by klausenbusk** [comment]
> @klausenbusk if you use TWRP you can choose to skip verification.

I use Cyanogenmod Recovery.

**Comment by mfonville** [comment]
@klausenbusk I strongly suggest to use TWRP and not Cyanogenmod Recovery, if available for your device. Cyanogenmod is still a recipe for disaster unfortunately :-/
At https://twrp.me/Devices/ you can find the supported devices.

**Comment by klausenbusk** [comment]
after a lot of fiddle, I finally got the zip signed, but now there is a new problem:
```
ln: cannot create symbolic link from '/tmp/busybox' to '/tmp/bin/acpid': Permission denied
ln: /tmp/bin/acpid: Permission denied
ln: /tmp/bin/acpid: Permission denied
```
Same problems as you had.

**Comment by mfonville** [comment]
@klausenbusk that is the fault of Cyanogenmod Recovery :/ ; exact cause & fix still unknown

**Comment by klausenbusk** [comment]
> @klausenbusk that is the fault of Cyanogenmod Recovery :/ ; exact cause & fix still unknown

I found the problem :) Selinux `setenforce 0` to disable it, and I can run the script! :)

Now I just need to figure out how to fix
```
/sideload/package.zip opened
 extracting: zip
bash: applet not found
```

**Comment by klausenbusk** [comment]
> bash: applet not found

Problem found. As default busybox is compiled with `CONFIG_FEATURE_BASH_IS_NONE=y`, we shouldn't depends on that busybox has been compiled with either `CONFIG_FEATURE_BASH_IS_ASH` or `CONFIG_FEATURE_BASH_IS_HUSH`

Could you change https://github.com/opengapps/opengapps/blob/master/scripts/inc.installer.sh#L98 from bash to either ash/hush or sh?

**Comment by klausenbusk** [comment]
https://github.com/yashdsaraf/busybox seems to have been compiled with `CONFIG_FEATURE_BASH_IS_ASH=y`.

**Comment by mfonville** [comment]
@klausenbusk because we use bashims we made the shebang `bash`, so that we have optimal shellcheck checking, and our own bundled busybox is compiled with it, so I put it like that on purpose and would prefer to keep it that way.

Would we be able to run setenforce from our update-binary script?

**Comment by yashdsaraf** [comment]
@klausenbusk Will you be able to try out [this](https://app.box.com/s/1vy5brqd5fhtu00ah1scmwb56hp886j4) busybox binary.
Please report back if it works out for you.

**Comment by klausenbusk** [comment]
> so that we have optimal shellcheck checking

Changing it only in `inc.installer.sh` shouldn't affect shellcheck.
Pros:
* People can use regular busybox binary with default settings

**Comment by klausenbusk** [comment]
> @klausenbusk Will you be able to try out this busybox binary.

Seems to work, only tested by:
```
adb push busybox /tmp
adb shell
chmod +x /tmp/busybox
/tmp/busybox ls
```

**Comment by yashdsaraf** [comment]
@justmwa @klausenbusk  @Decatf I've switched to a hard float toolchain with vfpv2 extension (backwards compatible with vfp as per the buildroot docs) for the latest busybox release.
Could you please check whether the attached binary works on devices without NEON support (Tegra 2)?
[busybox-arm](https://dl.dropboxusercontent.com/s/l6236u75yfyblsi/busybox-arm-sel)

**Comment by justmwa** [comment]
I guess it does, latest gapps installed without issues.
