### ISSUE TITLE
Android N and Master Branch build libchrome.so

### ISSUE THREAD

**Issue by Khaon** [opengapps/opengapps#282]
Android N preview and master branch build from source libchrome.so.

Indeed you can find this repo  a N-preview-1 and master branches: 
https://android.googlesource.com/platform/external/libchrome/

Some component from either N-preview or master needs the libchrome:
https://android.googlesource.com/platform/system/bt/+/android-n-preview-1/main/Android.mk#66

Currently the install script deletes any libchrome.so found:
https://github.com/opengapps/opengapps/blob/master/scripts/inc.installer.sh#L1745

**reproduce steps:**

1. Install Master or Android N Preview AOSP build.
2. Install Pico opengapps package
3. Boot, try to turn BT on 
4. Logcat says libchrome.so is missing

> 03-19 02:25:14.664 12148 12148 E BluetoothSdpJni: Bluetooth module is not loaded
> 03-19 02:25:17.809 12169 12169 E HAL     : load: module=/system/lib/hw/bluetooth.default.so
> 03-19 02:25:17.809 12169 12169 E HAL     : dlopen failed: library "libchrome.so" not found

**Comment by mfonville** [comment]
@rapperskull the current libchrome removal scripts were created for "For Stock"-mode. Could you think of a way we could handle this situation appropriately for when Android N will be released?

**Comment by Khaon** [comment]
Currently, on marshmallow or lollipop, what is providing libchrome ? The chrome app ?

One solution for me is
 - Check the OS version and remove or not accordingly

**Comment by rapperskull** [comment]
Maybe I have a solution, I'll check the N factory image and push a commit.
