### ISSUE TITLE
Can't install Google Dialer manually

### ISSUE THREAD

**Issue by JoshuaOrphir** [opengapps/opengapps#287]
The GApps update after 03/21 uninstalled the Google Dialer, which was installed as user app.
And a reinstall of the apk does not succeed on nano arm64.

**Comment by mfonville** [comment]
Please read the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ#2-im-having-a-problem-with-my-open-gapps-install-what-information-do-you-need-to-help-me) and the support instructions mentioned. You need to use [XDA Forum[(http://forum.xda-developers.com/android/software/Open-GApps-t3098071) for support requests, directly opening GitHub issues is *not* appreciated.

PS: Please remember to at least include your installation debug log and (if applicable) a logcat when requesting support.
