### ISSUE TITLE
Aroma not installing Google Dialer

### ISSUE THREAD

**Issue by gpvecchi** [opengapps/opengapps#289]
As title, even is selected no Google dialer in priv-apps...

**Comment by mfonville** [comment]
Please read the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ#2-im-having-a-problem-with-my-open-gapps-install-what-information-do-you-need-to-help-me) and the support instructions mentioned. You need to use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071) for support requests, directly opening GitHub issues is *not* appreciated.

**PS: Please remember to at least include your installation debug log and (if applicable) a logcat when requesting support.**

^^You have not submitted a single installation debug log on your XDA posts about dialer^^ That means they are ignored as stated in OP
