### ISSUE TITLE
Google Plus and Hangouts conflict

### ISSUE THREAD

**Issue by tienthanh2509** [opengapps/opengapps#29]
Vi: "Trên android kitkat, google plus và hangouts xung đột thư viện khiến cho khi cài đặt cùng lúc 2 ứng dụng này. ứng dụng sau cùng sẽ không thể hoạt động."

En: on android kitkat, google plus and hangouts library conflict caused when install 2 applications at the same time, g+ or hangouts will be force close.

P/s: Sorry for my bad english

**Comment by tienthanh2509** [comment]
This is conflict lib: libcronet.so

**Comment by mfonville** [comment]
Yes, that is a known issue. Therefore those applications are installed on /data/ and not on /system/. So this conflict is not possible with current Open GApps builds (if everything works as it should). So I will mark it invalid for now. (Also, please English only, the team is a multi-lingual, but no Vietnamese).
