### ISSUE TITLE
Cyanogenmod Recovery support (selinux)

### ISSUE THREAD

**Issue by klausenbusk** [opengapps/opengapps#299]
**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps installation fails:*
- [x] Is the issue reproducible using the latest version of your recovery?
- [ ] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

**Issue description:**
As I found out in https://github.com/opengapps/opengapps/issues/278#issuecomment-205008056 , the reason why Open GApps is failing installing on Cyanogenmod Recovery is because of selinux.

I only opened this issue, so we don't forget it.

Kristian

**Comment by mfonville** [comment]
@klausenbusk Yesterday I had done this commit (because after you did mention it I had put it on my endless TODO list ;-) )
https://github.com/opengapps/opengapps/commit/a0832927c596153b2549a600061fd8ffeb67dc79
So, if that works, it might already be implemented.

**Comment by mfonville** [comment]
@klausenbusk can you confirm that this issue is resolved?

**Comment by klausenbusk** [comment]
> @klausenbusk can you confirm that this issue is resolved?

I will test when I get some time, I haven't forget it (yet) :)

**Comment by gentoo-root** [comment]
@mfonville even with `setenforce 0` I get permission denied error on cyanogenmod recovery when trying to `ln -sf /tmp/busybox-arm /tmp/bin/[`, and `ERROR 10: Failed to set-up Open GApps' pre-bundled busybox` appears.

**Comment by mfonville** [comment]
@gentoo-root thanks for testing. Damn CM recovery :-/
If you run `setenforce 0` from the shell does it give the same error, is it only when installing a flashable zip?

**Comment by gentoo-root** [comment]
@mfonville when I run `setenforce 0` from the root shell on booted device, it succeeds. However, it fails when run from zip. It seems that CM recovery has no adb shell capability, so I was unable to test `setenforce 0` from the recovery shell.

When run from zip, `id` command shows the following: `uid=0(root) gid=0(root) groups=0(root) context=u:r:recovery:s0`
In the shell on booted device it says: `uid=0(root) gid=0(root) groups=0(root) context=u:r:sudaemon:s0`

It seems that these policies differ in the way that [the first one](https://github.com/CyanogenMod/android_external_sepolicy/blob/cfce3d6dcd8f7064eeef8f682d6d478106248a58/recovery.te) can't set selinux to the permissive mode, and [the second](https://github.com/CyanogenMod/android_external_sepolicy/blob/cfce3d6dcd8f7064eeef8f682d6d478106248a58/su.te#L16) can.

So, it seems that we can't disable selinux, we can't create symlinks in /tmp. But we can run busybox, and it is really enough. For example, as far as I remember when you configure busybox you can choose `busybox --install` behavior, and one possible option is to install shell script wrappers for every applet. We can try that option in case when symlinking fails.

**Comment by mfonville** [comment]
@gentoo-root I think that if we are unable to make the symlinks the `--install` also wouldn't work, because it uses the same trick (with hard links) AFAIK.

It seems CM recovery is doing everything in their power to prevent possibly abusive scripts from running. Big chance we can *only* support it when Toybox will be more complete and the busybox won't be necessary anymore :-/

**Comment by gentoo-root** [comment]
>I think that if we are unable to make the symlinks the --install also wouldn't work, because it uses the same trick (with hard links) AFAIK.

@mfonville Please read more carefully the last two sentences of my message ;)
I mentioned that there is `busybox --install` mode that doesn't make any symlinks or hardlinks but instead installs shell script wrappers. It is turned on by CONFIG_INSTALL_APPLET_SCRIPT_WRAPPERS option. We can fall back to this mode in case when symlinking fail.

**Comment by mfonville** [comment]
@yashdsaraf would it be possible to make an experimental build of busybox with that wrapper enabled?

**Comment by gentoo-root** [comment]
I've read busybox docs another time, and seems that CONFIG_INSTALL_APPLET_SCRIPT_WRAPPERS is not what we need, sorry for misleading.
This option only affects `make install` behavior, but does not affect `busybox --install`.
But we still can generate those script wrappers manually in our update-binary if symlinking fails.

**Comment by gentoo-root** [comment]
I've managed to successfully install opengapps with patch from #309.
(For some reason I see google services crashes though I gave them all permissions, but it is irrelevant to this bug, I think.)

**Comment by mfonville** [comment]
ok great; than you can ignore my question in #309 it cross-posted :-D
