### ISSUE TITLE
Set Google Dialer to default phone app

### ISSUE THREAD

**Issue by Acris** [opengapps/opengapps#301]
**Issue description:**
When I installed Google dialer, it's not the default phone app, when I try to make a call, my phone will reboot(soft reboot). When I set Google dialer became the default phone app on Setting -> App, it don't crash. So, can you make Google dialer became default phone app when flash OpenGapps?

**Comment by mfonville** [comment]
I had already thought about this idea, and researched it a bit, but still haven't found a way to do this yet.

**Comment by AnimbusDev** [comment]
@mfonville settings command maybe?

**Comment by mfonville** [comment]
@AnimbusDev keep in mind we are in recovery :-/
I had looked at the `pm` sourcecode, but I only did see removal of default and not setting defaults for dialer.

**Comment by errikos** [comment]
For me Google Phone works if stock Dialer is also installed and Enabled. If stock Dialer is uninstalled, Google Phone causes reboot upon placing a call. If stock Dialer is disabled, then Google Phone makes the call, but there is no InCallUI, ie. the call goes on fine, but you can't do anything with it (like ending the call for example).

**Comment by mfonville** [comment]
@errikos which device and ROM are you using?

**Comment by errikos** [comment]
@mfonville Sorry, my omission. I have a G2-D802 and I am using CM13 latest NIGHTLY (but also happens with SNAPSHOT).

**Comment by nvenasquez** [comment]
Same thing happened on my phone when OPENGAPPS stock package still has no Google phone included I've installed Google Phone via Play Store directly. It works but when I disabled stock dialer Google phone still works but no CallerUI shown/displayed and can't even hang up a call, but right now the Google Phone app included on the Stock Packages doesn't even installed on my device. My device is Oppo Find 7a on Nameless ROM 3.0/6.0.1

**Comment by mfonville** [comment]
Please check http://forum.xda-developers.com/showpost.php?p=66425274&postcount=2529 for what is going to change in future builds.
We probably can't resolve the issues with a broken in-Call UI, because those are depended on the telephony-application provided for the specific device.
Best is NOT to use Google Dialer on non-Nexus devices.

**Comment by osm0sis** [comment]
This should work from recovery. ;)

set_dialer.sh
```
#!/sbin/sh
# osm0sis @ xda-developers

set_ver=122;
set_sec=/data/system/users/0/settings_secure.xml;
if [ -f "$set_sec" ]; then
  if [ ! -z "$(grep dialer_default_application $set_sec)" ]; then
    if [ -z "$(grep 'dialer_default_application" value="com.google.android.dialer' $set_sec)" ]; then
      entry=$(grep -o 'dialer_default_application" value=.*$' $set_sec);
      newentry='dialer_default_application" value="com.google.android.dialer" package="android" />';
      sed -i "s;${entry};${newentry};" $set_sec;
    fi;
  else
    max=0;
    for i in $(grep -o 'id=.*$' $set_sec | cut -d\" -f2); do
      test $i -gt $max && max=$i;
    done;
    entry='  <setting id="'$((max + 1))'" name="dialer_default_application" value="com.google.android.dialer" package="android" />';
    line=$((`grep -n "<settings version=" $set_sec | cut -d: -f1` + 1));
    sed -i "${line}s;^;${entry}\n;" $set_sec;
  fi;
else
  echo "<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>" > $set_sec;
  echo '<settings version="'$set_ver'">' >> $set_sec;
  echo '  <setting id="1" name="dialer_default_application" value="com.google.android.dialer" package="android" />' >> $set_sec;
  echo '</settings>' >> $set_sec;
fi;
chown system:system $set_sec;
chmod 600 $set_sec;


```

**Comment by mfonville** [comment]
Notice to myself; Android code that handles the default dialer: https://android.googlesource.com/platform/frameworks/base/+/master/services/core/java/com/android/server/telecom/TelecomLoaderService.java

**Comment by mfonville** [comment]
@osm0sis versioncodes background: https://android.googlesource.com/platform/frameworks/base/+/android-6.0.0_r1/packages/SettingsProvider/src/com/android/providers/settings/SettingsProvider.java#1928

**Comment by osm0sis** [comment]
Updated the above script with clean install dir prep. Tested on a clean install on CM13 and it works! :D

**Comment by errikos** [comment]
Xcx you xcx xvv xcx free DX setup xvv BC CV vdjmr

**Comment by mjevange** [comment]
Has there been any firther progress on this?
I'm faced with no callUI shown after disabling included Dailer and trying to use Google Dialer or otherwise

**Comment by osm0sis** [comment]
It's fixed and closed. What you've got is a separate issue. Please open a new one and add logs, screen shot of settings where Dialer is set and the contents of /data/system/users/0/settings_secure.xml
