### ISSUE TITLE
Can't remove CM Screencast

### ISSUE THREAD

**Issue by nephilin82** [opengapps/opengapps#305]
Hello,

I'd like to remove some apps during installation of my gapps. The only one i can't remove is CyanogenMod Screencast. In my .gapp.config file , i've tryied screencast, Screencast, and CMScreencast keywords, but they don't work. 
Can you tell me the keyword i've to put, please?
 I've Cm13 on my Nexus. 

Best Regards.

**Comment by robin-vandaele** [comment]
You should read the guide for gapps-config
https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options
There is a feature that can remove any app by using it's package name

**Comment by nephilin82** [comment]
Thank you for the answer. I already use this feature by adding package name in the .gapps.config file. But I didn't find the exact keyword to remove Screencast.

**Comment by robin-vandaele** [comment]
Try (Screencast) with the parentheses
@mfonville could maybe add a read gapps keyword for the screencastapp in the feature

**Comment by mfonville** [comment]
@robin-vandaele @nephilin82 I could, but in that case I do need the full paths (e.g. is it in /app/ or in /priv-app/)

@nephilin82 In principle you also have asked your question at the wrong place. As the FAQ and support page clearly state, you should use XDA Forum for support requests and not have opened an issue here on GitHub, and at the very least you should have included your debug logs. If you'd have provided those I could have seen the full paths already and added this keyword pro-actively.

**Comment by robin-vandaele** [comment]
@mfonville Just so you don't have to search this anymore: On my rom, the screencast app resides in  /system/priv-app/Screencast

**Comment by nephilin82** [comment]
@robin-vandaele I tried, and it's that !!! Thank you very much.

@mfonville I'm really sorry to have asked my question in the wrong place. If i have an other question i'll go to the XDA forum.

**Comment by mfonville** [comment]
I added CMScreencast as a keyword for future builds.
