### ISSUE TITLE
Services keep crashing

### ISSUE THREAD

**Issue by WalrusInAnus** [opengapps/opengapps#306]
I have CM11 installed with Pico version of gapps (and yes I am using the correct version for my CM), and various Google services keep crashing all the time, even right after first boot of the phone. It's extremely annoying. I don't know what to do or how to troubleshoot it, but it's obviously caused by gapps, so I am posting it here.

**Comment by mfonville** [comment]
Please read the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ#2-im-having-a-problem-with-my-open-gapps-install-what-information-do-you-need-to-help-me) and the support instructions mentioned. You need to use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071) for support requests, directly opening GitHub issues is *not* appreciated.

PS: Please remember to at least include your installation debug log and (if applicable) a logcat when requesting support.
