### ISSUE TITLE
Replace the service restart loop with a limited tries

### ISSUE THREAD

**Issue by Mannshoch** [opengapps/opengapps#307]
I have the Problem, that after updating my Galaxy s2 and CM13 with OpenGaaps nano (20160430) I got Service error on start. On pressing OK it appears again. Please break this loop. If it’s not possible to install gaaps this app should not end in a infinite loop.

**Comment by mfonville** [comment]
Please read the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ#2-im-having-a-problem-with-my-open-gapps-install-what-information-do-you-need-to-help-me) and the support instructions mentioned. You need to use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071) for support requests, directly opening GitHub issues is *not* appreciated.

PS: Please remember to at least include your installation debug log and (if applicable) a logcat when requesting support.

**Comment by Mannshoch** [comment]
seems to be a missunderstood. After some time I was able to get it work. But I think a such infinite loop is a quite bad habit. so my Request only have to do with this.

**Comment by mfonville** [comment]
@Mannshoch your experience is a mix of the properties of the ROM and Google's own app. It is not caused by Open GApps' scripts and neither we can do anything about it. And without any logs we can't even investigate anything.

**Comment by Mannshoch** [comment]
hmm. An I thought it's only a Problem of the Autostart script. The Background seems more complicate then it seems.
