### ISSUE TITLE
PreODEX flag not working

### ISSUE THREAD

**Issue by legendtang** [opengapps/opengapps#308]
I add the PreODEX in gapps-config.txt and it does show `Smart ART Pre-ODEX | true [preodex]` but no odex files were found after the first boot.

Here is the full debug log. Thanks!
[open_gapps_debug_logs.tar.gz](https://github.com/opengapps/opengapps/files/244038/open_gapps_debug_logs.tar.gz)

**Comment by mfonville** [comment]
@legendtang pre-odex is at the moment disabled (even when using the flag), because some problems are still unresolved. I hope to tackle those in the near-future and be able to re-enable the flag.

**Comment by legendtang** [comment]
@mfonville Thanks for the explanation. Would you please update the wiki temperately?
