### ISSUE TITLE
domain and changing projectpage to organizationpage

### ISSUE THREAD

**Issue by bgiesing** [opengapps/opengapps#31]
One thing I noticed is how long the URL for the download site is... We could register something like `opengapps.cf` for free and then forward the GitHub page to it.

Three things about this:

1. Old domain would still redirect!
2. Does require DNS but that can be free also (aka [ClouDNS](http://cloudns.net))
3. Not as memorable as a `.com` but would still be a lot shorter and easier to remember than opengapps.github.io/opengapps

Any thoughts guys? @opengapps/general 

Task List
=======
- [x] Get Free Domain
- [x] Forward free domain to GitHub Pages
- [x] Look into a "Paid" domain like ~~`.com`~~`.org`
- [x] Forward "Paid" domain to GitHub Pages
- [x] Update README to point to new domain
- [x] Move Project page to Organization Page
- [x] Redirect `http://opengapps.org/opengapps` to `http://opengapps.org`
- [ ] Close 'OLD' `gh-pages` branch -> there are too many links to this old URL. We cannot abandon it for a long time.

**Comment by rapperskull** [comment]
We can just register a free .cf domain and the use the built-in tools to redirect it to http://opengapps.github.io/opengapps

BTW opengapps.tk, opengapps.ml, opengapps.ga, opengapps.cf and opengapps.gq are all registered. I don't know if it was @mfonville or not.

**Comment by bgiesing** [comment]
@rapperskull It was me, I was making sure nobody would "squat" on them.

**Comment by rapperskull** [comment]
OK then set a redirect on all of them. I don't think that there's nothing wrong.

**Comment by bgiesing** [comment]
@rapperskull @mfonville Can somebody give me write access to this repo? If I am to redirect the proper way, I would have to create a file called `CNAME` with `opengapps.cf` in the file. The other domains would redirect to the new url.

**Comment by mfonville** [comment]
I will look into it. We can even consider a payed domain.
I think I will change the concept of the homepage to a 'organization' page of github instead of a projectpage (did not know of the difference/existence before), which should shorten the URL at least to not have a /opengapps in it.

It will have to wait a few hours or a day though, since I am enjoying some music @ a festival :-)

**Comment by bgiesing** [comment]
Well, just a good example to look on...

My website is done this exact way: http://voxive.cf and here's the GH repo where you can see the CNAME file: https://github.com/TeamVoxive/teamvoxive.github.io

Do you think if I pull request it, you could merge it while at a festival? LOL

**Comment by bgiesing** [comment]
Well there's a pull request if anybody has some free time with write access! #32

**Comment by mfonville** [comment]
Octodroid ftw

**Comment by bgiesing** [comment]
It's live already! http://opengapps.cf

I am going to forward the other domains (.tk,etc.) in just a second!

**Comment by bgiesing** [comment]
Aaaaannnnddd maybe not... "Free domain can't be forwarded to free domain"

Well that should be good enough, and I own all the free ones just in case somebody wanted to "squat".

**Comment by bgiesing** [comment]
@mfonville Made another pull (#33) for updating the README to the new link.

Also, added a "Task List" to the OP to track the progress.

**Comment by mfonville** [comment]
Rather not yet, I registered opengapps.org :)

**Comment by bgiesing** [comment]
@mfonville One suggestion for the new 'org' page, even though the old URL works (but redirects to `opengapps.org/opengapps`. I would create a 301 redirect to permanently move to `opengapps.org`

Also, I would look at [Bounce.Bar][1] as you can create a temp. banner at the top of the page when it detects somebody came from the old URL and tell them the new one for the future!

[1]: http://bounce.bar

**Comment by bgiesing** [comment]
@mfonville Found this guide for GH-Pages 301 redirect using CloudFlare (which everybody should use anyway! :smile: 

http://ianrose.me/2014/03/30/permanent-rediect-github-project-page/

**Comment by mfonville** [comment]
I think I will just use a temporary html+javascript redirect, and remove that gh-pages in a few days.

**Comment by mfonville** [comment]
Since we cannot remove gh-pages because the internet is full with links to the old URL, we will just leave the forward in place and only remove it in some far distant future.
