### ISSUE TITLE
GoogleSignatureVerifier & PlayServices

### ISSUE THREAD

**Issue by mikalackis** [opengapps/opengapps#311]
I just flashed my Nexus 5 with a new AOSP rom compiled by myself and I noticed that with the latest source base of opengapps and new AOSP tag version (android-6.0.1_r41) I constantly get a notification saying: 
Google Play service won't run unless you update Google Play service.

When I click on it to go to Play store, I dont have an option to update it, just DEACTIVATE button. 

As for logcat, it seems that there is an issue with signature verification:
`5-05 22:46:07.583  1833  1855 V GoogleSignatureVerifier: com.google.android.gms signature not valid.  Found: 
05-05 22:46:07.583  1833  1855 V GoogleSignatureVerifier: MIIEQzCCAyugAwIBAgIJAMLgh0ZkSjCNMA0GCSqGSIb3DQEBBAUAMHQxCzAJBgNVBAYTAlVTMRMw
05-05 22:46:07.583  1833  1855 V GoogleSignatureVerifier: EQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtHb29n
05-05 22:46:07.583  1833  1855 V GoogleSignatureVerifier: bGUgSW5jLjEQMA4GA1UECxMHQW5kcm9pZDEQMA4GA1UEAxMHQW5kcm9pZDAeFw0wODA4MjEyMzEz
05-05 22:46:07.583  1833  1855 V GoogleSignatureVerifier: MzRaFw0zNjAxMDcyMzEzMzRaMHQxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYw
05-05 22:46:07.583  1833  1855 V GoogleSignatureVerifier: FAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtHb29nbGUgSW5jLjEQMA4GA1UECxMHQW5k
05-05 22:46:07.583  1833  1855 V GoogleSignatureVerifier: cm9pZDEQMA4GA1UEAxMHQW5kcm9pZDCCASAwDQYJKoZIhvcNAQEBBQADggENADCCAQgCggEBAKtW
05-05 22:46:07.583  1833  1855 V GoogleSignatureVerifier: LgDYO6IIrgqWbxJOKdoR8qtW0I9Y4sypEwPpt1TTcvZApxsdyxMJZ2JORland2qSGT2y5b+3JKke
05-05 22:46:07.583  1833  1855 V GoogleSignatureVerifier: dxiLDmpHpDsz2WCbdxgxRczfey5YZnTJ4VZbH0xqWVW/8lGmPav5xVwnIiJS6HXk+BVKZF+JcWjA
05-05 22:46:07.583  1833  1855 V GoogleSignatureVerifier: sb/GEuq/eFdpuzSqeYTcfi6idkyugwfYwXFU1+5fZKUaRKYCwkkFQVfcAs1fXA5V+++FGfvjJ/Cx
05-05 22:46:07.583  1833  1855 V GoogleSignatureVerifier: URaSxaBvGdGDhfXE28LWuT9ozCl5xw4Yq5OGazvV24mZVSoOO0yZ31j7kYvtwYK6NeADwbSxDdJE
05-05 22:46:07.583  1833  1855 V GoogleSignatureVerifier: qO4k//0zOHKrUiGYXtqw/A0LFFtqoZKFjnkCAQOjgdkwgdYwHQYDVR0OBBYEFMd9jMIhF1Ylmn/T
05-05 22:46:07.583  1833  1855 V GoogleSignatureVerifier: gt9r45jk14alMIGmBgNVHSMEgZ4wgZuAFMd9jMIhF1Ylmn/Tgt9r45jk14aloXikdjB0MQswCQYD
05-05 22:46:07.583  1833  1855 V GoogleSignatureVerifier: VQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIG
05-05 22:46:07.583  1833  1855 V GoogleSignatureVerifier: A1UEChMLR29vZ2xlIEluYy4xEDAOBgNVBAsTB0FuZHJvaWQxEDAOBgNVBAMTB0FuZHJvaWSCCQDC
05-05 22:46:07.583  1833  1855 V GoogleSignatureVerifier: 4IdGZEowjTAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBAUAA4IBAQBt0lLO74UwLDYKqs6Tm8/y
05-05 22:46:07.583  1833  1855 V GoogleSignatureVerifier: zKkEu116FmH4rkaymUIE0P9KaMftGlMexFlaYjzmB2OxZyl6euNXEsQH8gjwyxCUKRJNexBiGcCE
05-05 22:46:07.583  1833  1855 V GoogleSignatureVerifier: yj6z+a1fuHHvkiaai+KL8W1EyNmgjmyy8AW7P+LLlkR+ho5zEHatRbM/YAnqGcFh5iZBqpknHf1S
05-05 22:46:07.583  1833  1855 V GoogleSignatureVerifier: KMXFh4dd239FJ1jWYfbMDMy3NS5CTMQ2XFI1MvcyUTdZPErjQfTbQe3aDQsQcafEQPD+nqActifK
05-05 22:46:07.583  1833  1855 V GoogleSignatureVerifier: Z0Np0IS9L9kR/wbNvyz6ENwPiTrjV2KRkEjH78ZMcUQXg0L3BYHJ3lc69Vs5Ddf9uUGGMYldX3Wf
05-05 22:46:07.583  1833  1855 V GoogleSignatureVerifier: MBEmh/9iFBDAaTCK
`

Since opengapps detects my device and installs proper version of PlayServices, could it be that this needs to be updated to the latest version?

I used the same setup with previous builds and everything was ok, this PlayService update thing started appearing with the latest AOSP source for my device.

Thanks in advance

**Comment by ticpu** [comment]
I have the same message in ADB logcat. I'm having some GMS crashes, did you find anything useful?

**Comment by ticpu** [comment]
Same Android version, OMNIrom flavor with pico OpenGapps.

Example gms related crash from Twitter:

> 05-14 10:23:17.526  5357  5440 E AndroidRuntime: FATAL EXCEPTION: IntentService[GCMIntentService-49625052041-1]
> 05-14 10:23:17.526  5357  5440 E AndroidRuntime: Process: com.twitter.android, PID: 5357
> 05-14 10:23:17.526  5357  5440 E AndroidRuntime: java.lang.SecurityException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms (has extras) } without permission com.google.android.c2dm.permission.RECEIVE
> 05-14 10:23:17.526  5357  5440 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1245)
> 05-14 10:23:17.526  5357  5440 E AndroidRuntime: 	at android.app.ContextImpl.startService(ContextImpl.java:1222)
> 05-14 10:23:17.526  5357  5440 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:581)
> 05-14 10:23:17.526  5357  5440 E AndroidRuntime: 	at com.google.android.gms.gcm.c.a(Unknown Source)
> 05-14 10:23:17.526  5357  5440 E AndroidRuntime: 	at com.google.android.gms.gcm.c.a(Unknown Source)
> 05-14 10:23:17.526  5357  5440 E AndroidRuntime: 	at com.google.android.gcm.GCMBaseIntentService.c(Twttr:311)
> 05-14 10:23:17.526  5357  5440 E AndroidRuntime: 	at com.google.android.gcm.GCMBaseIntentService.onHandleIntent(Twttr:219)
> 05-14 10:23:17.526  5357  5440 E AndroidRuntime: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
> 05-14 10:23:17.526  5357  5440 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 05-14 10:23:17.526  5357  5440 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
> 05-14 10:23:17.526  5357  5440 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)
> 05-14 10:23:17.528   532  2232 W ActivityManager:   Force finishing activity com.twitter.android/.MainActivity
