### ISSUE TITLE
show the detected Android version also when complaining about it

### ISSUE THREAD

**Issue by muelli** [opengapps/opengapps#312]
I am trying to install the arm64 pico package for Android 5.1 for the CM12.1 image for my TCL M3G (8 May 2016 Size: 49.85 MiB).  The installer complains about the GApps being *only* for Android version 5.1. It does not, however, show what it thinks I have for a version. I am quite confident that I have an Android 5.1, so it would have helped me to see what it thinks it has detected.

**Comment by mfonville** [comment]
Done
