### ISSUE TITLE
Android 6.0 / SDK23 is not recognized as such

### ISSUE THREAD

**Issue by cristisilaghi** [opengapps/opengapps#313]
Hey there. I have a problem with Stock OpenGapps package.

I get "Updater process eneded with ERROR: 20".

I have the issue with the latest version of TWRP (TWRP 3.0.2-1).

My device is SAMSUNG Galaxy S2 (i9100) running CyanogenMod 13 (20160510).

I've attached a screenshot, I hope this is useful.

![screenshot_2016-05-10-09-55-53](https://cloud.githubusercontent.com/assets/2406819/15151354/7402b88a-16d9-11e6-995d-71a21215c973.png)

**Comment by mfonville** [comment]
Could you attach your debug log, or otherwise the /system/build.prop of your device?

**Comment by cristisilaghi** [comment]
I have build.prop: http://pastebin.com/raw/rai1wVxX

**Comment by mfonville** [comment]
@cristisilaghi could you upload the actual file instead a snippet of the content? Because I expect encoding issues.

**Comment by cristisilaghi** [comment]
You may be right.
I will try to see if I encounter same issue with the default build.prop (because I modified the file).
I will report if I will receive same error with a default build.prop, but I can't right now. I will try this tommorow :)

**Comment by cristisilaghi** [comment]
UPDATE: Yeah, you can close this issue.
It seems that with the default build.prop it's working properly.
The issue in my case is very likely to have been regarding file encoding :)

Thank you anyway! :+1:

**Comment by mfonville** [comment]
Ok. Tip for next time when seeking support, please use XDA Forum instead of directly opening an issue. The community there can help you out, leaving more dev time for me.
