### ISSUE TITLE
Why not add .torrent as download?

### ISSUE THREAD

**Issue by ky0ncheng** [opengapps/opengapps#320]
And you can make a snapshot version pre month.

Github raw download url make some errors with AWS cdn always...

**Comment by ngrhd** [comment]
True +1

**Comment by mfonville** [comment]
We let the pre-built downloads run on purpose go via opengapps.org, see http://opengapps.org/blog/post/2016/03/18/the-no-mirror-policy/ for details why.
Also my buildbot lacks the diskspace and upload bandwidth to seed all the packages. Another 'problem' is that most packages are outdated after 1 day, so they won't be seeded for long. And commercial HTTP-to-torrent seeders I have reviewed up till now don't offer the necessary quotas for free. So for the moment this is no go, I am sorry.
