### ISSUE TITLE
Only remove packages that are part of the variant being installed. Unless explicitly defined with a keyword.

### ISSUE THREAD

**Issue by MSF-Jarvis** [opengapps/opengapps#324]
**Only issues related to the code of The Open GApps Project scripts themselves**
If you have found an issue with a pre-built OpenGApps.org package please use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**
- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope _(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))_

_If Open GApps compilation fails:_
- [x] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aopen+is%3Aissue) and has not been discussed before in the list of [closed issues](https://github.com/opengapps/opengapps/issues?q=is%3Aissue+is%3Aclosed)

~_If Open GApps installation fails:_
- [x] Is the issue reproducible using the latest version of your recovery?
- [x] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? _(other recoveries are only best-effort)_~

~_If receiving force closures after Open GApps installation:_
- [x] The issue is **NOT** an error within one of the bundled Google applications itself _(verify by e.g. installing the application from the Play Store instead)_
- [x] The issue is reproducible on clean (=wiped /data/ partition) installation
- [x] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [x] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied~

**Issue description:**
I installed the OpenGapps nano package onto my stock ROM (clean AOSP, Android One second gen MTK variant) to update the core apps like Play Store, Google etc. When I booted back into AOSP, my Google Now Launcher was gone, so was Keep and Gmail.

**Reproduction Steps:**
1. Install OpenGapps nano package over a clean AOSP factory ROM
2. Boot back to find apps mentioned above missing.

**Expected behavior:**

Only the apps the Installer is adding should have been removed

**Observed behavior:**

 But it did a general cleanup from what I can deduce.

**Installation debug log and logcat of FC:**

![Debug log of the Open GApps installation](https://transfer.sh/RrMd3/open-gapps-logs.zip)

**Comment by mfonville** [comment]
Where you apps installed on `/system`? Because Open GApps currently doesn't (and can't) differentiate between wanting to remove an app, or not wanting to update an app. So it removes any app on `/system` that is part of the Open GApps installation options (including the bigger packages).

**Comment by MSF-Jarvis** [comment]
I'm assuming the "Where you" is a typo that means "Were your". Yes, they were all on `/system`, and OpenGapps did kill off all Google Apps it found (Thanks for that, I was being a bit lazy to remove the extra Play Movies and other bloat :p )

**Comment by MSF-Jarvis** [comment]
But I kinda like and use Keep and Gmail, so it's a :( for removing them too...

**Comment by MSF-Jarvis** [comment]
@opengapps/developers is this something we can expect to be _ever_ added into the installer?

**Comment by mfonville** [comment]
@MSF-Jarvis indeed I meant 'were'.
I think we will probably change this yes. The current behaviour is according to how PA GApps behaved, but it does not match people's expectations.
I guess we will do this when we are going to revise the current package sets, names and the config.

I will update the description accordingly.

**Comment by MSF-Jarvis** [comment]
Thanks @mfonville. We should keep this open,no?

**Comment by mfonville** [comment]
@MSF-Jarvis we keep this open as tracking bug

**Comment by MSF-Jarvis** [comment]
@mfonville any headstart with this?

**Comment by mfonville** [comment]
@MSF-Jarvis not yet, some recent health issues have severely slowed down my pace of development :(

**Comment by MSF-Jarvis** [comment]
Looks like this is fixed :)
