### ISSUE TITLE
Script on Download Site not working

### ISSUE THREAD

**Issue by hurzl** [opengapps/opengapps#329]
Never stops "searching"

**Comment by mfonville** [comment]
The GitHub API might have had some downtime, or your might have surpassed the API limit.
Try at a later moment again, if you keep continuing having issues, please use the XDA forum for support.

**Comment by hurzl** [comment]
Neither of the above.

**Comment by mfonville** [comment]
Disable adblockers or other potentially blocking extensions, make sure javascript is enabled. If you keep having issue, please write on the XDA thread.
