### ISSUE TITLE
make failure due to missing blacklist

### ISSUE THREAD

**Issue by MSF-Jarvis** [opengapps/opengapps#332]
**Only issues related to the code of The Open GApps Project scripts themselves**
If you have found an issue with a pre-built OpenGApps.org package please use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [ x ] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [ x ] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [ x ] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aopen+is%3Aissue) and has not been discussed before in the list of [closed issues](https://github.com/opengapps/opengapps/issues?q=is%3Aissue+is%3Aclosed)

**Issue description:**
Generic `make` does not complete 

**Reproduction Steps:**

1. Install android-build-tools using @mfonville's PPA
2. Clone OpenGapps/OpenGapps and do a shallow clone of sources
3. Run `make`

**Expected behavior:**

All packages complete assembling 

**Observed behavior:**

`make` failed with below mentioned error

**Installation debug log and logcat of FC:**

```
Fetching GApps/speech-common from the cache
Fetching GApps/sheets-arm from the cache
Fetching GApps/slides-arm from the cache
Fetching GApps/taggoogle-all from the cache
Fetching GApps/talkback-all from the cache
Fetching GApps/street-arm from the cache
Fetching GApps/translate-arm from the cache
Fetching GApps/youtube-arm from the cache
Fetching GApps/webviewgoogle-arm from the cache
Fetching Optional/swypelibs-lib-arm from the cache
Fetching GApps/zhuyin-arm from the cache
INFO: Total size compressed applications: 737M                          Packaging and signing /root/opengapps/out/open_gapps-arm-6.0-aroma-20160611-UNOFFICIAL.zip...                                                   SUCCESS: Built Open GApps variation aroma with API 23 level for arm as /root/opengapps/out/open_gapps-arm-6.0-aroma-20160611-UNOFFICIAL.zip
--------------------------------------------------------------------
Illegal combination of Platform and API
Makefile:55: recipe for target 'arm64-19-super' failed
make: *** [arm64-19-super] Error 1

real    37m16.003s
user    77m1.254s
sys     11m50.639s
root@build-box:~/opengapps#
```

I believe this is happening due to a flaw in your permutations and combinations algorithm which should blacklist arm64-19 builds since from knowledge, no arm64 devices have been released running Android 4.4

**Comment by mfonville** [comment]
@MSF-Jarvis the prevention of building "the impossible combinations" is only partially handled in the makefile (which only has a simplified mechanism) and partially in the build_gapps.sh

Did the `make` command finish building all valid combinations, or did it end prematurely?

**Comment by MSF-Jarvis** [comment]
It ended prematurely. I only had all the `arm` packages, from API level 19
thru 23, and all variants, but nothing else at all.

**Comment by mfonville** [comment]
@MSF-Jarvis The `exit 1` within the if-statement ended the script too early in this generic `make` call. It should now be fixed.
