### ISSUE TITLE
Google Play Music should replace AOAP Music Player

### ISSUE THREAD

**Issue by aqu0s** [opengapps/opengapps#337]
**Only issues related to the code of The Open GApps Project scripts themselves**
If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

[x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
[x] The issue is part of The Open GApps Project scope _(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))_

_If Open GApps compilation fails:_
[ ] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aopen+is%3Aissue) and has not been discussed before in the list of [closed issues](https://github.com/opengapps/opengapps/issues?q=is%3Aissue+is%3Aclosed)

_If Open GApps installation fails:_
[ ] Is the issue reproducible using the latest version of your recovery?
[ ] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? _(other recoveries are only best-effort)_

_If receiving force closures after Open GApps installation:_
[ ] The issue is **NOT** an error within one of the bundled Google applications itself _(verify by e.g. installing the application from the Play Store instead)_
[ ] The issue is reproducible on clean (=wiped /data/ partition) installation
[ ] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
[ ] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**
Google Play Music should replace AOSP Music Player.

**Reproduction Steps:**
1. Install Cyanogenmod 13 as you would
2. Install OpenGApps as you would (Stock package in this scenario.)

**Expected behavior:**

On first boot any pre-installed music players should be replaced with GPM.

**Observed behavior:**

On first boot there are duplicate music apps.

**Installation debug log and logcat of FC:**

[Debug log of the Open GApps installation](url)

[A logcat of the moment I receive the force closure (if applicable)](url)

**Comment by mfonville** [comment]
@aqu0s you need to include at minimum your debug log, otherwise I can't see which paths are used by the AOSP Music app

**Comment by jawz101** [comment]
Personally I don't want it to.  I'm someone who wants to move _away_ from the cloud for access to my music because it chews up data.  Maybe have it as an advanced option to remove a stock player but not replace it.

**Comment by fenglc** [comment]
@aqu0s  Cyanogenmod 13 Music path is  /system/app/Eleven/Eleven.apk

**Comment by mfonville** [comment]
@fenglc that path is already removed if you use the `cmmusic` keyword.
But you should *not* put these regular keywords between  the ()-brackets. Those ()-brackets are only to remove certain fixed paths (and not for keywords).

**Comment by fenglc** [comment]
Rom: cm-13.0-20160819-SNAPSHOT-ZNH5YAO0IN-bacon
GApps: open_gapps-arm-6.0-stock-20160901
Recovery: twrp-3.0.2-0-bacon

**Steps:**
- Install Cyanogenmod 13
- Install OpenGApps

On first boot there are duplicate music apps.
Google Play Music does not replace CM Music (_com.cyanogenmod.eleven_).

@mfonville Please see my debug logs again.
[open_gapps_debug_logs.tar.gz](https://github.com/opengapps/opengapps/files/451755/open_gapps_debug_logs.tar.gz)

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
