### ISSUE TITLE
Not Able to Flash on 32bit ROM with 64bit cpu n Kernel [Cm13]

### ISSUE THREAD

**Issue by aapav01** [opengapps/opengapps#339]
##############################
  _____   _____   ___   ____  
 /  _  \ |  __ \ / _ \ |  _ \ 
|  / \  || |__) | |_| || | \ \
| |   | ||  ___/|  __/ | | | |
|  \ /  || |    \ |__  | | | |
 \_/ \_/ |_|     \___| |_| |_|
       ___   _   ___ ___  ___ 
      / __| /_\ | _ \ _ \/ __|
     | (_ |/ _ \|  _/  _/\__ \
      \___/_/ \_\_| |_|  |___/
##############################
 
Open GApps mini 6.0 - 20160629
 
- Mounting  /system
 
- Gathering device & ROM information
 
* Incompatible GApps Currently Installed *
 
This Open GApps package can ONLY be installed
on top of an existing installation of Open GApps
or a clean AOSP/CyanogenMod ROM installation,
or a Stock ROM that conforms to Nexus standards.
You must wipe (format) your system partition
and flash your ROM BEFORE installing Open GApps.
 
******* GApps Installation failed *******
 
- Copying Log to /external_sdcard
 
- NO changes were made to your device
 
Installer will now exit...
 
Error Code: 40
cp: can't stat '': No such file or directory
cp: can't stat '/system/default.prop': No such file or directory
cp: can't stat '/data/local.prop': No such file or directory
cp: can't stat '/build.prop': No such file or directory
cp: can't stat '/system/addon.d/70-gapps.sh': No such file or directory
cp: can't stat '/cache/recovery/log': No such file or directory
CANNOT LINK EXECUTABLE: "/sbin/liblog.so" is 64-bit instead of 32-bit
page record for 0xf754902c was not found (block_size=32)
- Unmounting  /system

**Comment by mfonville** [comment]
Please attach at least your debug log (the tar.gz file)
