### ISSUE TITLE
Bluetooth media_button_receiver youtube issue

### ISSUE THREAD

**Issue by ljmellor** [opengapps/opengapps#341]
**Issue description:**
After using the youtube application bluetooth media controls no longer function

**Reproduction Steps:**

1. Use bluetooth media buttons to play music
2. Open youtube and watch a video
3. Attempt to start music via bluetooth again (to no avail)

**Expected behavior:**

Music begins to play and all is joyous.

**Observed behavior:**

Music doesn't begin to play and all is awful

**Installation debug log and logcat of FC:**

To cure this issue I have to edit /data/system/users/0/settings_secure.xml and remove the youtube info from the media_button_receiver line (I replace it with a 1), after this bluetooth works fine again until I play a youtube video.

I noticed that the cm13 team haven't fixed this in months and therefore assumed that it is an issue with opengapps as without that there is no youtube to be had in cm13.

If I'm posting in the wrong place then feel free to tell me politely, I just want this major annoyance fixed (nobody enjoys editing xml in a layby for the sake of listening to music on the go).

**Comment by mfonville** [comment]
Hi @ljmellor,

Unfortunately the issue you reported is something the CM people have to fix :-(
settings_secure.xml is populated by the ROM with values that are chosen by the ROM and by the applications that interacting with Android settings management.
If the default is wrong, it is up to the CM to change that value, if YouTube always sets a wrong value, Google should fix the YouTube app. Or there is a problem in the music+bluetooth app that they are interacting with this settings-value in unexpected way.

I am not sure where, whether it is was Gitter or on XDA, but I think somebody else was experiencing something similar with CM. It might be worth to check out if maybe an unofficial CM spin for your device has a workaround for your issue.

**Comment by ljmellor** [comment]
There are lots of people experiencing the issue. The default value is fine, that gets changed upon playing a video in youtube which in turn screws it up. I guess my fight goes on to Google, goodness help me with that one!

Do you have any suggestions as to where I would begin to report this to them?

**Comment by mfonville** [comment]
You can use the feedback button inside the YT app.

Best would be to verify that the issue happens at stock ROMs too. If those have no issue Google probably won't fix it.
