### ISSUE TITLE
Pulldown menu and Home button

### ISSUE THREAD

**Issue by kronflux** [opengapps/opengapps#342]
Seems currently, (I'm using latest nightly of CyanogenMod 13 and latest nightly of OpenGapps) Gapps is breaking the pulldown menu and the home button.
I've tried flashing just CM and it works perfectly.
I assume it has something to do with the July updates.

**Comment by mfonville** [comment]
Please read the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ#2-im-having-a-problem-with-my-open-gapps-install-what-information-do-you-need-to-help-me) and the support instructions mentioned. You need to use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071) for support requests, directly opening GitHub issues is *not* appreciated.

PS: Please remember to at least include your installation debug log and (if applicable) a logcat when requesting support.


For your problem: on CM you should not remove CMSetupWizard, their pulldown menu breaks if not provisioned by their own setupwizard

**Comment by kronflux** [comment]
sorry about that! should have read before posting. Oddly, I've been removing it for a long time, and never had issues. but I'll give it a try - if it doesn't work I'll go the XDA route, thanks for taking the time to respond, and apologies again!

**Comment by mfonville** [comment]
No problem! :)

**Comment by kronflux** [comment]
tried it, and it worked! really strange, like I said, I've been using the same gapps-config for probably over a year now, never had this issue before. They must have changed something. I did a little searching and it looks like this has happened before, with the same solution. odd that it wasn't a problem for so long.

Thanks again! Cheers!

**Comment by Bonoboo** [comment]
@kronflux 
You mentioned solution.
Please, can you share it?

**Comment by kronflux** [comment]
@Bonoboo, please read the full issue history before posting questions. This was very clearly answered by @mfonville.

> For your problem: on CM you should not remove CMSetupWizard, their pulldown menu breaks if not provisioned by their own setupwizard

**Comment by Bonoboo** [comment]
@kronflux, thanks for quick answer.
Sorry, somehow missed this.

Yes, I know CM now depends from CMSetupWizard.
But anyway one user had same problem without config or touching that APK.
He wipes /data and /system, flashes CM13 Nightly (nicki, Xperia M), latest pico gapps, completes setup wizard and still can't pulldown notification bar.
Problem resolved only after using 21.07 pico gapps.

Only then Google pointed me to this page:
https://github.com/opengapps/opengapps/wiki/Notes-for-CMSetupWizard
I'm sure, adding _cm_setup_wizard_completed_ can resolve problem.
Previously he tried only _device_provisioned_ and _user_setup_complete_

Only question is why this happened.
No recent CM commits related to this.
Anyway thanks too all.
