### ISSUE TITLE
trolls removed the FAQ?

### ISSUE THREAD

**Issue by mrexodia** [opengapps/opengapps#343]
Over [here](https://github.com/opengapps/opengapps/wiki/_history) commits 5c7b31e and ec6084b destroyed pages of the Wiki. Was this intentional or just griefing? I tried to revert the commits, but I cannot push directly to the Wiki.

**Comment by NicholasBuse** [comment]
I grabbed the two files in question from opengapps/opengapps.wiki@5c7b31e and opengapps/opengapps.wiki@ec6084b and made commits of opengapps/opengapps.wiki@44ea12cb02d48d42a8ec5cfd45e149a074cdf2ef and opengapps/opengapps.wiki@9f452d792f7e9580da4d808399124adb69a5f00d

@mfonville, This can be closed now...

**Comment by mrexodia** [comment]
Thanks!
