### ISSUE TITLE
Allow skip of initial setup

### ISSUE THREAD

**Issue by ktechmidas** [opengapps/opengapps#345]
Hello,

When I first install gapps then factory reset it wants a connection to Google but doesn't allow me to set up a VPN beforehand. The HTTP proxy isn't listened to, which seems to be the only 'bypass' option I has. Instead it decides to "Check Connection" for 2 minutes, before giving up and restarting the whole process.

This is a problem in countries like China, where Google is blocked and I need to setup shadowsocks before I connect to Google.

**Comment by mfonville** [comment]
Did you already try the clockwise corner tapping to bypass the setupwizard?
(as shown in http://pocketnow.com/how-to/android-quick-tip-how-to-bypass-touch-the-android-to-begin-video )

**Comment by ktechmidas** [comment]
Excellent, it skipped! Thank you, been trying to get it working for a while now...

**Comment by mfonville** [comment]
@ktechmidas great that it worked. Maybe you'd be willing to write something about it for the wiki to help others in the same situation? :-)

**Comment by mfonville** [comment]
Thanks!
