### ISSUE TITLE
Setup FC after (clean) flash

### ISSUE THREAD

**Issue by yooouuri** [opengapps/opengapps#347]
**Issue description:**
The Google setup FC after a clean flash

**Reproduction Steps:**

1. Install CM and wipe dalvik/cache
2. Install Gapps (aroma, choose Chrome only) and wipe dalvik/cache
3. Let the Phone boot, after a few steps the Setup FC

**Expected behavior:**

Using the Google setup to add your account etc..

**Observed behavior:**

The Setup FC after a few steps

**Installation debug log and logcat of FC:**

Not able to get the logcat, wil try later.

**Comment by mfonville** [comment]
Please read the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ#2-im-having-a-problem-with-my-open-gapps-install-what-information-do-you-need-to-help-me) and the support instructions mentioned. You need to use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071) for support requests, directly opening GitHub issues is *not* appreciated.

PS: Please remember to at least include your installation debug log and (if applicable) a logcat when requesting support.
