### ISSUE TITLE
Apps was empty, file size 0

### ISSUE THREAD

**Issue by vounter** [opengapps/opengapps#349]
**Issue description:**
[Short description of problem here]
after install i doesnt have a error. i just have a empty apps

`# Begin Open GApps Install Log
------------------------------------------------------------------
            ROM Android version | 7.0
                   ROM Build ID | aosp_hammerhead-userdebug 7.0 NRD90M eng.sansan.20160903.075508 test-keys
          ROM Version increment | eng.sansan.20160903.075508
                ROM SDK version | 24
        ROM/Recovery modversion | OmniROM-5.0.2-20150623-hammerheaad-HOMEMADE
                Device Recovery | TWRP 2.8.7.1
                    Device Name | hammerhead
                   Device Model | AOSP on HammerHead
                    Device Type | phone
                     Device CPU | armeabi-v7a,armeabi
             Installer Platform | arm
                   ROM Platform | arm
           Display Density Used | 480
                   Install Type | Dirty[Data NOT Wiped]
             Smart ART Pre-ODEX | false
Google Camera already installed | false
          FaceUnlock Compatible | true
       Google Camera Compatible | true
      New Camera API Compatible | true[whitelist]
          Current GApps Version | No GApps Installed
       Installing GApps Zipfile | /sdcard/open_gapps-arm-7.0-aroma-20160903.zip
       Installing GApps Version | 20160903
          Installing GApps Type | aroma
                    Config Type | exclude
             Using gapps-config | /tmp/aroma/.gapps-config
      Remove Stock/AOSP Browser | true[default]
       Remove Stock/AOSP Camera | false[NO_CameraGoogle]
        Remove Stock/AOSP Email | true[default]
      Remove Stock/AOSP Gallery | true[default]
     Remove Stock/AOSP Launcher | true[default]
      Remove Stock/AOSP MMS App | true[default]
     Remove Stock/AOSP Pico TTS | true[default]
         Ignore Google Contacts | false
           Ignore Google Dialer | false
         Ignore Google Keyboard | false
Ignore Google Package Installer | false
          Ignore Google NFC Tag | false
          Ignore Google WebView | false
         Total System Size (KB) | 1033516
         Used System Space (KB) | 658016
        Current Free Space (KB) | 375500
   Post Install Free Space (KB) | 532572   << See Calculations Below
------------------------------------------------------------------
# End Open GApps Install Log

WARNING: Google Camera has/will not be installed as requested. Google Camera
can only be installed during a Clean Install or as an update to an existing
GApps Installation.

!!! WARNING !!! - Duplicate files were found between your ROM and this GApps
package. This is likely due to your ROM's dev including Google proprietary
files in the ROM. The duplicate files are shown in the log portion below.

# Begin GApps <> ROM Duplicate File List
/system/vendor/lib/libfrsdk.so
# End GApps <> ROM Duplicate File List

# Begin GApps Size Calculations
------------------------------------------------------------------
  TYPE  |         DESCRIPTION        |      SIZE |   TOTAL
        |         Current Free Space |    375500 |  375500
 Remove |             Existing GApps | +    1384 |  376884
 Remove |             Obsolete Files | +    1416 |  378300
 Remove |                    browser | +     104 |  378404
 Remove |            calculatorstock | +     976 |  379380
 Remove |              calendarstock | +    4416 |  383796
 Remove |                 clockstock | +    7452 |  391248
 Remove |              contactsstock | +   10544 |  401792
 Remove |                dialerstock | +   14632 |  416424
 Remove |                      email | +   15080 |  431504
 Remove |              exchangestock | +       0 |  431504
 Remove |                    gallery | +   10048 |  441552
 Remove |              keyboardstock | +   19112 |  460664
 Remove |                   launcher | +    4600 |  465264
 Remove |                        mms | +   16096 |  481360
 Remove |      packageinstallerstock | +    8404 |  489764
 Remove |                    picotts | +    6696 |  496460
 Remove |                  provision | +      44 |  496504
 Remove |                   tagstock | +    1120 |  497624
 Remove |               webviewstock | +   44164 |  541788
Install |                       Core | -       0 |  541788
Install |                 androidpay | -       0 |  541788
Install |                      books | -       0 |  541788
Install |           calculatorgoogle | -       0 |  541788
Install |             calendargoogle | -       0 |  541788
Install |                     chrome | -       0 |  541788
Install |                clockgoogle | -       0 |  541788
Install |                 cloudprint | -       0 |  541788
Install |             contactsgoogle | -       0 |  541788
Install |            dialerframework | -       0 |  541788
Install |               dialergoogle | -       0 |  541788
Install |                    dmagent | -       0 |  541788
Install |                       docs | -       0 |  541788
Install |                      drive | -       0 |  541788
Install |                       ears | -       0 |  541788
Install |                      earth | -       0 |  541788
Install |             exchangegoogle | -       0 |  541788
Install |                 facedetect | -       0 |  541788
Install |                 faceunlock | -       0 |  541788
Install |                    fitness | -       0 |  541788
Install |                        gcs | -       0 |  541788
Install |                      gmail | -       0 |  541788
Install |                  googlenow | -       0 |  541788
Install |                 googleplus | -       0 |  541788
Install |                  googletts | -       0 |  541788
Install |                   hangouts | -       0 |  541788
Install |                    hotword | -       0 |  541788
Install |                      indic | -       0 |  541788
Install |                   japanese | -       0 |  541788
Install |                       keep | -       0 |  541788
Install |             keyboardgoogle | -       0 |  541788
Install |                     korean | -       0 |  541788
Install |                       maps | -       0 |  541788
Install |                  messenger | -       0 |  541788
Install |                     movies | -       0 |  541788
Install |                      music | -       0 |  541788
Install |                  newsstand | -       0 |  541788
Install |                 newswidget | -       0 |  541788
Install |     packageinstallergoogle | -       0 |  541788
Install |                     photos | -       0 |  541788
Install |                     pinyin | -       0 |  541788
Install |                  playgames | -       0 |  541788
Install |               printservice | -       0 |  541788
Install |                  projectfi | -       0 |  541788
Install |                     search | -       0 |  541788
Install |                     sheets | -       0 |  541788
Install |                     slides | -       0 |  541788
Install |                     speech | -       0 |  541788
Install |                     street | -       0 |  541788
Install |                  taggoogle | -       0 |  541788
Install |                   talkback | -       0 |  541788
Install |                  translate | -       0 |  541788
Install |                  vrservice | -       0 |  541788
Install |              webviewgoogle | -       0 |  541788
Install |                    youtube | -       0 |  541788
Install |                     zhuyin | -       0 |  541788
        |               Buffer Space | -    9216 |  532572
------------------------------------------------------------------
                        Post Install Free Space |  532572
------------------------------------------------------------------

# End GApps Size Calculations

# Begin User's gapps-config

# End User's gapps-config
`

**Comment by mfonville** [comment]
yes, I made a fix for this yesterday: https://github.com/opengapps/opengapps/commit/3a9576e8ad20bad321a947a4d00b1286c0e192a7
fix will be in the next builds.
