### ISSUE TITLE
Bug in The GApps ( 09/09/2016 and 10/10/2016 )

### ISSUE THREAD

**Issue by LS002** [opengapps/opengapps#351]
By downloading the GAPPS days 09/09 and 10/10, I noticed a BUG very annoying and persistent, every time appears on the screen ''the synchronizer google contacts stopped working'' how can I fix this BUG ?

**Comment by mfonville** [comment]
please use XDA forum for support requests; the answer to your problem can be found here: http://forum.xda-developers.com/showpost.php?p=68623086&postcount=3125

Also *never* post without including any debug logs please.
