### ISSUE TITLE
Keyboard crash

### ISSUE THREAD

**Issue by dzfacts** [opengapps/opengapps#354]
Google keyboard is crashing on settings screen on my Nexus 5, on 6.0.1 and 7.0 ROMs, installing an update didnt fix the problem, I had no other option then a re-flash.

**Comment by mfonville** [comment]
Please read the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ#2-im-having-a-problem-with-my-open-gapps-install-what-information-do-you-need-to-help-me) and the support instructions mentioned. You need to use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071) for support requests, directly opening GitHub issues is *not* appreciated.

PS: Please remember to at least include your installation debug log and (if applicable) a logcat when requesting support.
