### ISSUE TITLE
Incorrect SELinux labels after flashing OpenGapps

### ISSUE THREAD

**Issue by luk1337** [opengapps/opengapps#355]
**Only issues related to the code of The Open GApps Project scripts themselves**
If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

[ ] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
[ ] The issue is part of The Open GApps Project scope _(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))_

_If Open GApps compilation fails:_
[ ] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aopen+is%3Aissue) and has not been discussed before in the list of [closed issues](https://github.com/opengapps/opengapps/issues?q=is%3Aissue+is%3Aclosed)

_If Open GApps installation fails:_
[ ] Is the issue reproducible using the latest version of your recovery?
[ ] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? _(other recoveries are only best-effort)_

_If receiving force closures after Open GApps installation:_
[ ] The issue is **NOT** an error within one of the bundled Google applications itself _(verify by e.g. installing the application from the Play Store instead)_
[ ] The issue is reproducible on clean (=wiped /data/ partition) installation
[ ] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
[ ] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**
So I am labeling some stuff in /system/lib and after flashing OpenGapps package it's relabeled to u:object_r:system_file:s0

**Reproduction Steps:**
1. Flash a CM build that labels anything in /system/lib/
2. Flash OpenGapps
3. Label is set to u:object_r:system_file:s0 instead of what it was set before

**Expected behavior:**

I guess labels should be set on specific files not recursively on whole /system/lib

**Observed behavior:**

Labels are restored recursively on whole /system/lib as seen here: https://github.com/opengapps/opengapps/blob/master/scripts/inc.installer.sh#L2251

**Installation debug log:**

[Labels before and after installing Open Gapps](http://hastebin.com/ucecahiyom.pl)

**Comment by TheCrazyLex** [comment]
Bump. This is a pretty big issue actually. @mfonville
