### ISSUE TITLE
AOSP   nexus6p   build with opengapp   failed

### ISSUE THREAD

**Issue by huml126** [opengapps/opengapps#359]
I follow this  https://github.com/opengapps/aosp_build to build with opengapp ,but make  failed!

AOSP build  almost 30 minutes . Then these failed!

FAILED: /bin/bash -c "(rm -f out/target/product/angler/obj/APPS/AndroidForWork_intermediates/package.apk ) && (cp  out/target/product/angler/obj/APPS/AndroidForWork_intermediates/package.apk ) && (if (zipinfo out/target/product/angler/obj/APPS/AndroidForWork_intermediates/package.apk 'lib/*.so' 2>/dev/null | grep -v ' stor ' >/dev/null) ; then rm -rf out/target/product/angler/obj/APPS/AndroidForWork_intermediates/uncompressedlibs && mkdir out/target/product/angler/obj/APPS/AndroidForWork_intermediates/uncompressedlibs; unzip out/target/product/angler/obj/APPS/AndroidForWork_intermediates/package.apk 'lib/*.so' -d out/target/product/angler/obj/APPS/AndroidForWork_intermediates/uncompressedlibs && zip -d out/target/product/angler/obj/APPS/AndroidForWork_intermediates/package.apk 'lib/*.so' && ( cd out/target/product/angler/obj/APPS/AndroidForWork_intermediates/uncompressedlibs && find lib -type f | sort | zip -D -X -0 ../package.apk -@ ) && rm -rf out/target/product/angler/obj/APPS/AndroidForWork_intermediates/uncompressedlibs; fi ) && (if ! out/host/linux-x86/bin/zipalign -c -p 4 out/target/product/angler/obj/APPS/AndroidForWork_intermediates/package.apk >/dev/null ; then mv out/target/product/angler/obj/APPS/AndroidForWork_intermediates/package.apk out/target/product/angler/obj/APPS/AndroidForWork_intermediates/package.apk.unaligned; out/host/linux-x86/bin/zipalign -f -p 4 out/target/product/angler/obj/APPS/AndroidForWork_intermediates/package.apk.unaligned out/target/product/angler/obj/APPS/AndroidForWork_intermediates/package.apk.aligned; mv out/target/product/angler/obj/APPS/AndroidForWork_intermediates/package.apk.aligned out/target/product/angler/obj/APPS/AndroidForWork_intermediates/package.apk; fi )"
cp: missing destination file operand after `out/target/product/angler/obj/APPS/AndroidForWork_intermediates/package.apk'
Try `cp --help' for more information.
.....
ninja: build stopped: subcommand failed.
make: *** [ninja_wrapper] Error 1

![image](https://cloud.githubusercontent.com/assets/10299866/19230465/357b936a-8f07-11e6-8dea-b7955df0ef96.png)

**Comment by Blystad** [comment]
Hmm, @mfonville have the com.google.android.androidforwork package disappeared?

**Comment by huml126** [comment]
all the build log file in the follow
[log.txt](https://github.com/opengapps/opengapps/files/519197/log.txt)

**Comment by mfonville** [comment]
@Blystad yes, it was purged some time ago, because it has been abandoned by Google and not been bundled on stock ROMs for quite some time.

**Comment by Blystad** [comment]
Should be fixed with https://github.com/opengapps/aosp_build/commit/bf18445100c5aeee921b70947425dceaccc928c0

**Comment by huml126** [comment]
Thanks very much !  but  make success. Also ,have such problem "system image is out of space", I follow this
[system image is out of space](https://github.com/opengapps/aosp_build/issues/13)

make sucess #13

**Comment by Blystad** [comment]
Specify a smaller `GAPPS_VARIANT` - e.g. `micro` or `mini`.
