### ISSUE TITLE
There isn't a single hint in the faq or wiki on how to determine your devices architecture.

### ISSUE THREAD

**Issue by MrStonedOne** [opengapps/opengapps#362]
Title says it all.

**Comment by deadman96385** [comment]
If your device has a intel cpu its most likely a x86 (There are almost no x86_64 currently)
If your device has a non 64 bit qualcomm cpu its most likely arm
If your device is newer and has a 64 bit qualcomm cpu its most likely arm64

**Comment by USBhost** [comment]
uname -m

In terminal

**Comment by mfonville** [comment]
Many phones also show it in Settings -> About Phone, and there are many apps that provide this information and it can also be found in the build.prop of the ROM.

The labels on opengapps.org already provide some hints, which one to pick. If you think the documentation can be improved to help other people, please feel free to edit the wiki. Community collaboration is key!
