### ISSUE TITLE
Google Photos recognizes phone as Pixel

### ISSUE THREAD

**Issue by m-dar** [opengapps/opengapps#366]
I installed the Aroma package on the Moto G (xt1032), running CM13 nightly 22/10. After downloading the Google Photos app, it shows that I have a Pixel phone and tries to give me free storage. Its identical to the issue mentioned here: http://www.reddit.com/r/nexus6p/comments/58pih4/_/

**Comment by mfonville** [comment]
Could you remove these 2 lines from `/system/etc/sysconfig/nexus.xml` and report back to me?
```
<feature name="com.google.android.apps.photos.NEXUS_PRELOAD" />
<feature name="com.google.android.apps.photos.nexus_preload" />
```

**Comment by m-dar** [comment]
It worked, thanks!

**Comment by mfonville** [comment]
Ok, I will fix that in our defaults
