### ISSUE TITLE
Busybox segfaults with error 139

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#367]
During install at a Samsung Galaxy Tab 3 10.1 LTE the installer crashes, error 139.
Googling for the error points at a segfault (possibly during the mount operation?)

If user uses an older opengapps version, with the older busybox, the problem does not occur. user will upload his debug logs below.

@yashdsaraf

**Comment by Lucamenca16** [comment]
Hi at all i uploading the file
[open_gapps_log.tar.gz](https://github.com/opengapps/opengapps/files/555591/open_gapps_log.tar.gz)

**Comment by mfonville** [comment]
(ps: to @yashdsaraf should I maybe at certain cpu-capability detection commands to the debug logger?)

**Comment by yashdsaraf** [comment]
@Lucamenca16 Could you please flash [this](https://dl.dropboxusercontent.com/s/8fsw8m020e8fcsk/bb-debug.zip) and report back with __/sdcard/bb-checker.log__ (if /sdcard is not present or not accessible, /data or /cache will be used for bb-checker.log)

**Comment by Lucamenca16** [comment]
@yashdsaraf Hello i flash this file now one moment please. Ok i have TWRP.

**Comment by Lucamenca16** [comment]
This is the file
[bb-checker.tar.gz](https://github.com/opengapps/opengapps/files/558106/bb-checker.tar.gz)

**Comment by yashdsaraf** [comment]
@mfonville As you can see in the log attached above by @Lucamenca16 , busybox is not causing any errors. The _busybox.old_ section consists the output of busybox 1.25.0 and _busybox.new_ consists of busybox 1.25.1 (the one updated in the opengapps source)

**Comment by mfonville** [comment]
hmm, based on what I did find on Google, could we let the busybox perform `mount` commands on the various partitions ("/cache" "/data" "/persist" "/system" "/vendor") ? That is I think the most suspicious command that might cause the error.

Because the only change to the script between the two trials that @Lucamenca16 did do, one with failure, and one with success, was the busybox update :-/

**Comment by yashdsaraf** [comment]
@Lucamenca16  As @mfonville mentioned the error might be in one of the commands in busybox. So I've made [this](https://dl.dropboxusercontent.com/s/smr1qcl5c86zg23/bb-debug.zip) flashable zip. It will cross check the working of all applets with the older busybox and log the discrepancies if any. The flashing instructions are same as before, and do report back with the **bb-checker.log**.

**Comment by mfonville** [comment]
@Lucamenca16 could you try if this x86 package (6.0 pico) does work correctly for you?

https://dl.dropboxusercontent.com/u/7278254/open_gapps-x86-6.0-pico-20161030-UNOFFICIAL.zip

**Comment by Lucamenca16** [comment]
@mfonville Yes i try now, sorry for i'm too late.

**Comment by Lucamenca16** [comment]
The flash of the file is good.

**Comment by Lucamenca16** [comment]
@mfonville Can you send me the super pack of the file?? Thanks so much.

**Comment by mfonville** [comment]
@Lucamenca16 please hang around for some more time, we will give another file to test with.
If that one works, it will go into the daily and then you will have a super package tomorrow ;)

**Comment by Lucamenca16** [comment]
@mfonville Ok much thanks :)

**Comment by Lucamenca16** [comment]
@mfonville Impossible to open HOME in Android. What can i do?

**Comment by Xpertzone** [comment]
@Lucamenca16, @mfonville Pico, nano, micro, mini, full set properly. It is not set only stock and super. It all started after the added Pixel Launcher.

**Comment by mfonville** [comment]
@Lucamenca16 could you please test this package?
https://dl.dropboxusercontent.com/u/7278254/open_gapps-x86-6.0-pico-20161031-UNOFFICIAL.zip

**Comment by Lucamenca16** [comment]
@mfonville Yes i'm flashing the file

**Comment by Lucamenca16** [comment]
@mfonville Nothing the flash ok but same error in android

**Comment by Xpertzone** [comment]
[open_gapps_log.unoficial_x86_pico.zip](https://github.com/opengapps/opengapps/files/562563/open_gapps_log.unoficial_x86_pico.zip)

**Comment by yashdsaraf** [comment]
@Xpertzone Was the installation successfull?

**Comment by Lucamenca16** [comment]
the Installation is successfull but in Android i receve this error: Impossible to start HOME

**Comment by mfonville** [comment]
@Lucamenca16 ok, thanking you for flashing the file. So that fixes the busybox issue then.

The issue with your HOME problem I cannot help you with (at this moment), for that you can post a logcat (and debug logs) in the XDA Forum where the rest of the community can probably help you further.

**Comment by Xpertzone** [comment]
@yashdsaraf 
[recovery.zip](https://github.com/opengapps/opengapps/files/562634/recovery.zip)
Pico, nano, micro, mini, full set properly. It is not set only stock and super. It all started after the added Pixel Launcher. Debug log gapps 0byte, i dont know
