### ISSUE TITLE
Pixel Launcher Not Installing In Aroma

### ISSUE THREAD

**Issue by adamdagan7** [opengapps/opengapps#369]
Hello,
Selecting Pixel launcher in latest aroma package (29/10) will not install it.
Seems to be because something is commented out in the scripts.
See lines 571-587 and 637-641 in 
https://github.com/opengapps/opengapps/blob/master/scripts/inc.aromadata.sh

**Comment by mfonville** [comment]
Ah, yes you are right, forgot to uncomment those when they were going live with 7.1
