### ISSUE TITLE
Missing google system webview

### ISSUE THREAD

**Issue by ilmich** [opengapps/opengapps#372]
Hi,

is there a reason within the exclusion of google system webview from all variant of opengapps!?

Cheers
Michele

**Comment by mfonville** [comment]
In stock and larger google webview is available

**Comment by Rikk** [comment]
Was to ask the same. I think it would be good to have it in most packages (maybe all except Pico?).
Stock WebView doesn't get updated by Play Store. This plus the fact many browsers rely on WebView could be a vector for security issues.
But, considering Internet is used by almost every smartphone user, I think it could be considered enough important to have it on all packages replacing stock.

**Comment by USBhost** [comment]
@Rikk 

A user can just install it from Google play.

**Comment by Rikk** [comment]
Yes, but imo it is not obvious for unskilled users. I believe most will think that the browser he uses is not actually just a skin for WebView; will this kind of user ever search Store for it?

**Comment by mfonville** [comment]
@Rikk not all ROMs support the custom webview (yet); but we will try to bring it to probably also some smaller package flavours when revising the package' contents.
