### ISSUE TITLE
Setup Wizard FC Problem In PURE AOSP 7.1 Rom 

### ISSUE THREAD

**Issue by LeMon-TheGreenFish** [opengapps/opengapps#373]
**Setup wizerd force stop problem in PURE AOSP 7.1 ROM **

**Issue description:**

[When I Install AOSP 7.1 ROM FULLY FIXED ROM without camera focus bugs but when I install mini,nano,Pico,micro Open GApps in My AOSP 7.1 ARM version then it not work..... After turn on device it say that setup wizard FC............. So please help Me and my friends who facing same issue please]

**Comment by mfonville** [comment]
Please read the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ#2-im-having-a-problem-with-my-open-gapps-install-what-information-do-you-need-to-help-me) and the support instructions mentioned. You need to use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071) for support requests, directly opening GitHub issues is *not* appreciated.

PS: Please remember to at least include your installation debug log and (if applicable) a logcat when requesting support.
