### ISSUE TITLE
Install pixel launcher and also keep stock launcher in super package

### ISSUE THREAD

**Issue by kaushikyash** [opengapps/opengapps#377]
I am installing super package but in this package the now and pixel launcher replace the stock launcher which I don't want to, also I want to keep AOSP camera app and skip installation of Google camera how can I do this?

**Comment by robinkooli** [comment]
Use aroma package or read this wiki page for manual ways to remove apps from installing
https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options

**Comment by mfonville** [comment]
ty for answering it @robinkooli
