### ISSUE TITLE
Unnecessary GMS apk

### ISSUE THREAD

**Issue by Displax** [opengapps/opengapps#378]
[This](https://github.com/opengapps/arm/tree/master/priv-app/com.google.android.gms/20/240) GMS variant (534) is for Android Wear devices. I don`t think you need it.

**Comment by mfonville** [comment]
Thanks for the notice; I think we will track it nonetheless, but maybe we have to mark it as 'wear' or so.
I will look into it when I'll find some time :)

CC @NicholasBuse

**Comment by mfonville** [comment]
I now added explicit detection of the watch variant for GMS: https://github.com/opengapps/opengapps/commit/f8f3d1b54047c1d67e4d4f195caadd0b01894a6e
