### ISSUE TITLE
Doesn't recognize it has root permissions

### ISSUE THREAD

**Issue by ghctim** [opengapps/opengapps#379]
I have installed the app on CM 12.1 and I have granted it root permissions but it doesn't recognize this.  When I try to install it tells me I must grant it root access but when I look at the APK permissions in CM12.1, it is already granted root

**Comment by ghctim** [comment]
then I installed it as a system app and I am still getting the same error

**Comment by mfonville** [comment]
@ghctim Issues with the opengapps.org app should be reported here: https://github.com/opengapps/opengapps-app-support/issues

This bugtrackers is for the open gapps project scripts.
