### ISSUE TITLE
stable branch

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#38]
After the multi dpi is in place, I would want to branch of stable builds, which will only include tested code. And should reduce the amount of necessary 'daily' releases to the point of 'only' when Google updates an app. And a branch where the experimental development will continue and later be backported.
This should make the gapps more stable and attractive to a larger community.

What are the thoughts of the other developers on this?

TODO:
- [x] Let report_sources create a hash per architecture's packages that are used for a build
- [x] Change buildbot to look for report_sources hash per architecture
- [x] Trigger build per architecture if hash has changed
- [x] Upload builds to an architecture's own releases
- [x] Let the website check the architecture's release pages for the latest builds, not the global one
- [x] Aggegrate the RSS feeds of each architecture's release page into one stream to be used for PushBullet and Twitter (and also RSS itself, to be integrated on the website)
- [x] Mark the releases as stable

**Comment by rapperskull** [comment]
That's obviously a good idea. Developing in another branch help the developers and the users. We can merge the developer branch with master on Update Wednesday so that the new builds will be generated only when needed.

**Comment by mfonville** [comment]
about timing the updates of Google's things: I could split out the release packages of each architecture per repository (so the 'arm' packages attached to the 'arm' sources repository).
And only build their releases if their own repository or if 'all' is updated.

**Comment by mfonville** [comment]
I am now thinking, that updating the 'arm' sources could also imply a new arm64 build, if it is a 'fall back' package.
I think I might have to write a report_sources-derived script that could simply check if any package that is used in a specific architecture's build has been updated, which would then trigger the creation of a new release.

**Comment by rapperskull** [comment]
That can also help in the creation of the automatic changelog, listing all updated apps.

**Comment by mfonville** [comment]
I made report_sources.sh now able to analyze all packages used for an architecture (and api level) build and publish its findings in a hash.

So the next step is that my buildbot will analyze these hashes to determine if a new build will be done for an architecture.
- [ ] Change buildbot to look for report_sources hash per architecture
- [ ] Trigger build per architecture if hash has changed
- [ ] Upload builds to an architecture's own releases
- [ ] Let the website check the architecture's release pages for the latest builds, not the global one
- [ ] Aggegrate the RSS feeds of each architecture's release page into one stream to be used for PushBullet and Twitter (and also RSS itself, to be integrated on the website)
- [ ] Mark the releases as stable

**Comment by mfonville** [comment]
So, I prepared a version of the buildbot that can publish to the architecture's repositories. So that we can create seperate 'last release's for each architecture variants. It is instructed to only build a new version of all android versions if something changes for the most recent android versions, ergo, if 5.1 gets an update, all versions will be rebuild and published.

I now have to adjust the website to be to query each of these architecure's repositories, instead of only the opengapps repository, for the latest release.

Meanwhile I thought, it would also a good moment, when we have multidpi stable, to mark that moment those builds as 'release'-ready instead of as a pre-release.

**Comment by mfonville** [comment]
I have everything for this now staged, so I hope it can go live tomorrow.

**Comment by mfonville** [comment]
Everything is online, stable is ready to go!

**Comment by mfonville** [comment]
A note to all @opengapps/developers ; with the stable branch in place, please don't commit directly to 'master' anymore if you are developing new code. Fork it into a different branch, test it, and only if it is found to be working it should be pulled into master.
