### ISSUE TITLE
I can't install Google Clock

### ISSUE THREAD

**Issue by szhu** [opengapps/opengapps#380]
**Issue description:**

I can't install Google Clock.

**Reproduction Steps:**

1. Use recovery twrp-3.0.2-2-bullhead.img
2. Wipe /system
3. Install cm-14.1-20161111-NIGHTLY-bullhead.zip
4. Install open_gapps-arm64-7.1-aroma-20161111.zip
5. Choose to install Google Clock and remove stock clock.
6. Wipe cache and dalvik-cache
7. Reboot

**Expected behavior:**

Google Clock is installed.

**Observed behavior:**

- There is no clock app.
- I cannot install Google Clock from the Play Store (Error code: -505)
- I cannot sideload a Google Clock apk:`"Attempt to re-install com.google.android.deskclock without first uninstalling package running as com.android.deskclock"`
- `adb shell pm list packages` doesn't show any clock apps.
- /system/app/DeskClock is removed and /system/app/PrebuiltDeskClockGoogle is added.
- When I copy /system/app/PrebuiltDeskClockGoogle to /sdcard and open it, Package installer says "The package appears to be corrupt."

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

Debug log:
https://gist.github.com/szhu/53cc000b5bbcf1820a5f275e0006789f

**Comment by mfonville** [comment]
Would you mind to test with another packages than Aroma, but with a '.gapps-config.' file instead?
Also, could you check if the clock app is also not shown in the list at settings -> apps -> show system apps?

**Comment by szhu** [comment]
Clock app is not shown.

Is there a generator for `.gapps-config` or can you make me one? I understand aroma but the `.gapps-config` is kind of long, even though it supports pretty much the same options.

**Comment by mfonville** [comment]
@szhu if you install the 'mini' package (or a larger one) the clock will be installed without making the `.gapps-config`; would it be possible for you to test with that package?

**Comment by szhu** [comment]
This is my personal device and I didn't want to risk losing app data for the apps that would become uninstalled as a result of installing a smaller package, so instead I took the time to figure out how to use `gapps-config`.

And the verdict: Clock is still not installed.

`adb shell ls /system/app/PrebuiltDeskClockGoogle`: yes
`adb shell pm list packages | grep -F .clock`: no
In Settings > Apps? no

**Comment by windrof123** [comment]
Exact same problem with CM 14.1-20161202-nightly-m8

**Comment by mfonville** [comment]
Very interesting; because the Clock app is for all Android versions (4.4 and up) the same APK.
So that it fails on only 7.1 is a weird situation.

Could you get a logcat that includes the logs of booting the device? It might give us more information why packagemanager doesn't process the APK.

**Comment by dakoslug** [comment]
Same problem with the latest osprey CM14.1 nightly.

**Comment by TheMic** [comment]
I have the same issue... OP2 with last CM14.1 nightly

**Comment by ZWindL** [comment]
Same issue CM 14.1 on Nubia z7 mini(nx 507j), is there any possible to reinstall the stock clock again?

**Comment by mfonville** [comment]
if **no-one** provides *any* I will never be able to even investigate this issue

**Comment by szhu** [comment]
ok @mfonville here you go!

https://gist.github.com/szhu/e78de8c05fa3b1c60d1538ceb491b311

**Comment by szhu** [comment]
Also! Here's the logcat if I copy PrebuiltDeskClockGoogle.apk elsewhere and try to sideload it:

```
12-13 12:56:55.533   869  2940 E PackageInstaller: Commit of session 225627731 failed: Failed to collect certificates from /data/app/vmdl225627731.tmp/PackageInstaller: META-INF/CERT.SF indicates /data/app/vmdl225627731.tmp/PackageInstaller is signed using APK Signature Scheme v2, but no such signature was found. Signature stripped?
12-13 12:56:55.542 13488 13488 D InstallAppProgress: Installation error code: 4
```

**Comment by ZWindL** [comment]
@mfonville And here's mine.
[my .gapps_config](https://gist.github.com/ZWindL/c451a91519688bd53d5d5e2bcdb7d8fe)
[open_gapps_debug_logs.tar.gz](https://github.com/opengapps/opengapps/files/650720/open_gapps_debug_logs.tar.gz)
[open_gapps_log.txt](https://github.com/opengapps/opengapps/files/650721/open_gapps_log.txt)

**Comment by szhu** [comment]
@ZWindL, while I'm sure your help is appreciated, I think @mfonville was looking for the device startup logs, not the GApps install logs. We've basically already determined that the installer copies the files to the correct location, we just need to know why the system can't process it on boot. 

> Could you get a logcat that includes the logs of booting the device? It might give us more information why packagemanager doesn't process the APK.

**Comment by ZWindL** [comment]
@szhu Ahh.... my fault... I misunderstanded. Sorry for that.

**Comment by mfonville** [comment]
Thank you for the log.

It seems that the Packagemanager is sort of 'surprised' that the AOSP one is gone, and refuses to process the Google one.

I have the suspicion that CyanogenMod's platform extension is at fault.

Could you try to remove the following files and test if the clock then does work (and if not, collect the logcat again):
```
/system/framework/org.cyanogenmod.platform-res.apk
/system/framework/org.cyanogenmod.platform.jar
```

**Comment by szhu** [comment]
I cannot get a logcat because the system will not boot past the point where logcat and/or adbd starts when I remove those files.

**Comment by mfonville** [comment]
@szhu thanks for testing
I am not sure yet how to further tackle this issue
Maybe @rapperskull or @thecrazylex have an idea?

**Comment by windrof123** [comment]
Clock magically appeared after updating to a new nightly about a week ago. Everything works well now.

**Comment by szhu** [comment]
Same, Clock is back for me too.

cm-14.1-20161220-NIGHTLY-bullhead.zip
open_gapps-arm64-7.1-stock-20161220.zip
