### ISSUE TITLE
Can't see Pixel Icons

### ISSUE THREAD

**Issue by joakin2k** [opengapps/opengapps#381]
Using Cyanogenmod Nightly on Oneplus One and custom(config file) Stock OpenGapps:

Removing stock launcher (cyanogen's trebuchet) adding "browser to the file" , including Search, Pixel Launcher, Pixel Icons and Wallpapers (to fully work) , all works except the Pixel Icons...

Any advice?... I search in the system an there isn't pixel icons app-

**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [x] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aissue)

*If Open GApps installation fails:*
- [x] Is the issue reproducible using the latest version of your recovery?
- [x] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

*If receiving force closures after Open GApps installation:*
- [ ] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [ ] The issue is reproducible on clean (=wiped ``/data/`` partition) installation
- [ ] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [ ] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**

[Short description of problem here]

**Reproduction Steps:**

1. [First Step]
2. [Second Step]
3. [Other Steps...]

**Expected behavior:**

[Describe expected behavior here]

**Observed behavior:**

[Describe observed behavior here]

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

[Debug log of the Open GApps installation](url)

[A logcat of the moment I receive the force closure (if applicable)](url)

**Comment by codebucketdev** [comment]
I cannot confirm your issue, but I can confirm that I see some Pixel icons when I do a install with my own gapps-config, in which I excluded explicitly the installation of the icons.

Please fix this issue, it looks awkward to have only Messenger with a Pixel icon.
My gapps-config: http://pastebin.com/yU8FWrxk

**Comment by codebucketdev** [comment]
Ok, it seems that Google is forcing their Pixel icons against their theory, weird...

**Comment by mfonville** [comment]
I believe that picking the Pixel or non-Pixel icon is a setting in the ROM and not in the gapps.

https://www.xda-developers.com/psa-android-7-1-circular-icon-support-is-determined-by-the-oem/

Also I see no way how the gapps scripts could resolve this, for further support please use the XDA forums.
