### ISSUE TITLE
Play Services FC After 20161106 (7.1/Pico/ARM)

### ISSUE THREAD

**Issue by airend** [opengapps/opengapps#384]
**Issue description:**

` W OpenGLRenderer: Bitmap too large to be uploaded into a texture (2049x1152, max=2048x2048)`

Pico packages starting with 20161108 contain Play Services with assets that trigger the above error. Thus, clean installation is not possible, nor upgrade (constant FCs). While this may not be due to Open GApps packaging, but rather to latest APKs included, do you think more compatible Play Services will be included in the future? Or, is it possible to convert some of these extremely large assets to something more manageable on a great number of devices out there?

**Comment by mfonville** [comment]
@airend could you include your debug log?
It would be interesting to see which variant of Play Services was installed.

**Comment by airend** [comment]
I tried again with 20161118, and it fails at the same point, yet logs are different, and now it won't work even on hammerhead (in addition to grouper, and a bunch of OMAPs; 20161106 is last version that works everywhere). So, I don't know anymore if it's about assets or something more subtle; no tombstones generated, but am attaching the debug logs: [open_gapps_debug_logs.tar.gz](https://github.com/opengapps/opengapps/files/601504/open_gapps_debug_logs.tar.gz)

**Comment by mfonville** [comment]
Hmm, interesting, so you do get the proper 240dpi Play Services version installed.
I suspect that either this is now a ROM issue, or Google will have f*cked this up for all 240dpi devices. If so, they will probably release a fix soon, I assume.

I don't see the possibility we could fix this as Open GApps, and can only recommend you to use an older package for the moment, until Google sorts this out.

**Comment by airend** [comment]
> Hmm, interesting, so you do get the proper 240dpi Play Services version installed.
I suspect that either this is now a ROM issue, or Google will have f*cked this up for all 240dpi devices. If so, they will probably release a fix soon, I assume.

Right, that's my conclusion as well, that it's Google's culprit. Since it happens on hammerhead and grouper too, all with different screen densities, it may be more subtle, and I wish I had an ARM64 device to test.

BTW, tried a different path; with version 20161118, the crash only happens if I try to restore a device backup, and can finish setup as new. The problem with last fully working 20161106 is that it only allows selection of the first device backup linked to account, so I'll keep an eye on upcoming fixes.

**Comment by mfonville** [comment]
@airend alright, and otherwise try to send Google an explicit error about this, very probably this can be recreated on official/stock ROMs too
