### ISSUE TITLE
AOSP camera not replaced 

### ISSUE THREAD

**Issue by Lukypie** [opengapps/opengapps#387]
Nexus 5x
Official cm14.1 build
ARM64 stock 7.1 gapps package
The script seems to not replace the stock aosp cm14 camera with the Google one.

**Comment by mfonville** [comment]
You need to upload at the very least your debug logs (the .tar.gz file)

**Comment by Lukypie** [comment]
[open_gapps_log.txt](https://github.com/opengapps/opengapps/files/611282/open_gapps_log.txt)
[open_gapps_debug_logs.tar.gz](https://github.com/opengapps/opengapps/files/611281/open_gapps_debug_logs.tar.gz)

Tried both Aroma installer, and the stock version.

**Comment by mfonville** [comment]
Ok, the log clearly states: you did not install on a clean `/data` partition. That is why Google Camera was not being installed by the installer. Flashing Google Camera is only possible on 'clean' installations (= wiped /data/ as described in the FAQ)

If Google Camera is not installed, the Stock Camera is sub-sequentially not removed.

So there is no error in the script. If you need more help, please use the forum for support requests.
