### ISSUE TITLE
Trusted face not working in android 7.0.

### ISSUE THREAD

**Issue by RoshVP** [opengapps/opengapps#390]

**Comment by enndubyu** [comment]
Logcat:

11-26 00:32:07.347 E/AndroidRuntime(840): FATAL EXCEPTION: main
11-26 00:32:07.347 E/AndroidRuntime(840): Process: com.android.facelock, PID: 840
11-26 00:32:07.347 E/AndroidRuntime(840): java.lang.UnsatisfiedLinkError: dlopen failed: library "libprotobuf-cpp-full.so" not found
11-26 00:32:07.347 E/AndroidRuntime(840): 	at java.lang.Runtime.loadLibrary0(Runtime.java:989)
11-26 00:32:07.347 E/AndroidRuntime(840): 	at java.lang.System.loadLibrary(System.java:1530)
11-26 00:32:07.347 E/AndroidRuntime(840): 	at com.google.android.libraries.vision.facenet.FaceNet.<clinit>(FaceNet.java:67)
11-26 00:32:07.347 E/AndroidRuntime(840): 	at com.google.android.libraries.vision.facenet.FaceNet.createFromAssets(FaceNet.java:118)
11-26 00:32:07.347 E/AndroidRuntime(840): 	at com.android.facelock.FaceLockUtil.initialize(FaceLockUtil.java:140)
11-26 00:32:07.347 E/AndroidRuntime(840): 	at com.android.facelock.SetupEnrollmentScreen.onCreate(SetupEnrollmentScreen.java:489)
11-26 00:32:07.347 E/AndroidRuntime(840): 	at android.app.Activity.performCreate(Activity.java:6679)
11-26 00:32:07.347 E/AndroidRuntime(840): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
11-26 00:32:07.347 E/AndroidRuntime(840): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2617)
11-26 00:32:07.347 E/AndroidRuntime(840): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2725)
11-26 00:32:07.347 E/AndroidRuntime(840): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
11-26 00:32:07.347 E/AndroidRuntime(840): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1472)
11-26 00:32:07.347 E/AndroidRuntime(840): 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-26 00:32:07.347 E/AndroidRuntime(840): 	at android.os.Looper.loop(Looper.java:154)
11-26 00:32:07.347 E/AndroidRuntime(840): 	at android.app.ActivityThread.main(ActivityThread.java:6145)
11-26 00:32:07.347 E/AndroidRuntime(840): 	at java.lang.reflect.Method.invoke(Native Method)
11-26 00:32:07.347 E/AndroidRuntime(840): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
11-26 00:32:07.347 E/AndroidRuntime(840): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

**Comment by Evisceration** [comment]
@enndubyu report this to the maintainer of the rom.

libprotobuf-cpp-full needs to get added to product packages.

```
PRODUCT_PACKAGES += \
    libprotobuf-cpp-full
```

**Comment by mfonville** [comment]
@Evisceration thanks for answering this one!

**Comment by Evisceration** [comment]
just in case, uploaded a commit to CyanogenMod code review, which adds the lib globally

https://review.cyanogenmod.org/#/c/174078/
