### ISSUE TITLE
Propose editing "Advanced Features and Options" Wiki page

### ISSUE THREAD

**Issue by szhu** [opengapps/opengapps#391]
The ["Advanced Features and Options" page](https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options) lists all the Google apps, but in everything is in alphabetical order by code name and it's pretty overwhelming to anyone who looks at it. It's more likely that people want it grouped by package level, and sorted by the app name.

I propose swapping that section out with this:

|           Code           |                                                                                        Description                                                                                        |
|--------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Pico+**                |                                                                                                                                                                                           |
| `DialerFramework`        | Dialer Framework                                                                                                                                                                          |
| `CalSync`                | Google Calendar Sync (except if Google Calendar is being installed)                                                                                                                       |
| `GoogleTTS`              | [Google Text-to-Speech](https://play.google.com/store/apps/details?id=com.google.android.tts) (Micro+ on 5-, Pico+ on 6+)                                                             |
| `PackageInstallerGoogle` | Google Package Installer                                                                                                                                                                  |
|                          |                                                                                                                                                                                           |
| **Nano+**                |                                                                                                                                                                                           |
| `FaceDetect`             | FaceUnlock                                                                                                                                                                                |
| `FaceUnlock`             | FaceUnlock                                                                                                                                                                                |
| `Search`                 | [Google Search](https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox) (including includes `Hotword`, excluding excludes `GoogleNow` and `PixelLauncher`) |
| `Speech`                 | Offline Speech Files                                                                                                                                                                      |
| `Hotword`                | OK Google Hotword Enrollment                                                                                                                                                              |
|                          |                                                                                                                                                                                           |
| **Micro+**               |                                                                                                                                                                                           |
| `Gmail`                  | [Gmail](https://play.google.com/store/apps/details?id=com.google.android.gm)                                                                                                              |
| `CalendarGoogle`         | [Google Calendar](https://play.google.com/store/apps/details?id=com.google.android.calendar)                                                                                              |
| `ExchangeGoogle`         | Google Exchange Services                                                                                                                                                                  |
| `GoogleNow`              | [Google Now Launcher](https://play.google.com/store/apps/details?id=com.google.android.launcher) (requires `Search`)                                                                      |
| `GoogleTTS`              | [Google Text-to-Speech](https://play.google.com/store/apps/details?id=com.google.android.tts) (Micro+ on 5.0-, Pico+ on 6.0+)                                                             |
|                          |                                                                                                                                                                                           |
| **Mini+**                |                                                                                                                                                                                           |
| `CalculatorGoogle`       | [Google Calculator](https://play.google.com/store/apps/details?id=com.google.android.calculator)                                                                                          |
| `ClockGoogle`            | [Google Clock](https://play.google.com/store/apps/details?id=com.google.android.deskclock)                                                                                                |
| `Maps`                   | [Google Maps](https://play.google.com/store/apps/details?id=com.google.android.apps.maps)                                                                                                 |
| `TagGoogle`              | Google NFC Tags                                                                                                                                                                           |
| `Photos`                 | [Google Photos](https://play.google.com/store/apps/details?id=com.google.android.apps.photos)                                                                                             |
| `GooglePlus`             | [Google+](https://play.google.com/store/apps/details?id=com.google.android.apps.plus)                                                                                                     |
| `Hangouts`               | [Hangouts](https://play.google.com/store/apps/details?id=com.google.android.talk)                                                                                                         |
| `YouTube`                | [YouTube](https://play.google.com/store/apps/details?id=com.google.android.youtube)                                                                                                       |
|                          |                                                                                                                                                                                           |
| **Full+**                |                                                                                                                                                                                           |
| `Chrome`                 | [Google Chrome Browser](https://play.google.com/store/apps/details?id=com.android.chrome)                                                                                                 |
| `CloudPrint`             | [Google Cloud Print](https://play.google.com/store/apps/details?id=com.google.android.apps.cloudprint)                                                                                    |
| `Docs`                   | [Google Docs](https://play.google.com/store/apps/details?id=com.google.android.apps.docs.editors.docs)                                                                                    |
| `Drive`                  | [Google Drive](https://play.google.com/store/apps/details?id=com.google.android.apps.docs)                                                                                                |
| `Fitness`                | [Google Fit](https://play.google.com/store/apps/details?id=com.google.android.apps.fitness)                                                                                               |
| `Keep`                   | [Google Keep](https://play.google.com/store/apps/details?id=com.google.android.keep)                                                                                                      |
| `NewsWidget`             | [Google News & Weather](https://play.google.com/store/apps/details?id=com.google.android.apps.genie.geniewidget)                                                                          |
| `Books`                  | [Google Play Books](https://play.google.com/store/apps/details?id=com.google.android.apps.books)                                                                                          |
| `PlayGames`              | [Google Play Games](https://play.google.com/store/apps/details?id=com.google.android.play.games)                                                                                          |
| `Movies`                 | [Google Play Movies & TV](https://play.google.com/store/apps/details?id=com.google.android.videos)                                                                                        |
| `Music`                  | [Google Play Music](https://play.google.com/store/apps/details?id=com.google.android.music)                                                                                               |
| `NewsStand`              | [Google Play Newsstand](https://play.google.com/store/apps/details?id=com.google.android.apps.magazines)                                                                                  |
| `Sheets`                 | [Google Sheets](https://play.google.com/store/apps/details?id=com.google.android.apps.docs.editors.sheets)                                                                                |
| `Slides`                 | [Google Slides](https://play.google.com/store/apps/details?id=com.google.android.apps.docs.editors.slides)                                                                                |
| `Talkback`               | [Google TalkBack](https://play.google.com/store/apps/details?id=com.google.android.marvin.talkback)                                                                                       |
|                          |                                                                                                                                                                                           |
| **Stock+**               |                                                                                                                                                                                           |
| `CameraGoogle`           | [Google Camera](https://play.google.com/store/apps/details?id=com.google.android.GoogleCamera)                                                                                            |
| `ContactsGoogle`         | [Google Contacts](https://play.google.com/store/apps/details?id=com.google.android.contacts)                                                                                              |
| `DialerGoogle`           | [Google Dialer](https://play.google.com/store/apps/details?id=com.google.android.dialer)                                                                                                  |
| `KeyboardGoogle`         | [Google Keyboard](https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin)                                                                                     |
| `Messenger`              | [Google Messenger](https://play.google.com/store/apps/details?id=com.google.android.apps.messaging) (except on tablet devices)                                                            |
| `PixelIcons`             | Google Pixel Icons                                                                                                                                                                        |
| `StorageManagerGoogle`   | Google Storage Manager                                                                                                                                                                    |
| `VRService`              | Google VR Services                                                                                                                                                                        |
| `WebViewGoogle`          | [Google Webview](https://play.google.com/store/apps/details?id=com.google.android.webview)                                                                                                |
| `PixelLauncher`          | [Pixel Launcher](https://play.google.com/store/apps/details?id=com.google.android.apps.nexuslauncher) (requires `Search` and `Wallpapers`)                                                |
| `PrintServiceGoogle`     | Print Service Recommendation Service                                                                                                                                                      |
| `Wallpapers`             | [Wallpapers](https://play.google.com/store/apps/details?id=com.google.android.apps.wallpaper)                                                                                             |
|                          |                                                                                                                                                                                           |
| **Super+**               |                                                                                                                                                                                           |
| `AndroidPay`             | [Android Pay](https://play.google.com/store/apps/details?id=com.google.android.apps.walletnfcrel)                                                                                         |
| `DMAgent`                | [Google Apps Device Policy](https://play.google.com/store/apps/details?id=com.google.android.apps.enterprise.dmagent)                                                                     |
| `GCS`                    | [Google Connectivity Services](https://play.google.com/store/apps/details?id=com.google.android.apps.gcs) (excluding also excludes Project Fi)                                            |
| `Earth`                  | [Google Earth](https://play.google.com/store/apps/details?id=com.google.earth)                                                                                                            |
| `Indic`                  | [Google Indic Keyboard](https://play.google.com/store/apps/details?id=com.google.android.apps.inputmethod.hindi)                                                                          |
| `Japanese`               | [Google Japanese Input](https://play.google.com/store/apps/details?id=com.google.android.inputmethod.japanese)                                                                            |
| `Korean`                 | [Google Korean Input](https://play.google.com/store/apps/details?id=com.google.android.inputmethod.korean)                                                                                |
| `Pinyin`                 | [Google Pinyin Input](https://play.google.com/store/apps/details?id=com.google.android.inputmethod.pinyin)                                                                                |
| `Street`                 | [Google Street View](https://play.google.com/store/apps/details?id=com.google.android.street)                                                                                             |
| `Translate`              | [Google Translate](https://play.google.com/store/apps/details?id=com.google.android.apps.translate)                                                                                       |
| `Zhuyin`                 | [Google Zhuyin Input](https://play.google.com/store/apps/details?id=com.google.android.apps.inputmethod.zhuyin)                                                                           |
| `ProjectFi`              | [Project Fi by Google](https://play.google.com/store/apps/details?id=com.google.android.apps.tycho)                                                                                       |

Here is the Markdown source (edited with [SublimeTableEditor](https://github.com/vkocubinsky/SublimeTableEditor)):

```
|           Code           |                                                                                        Description                                                                                        |
|--------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Pico+**                |                                                                                                                                                                                           |
| `DialerFramework`        | Dialer Framework                                                                                                                                                                          |
| `CalSync`                | Google Calendar Sync (except if Google Calendar is being installed)                                                                                                                       |
| `GoogleTTS`              | [Google Text-to-Speech](https://play.google.com/store/apps/details?id=com.google.android.tts) (Micro+ on 5.0-, Pico+ on 6.0+)                                                             |
| `PackageInstallerGoogle` | Google Package Installer                                                                                                                                                                  |
|                          |                                                                                                                                                                                           |
| **Nano+**                |                                                                                                                                                                                           |
| `FaceDetect`             | FaceUnlock                                                                                                                                                                                |
| `FaceUnlock`             | FaceUnlock                                                                                                                                                                                |
| `Search`                 | [Google Search](https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox) (including includes `Hotword`, excluding excludes `GoogleNow` and `PixelLauncher`) |
| `Speech`                 | Offline Speech Files                                                                                                                                                                      |
| `Hotword`                | OK Google Hotword Enrollment                                                                                                                                                              |
|                          |                                                                                                                                                                                           |
| **Micro+**               |                                                                                                                                                                                           |
| `Gmail`                  | [Gmail](https://play.google.com/store/apps/details?id=com.google.android.gm)                                                                                                              |
| `CalendarGoogle`         | [Google Calendar](https://play.google.com/store/apps/details?id=com.google.android.calendar)                                                                                              |
| `ExchangeGoogle`         | Google Exchange Services                                                                                                                                                                  |
| `GoogleNow`              | [Google Now Launcher](https://play.google.com/store/apps/details?id=com.google.android.launcher) (requires `Search`)                                                                      |
| `GoogleTTS`              | [Google Text-to-Speech](https://play.google.com/store/apps/details?id=com.google.android.tts) (Micro+ on 5.0-, Pico+ on 6.0+)                                                             |
|                          |                                                                                                                                                                                           |
| **Mini+**                |                                                                                                                                                                                           |
| `CalculatorGoogle`       | [Google Calculator](https://play.google.com/store/apps/details?id=com.google.android.calculator)                                                                                          |
| `ClockGoogle`            | [Google Clock](https://play.google.com/store/apps/details?id=com.google.android.deskclock)                                                                                                |
| `Maps`                   | [Google Maps](https://play.google.com/store/apps/details?id=com.google.android.apps.maps)                                                                                                 |
| `TagGoogle`              | Google NFC Tags                                                                                                                                                                           |
| `Photos`                 | [Google Photos](https://play.google.com/store/apps/details?id=com.google.android.apps.photos)                                                                                             |
| `GooglePlus`             | [Google+](https://play.google.com/store/apps/details?id=com.google.android.apps.plus)                                                                                                     |
| `Hangouts`               | [Hangouts](https://play.google.com/store/apps/details?id=com.google.android.talk)                                                                                                         |
| `YouTube`                | [YouTube](https://play.google.com/store/apps/details?id=com.google.android.youtube)                                                                                                       |
|                          |                                                                                                                                                                                           |
| **Full+**                |                                                                                                                                                                                           |
| `Chrome`                 | [Google Chrome Browser](https://play.google.com/store/apps/details?id=com.android.chrome)                                                                                                 |
| `CloudPrint`             | [Google Cloud Print](https://play.google.com/store/apps/details?id=com.google.android.apps.cloudprint)                                                                                    |
| `Docs`                   | [Google Docs](https://play.google.com/store/apps/details?id=com.google.android.apps.docs.editors.docs)                                                                                    |
| `Drive`                  | [Google Drive](https://play.google.com/store/apps/details?id=com.google.android.apps.docs)                                                                                                |
| `Fitness`                | [Google Fit](https://play.google.com/store/apps/details?id=com.google.android.apps.fitness)                                                                                               |
| `Keep`                   | [Google Keep](https://play.google.com/store/apps/details?id=com.google.android.keep)                                                                                                      |
| `NewsWidget`             | [Google News & Weather](https://play.google.com/store/apps/details?id=com.google.android.apps.genie.geniewidget)                                                                          |
| `Books`                  | [Google Play Books](https://play.google.com/store/apps/details?id=com.google.android.apps.books)                                                                                          |
| `PlayGames`              | [Google Play Games](https://play.google.com/store/apps/details?id=com.google.android.play.games)                                                                                          |
| `Movies`                 | [Google Play Movies & TV](https://play.google.com/store/apps/details?id=com.google.android.videos)                                                                                        |
| `Music`                  | [Google Play Music](https://play.google.com/store/apps/details?id=com.google.android.music)                                                                                               |
| `NewsStand`              | [Google Play Newsstand](https://play.google.com/store/apps/details?id=com.google.android.apps.magazines)                                                                                  |
| `Sheets`                 | [Google Sheets](https://play.google.com/store/apps/details?id=com.google.android.apps.docs.editors.sheets)                                                                                |
| `Slides`                 | [Google Slides](https://play.google.com/store/apps/details?id=com.google.android.apps.docs.editors.slides)                                                                                |
| `Talkback`               | [Google TalkBack](https://play.google.com/store/apps/details?id=com.google.android.marvin.talkback)                                                                                       |
|                          |                                                                                                                                                                                           |
| **Stock+**               |                                                                                                                                                                                           |
| `CameraGoogle`           | [Google Camera](https://play.google.com/store/apps/details?id=com.google.android.GoogleCamera)                                                                                            |
| `ContactsGoogle`         | [Google Contacts](https://play.google.com/store/apps/details?id=com.google.android.contacts)                                                                                              |
| `DialerGoogle`           | [Google Dialer](https://play.google.com/store/apps/details?id=com.google.android.dialer)                                                                                                  |
| `KeyboardGoogle`         | [Google Keyboard](https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin)                                                                                     |
| `Messenger`              | [Google Messenger](https://play.google.com/store/apps/details?id=com.google.android.apps.messaging) (except on tablet devices)                                                            |
| `PixelIcons`             | Google Pixel Icons                                                                                                                                                                        |
| `StorageManagerGoogle`   | Google Storage Manager                                                                                                                                                                    |
| `VRService`              | Google VR Services                                                                                                                                                                        |
| `WebViewGoogle`          | [Google Webview](https://play.google.com/store/apps/details?id=com.google.android.webview)                                                                                                |
| `PixelLauncher`          | [Pixel Launcher](https://play.google.com/store/apps/details?id=com.google.android.apps.nexuslauncher) (requires `Search` and `Wallpapers`)                                                |
| `PrintServiceGoogle`     | Print Service Recommendation Service                                                                                                                                                      |
| `Wallpapers`             | [Wallpapers](https://play.google.com/store/apps/details?id=com.google.android.apps.wallpaper)                                                                                             |
|                          |                                                                                                                                                                                           |
| **Super+**               |                                                                                                                                                                                           |
| `AndroidPay`             | [Android Pay](https://play.google.com/store/apps/details?id=com.google.android.apps.walletnfcrel)                                                                                         |
| `DMAgent`                | [Google Apps Device Policy](https://play.google.com/store/apps/details?id=com.google.android.apps.enterprise.dmagent)                                                                     |
| `GCS`                    | [Google Connectivity Services](https://play.google.com/store/apps/details?id=com.google.android.apps.gcs) (excluding also excludes Project Fi)                                            |
| `Earth`                  | [Google Earth](https://play.google.com/store/apps/details?id=com.google.earth)                                                                                                            |
| `Indic`                  | [Google Indic Keyboard](https://play.google.com/store/apps/details?id=com.google.android.apps.inputmethod.hindi)                                                                          |
| `Japanese`               | [Google Japanese Input](https://play.google.com/store/apps/details?id=com.google.android.inputmethod.japanese)                                                                            |
| `Korean`                 | [Google Korean Input](https://play.google.com/store/apps/details?id=com.google.android.inputmethod.korean)                                                                                |
| `Pinyin`                 | [Google Pinyin Input](https://play.google.com/store/apps/details?id=com.google.android.inputmethod.pinyin)                                                                                |
| `Street`                 | [Google Street View](https://play.google.com/store/apps/details?id=com.google.android.street)                                                                                             |
| `Translate`              | [Google Translate](https://play.google.com/store/apps/details?id=com.google.android.apps.translate)                                                                                       |
| `Zhuyin`                 | [Google Zhuyin Input](https://play.google.com/store/apps/details?id=com.google.android.apps.inputmethod.zhuyin)                                                                           |
| `ProjectFi`              | [Project Fi by Google](https://play.google.com/store/apps/details?id=com.google.android.apps.tycho)                                                                                       |
```

**Comment by szhu** [comment]
Also I propose adding the same content, but in gapps-config format, to quickly give everyone a starting point for their config file. (à la the default `/etc/apache2/httpd.conf` file)

```sh
# Pico+
DialerFramework        # Dialer Framework
CalSync                # Google Calendar Sync (except if Google Calendar is being installed)
GoogleTTS              # Google Text-to-Speech (Micro+ on 5.0-, Pico+ on 6.0+)
PackageInstallerGoogle # Google Package Installer

# Nano+
FaceDetect             # FaceUnlock
FaceUnlock             # FaceUnlock
Search                 # Google Search (including includes Hotword, excluding excludes GoogleNow and PixelLauncher)
Speech                 # Offline Speech Files
Hotword                # OK Google Hotword Enrollment

# Micro+
Gmail                  # Gmail
CalendarGoogle         # Google Calendar
ExchangeGoogle         # Google Exchange Services
GoogleNow              # Google Now Launcher (requires Search)
GoogleTTS              # Google Text-to-Speech (Micro+ on 5.0-, Pico+ on 6.0+)

# Mini+
CalculatorGoogle       # Google Calculator
ClockGoogle            # Google Clock
Maps                   # Google Maps
TagGoogle              # Google NFC Tags
Photos                 # Google Photos
GooglePlus             # Google+
Hangouts               # Hangouts
YouTube                # YouTube

# Full+
Chrome                 # Google Chrome Browser
CloudPrint             # Google Cloud Print
Docs                   # Google Docs
Drive                  # Google Drive
Fitness                # Google Fit
Keep                   # Google Keep
NewsWidget             # Google News & Weather
Books                  # Google Play Books
PlayGames              # Google Play Games
Movies                 # Google Play Movies & TV
Music                  # Google Play Music
NewsStand              # Google Play Newsstand
Sheets                 # Google Sheets
Slides                 # Google Slides
Talkback               # Google TalkBack

# Stock+
CameraGoogle           # Google Camera
ContactsGoogle         # Google Contacts
DialerGoogle           # Google Dialer
KeyboardGoogle         # Google Keyboard
Messenger              # Google Messenger (except on tablet devices)
PixelIcons             # Google Pixel Icons
StorageManagerGoogle   # Google Storage Manager
VRService              # Google VR Services
WebViewGoogle          # Google Webview
PixelLauncher          # Pixel Launcher (requires Search and Wallpapers)
PrintServiceGoogle     # Print Service Recommendation Service
Wallpapers             # Wallpapers

# Super+
AndroidPay             # Android Pay
DMAgent                # Google Apps Device Policy
GCS                    # Google Connectivity Services (excluding also excludes Project Fi)
Earth                  # Google Earth
Indic                  # Google Indic Keyboard
Japanese               # Google Japanese Input
Korean                 # Google Korean Input
Pinyin                 # Google Pinyin Input
Street                 # Google Street View
Translate              # Google Translate
Zhuyin                 # Google Zhuyin Input
ProjectFi              # Project Fi by Google
```

**Comment by szhu** [comment]
And same for apps to remove:

```sh
# Remove apps (uncomment to remove)
# (BasicDreams)             # Basic Dreams Wallpaper
# (CMAccount)               # CM Account Application
# (CMAudioFX)               # CM AudioFX
# (CMFileManager)           # CM File Manager
# (CMMusic)                 # CM Music
# (CMScreenCast)            # CM ScreenCast app
# (CMSetupWizard)           # CM Setup Wizard (see Notes for CMSetupWizard)
# (CMUpdater)               # CM Updater
# (CMWallpapers)            # CM Wallpapers
# (CMWeatherProvider)       # CM Weather Underground
# (DashClock)               # DashClock Widget (found in certain ROMs)
# (Galaxy)                  # Galaxy (also known as BlackHole) Wallpaper
# (Hexo)                    # Hexo Libre Theme
# (HoloSpiral)              # Holo Spiral Wallpaper
# (NoiseField)              # Noise Field Wallpaper
# (OmniSwitch)              # OmniSwitch recent apps switcher replacement
# (Phasebeam)               # Phasebeam Wallpaper
# (PhotoPhase)              # Photo Phase Wallpaper
# (PhotoTable)              # Photo Table Wallpaper
# (Browser)                 # Stock Browser
# (CalculatorStock)         # Stock Calculator (automatically removed when Google Calculator is installed)
# (CalendarStock)           # Stock Calendar (automatically removed when Google Calendar is installed)
# (CameraStock)             # Stock Camera
# (ClockStock)              # Stock Desk Clock (automatically removed when Google Desk Clock is installed)
# (Email)                   # Stock Email Client
# (ExchangeStock)           # Stock Exchange Services (automatically removed when Google Exchange Services is installed)
# (MzFileManager)           # Stock FlymeOS File Manager
# (MzPay)                   # Stock FlymeOS Pay system (because MzPay services works only in China)
# (MzSetupWizard)           # Stock FlymeOS SetupWizard
# (MzUpdater)               # Stock FlymeOS Updaters
# (MzWeather)               # Stock FlymeOS Weather (because MzWeather service work only in China)
# (FMRadio)                 # Stock FM Radio (not found on all devices or ROMs)
# (Gallery)                 # Stock Gallery
# (KeyboardStock)           # Stock Keyboard (automatically removed when Google Keyboard is installed)
# (Launcher)                # Stock Launcher(s)
# (LiveWallpapers)          # Stock Live Wallpapers
# (LockClock)               # Stock Lockscreen Clock Widget
# (Studio)                  # Stock Movie Studio
# (TagStock)                # Stock NFC Tags (automatically removed when Google NFC Tags is installed)
# (PicoTTS)                 # Stock PicoTTS
# (PrintServiceStock)       # Stock Print Service Recommendation Service (automatically removed when Google Print Service Recommendation Service is installed)
# (SimToolKit)              # Stock SimToolKit
# (MMS)                     # Stock SMS (automatically removed if Google Messenger and/or Hangouts is installed)
# (StorageManagerStock)     # Stock Storage Manager (automatically removed when Google Storage Manager is installed)
# (Terminal)                # Stock Terminal
# (Themes)                  # Stock Theme Engine (Will break the Settings Entry and can cause unexpected reboots on some ROMs)
# (VisualizationWallpapers) # Stock Visualization Wallpapers
# (WhisperPush)             # Stock WhisperPush support
```

**Comment by mfonville** [comment]
Hey, sorry for my late response, but go ahead with these changes!

**Comment by szhu** [comment]
@mfonville I edited the page. Can you check to make sure I didn't change anything for the worse? Thanks

**Comment by mfonville** [comment]
@szhu thanks for your changes;
I noticed one error (I should have seen it when you commented it, but I missed it);
for the stock removals like `Email` they don't need to be between `()`

The `()` are only used to remove apps that are not part of the predefined list, with the 'universal removal'.

Also, I think that it might be OK to drop the list of links to the GApps on the Play Store from this page, since the links cannot be in-lined in this format. And try to add the links in the list of all the package-pages (so Stock, Super, Full etc)

**Comment by szhu** [comment]
Thanks for the suggestions!

> I noticed one error (I should have seen it when you commented it, but I missed it); for the stock removals like Email they don't need to be between ()

Fixed.

In my personal config file, I put parens and the installer seemed to recognize it. However, removals did not appear to get correctly written into addons.d, since after an upgrade, the apps I wanted removed would re-appear. Could the parens be causing this issue?

> Also, I think that it might be OK to drop the list of links to the GApps on the Play Store from this page, since the links cannot be in-lined in this format. And try to add the links in the list of all the package-pages (so Stock, Super, Full etc)

I might get to it when I have time, but since I'm not adding the links in elsewhere yet, I left the links at the bottom of the page for now.

**Comment by mfonville** [comment]
If reflashing GApps, the universal removal feature can't find the things between () if they were already removed (because it can't find the paths, it normally has to account for checking both app and priv-app and capitalization). So in that case they don't get added to addon.d anymore, and thus if upgrading the ROM they can re-appear.

So if you use that feature, it is only guaranteed to work 100% properly on fresh flash on /system. I looked for workaround/fixes, but none of them is easy to implement.

If you find time to upgrade those links at a later moment, that'd be cool :-)

**Comment by szhu** [comment]
Okay, I probably re-flashed GApps multiple times, so that would explain it. Is there a thread for this issue? I thought of a potential solution:

After `/system/priv-app/SpareParts/SpareParts.apk` is found, delete everything in the `/system/priv-app/SpareParts` folder and leave a new blank file `/system/priv-app/SpareParts/SpareParts.apk.removed-by-opengapps`.

The GApps install process would work as follows:

1. Find all `.apk.removed-by-opengapps` files in `/system`.  
   Rename each of them to `.apk.removed-by-opengapps-old`
2. Let's say the keyword is `(SpareParts)`. Look for `SpareParts.apk` as usual, but also look for `SpareParts.apk.removed-by-opengapps-old`.
3. When `SpareParts.apk[.removed-by-opengapps-old]` is found, delete the contents of the folder and leave an empty `SpareParts.apk.removed-by-opengapps` file behind.
4. Delete all `.apk.removed-by-opengapps-old` files.

The addons.d upgrade process would not be significantly changed except for the paragraph above (leaving behind the `.apk.removed-by-opengapps` file).

The `.removed-by-opengapps` files can be empty or can contain a sentence or two to explain their purpose.

**Comment by mfonville** [comment]
The most practical solution is probably to mark the paths in our current addon.d file in an easy processable manner, and let the installer read this file when generating the new addon.d, copying over the already existing paths of the previous flash.

**Comment by osm0sis** [comment]
I'll look into @mfonville's idea there and see what I can come up with for a PR since I also noticed this issue recently. :+1:
