### ISSUE TITLE
Setup Wizard Has Stopped Working

### ISSUE THREAD

**Issue by jrussell88** [opengapps/opengapps#392]
Xiomi Mi-5s
Xiaomi MIUI-8 roms: xiaomi.eu_multi_MI5S_V8.0.10.0.MAGCNDH_v8-6.0 and xiaomi.eu_multi_MI5S_6.10.27_v8-6.0
Arm64
pico, nano, mini, stock 20161125

On reboot after loading Gapps, the Setup Wizard repeatedly pops up an error message: 

> Setup Wizard Has Stopped Working

, which it's not possible to bypass.

Logcat excerpt (logcat *:E):

> --------- beginning of crash
> 11-28 09:39:05.563  4674  4674 E AndroidRuntime: FATAL EXCEPTION: main
> 11-28 09:39:05.563  4674  4674 E AndroidRuntime: Process: com.google.android.setupwizard, PID: 4674
> 11-28 09:39:05.563  4674  4674 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.google.android.setupwizard.SetupWizardApplication: java.lang.SecurityException: addOnSubscriptionsChangedListener: Neither user 10100 nor current process has android.permission.READ_PHONE_STATE.
> 11-28 09:39:05.563  4674  4674 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java)
> 11-28 09:39:05.563  4674  4674 E AndroidRuntime: 	at android.app.ActivityThread.access$1600(ActivityThread.java)
> 11-28 09:39:05.563  4674  4674 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
> 11-28 09:39:05.563  4674  4674 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java)
> 11-28 09:39:05.563  4674  4674 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java)
> 11-28 09:39:05.563  4674  4674 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java)
> 11-28 09:39:05.563  4674  4674 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 11-28 09:39:05.563  4674  4674 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
> 11-28 09:39:05.563  4674  4674 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
> 11-28 09:39:05.563  4674  4674 E AndroidRuntime: Caused by: java.lang.SecurityException: addOnSubscriptionsChangedListener: Neither user 10100 nor current process has android.permission.READ_PHONE_STATE.
> 11-28 09:39:05.563  4674  4674 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java)
> 11-28 09:39:05.563  4674  4674 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java)
> 11-28 09:39:05.563  4674  4674 E AndroidRuntime: 	at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.addOnSubscriptionsChangedListener(ITelephonyRegistry.java)
> 11-28 09:39:05.563  4674  4674 E AndroidRuntime: 	at android.telephony.SubscriptionManager.addOnSubscriptionsChangedListener(SubscriptionManager.java)
> 11-28 09:39:05.563  4674  4674 E AndroidRuntime: 	at com.google.android.setupwizard.carrier.PhoneMonitor.<init>(PhoneMonitor.java:509)
> 11-28 09:39:05.563  4674  4674 E AndroidRuntime: 	at com.google.android.setupwizard.carrier.PhoneMonitor.initInstance(PhoneMonitor.java:70)
> 11-28 09:39:05.563  4674  4674 E AndroidRuntime: 	at com.google.android.setupwizard.SetupWizardApplication.onCreate(SetupWizardApplication.java:27)
> 11-28 09:39:05.563  4674  4674 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java)
> 11-28 09:39:05.563  4674  4674 E AndroidRuntime: 	... 9 more
> 

The fix is from the adb shell:
`pm grant com.google.android.setupwizard android.permission.READ_PHONE_STATE`

**Comment by mfonville** [comment]
Did you wipe `/data` partition before flashing GApps and do you have a debug log of the install? (the .tar.gz file)

**Comment by jrussell88** [comment]
Wiped - TWRP factory reset. I have the debug log of my last install; was my n'th run and I note it says I didn't wipe. Possibly after fixing pico OpenGApps I installed the stock version over it; but I think I did wipe it.  

[open_gapps_debug_logs.tar.gz](https://github.com/opengapps/opengapps/files/616637/open_gapps_debug_logs.tar.gz)

**Comment by mfonville** [comment]
hmm, then probably your TWRP factory reset did not properly wipe.

Because this problem can/should only happen on 6.0+ if you flash GApps the first time, and /data/ is not completely clean.
Otherwise the ROM should grant permissions, and if it doesn't it should add the permissions-patch to increase compatibility.

For further support please use the XDA Forum

**Comment by jrussell88** [comment]
Thanks. I've gone through the installation process for the OpenGApps, and also the two versions of the MIUI-8 Rom over half a dozen times over the last few days wiping every time with identical results. 

Actually I think this issue is covered in the Android 6.0 release notes in the Wiki - the permissions patch and workaround. I'm afraid I didn't find that sooner, but it looks like this rom doesn't grant permissions - quite a few references to the same issue, and at least one solution is to fix the permission from Settings. Perhaps Xiaomi are trying to promote their ecosystem rather than Google's.

**Comment by andy1247008998** [comment]
I have a similar issue.
Devices: Xiaomi 5s plus (Natrium)
setupwizard shows up when I reformat /data partition after OpenGapps installed.

**Comment by mfonville** [comment]
It seems miui ROM does silent assumptions about the setup wizard application, and that Google's one (of course) dos not contain a miui-theme. It would be up to the miui devs to solve this.
