### ISSUE TITLE
rapid dexopt for google contacts sync adapter

### ISSUE THREAD

**Issue by wazeeahmed** [opengapps/opengapps#393]
i tried clean flash of resurrection remix 5.7.4 20161009 sprout4 . But com.google.contacts.sync.adapter app's dexopt process occurs everytime i restart the phone . or sometimes only starting apps . I thought clean flash might fix it . But it didn't . Any lights on this ?
here are the logs : 
[open_gapps_debug_logs.tar.gz](https://github.com/opengapps/opengapps/files/619501/open_gapps_debug_logs.tar.gz)
[open_gapps_log.txt](https://github.com/opengapps/opengapps/files/619503/open_gapps_log.txt)

Hope this annoying bug will be fixed .

**Comment by mfonville** [comment]
Please make a logcat of your error; and then post it on the XDA Forum Thread
