### ISSUE TITLE
pixelicons not working on Android 7.0 and 7.1 as intended

### ISSUE THREAD

**Issue by Sparker0i** [opengapps/opengapps#394]
I installed OpenGapps using the Aroma package. I install pre-requisites for Pixel Launcher (and Pixel Icons) from the Aroma Setup Wizard.

On booting, when I select Pixel Launcher as default, except Google Drive, Play Games and Play Newsstand, none of the icons appear as they are supposed to after Pixel Icons installation, it just appears as the old, stock icons.

I've tried this on CyanogenMod 14/14.1 on Redmi Note 3(arm64), Resurrection Remix (5.8.0) on Redmi Note 3.

Maybe if this is a bug (because it works for 3 apps at least), but can this be considered?

**Comment by mfonville** [comment]
I believe whether the round icons are used or not is a setting in the ROM.
GitHub is not the best place to discuss this, best use our XDA Forum thread to receive answers from the community
