### ISSUE TITLE
Add support for ROMs that have GApps built-in into the system image

### ISSUE THREAD

**Issue by TheComputerGuy96** [opengapps/opengapps#395]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps installation fails:*
- [x] Is the issue reproducible using the latest version of your recovery?
- [x] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

**Issue description:**

There should be support for ROMs that have GApps built-in 

**Reproduction Steps:**

1. Flash Open GApps package on a ROM that has GApps built-in

**Expected behavior:**

The installer should wipe them and continue the install

**Observed behavior:**

Installer throws an error and aborts the install

**Comment by mfonville** [comment]
If you have a stock ROM, it will update the GApps on it in 'for stock' modus.
If you have aROM with a g.prop but not Open GApps, we don't update it. That it is on-purpose and also not fixable, because it is not supported and can lead to nasty situations.

If ROM devs include their own GApps that are not Open GApps, we can't support.

**Comment by TheComputerGuy96** [comment]
BTW, what issues does updating GApps cause (but you MUST assume that the phone is factory reset (I mean that it has its /cache and /data partitions completely wiped) and has installed a ROM that has non-Open GApps in the /system partition)?

I've deleted some GApps-related stuff (and that g.prop) from the /system partition when my ROM has been flashed (but not booted) and Open GApps flashed fine and worked fine (so we can just detect if /data partition is clean, and if it's clean (and if it's not clean, then the installer will abort the install), then the installer will detect if there's the /system/etc/g.prop file (and if there's no file like that, then the installer will do what you said), and if there's the /system/etc/g.prop file, then the installer wipe GApps-related stuff that is there in the /system partition and continue the install of Open GApps)

**Comment by TheComputerGuy96** [comment]
@mfonville Please read my comment

**Comment by mfonville** [comment]
If you use other GApps they might have used other filepaths, if the same application is installed twice on different locations, you will get unexpected results.

That is why we stick to this use case, any other situation is considered unsupported (aside from that Google has already shown not to like bundling GApps with a ROM if not part of the OHA and passing their verification; only flashing GApps aftermarket by the user itself has been allowed)
