### ISSUE TITLE
PLAY STORE NOT GETTING INSTALLED

### ISSUE THREAD

**Issue by pritamdstan** [opengapps/opengapps#397]
in the latest gapps package of ARM 5.1 AROMA dated 8/12/2016  , the play store is not getting installed. currently using samsung J200G.

**Comment by mfonville** [comment]
Please read the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ#2-im-having-a-problem-with-my-open-gapps-install-what-information-do-you-need-to-help-me) and the support instructions mentioned. You need to use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071) for support requests, directly opening GitHub issues is *not* appreciated.

PS: Please remember to at least include your installation debug log and (if applicable) a logcat when requesting support.

**Comment by ET-Bent** [comment]
Encountering the same issue on a OnePlus2. Any further info's on that?

(FAQ does not help here!)

**Comment by mfonville** [comment]
@ET-Bent as described, if you encounter any issues, please use the XDA forum to get help

**Comment by pritamdstan** [comment]
@ET-Bent found a workaround. the new gapps dont contain any playstore, or whatever it is the play store is not getting installed in any builds of gapps. So I extracted the play store from the official firmware and pushed it in the system of the present firmware.  It works, given the both firmwares are same, just the present one is deodexed.
