### ISSUE TITLE
Add Wallpapers in gapps-config would cancel pixellauncher's install

### ISSUE THREAD

**Issue by lzp4ever** [opengapps/opengapps#398]
Add Wallpapers in gapps-config would cancel pixellauncher's install, but there is no any description in Stock Package's Wiki page

**Comment by mfonville** [comment]
It is described in: https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options :

`PixelLauncher` - To Exclude/Include Pixel Launcher (requires `Search` and `Wallpapers`) [Super/Stock]

If you have more support questions, please first use XDA Forum
