### ISSUE TITLE
Reduce GApps packages size

### ISSUE THREAD

**Issue by rapperskull** [opengapps/opengapps#40]
With the introduction of multiple versions of the same app to support multiple screen densities the size of the packages grew a lot.
As already discussed we'll use the XZ compression algorithm to store the apps in the zip file as save a lot of space.

**Comment by mfonville** [comment]
Btw, what about a hybrid solution? So only xz-zipping those folders that actually have multi DPI variants, and keeping the other packages as folders? That should have a positive impact on speed, while not having to rewrite the whole size-detection mechanism?
One could check if in a folder there is a .tar.xz file, and the follow the .xz mechanism, and otherwise fall back on the legacy code.

**Comment by rapperskull** [comment]
Adopting this solution requires the compression of the zip file, and probably the extraction of the tar.xz files from the archive will add more time. Probably storing of the size of all the folders is a better solution. For now I'll build and test the fornexus package to see how it performs on my Nexus 5 and if all the apps are installed. Then we'll plan a solution.

**Comment by rapperskull** [comment]
As on your device the size calculation is very slow also on my Nexus 5. It's a lot faster on Ubuntu (probably because of more RAM). One thing we can do is store the result of which_dpi instead of calling that function again when extracting the files. The size calculation process will still be slow, but the extraction faster.
But probably storing what we need in a text file when building the package is better (and certainly faster). We can maybe first try to store only the densities: in this way we can skip one of the two tar calls, while keeping things easy.

**Comment by mfonville** [comment]
I think the size of /tmp is limited to the amount of RAM the device has. And since plenty of devices are short of RAM, storing all the extracted files from calculation to installation is probably not the best idea.

I think having compression turned back on for the zip in the hybrid solution is not a bad thing, since decompressing a zip on the phone does not put that much strain on a CPU. And the buildbot has plenty of time to build the zips every night (when GitHub fixes their upload).

**Comment by rapperskull** [comment]
I thought about storing only the result of which_dpi and not to keep the tar.xz files. Separating DPI-specific and non-DPI-specific apps in folders and archives is only a temporary solution because more apps could became DPI-specific and the good effects will fade away.

For now I'll store the available densities in a text file so that we can avoid calling tar in which_dpi, then if it's not sufficient, I'll try to also store the sizes, so we can avoid calling tar in get_appsize too.

**Comment by mfonville** [comment]
ok, so if you store the result of which_dpi, how many xz-extractions do we save? And you store the which_dpi during the generation of the package, or during the execution in recovery?

Your point about the it being a temporary solution is true.

**Comment by rapperskull** [comment]
If we store the result, we'll not save any extraction (that's BTW the fastest thing in the entire process), but we avoid calling tar again to list all densities (again). Every tar call is very slow, because the entire archive have to be processed. I'm talking about the execution in recovery BTW.
If we save the available DPIs before, when building, we can avoid both tar calls (during size calculation and extraction) and save more time. If we also save the sizes, we avoid another call during get_appsize, but I have to find a convenient way to store the results.

**Comment by mfonville** [comment]
Ok, now I understand what you mean. I my mind tar [operations = xz operations], but of course they are not :-P
So yeah, saving those extra TAR calls is then indeed the best way to go. If it keeps going too slow, we can add those other workarounds if necessary.

**Comment by mfonville** [comment]
I think I will want to 'try' for the next xz-compressed build with -9 instead of -9e, to see if building goes any faster at the buildbot server, because at the moment it is slow as hell, and doing so many builds, it adds up.

**Comment by rapperskull** [comment]
If you can change it manually, please test it, and if there's a real speed improvement, we'll change and commit.

**Comment by mfonville** [comment]
Yeah, I did change it manually now, so all builds now (after arm4.4 and arm5.0) will be done with this 'lower' setting, and I am monitoring the cpu and memory usage.

**Comment by mfonville** [comment]
It is barely better, so I think I will try to implement a much better solution for us: a caching mechanism :)
