### ISSUE TITLE
installer: Missing ContactsStock in optional_aosp_remove_list

### ISSUE THREAD

**Issue by airend** [opengapps/opengapps#403]
**Issue description:**

Although it's being used internally, the `ContactsStock` keyword is not parsed in the config file. Any reason for not adding `contactsstock` to `optional_aosp_remove_list ` in `scripts/inc.installer.sh`?

**Comment by chinmaykunkikar** [comment]
@airend I know it's been a while since this is here, but can you tell me on what ROM/firmware you experienced this?

**Comment by airend** [comment]
I think it was a self-built AOSP 7.0, and the issue I was describing got solved after adding `contactsstock` to `optional_aosp_remove_list`. I haven't checked the current behavior, so it may be fixed.

**Comment by chinmaykunkikar** [comment]
Great to know that @airend :+1:
Now if you are sure about it, can you, if not then ask moderators to close this issue?

**Comment by airend** [comment]
Sure, I just checked on a fresh `N2G47T` build with today's pico GApps, and this quirk persists. AOSP Calculator, Calendar, and Clock are all removed as expected, but Contacts persists (unless I edit `installer.sh` as described above. Anyway, I'm going to close the issue now since it's not terribly important.

**Comment by mfonville** [comment]
the reason that it is not in the list (and only used internally) is that the OS expects to always have one "contacts" application installed
