### ISSUE TITLE
Pixel XL

### ISSUE THREAD

**Issue by cjkacz** [opengapps/opengapps#406]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [x ] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [ ] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [ ] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aissue)

*If Open GApps installation fails:*
- [ ] Is the issue reproducible using the latest version of your recovery?
- [ ] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

*If receiving force closures after Open GApps installation:*
- [ ] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [ ] The issue is reproducible on clean (=wiped ``/data/`` partition) installation
- [ ] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [ ] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**

[Short description of problem here]

**Reproduction Steps:**

1. [First Step]
2. [Second Step]
3. [Other Steps...]

**Expected behavior:**

[Describe expected behavior here]

**Observed behavior:**

[Describe observed behavior here]

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

[Debug log of the Open GApps installation](url)

[A logcat of the moment I receive the force closure (if applicable)](url)

Build error trying to build gapps in marlin 7.1.1

FAILED: /bin/bash -c "(echo -e \"target \"\"\\033[36m\"\"Prebuilt:\"\"\\033[0m\"\" GoogleCalendarSyncAdapter (/home/cjkacz/7.1.1/out/target/product/marlin/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk)\" ) && (mkdir -p /home/cjkacz/7.1.1/out/target/product/marlin/obj/APPS/GoogleCalendarSyncAdapter_intermediates/ ) && (/home/cjkacz/7.1.1/out/host/linux-x86/bin/acp -fp  /home/cjkacz/7.1.1/out/target/product/marlin/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk ) && (if (zipinfo /home/cjkacz/7.1.1/out/target/product/marlin/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk 'lib/*.so' 2>/dev/null | grep -v ' stor ' >/dev/null) ; then rm -rf /home/cjkacz/7.1.1/out/target/product/marlin/obj/APPS/GoogleCalendarSyncAdapter_intermediates/uncompressedlibs && mkdir /home/cjkacz/7.1.1/out/target/product/marlin/obj/APPS/GoogleCalendarSyncAdapter_intermediates/uncompressedlibs; unzip /home/cjkacz/7.1.1/out/target/product/marlin/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk 'lib/*.so' -d /home/cjkacz/7.1.1/out/target/product/marlin/obj/APPS/GoogleCalendarSyncAdapter_intermediates/uncompressedlibs && zip -d /home/cjkacz/7.1.1/out/target/product/marlin/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk 'lib/*.so' && ( cd /home/cjkacz/7.1.1/out/target/product/marlin/obj/APPS/GoogleCalendarSyncAdapter_intermediates/uncompressedlibs && find lib -type f | sort | zip -D -X -0 ../package.apk -@ ) && rm -rf /home/cjkacz/7.1.1/out/target/product/marlin/obj/APPS/GoogleCalendarSyncAdapter_intermediates/uncompressedlibs; fi ) && (if ! /home/cjkacz/7.1.1/out/host/linux-x86/bin/zipalign -c -p 4 /home/cjkacz/7.1.1/out/target/product/marlin/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk >/dev/null ; then mv /home/cjkacz/7.1.1/out/target/product/marlin/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk /home/cjkacz/7.1.1/out/target/product/marlin/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk.unaligned; /home/cjkacz/7.1.1/out/host/linux-x86/bin/zipalign -f -p 4 /home/cjkacz/7.1.1/out/target/product/marlin/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk.unaligned /home/cjkacz/7.1.1/out/target/product/marlin/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk.aligned; mv /home/cjkacz/7.1.1/out/target/product/marlin/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk.aligned /home/cjkacz/7.1.1/out/target/product/marlin/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk; fi )"
target Prebuilt: GoogleCalendarSyncAdapter (/home/cjkacz/7.1.1/out/target/product/marlin/obj/APPS/GoogleCalendarSyncAdapter_intermediates/package.apk)
acp: missing destination file

**Comment by mfonville** [comment]
Could you try with the packages from tomorrow, May 27th?
Pixel support should be fixed with https://github.com/opengapps/opengapps/commit/3a217a58e56fbf9a706d7ef012799ce14b05e4c6

**Comment by cjkacz** [comment]
I will try to build them sometime this weekend for sure!
