### ISSUE TITLE
Installer should switch error receiver to Google Play services (gms) for Nexus experience

### ISSUE THREAD

**Issue by osm0sis** [opengapps/opengapps#407]
In build.prop on CM:
`ro.error.receiver.system.apps=org.cyanogenmod.bugreport`

Changing this to `com.google.android.gms` once Google Play services are installed via GApps results in the same bug reporting experience as a stock Nexus device (which do have this set in build.prop), so should be preferred over AOSP or CM's variants.

A simple sed on the build.prop as part of the installer would do the trick, and maybe it could be opted out with a keyword like forcestockbugreport or something. 👍

**Comment by KreAch3R** [comment]
A lot of AOSP roms already do this (check also the line below that): 
https://github.com/krexus/vendor_krexus/blob/n%2B/products/common.mk#L15..L16

but I agree it's a GApps related prop.

**Comment by mfonville** [comment]
@osm0sis would you be willing/able to put the `sed` for that in a PR?

**Comment by osm0sis** [comment]
Yup, I can do that. Probably in the new year once I've got a few days off. I'll probably put it down by the dialer workaround. Sound good?

**Comment by osm0sis** [comment]
Should work with the above commit merged.
