### ISSUE TITLE
Uninstaller for GApps? MIUI8 keeps GApps crashing.

### ISSUE THREAD

**Issue by GGGunrunner** [opengapps/opengapps#408]
Trying to make it work on Galaxy Note 4 with MIUI8. There are leftovers from MIUI7 because I migrated my data from it.

Is there a way to wipe GApps clean and try a fresh install? No sight of an uninstaller. 

# End Open GApps Install Log

!!! WARNING !!! - Duplicate files were found between your ROM and this GApps
package. This is likely due to your ROM's dev including Google proprietary
files in the ROM. The duplicate files are shown in the log portion below.

# Begin GApps <> ROM Duplicate File List
/system/app/WebViewGoogle
/system/etc/permissions/com.google.android.maps.xml
/system/etc/permissions/com.google.android.media.effects.xml
/system/etc/permissions/com.google.widevine.software.drm.xml
/system/etc/preferred-apps/google.xml
/system/etc/sysconfig/google.xml
/system/lib/libfilterpack_facedetect.so
/system/usr/srec/en-US/
# End GApps <> ROM Duplicate File List

**Comment by mfonville** [comment]
Wipe /system and reflash your ROM

for more support questions please use xda
