### ISSUE TITLE
Ok Google everywhere / Hotword detection

### ISSUE THREAD

**Issue by KreAch3R** [opengapps/opengapps#409]
**Issue description:**

Latest Open-GApps (both Stock and Nano) can't allow "Ok, Google" hotword detection in Google Assistant to work correctly on bullhead, hammerhead (tested by me) and angler (reported). Dynamic GApps by @beanstown106 currently provide the correct behavior for bullhead and angler, but hammerhead has still the problem mentioned below.

**Reproduction Steps:** / **Observed behavior:**

**For arm64 (bullhead, angler)**

1. Google Assistant --> Settings --> "Ok Google" detection
2. Try to enable both switches
3. If you only see one switch, try to enable Smart Lock --> Voice, then the second switch should appear
4. The second switch "use everywhere" switches back to off.
5. Logcat shows a specific error (I can record it next time I test it, sorry for that)

**For arm (hammerhead)**

1. Google Assistant --> Settings --> "Ok Google" detection
2. Try to enable both switches
3. If you only see one switch, try to enable Smart Lock --> Voice, then the second switch should appear
4. Second switch stays on
5. Ok Google works everywhere (only on screen on, because hammerhead)
6. Google Assistant needs retraining every time
7. Trying to "delete voice model" FCs leads you to a NullPointerException:
https://hastebin.com/lafazopeda.sql

**Expected behavior:**

"Ok Google" everywhere should work. The second switch on GA Settings should work on angler, bullhead. On hammerhead, it shouldn't need retraining every time.

Full / Mini Dynamic GApps have it working on bullhead, angler, so it must be a config file / apk used that's different, and collectively, we should be able to pinpoint that.

**Comment by mfonville** [comment]
I recently did do some research on the Hotword APKs, and they are all the same except for some memory mapping locations, that all differ for each device.

So it seems we will need to make a mechanism that installs a different hotword apk per device

**Comment by KreAch3R** [comment]
if that's the case, yes that would be very hard to do.

So you're thinking that it depends solely on the Hotword apk? That could be easily tested by flashing Open-GApps and replacing Hotword apk with the one @beanstown106 uses? Or are there libs / .xml files involved?

Also, regarding hammerhead, I tried to troubleshoot it a bit on my own. It seems that it could be a permissions problem, in the following directory:
/data/data/com.google.android.googlequicksearchbox/app_sid

because I tried to chmod it into 777 and then files started appearing in that folder. But the app behavior didn't change (i.e. it still asked to be retrained).

I don't think a "install per device" will be feasible, yeah. But we can at least make it work for some devices (angler, bullhead) like it does on Dynamic GApps, and maybe pinpoint the correct Hotword for hammerhead (if it exists) so a flashable zip could be made (for anyone willing enough to find it).
 
If you've got any other ideas for me to test, I can do the debugging. I just don't know where to start.

**Comment by dcd** [comment]
Yes, it depends solely on the Hotword apk.

If you replace the HotwordEnrollment.apk with stock immediately after flashing gapps, the issue is resolved (bullhead)

No libs/xml

**Comment by dcd** [comment]
It's worth noting that bullhead's vendor repo ships the stock HotwordEnrollment.apk.

Flashing an opengapps package including HotwordEnrollment.apk results in the non-working state.

A previously reported bug (that I can't find now): using a gapps-config.txt results in the opengapps installer removing the stock version and not replacing with its own, leaving the device with no HotwordEnrollment.apk at all.  A workaround is to remove the stock version before flashing opengapps.  This results in the same non-working state.

It seems to me the easier solution would be to not remove/replace it.

**Comment by KreAch3R** [comment]
Thanks for the nice info @dcd ! 

I tried downloading the latest official hammerhead image and I couldn't find a HotwordEnrollment apk in there, but I will re-try. Given your info, this would mean that the hammerhead problem is just because there is no official HotwordEnrollment for that.

I saw mentions that the latest Google App (maybe beta) apk solves both problems, but I wasn't able to test, yet.

Has anyone tried that?

**Comment by cabrerahector** [comment]
> Has anyone tried that?

I just did and "OK Google" seems to be working again (no retrain loop!) after installing the latest Google App beta from apkmirror (at the time of writing it's version 6.10.36.21 beta arm no dpi.)

**Comment by KreAch3R** [comment]
@cabrerahector I've seen mentions of that, but I haven't tried it yet. I'll grab the latest version and re-try.

**Comment by KreAch3R** [comment]
I just tried the 6.10.36.21 beta arm no dpi from apkmirror and I can confirm the same result, I think. Both "Ok Google everywhere" and "Smart unlock" (when the device hasn't gone to deep sleep due to hammerhead limitations) work. :)

**Comment by vdavy** [comment]
Hi all,

Just found this thread while googling this issue (I have a bullhead device and got the same issue), and you should have a look : https://plus.google.com/+NathanBenis/posts/ftAWjDCPeKC

**Comment by KreAch3R** [comment]
@vdavy That post was one of the outcomes of _this_ post. ;) (Nate is already mentioned in here). We are all aware already, thank you.

**Comment by Happyfeet01** [comment]
I have the same issue. The Hotword don't work. Android 7.1.1, Nexus 5x.

**Comment by eagleec** [comment]
By any chance is there a reliable method to get this working on angler?  As of 3/4/17 release I was still experiencing the hotword forced disabling.

**Comment by jakew02** [comment]
This works on bullhead with all packages: https://github.com/opengapps/opengapps/pull/460

**Comment by kockok** [comment]
Hello, please ADD "Hotword" and "Offline Speech" in pico variant. This is because most of other packages can be downloaded via google play. Thanks.

**Comment by josephcsible** [comment]
@kockok That's not at all related to this bug, and it's not a good idea either (Pico is supposed to be the smallest viable package).

**Comment by kockok** [comment]
@josephcsible Yeah, but I think this issue is closely related to my suggestion. If not touching Pico, I would suggest Nano to remove FaceDetect, FaceUnlock (really, nobody would use this technology these days) and Google App( can be downloaded via google play).

**Comment by juliohm1978** [comment]
I stumbled into this issue using MokeeDev (a LineageOS based ROM), but now I'm curious.

Where can I find the proprietary HotwordDetection APK for my device. I have an Asus Zenfone 2, Z00A model. Would this APK be inside the original firmware package?
