### ISSUE TITLE
Wiki - Aroma Package Screenshots Broken

### ISSUE THREAD

**Issue by tmartin357** [opengapps/opengapps#410]
The link for the screenshots of the installation process for the Aroma Package (Wiki) is broken (leads to a 404 page).
 
The link address is https://imgur.com/a/c9Jir
 
Revision: [609cf78](https://github.com/opengapps/opengapps/wiki/Aroma-Package/609cf789f49601a9015207f39561e6291e32523b)

**Comment by mfonville** [comment]
They are indeed missing, for some reason imgur has deleted them, it seems :-/
I tried checking if they were available in archive.org, but apparently not.

@johnnyxmas do you maybe still have them locally available to upload them again?

**Comment by johnnyxmas** [comment]
No; definitely long gone. Honestly, they may not even be applicable anymore. I also no longer have an Android device to make new ones on. One of you can feel free to make new ones; I believe I did it in a 5-minute period while microwaving some soup. 

Thanks,

JohnnyXmas | @j0hnnyxm4s
~~*\Sent while mobile/*~~

**Comment by chinmaykunkikar** [comment]
@tmartin357 @mfonville @johnnyxmas Just updated the wiki with the screenshots.
https://github.com/opengapps/opengapps/wiki/Aroma-Package/_compare/7086f3f02655eb8fac41cd7f7a691eb5727f371e

The updated link is - http://imgur.com/a/gBfR6

Hope this will close this issue 😄

**Comment by mfonville** [comment]
Super thanks @chinmaykunkikar !
