### ISSUE TITLE
Support for lineageos.org

### ISSUE THREAD

**Issue by gismo2004** [opengapps/opengapps#411]
CyanogenMod is now LineageOS, hence they have changed some names.

ro.build.flavor=cm_xxx 
has changed to 
ro.build.flavor=lineage_xxx

thus "cmcompatibilityhacks" are not enabled.
https://github.com/opengapps/opengapps/blob/master/scripts/inc.installer.sh#L1345

please add support for LineageOS

**Comment by jumoog** [comment]
no it's still  ro.build.flavor=cm_xxx

**Comment by gismo2004** [comment]
well, i have seen, that you already have created a pull-request!

THX for that!

and for clarification, this is how it should look like in future for all
devices:
https://review.lineageos.org/#/c/154693/
