### ISSUE TITLE
INFO ..... 

### ISSUE THREAD

**Issue by alviteri** [opengapps/opengapps#414]
I want know if this is opengapps related or rom .....

this is happening after install new OTA with cm/los recovery

https://hastebin.com/xodonodehu.vbs

@mfonville

**Comment by alviteri** [comment]
actual rom ... lineageOS

**Comment by mfonville** [comment]
`android.ext.services` AOSP one is replaced with its Google variant by GApps.

Don't use GitHub for support requests please.
You need to use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071) for support requests, directly opening GitHub issues is *not* appreciated.

**Comment by alviteri** [comment]
Maarten then when new OTA is installed will overwrite gapps one and then bootloop ... Or it seems
