### ISSUE TITLE
no report when simulating an opengapps installation

### ISSUE THREAD

**Issue by promeneur** [opengapps/opengapps#416]
**Issue description:**

case : I use opengapps android app (manualy using twrp 3.0.2-0-s2vep leads to the same problem)

I use "stock" package.

opengapps creates /sdcard/Download/OpenGapps/ folder where it puts zip files and others.

I put a file gapps-config.txt in /sdcard/Download/OpenGapps/ folder.
This file contains "Test" key because I want to be sure there is enough place in system partition for the list of apps I chosen to install. Then I expect a report with the size of the system partition and the size of what it would be installed.

I hit "install"
then
smartphone restarts launching twrp
then
twrp checks "super" package
then
we read messages indicating that twrp simulates installation, calculates space then creates a log 
then
smartphone restarts android

I go to see /sdcard/Download/OpenGapps/

There is no "open_apps_log.txt" file as expected. (see https://github.com/opengapps/opengap...es-and-Options)

but there is open_gapps_log.txt with date 1970/1/1

We can't read this file with MIXplorer editor.
We failed to get any property or permission. We can't delete it. we can't copy it.
MIXplorer has SU authorization. 

[Short description of problem here]

**Expected behavior:**
a report about simulation is created in opengapps folder

**Observed behavior:**

no report about simulation is created in opengapps folder

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

same problem as opengaps_log.txt for opengapps_debug_logs.tar.gz

**Comment by mfonville** [comment]
Could you boot into TWRP recovery manually, and check if you can then access the files using adb or the built-in filemanager of TWRP?
Because it seems like the TWRP doesn't have the date set correctly, nor the access rights to (files at ) /sdcard/

**Comment by promeneur** [comment]
with twrp i renamed the 2 files
then
i ask for twrp to simulate installation then it creates new files with the same problem.

perhaps the solution is to change the owner and group and the permissions?

i am not a techie. waht owner and group, what permissions?

**Comment by mfonville** [comment]
Set the permissions to read+write for owner+group+other

I will see if I can make the script enforce these proper permissions by default, even if TWRP doesn't set them correctly itself (as is the case in your situation, for unknown reasons)

**Comment by promeneur** [comment]
the problem of setting permission is that twrp each time we use it replaces open_gapps_log.txt by a new one with the same problem!

i experimented this : 

from twrp i delete open_gapps_log.txt
then
i restart smartphone
then
from my pc i create a text file open_gapps_log.txt in /sdcard/Download/OpenGapps/
this text file has no problem.
then
i switch off smartphone
then
i start smartphone in recovery mode
then
i ask twrp to simulate installation of "stock" package
then
i restart android
then
in /sdcard/Download/OpenGapss/ we found a new open_gapps_log.txt with the same problem.
 
perhaps i may create a bug report at https://github.com/TeamWin/Team-Win-Recovery-Project ?

**Comment by promeneur** [comment]
the problem comes from twrp.
before using twrp i made a clean install of opengapps android app.
opengapps creates a folder "OpenGapps".
i can list the contents of "OpenGapps" folder with user rights.

After simulation by twrp then:
- only if i get root rights i can list the contents of "OpenGapps".
- i can rename, delete, change permissions with only TWRP not with Mixplorer even with root right.

**Comment by promeneur** [comment]
i chnaged permissions of open_gapps_log.txt to 666 with TWRP
then
i restart android
then
nothing changes.
i can't read open_gapps_log.txt with Mixplorer editor.

**Comment by promeneur** [comment]
i updated twrp to 3.0.3.0-s2vep from https://s.basketbuild.com/devs/GHsR/RECOVERY
then no more problem.
now i get a report open_gapps_log.txt of simulating install of a custom "stock".

thanks to GHSR for this new version of TWRP s2vep for my Samsung S2 Plus.
