### ISSUE TITLE
Phonesky is not installed - 480: bad number

### ISSUE THREAD

**Issue by ishitatsuyuki** [opengapps/opengapps#417]
*If Open GApps installation fails:*
- [x] Is the issue reproducible using the latest version of your recovery?
- [x] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*
Side note: it's a badly maintained TWRP, but somehow still a decent version.

**Issue description:**

Phonesky is not extracted on installation. After the inspection of logs, I've found a suspicious entry:
```
Archive:  /sdcard/open_gapps-arm64-6.0-mini-20170107.zip
signed by SignApk
 extracting: /tmp/Core/vending-all.tar.lz  
ash: 480
480: bad number
ash: 480
480: bad number
ash: 480
480: bad number
ash: 480
480: bad number
ash: 480
480: bad number
ash: 480
480: bad number
Found Core/vending-all DPI path: unknown
/tmp/tar-arm: vending-all/common: Not found in archive
/tmp/tar-arm: Exiting with failure status due to previous errors
```

**Reproduction Steps:**

Device: 360 N4S / TWRP v3.0.2

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

[logs.tar.gz](https://github.com/opengapps/opengapps/files/691451/logs.tar.gz)

**Comment by mfonville** [comment]
Your build.prop is broken, you have twice this line:
`ro.sf.lcd_density=480`

According to the .prop standards, every property has to be unique and is only allowed once. Remove one of the two lines to make the prop-file compliant again.
