### ISSUE TITLE
Please add option to enable the Google Assistant.

### ISSUE THREAD

**Issue by LinkofHyrule89** [opengapps/opengapps#418]
A developer was trying to submit a patch to enable the Google Assistant in Lineage OS and was told it should be done in the gapps package instead. I'm simply posting this asking for this option which should be pretty simple to do since all it needs to do is add a line to system.props the Lineage OS dev said it can be accomplished with an ini.d script. Here's the commit for the changes. I know these changes work on the OnePlus One and Nexus 7 Flo and I imagine it works on most devices as well. https://review.lineageos.org/#/c/155887/1

**Comment by flo071** [comment]
it is working on OnePlus 2, 3 and galaxy s4 too. 
tried it all.

**Comment by archon810** [comment]
Interesting to see if this gets merged.

**Comment by mfonville** [comment]
Done, see https://github.com/opengapps/opengapps/pull/419#issuecomment-276917273 for more info
