### ISSUE TITLE
Force Google Messenger installation on tablets with SIM card slot/s

### ISSUE THREAD

**Issue by VincentJoshuaET** [opengapps/opengapps#420]
I have a tablet, when I flash Open GApps, Google Messenger is not installed because my device is detected as a "tablet".

**Comment by mfonville** [comment]
@VincentJoshuaET could you upload the debug tar gz? Maybe the build.prop contains hints how to detect the SIM capabilities for tablets in a reliable way

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
