### ISSUE TITLE
Google play services has stopped when installed on AOSP rom

### ISSUE THREAD

**Issue by shlatchz** [opengapps/opengapps#427]
I have installed [android-6.0.1_r72][1] *AOSP* Rom on a *Nexus 5* device.

The Rom doesn't come with *Google Apps*, so I've updated my Rom with the [following changes][3] and tried to install GApps from the [following site][2], but after the installation I get the following error countless of times:

> Unfortunately, Google Play services has stopped

I found this error in logcat:

> 01-17 11:14:52.750  3525  5402 E AndroidRuntime: FATAL EXCEPTION: GoogleLocationService

> 01-17 11:14:52.750  3525  5402 E AndroidRuntime: Process: com.google.android.gms.persistent, PID: 3525

> 01-17 11:14:52.750  3525  5402 E AndroidRuntime: java.lang.SecurityException: "gps" location provider requires ACCESS_FINE_LOCATION permission.

> 01-17 11:14:52.750  3525  5402 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1620)

> 01-17 11:14:52.750  3525  5402 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1573)

> 01-17 11:14:52.750  3525  5402 E AndroidRuntime: 	at android.location.ILocationManager$Stub$Proxy.addGpsStatusListener(ILocationManager.java:741)

> 01-17 11:14:52.750  3525  5402 E AndroidRuntime: 	at android.location.LocationManager.addGpsStatusListener(LocationManager.java:1522)

> 01-17 11:14:52.750  3525  5402 E AndroidRuntime: 	at aker.a(:com.google.android.gms:1064)

> 01-17 11:14:52.750  3525  5402 E AndroidRuntime: 	at akbc.b(:com.google.android.gms:6342)

> 01-17 11:14:52.750  3525  5402 E AndroidRuntime: 	at akbc.handleMessage(:com.google.android.gms:279)

> 01-17 11:14:52.750  3525  5402 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

> 01-17 11:14:52.750  3525  5402 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

> 01-17 11:14:52.750  3525  5402 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:61)

  [1]: https://source.android.com/source/build-numbers.html#source-code-tags-and-builds
  [2]: https://devs-lab.com/android-gapps-download.html#StockGoogle_Apps
  [3]: https://github.com/TeamExodus/frameworks_base/commit/9c36be651e83fb039a262682839bd920b033007a

**Comment by mfonville** [comment]
Please read the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ#2-im-having-a-problem-with-my-open-gapps-install-what-information-do-you-need-to-help-me) and the support instructions mentioned. You need to use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071) for support requests, directly opening GitHub issues is *not* appreciated.

PS: Please remember to at least include your installation debug log and (if applicable) a logcat when requesting support.
