### ISSUE TITLE
signapk.sh does not build a verifiable signature

### ISSUE THREAD

**Issue by Feelivent** [opengapps/opengapps#44]
Verifying the zip signature in TWRP 2.8.7.0 fails. 
Tested with open_gapps-arm-4.4-stock-20150704.zip and open_gapps-arm-4.4-stock-20150701.zip

Please do sign, even if it's just with AOSP test-keys, so at least integrity is guaranteed.
http://wiki.rootzwiki.com/Signing

**Comment by mfonville** [comment]
It is a known issue. We are still trying to work out the last problems with the signature, because we can't use apksign.jar and we do this manually from the shell. The signature in binary form in the zip comment field is still broken for unknown reason :-/

**Comment by mfonville** [comment]
I switched the stable branch for now to using signapk.jar, so from tomorrow on the zips will be signed properly.
We still want to fix the shell version though...

**Comment by Lekensteyn** [comment]
These implementations might be of interest:

update.zip installer and signature verification:
 - https://github.com/CyanogenMod/android_bootable_recovery/blob/cm-12.1/install.cpp#L249
 - https://github.com/CyanogenMod/android_bootable_recovery/blob/7b0fd22410453162a44d0fba9e446acb0dd904e9/verifier.cpp#L107

SignApk source:
 - https://github.com/android/platform_build/blob/master/tools/signapk/SignApk.java

**Comment by osm0sis** [comment]
Is this working yet? Signing a shell update-binary zip always created issues with unzip until I started using Chainfire's zipadjust binary. I built it for Windows but it should be easy to build for your build server as well.

http://forum.xda-developers.com/android/software-hacking/dev-complete-shell-script-flashable-zip-t2934449/post56621542

**Comment by mfonville** [comment]
No, it doesn't work yet. I was very close to it, but at some point other more important developments took priority.
Preference is still to get it working using (posix) shell tools, if possible.

**Comment by osm0sis** [comment]
Definitely check out Chainfire's source for zipadjust and MinSignApk then, maybe you can replicate what they do with shell tools. :+1:

**Comment by nezorflame** [comment]
@mfonville this should be closed now.
