### ISSUE TITLE
Shell code mistake in VR detection (20170204)

### ISSUE THREAD

**Issue by pturley0** [opengapps/opengapps#442]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [ ] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aissue)

*If Open GApps installation fails:*
- [x] Is the issue reproducible using the latest version of your recovery?
- [x] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

*If receiving force closures after Open GApps installation:*
- [ ] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [ ] The issue is reproducible on clean (=wiped ``/data/`` partition) installation
- [ ] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [ ] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**

The following shell script code in `installer.sh` has a mistake in it:

```
# Is device VRMode compatible
for xml in grep -rl 'name="android.software.vr.mode"' /system/etc/; do
  if ( awk -vRS='-->' '{ gsub(/<!--.*/,"")}1' $xml | grep -q 'name="android.software.vr.mode"' /system/etc/ ); then
    vrmode_compat=true
    break
  fi
  vrmode_compat=false
done
```

The _intent_ is to loop through all XML files under `/system/etc` that contain the string `name="android.software.vr.mode"`.

In fact, the `grep` command isn't being executed. Instead, the loop is iterating through the literal string elements:

* `grep`
* `-rl`
* _etc._

The `for` statement should instead be:

```
for xml in $(grep -rl 'name="android.software.vr.mode"' /system/etc/)
```

**Reproduction Steps:**

Attempt to install the 20170204 bundle.

**Expected behavior:**

Normal installation.

**Observed behavior:**

I see these error messages:

```
    awk: grep: No such file or directory
    awk: invalid option -- r
    BusyBox v1.26.2.YDS (2017-01-17 17:03:35 IST) multi-call binary.

    Usage: awk [OPTIONS] [AWK_PROGRAM] [FILE]...

    	-v VAR=VAL	Set variable
    	-F SEP		Use SEP as field separator
    	-f FILE		Read program from FILE
    	-e AWK_PROGRAM
```

**Comment by mfonville** [comment]
Thanks for notifying us of this mistake, I will solve this asap
