### ISSUE TITLE
WebViewStub should be hidden by default

### ISSUE THREAD

**Issue by wangcheng678** [opengapps/opengapps#446]
After I flashed GApps Stock on LineageOS 14.1. Google Play Store showed that Google WebView could be upgraded. But on my Pixel the WebView app is hidden by default. It will not shown at Play Store's My Apps page, nor will be upgraded util you manually enable it in Settings or its Play Store page (screenshot: https://imgur.com/gallery/Ek9Lz). 

I think there is no point to upgrade the WebView(Stub) app since Android N prefers Chrome as WebView provider. It should behave just like in Nexus/Pixel system.

**Comment by mfonville** [comment]
@wangcheng678 this is decided by the webview provider configuration; the patches are described in our wiki https://github.com/opengapps/opengapps/wiki/Notes-for-Android-7.x#webview-providers

The `isFallback` setting activates this behaviour; but there can only be one `isFallback` declaration, which tends to be reserved for the AOSP webview.

You can discuss this issue and behaviour with the ROM developers
