### ISSUE TITLE
Prevent removal of stock dialer app in super package

### ISSUE THREAD

**Issue by kaushikyash** [opengapps/opengapps#448]
I am installing the super package on a custom ROM, all I want is that the Google Phone app does not get installed and the stock AOSP dialer app does not get removed. I do not want to downsize because of the features of this(super) package. A quick response will be appreciated.

**Comment by josephcsible** [comment]
You can already do that via the config file.

**Comment by kaushikyash** [comment]
can u please explain the procedure or tell me the keyword because it is not given in the advanced features and options webpage, and i hope you understood that i want to preserve the stock dialer on installation of super package.

**Comment by josephcsible** [comment]
1. Support requests belong on XDA, not here.
2. The keyword to do what you want is "DialerGoogle", and it is listed on that wiki page.

**Comment by kaushikyash** [comment]
Sorry, I did not read the terms I was in a hurry, my phone was not working on the other ROM. I think this keyword will only prevent installing google dialer, the super gapps removes the default dialer also, what should I do about that?

**Comment by josephcsible** [comment]
Disabling the installation of Google Dialer automatically makes the stock dialer be preserved. (Again, the wiki page says this too, and questions like this being on XDA.)

**Comment by kaushikyash** [comment]
Thank you very much, but the wiki page does not say it prevents stock dialer removal. Anyways, thanks. Closing the issue.
