### ISSUE TITLE
Some apps in TVStock target wrong platform

### ISSUE THREAD

**Issue by Magendanz** [opengapps/opengapps#449]
Some apps in the TVStock package are targeting the wrong Android platform.  For example, I've been focusing on building Amlogic devices in 6.0.1 (SDK 23), but the following APKs in that build are currently targeting platformBuildVersionCode="24" (7.0) in their manifests:

- TVWidget (AtvWidget)
- TVWallpaper (LandscapeWallpaper)
- NoTouch (NoTouchAuthDelegate)
- TalkBack
- TVCustomization (AtvCustomization)
- TVRemote (AtvRemoteService)
- TVPackageInstallerGoogle (CanvasPackageInstaller)
- GamepadPairing (GamepadPairingService)
- TVSearch (Katniss)
- TVLauncher (LeanbackLauncher)
- SetupWraith
- LiveChannels (TV)

Fortunately, the 14 other APKs seem to be targeting the correct platform.

**Comment by Magendanz** [comment]
While you're looking at TVStock, here are a few more things to consider:

- Core/SetupWraith should replace preexisting SetupWizard
- GApps/packageinstallergoogle should replace PackageInstaller (as it's named on Fugu and Molly), not add GooglePackageInstaller
- GApps/tvpackageinstallergoogle should install CanvasPackageInstaller to app (as it is on Fugu and Molly), not priv-app
- GApps/tvremote-lib should be installed into priv-app with APK, not on its own in apps directory

There are still some other issues, but I suspect they're just missing permissions or certs that I'm trying to track down.

**Comment by Magendanz** [comment]
Whoops!  I missed a few:  The following APKs in the 6.0.1 builds are actually targeting SDK 25 (7.1.1):
- TVMusic (Music2Pano)
- TVMovies (VideosPano)
- WebViewGoogle
- TVVEnding (PhoneskyKamikazeCanvas)
- TVGmsCore (PrebuiltGmsCorePano)
Some of these newer apps don't have android.intent.category.LEANBACK_LAUNCHER, so they don't even show up in the LeanbackLauncher.

**Comment by mfonville** [comment]
Thanks for your input @Magendanz 

With the manifests/target platforms; the scripts organize the APKs on the minimum-apk level specified  in the manifest. Sometimes, even though the target says a higher sdk, it does say that it should support the lower sdk level. Did you notice that those APKs with higher targeted sdks did misbehave? or was it just something you noticed?

**Comment by Magendanz** [comment]
There were many that were misbehaving, although I discovered later that resigning APKs with the platform key solved most of the problems that I was seeing.

**Comment by Magendanz** [comment]
On a separate note:  We need to bundle TvProvider.  Live Channels (TV) won't work without it.

**Comment by mfonville** [comment]
TvProvider should be provided by the AOSP codebase afaik

**Comment by Magendanz** [comment]
Okay, I just started systematically reintroducing the apps with targetSdkVersion of 24 or higher, and it's definitely not a problem with the APK signatures.  (I resigned them all with the platform key.)  AtvWidget and LandscapeWallpaper still crash immediately on launch.  NoTouchAuthDelegate crashes during setup, and that blocked SetupWraith so I never got a chance to test Music2Pano or VideosPano.  It's 3:30am here, and so I'm going to skip on the priv-apps for now, but I think it's safe to say that the minSdkVersion doesn't seem to be a good indicator of compatibility.

**Comment by Magendanz** [comment]
BTW, TvProvider is a bunch of information for the Live Channels (TV) app, not TvSettings.  Without it, Live Channels quits on launch, so seems it should be bundled with TV.apk.

**Comment by Magendanz** [comment]
Are we running [lint](https://developer.android.com/studio/write/lint.html) against these packages to warn when they use any APIs above their minSdkVersion?

**Comment by Magendanz** [comment]
BTW, I find the following one-line batch file very helpful in exposing the different SDK targets in these APKs.  There are some interesting inconsistencies that I'm discovering.

forfiles /s /p "%~1" /m *.apk /c "cmd /c echo @file & aapt d badging @file | findstr Version & echo."

**Comment by Magendanz** [comment]
Also, the latest build of AtvRemoteService (version 1.1.0.3340186) in TVStock is the remote client, not the service.

**Comment by robinkooli** [comment]
Nice work! 👍

**Comment by Magendanz** [comment]
Okay, I've got a little puzzle here:  I'm looking at two versions of AtvCustomization and AtvWidget...and they're identical in every way that should matter:  Both res and smali directories are identical after decoding with apktool.  The only difference is the AndroidManifest.xml, where they have different platformBuildVersionCode and platformBuildVersionName values (23/6.0.1 and 24/7.0, respectively).  Both minSdkVersion and targetSdkVersion are 19, so neither should be calling SDK 24 APIs.

However, when I install the version with the 7.0 platform build version on 6.0.1, both crash trying to instantiate their receivers.  Apparently, it can't find the receiver class... but the classes are both there in the APK and in the right place.

Why would this happen??

**Comment by kurocygnus** [comment]
I'm with the same problem... Some apps are still with the wrong sdk, wich made then crash.

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
