### ISSUE TITLE
Do not remove LineageSetupWizard

### ISSUE THREAD

**Issue by zifnab06** [opengapps/opengapps#451]
This commit: https://github.com/opengapps/opengapps/commit/9208920945a3e46622c2bc0568733b8bdcaaf734

removes LineageSetupWizard in 14.1. Without it, you can't enable soft buttons or enable privacy guard. 

LineageSetupWizard is a complete rewrite using the new WizardManager. While I understand removing CMSetupWizard was required on 14.1 (as it was broken), we would prefer it if you did not remove LineageSetupWizard. 

Thanks!

**Comment by ciwrl** [comment]
[SUW-scripts-for-M.zip](https://github.com/opengapps/opengapps/files/781592/SUW-scripts-for-M.zip)

For context, see attached.

**Comment by mfonville** [comment]
@ciwrl be aware that the file link is still available for many, from their GitHub news feed.

I will fix this that it will not be removed on lineage by default, it will get its own new keyword
