### ISSUE TITLE
Does installing a set of apps via the play store provide a different user experience than using the corresponding GApps package?

### ISSUE THREAD

**Issue by praxiq** [opengapps/opengapps#452]
*NOTE*: Sorry I'm not following your template! This isn't about a bug in the code - consider this a documentation feature request. This is a question that probably ought to be answered in the (otherwise excellent and impressively complete!) FAQ.

There are 3 aspects to the question in the title:

First: If I install the Nano package, and then use the Play Store to install everything from the Stock package, will my phone now work the same way as if I had installed the Stock package to begin with? I understand that the apps will not be in the system partition this way, but is that the only difference?

Conversely: If I install the Stock package, can I uninstall individual apps the same way I normally uninstall apps on my phone? If so, if I delete all apps that are not in the Nano package, will the effect be essentially the same as if I had simply installed Nano to begin with?

Finally: The Stock package says it "replaces" lots of stock AOSP apps with Google's alternatives. Does this mean it makes the AOSP apps inaccessible, or simply that these apps get registered as the default handlers for certain intents? If I install Stock but want to use one particular AOSP app that has been replaced, can I do this the same way I would normally switch my default app for a particular action?

**Comment by mfonville** [comment]
Please read the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ#2-im-having-a-problem-with-my-open-gapps-install-what-information-do-you-need-to-help-me) and the support instructions mentioned. You need to use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071) for support requests, directly opening GitHub issues is *not* appreciated.

PS: Please remember to at least include your installation debug log and (if applicable) a logcat when requesting support.

**Comment by mfonville** [comment]
For the FAQ: feel free to improve the wiki, anyone can edit!
