### ISSUE TITLE
Add "Enable Daydream VR support" feature to Open GApps

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [opengapps/opengapps#453]
Open GApps has added an option to enable Google Assistant during installation: #419.

What about Google Daydream VR? ;)

To enable Google Daydream VR support on any not certified Android 7.0+ smartphone need to add

```xml
<feature name="android.software.vr.mode" />
<feature name="android.hardware.vr.high_performance" />
```

to `/system/etc/permissions/handheld_core_hardware.xml` file.

**Comment by SpasilliumNexus** [comment]
There seems to be a caveat to enabling this on a device that has been configured already (as in the user completed SetupWizard, Google syncs the user's account and other info to the device): Adding those entries and attempting to download apps such as Daydream VR will show up as incompatible. I'm not sure if an app's data (Play Store? Play Services? Google Framework?) needs to be cleared for the Play Store to see the device as compatible as I have not tried it.

However, adding those entries on a clean ROM install, before booting into Android, and going through SetupWizard, will make apps such as Daydream VR show up as compatible on the Play Store.

**Comment by FluorescentHallucinogen** [comment]
I just rebooted and everything works like a charm without clearing Google Play Store / Google Play Services / Google Framework app data. Looks like need to to wait a bit to Google VR Services and Google Daydream apps show up as compatible in Google Play Store.

@SpasilliumNexus, could you please create a pull request?

**Comment by mfonville** [comment]
The VR entries should be set be the ROM developers, if the hardware supports it.
Open GApps than automatically follows suit to install the the VRMode-variants of apps if it finds that they are supported.

**Comment by FluorescentHallucinogen** [comment]
@mfonville 

This is a workaround. Like a workaround to enable Google Assistant. For users who know what they do.

Google was an ad company and continues to be. It had most of its profit from ads. But now they are moving towards Apple like market approach. They are making software exclusive to their devices just to sell them and make them stand out. But not everyone has the money to purchase a brand new phone.

E.g. Google Nexus 5X is not Daydream certified. But I've enable Daydream VR support on it and all works like a charm! It's not a hardware limitation, it's software limitation. Why users should wait untill ROM developers enable Daydream support?

If you care about hardware (temperature sensors), need to add a disclaimer something like:
`By using this option, you are accepting the risk of potentially damaging your device if anything goes wrong or your handset overheats.`

**Comment by harut-222** [comment]
У меня Galaxy S3  rom 14.1 Можно ли установить Google daydream Как написать  скрипты flashable

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
