### ISSUE TITLE
Bootloop in Xiaomi Redmi Note 3 Pro

### ISSUE THREAD

**Issue by northtech-fw** [opengapps/opengapps#464]
openGAPPS PICO/ARM64/6.0 (from 4 March 2017 - 22 March 2017 Size: 75.78 MiB) induce bootloop in Xiaomi Redmi Note 3 Pro (Qualcomm).
In previously versions (PICO/ARM64/6.0) size been ~100 MiB and all was normal.

logs in twrp: not mount /system as before versions, only mount /persist.

**Comment by Sparker0i** [comment]
I've been using a Pico variant in RN3 Pro as well, but I haven't got the bootloop issue as you told. (PS. I used the build on 16th March or so). Given that you have been complaining about all the builds between 4th and 22nd March, I'd suggest you to download and install the latest build.
