### ISSUE TITLE
"Files" app?

### ISSUE THREAD

**Issue by kronflux** [opengapps/opengapps#465]
In the most recent LineageOS builds, I've noticed a "Files" app which I can't seem to find in the OpenGApps removal list.
The specific app name is "com.android.documentsui" which is located as "DocumentsUI.apk" under "system\priv-app"

Truthfully I have no idea what it is or what it's from, as I haven't had the time to do any amount of testing or searching, but I wanted to mention it so it can be added. :)

**Comment by TheComputerGuy96** [comment]
Here's the commit that adds "Files" app: https://github.com/LineageOS/android_frameworks_base/commit/4b90cd2e4bf9498d50825675138acc8cb70335fc

**Comment by mfonville** [comment]
@TheComputerGuy96 how essential is it? Do things break down if it is removed?

**Comment by Sparker0i** [comment]
@mfonville Well if you want to write something to external SD Card via file managers/any other app, it will open this particular 'Files' app, then will ask you to select the SD Card location. Without this app, I think it should be hard to achieve write access to SD Cards.

**Comment by osm0sis** [comment]
It's an integral app to Android. Originally it was exposed as the "Downloads" app with the file manager functionality under the hood, but starting with Nougat 7.1.2, I believe, Google/AOSP has switched it over to the full Files app, and LOS did so in advance.

Should not be removed.

**Comment by mfonville** [comment]
@osm0sis thanks for the clarification.
Then indeed not make this an app that can be removed with the regular keywords. Those that really want to purge it can always use the universal uninstaller method

**Comment by iceman1961** [comment]
Can anyone explain my messenger hack how to stop it did factory reset she
still able to activate camera
