### ISSUE TITLE
Potential problems with the 6.0 Installation script and SELinux contexts

### ISSUE THREAD

**Issue by pturley0** [opengapps/opengapps#466]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [ ] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aissue)

*If Open GApps installation fails:*
- [ ] Is the issue reproducible using the latest version of your recovery?
- [ ] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

*If receiving force closures after Open GApps installation:*
- [ ] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [ ] The issue is reproducible on clean (=wiped ``/data/`` partition) installation
- [ ] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [ ] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**

We install the 6.0 Pico bundle by executing the OpenGApps installation script, with minimal changes, directly on a `/system` file system image, on a host that isn't enforcing SELinux. We're particularly sensitive to holes in SELinux labeling after the OpenGApps installation.

After installing OpenGApps, I used the command `ls -1RZ | grep '?'` to search the resulting file system for paths that lacked SELinux contexts. I found the following:

- `addon.d`
- `build.prop`
- `app/LatinIME/lib64`
- `app/LatinIME/lib64/x86_64`
- `app/LatinIME/lib64/x86_64/libjni_keyboarddecoder.so`
- `app/LatinIME/lib64/x86_64/libjni_latinimegoogle.so`

I can't show that these files aren't labeled correctly when the installation is run on a "real" Android device, but I have suspicions and I thought I'd share them.

Perhaps someone with more understanding of both SELinux and OpenGApps can show that none of these is a problem in a "real" Android device. It wouldn't be _entirely_ unreasonable for someone to dismiss this issue out of hand because the use case is too far off the beaten path. On the other hand, I'm hoping to pique someone's curiosity...

These problems were discovered with the 20170204 6.0 bundle but, based on my inspection of the source, they also appear in the latest (20170321).

**Reproduction Steps:**

1. Install OpenGApps
2. Look for files lacking SELinux context using the command: `ls -1RZ | grep '?'`

**Expected behavior:**

After installing OpenGApps, no files/directories under `/system` should lack an SELinux context.

**Observed behavior:**

After installing OpenGApps, a number of files/directories under `/system` lack SELinux contexts.

**`addon.d`**

The installation script creates the file `/system/addon.d/70-gapps.sh`, and even sets its SELinux context:

    set_perm 0 0 755 "/system/addon.d/70-gapps.sh"
    ch_con "/system/addon.d/70-gapps.sh"

What it *doesn't* do is set the SELinux context of the `/system/addon.d` directory itself.

I haven't been able to locate the specific place in the installation script that creates `/system/addon.d`.

**`build.prop`**

Here's the snippet from the installation script that adjusts `build.prop`:

    # Use Gms (Google Play services) for feedback/bug reporting (instead of org.cyanogenmod.bugreport or others)
    sed -i "s/ro.error.receiver.system.apps=.*/ro.error.receiver.system.apps=com.google.android.gms/g" /system/build.prop
    sed -i "\:# Apply build.prop changes (from GApps Installer):a \    sed -i \"s/ro.error.receiver.system.apps=.*/ro.error.receiver.system.apps=com.google.android.gms/g\" /system/build.prop" $bkup_tail

    # Enable Google Assistant
    if ( grep -qiE '^googleassistant$' "$g_conf" ); then  #TODO this is not enabled by default atm; because Assistant still has various regressions compared to Google Now
      if ! grep -q "ro.opa.eligible_device=" /system/build.prop; then
        echo "ro.opa.eligible_device=true" >> /system/build.prop
      fi
      sed -i "\:# Apply build.prop changes (from GApps Installer):a \    if ! grep -q \"ro.opa.eligible_device=\" /system/build.prop; then echo \"ro.opa.eligible_device=true\" >> /system/build.prop; fi" $bkup_tail
    fi

Editing under _our_ conditions destroys the SELinux context of `build.prop`, and that context is never restored. Perhaps that's a non-problem for "real" devices.

**`app/LatinIME/lib64` and below**

Here's the snippet from the installation script that installs Swype:

        ui_print "- Installing swypelibs"
        extract_app "Optional/swypelibs-lib-$arch"  # Keep it simple, swypelibs is only lib-$arch
        install -d "/system/app/LatinIME/$libfolder/$arch"
        ln -sfn "/system/$libfolder/$keybd_lib_google" "/system/app/LatinIME/$libfolder/$arch/$keybd_lib_target" # create required symlink
        ln -sfn "/system/$libfolder/$keybd_dec_google" "/system/app/LatinIME/$libfolder/$arch/$keybd_dec_google" # create required symlink

This code uses `install` to create two new directories, and then creates symbolic links within them. It doesn't set the SELinux context for any of these.

**Comment by jawz101** [comment]
Bump

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
