### ISSUE TITLE
Xperia M Cyanogen mod 13 force close

### ISSUE THREAD

**Issue by BauerBG** [opengapps/opengapps#467]
Hi,

After I flashed open_gapps-arm-6.0-pico-20170324.zip my device is not working normal anymore.
Suddenly many apps force close.
Any way to completely remove it without flashing new rom?

Thank you Really much

**Comment by mfonville** [comment]
Please read the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ#2-im-having-a-problem-with-my-open-gapps-install-what-information-do-you-need-to-help-me) and the support instructions mentioned. You need to use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071) for support requests, directly opening GitHub issues is *not* appreciated.

PS: Please remember to at least include your installation debug log and (if applicable) a logcat when requesting support.
