### ISSUE TITLE
scripts/inc.signapk.sh requires xxd but does not check if in PATH

### ISSUE THREAD

**Issue by Bracket-** [opengapps/opengapps#47]
Missing check for xxd. e049739 introduced xxd usage but did not add a check to see if xxd is in PATH.

**Comment by mfonville** [comment]
signapk.sh usage has now moved to a side-branch. We will try to fix this later, when we will get signapk.sh shell version script properly working.

**Comment by mfonville** [comment]
This is merged in the signapkshell branch.
