### ISSUE TITLE
Allow installation of micro , pico , nano etc. variants from Aroma variant

### ISSUE THREAD

**Issue by Sparker0i** [opengapps/opengapps#473]
As we know Aroma variant is the superset of all other variants, I think you guys can provide an option to install micro, pico, nano etc. variants right from aroma.

How this option can be provided:
- User selects to install OpenGapps aroma from recovery
- He is presented with 3 options now : Customized installation, Complete installation, Exit. You guys can add a fourth option here : "Select a predefined variant" (or maybe something else)
- When he selects the option, he is presented with the variants he can install.

This can be a nice option for aroma build.

**Comment by icrunchbanger** [comment]
+1

**Comment by DeathCamel57** [comment]
+1

**Comment by rehannali** [comment]
+1

**Comment by Hammerfest** [comment]
+1
I have actually made a few posts regarding this on XDA
I want to be able to chose Nano, then from there either just install, OR customize by adding extra (IE I want/need Nano + whats needed for Project Fi! nothing else, just Nano + Fi!)

**Comment by chinmaykunkikar** [comment]
+1 @Sparker0i

**Comment by osm0sis** [comment]
AROMA seems to be a mess. It's more likely to be discontinued entirely than to be fixed, especially where AROMA itself is dead.
