### ISSUE TITLE
Issues with Android 7.1.2

### ISSUE THREAD

**Issue by kabirkalsi** [opengapps/opengapps#475]
SetupWizard FC's on Android 7.1.2 Waiting for fix

**Comment by NicholasBuse** [comment]
@mfonville , you can check with [icrunchbanger](https://forum.xda-developers.com/member.php?u=6733592) on [XDA](https://forum.xda-developers.com/showpost.php?p=71802639&postcount=4151). They updated SetupWizard and posted to [AndroidFileHost](https://www.androidfilehost.com/?fid=457095661767152746)

**Comment by icrunchbanger** [comment]
Hi there. If you need i can upload SetupWizard.apk from stock 7.1.2 image, since i dont know if i can create pull request for apk.

**Comment by mfonville** [comment]
Hey, I only had time irregularly lately. I will add the 7.1.2 setupwizard asap

**Comment by icrunchbanger** [comment]
@mfonville Appreciated. Keep up the good work :)

**Comment by mfonville** [comment]
https://github.com/opengapps/all/commit/36165c50e438f3e5193b07076b213d5bf19f1f9c
adds the setupwizards from 7.1.2

Take note, that the issue with 'restore from the cloud' is still broken unfortunately

**Comment by kabirkalsi** [comment]
@mfonville Setupwizard fc's are fixed now but my phone is struck at "Checking For Updates"... hope everything gets back to normal soon
