### ISSUE TITLE
Aroma Installer greyed out from website

### ISSUE THREAD

**Issue by rehannali** [opengapps/opengapps#477]
I don't know where to ask this question so I posted here. Sorry if this is a wrong place to ask a question.
Why Aroma Installer greyed out from the website though it is the best thing you want the app installed by your choice?
Is this option coming back or this is the end for aroma installer?

**Comment by mfonville** [comment]
Sometimes the buildbot does not have enough memory allocated to sign the build, resulting in it not being uploaded. I will manually fix it and allocate more memory for it.

**Comment by rehannali** [comment]
There is not only aroma launcher because I only see x64 based some variants aroma is present and in some variants only super and full gapps package is available. 
Would you tell me ETA of upload?

**Comment by mfonville** [comment]
They are now being uploaded, and luckily I was now able to structurally resolve this issue with updated tools from https://github.com/opengapps/opengapps/commit/63770a25a6066cc33a737903708803491dbcbcde
