### ISSUE TITLE
Restore data from google account

### ISSUE THREAD

**Issue by rehannali** [opengapps/opengapps#478]
I downloaded latest gapps and installed rom. I cannot restore rom google account it always says attach cable i.e. from ios restore, I don't know the exactly problem. Is there a problem with gapps because I can't find anything related to this problem.
x64 Aroma installer, nano latest build i.e. 14-4-2017.

I tried both variants but having the same issue. If I select start new device then google account showed up but I can't restore data from that method.

**Comment by YoDevil** [comment]
Can confirm on ARM releases from April 13 and next releases up to now.

**Comment by Rakpere** [comment]
Potential fix for this issue.

FIX FOR CLOUD BACKUP
OPENGAPPS ON 7.1.2
---------------------------------
Tested on Stock and Aroma packages
---------------------------------
After flashing rom, gapps and root, DON'T REBOOT
Go to TWRP mount menu mount system and exit, then go to
advanced --> file manager and browse to this location

/system/etc/sysconfig

Once in that location you see a file called "Nexus.xml", delete it and you should get cloud backup option once you boot the ROM.
---------------------------------

Confirmed working on atleast stock and aroma packages.

**Comment by MatthewFBullock** [comment]
Hi does this only work for 7.1.2? CRDroid only is up to 7.1.1 :(

**Comment by Rakpere** [comment]
We havent tested on 7.1.1 but go ahead and test :)

**Comment by MatthewFBullock** [comment]
@Rakpere just did. That location path isn't there after flashing 7.1.1

Maybe I'm doing something wrong? Maybe it's just late and I'm too sleepy to think straight haha

**Comment by Rakpere** [comment]
@MatthewFBullock Did you remember to mount system in TWRP?

**Comment by MatthewFBullock** [comment]
@Rakpere by mounting system do you mean just flashing the build onto my phone? Or is that something else? Normally I would just queue CRdroid first and opengapps second and just reboot once they're finished. I am not rebooting after flashing CRdroid/opengapps but that directory isn't found on my phone at least. I'm running CRdroid quark 2.4

**Comment by Rakpere** [comment]
@MatthewFBullock You have to delete the file in TWRP. Mount system in TWRP mount section and use the file manager under advanced. The dev team already made the fix for next release

**Comment by MatthewFBullock** [comment]
Sounds good! When's the next release? Is it nightly?

**Comment by Rakpere** [comment]
@MatthewFBullock I'm not OpenGapps dev, I just happened to find the issue with cloud backup

**Comment by mfonville** [comment]
This will be fixed in today's release (apr 18)
