### ISSUE TITLE
Potential fix on cloud restore on 7.1.2 roms

### ISSUE THREAD

**Issue by Rakpere** [opengapps/opengapps#480]
FIX FOR CLOUD BACKUP FOR OPENGAPPS ON 7.1.2
---------------------------------
Tested on Stock and Aroma packages
---------------------------------
After flashing rom, gapps and root, DON'T REBOOT
Go to TWRP mount menu mount system and exit, then go to
advanced --> file manager and browse to this location

/system/etc/sysconfig

Once in that location you see a file called "Nexus.xml", delete it and you should get cloud backup option once you boot the ROM.
---------------------------------

Script might need an update for 7.1.2 to exclude nexus.xml insertion to the folder.

**Comment by mfonville** [comment]
@Rakpere thank you very much for this hint, I can confirm your  method works to fix the issue and will put out a fix for upcoming builds

**Comment by Rakpere** [comment]
@mfonville Happy to help :)

**Comment by mfonville** [comment]
This will be the fix: https://github.com/opengapps/opengapps/commit/48577907d7c812774dc76b27323326f48ae2f595
