### ISSUE TITLE
[DOCS, incorrect] Prevent automatic Stock removals list

### ISSUE THREAD

**Issue by SimJoSt** [opengapps/opengapps#485]
**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

**Issue description:**

In the wiki/docs commit [`Edited entire page for clarity`](https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options/a6d33202958ed7721df6d439010f8a020b207d3f) by @szhu, 3 new apps were added to the list of apps, which can be prevented from being automatically removed, even though a Google app is installed, which would normally remove the stock version:

```
+CalendarStock # Don't remove Stock Calendar, even if Google Calendar is being installed
+ExchangeStock # Don't remove Stock Exchange services, even if Google Exchange Services is being installed
+KeyboardStock # Don't remove Stock Keyboard, even if Google Keyboard is being installed
```
*([Comparison](https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options/_compare/3b2db2cddc177b04d5e979567066a3c3a86e7ed7...a6d33202958ed7721df6d439010f8a020b207d3f))*

As far as I know, no feature to support these 3 extra apps was introduced. I stumbled upon this problem while trying to prevent `KeyboardStock` from being overwritten by `KeyboardGoogle` which didn't work.

I am aware that it says
> We will look for +Browser, +Email, +Gallery, +Launcher, +MMS, +PicoTTS **and more** to prevent their removal

since the commit [Initial work on 'super' package. Progress on #132](https://github.com/opengapps/opengapps/commit/403c8c46eec77c89f37ad65e75f28a12dff6de98#diff-74d20c82a2668860886a18a38e0f0601R779) by @rapperskull, but I could not find any changes that confirmed there were/are actually more apps on this list than mentioned in the comment, especially not the three mentioned in this issue.

**Reproduction Steps:**

1. Include (or don't exclude) `KeyboardGoogle` in config
2. add `+KeyboardStock` in config
3. install `stock` or `super`

**Expected behavior:**

`KeyboardGoogle` aswell as `KeyboardStock` should be installed on the device.

**Observed behavior:**

`KeyboardGoogle` is installed, KeyboardStock` is missing on the device.

Reproducible with `CalendarStock` (*and probably with `ExchangeStock`; **not tested!***).

**Edit:**
Device: (Lenovo) Zuk Z1 (ham)
OS: lineage-14.1-20170418-nightly
gapps: open_gapps-arm-7.1-super-20170424
recovery: twrp-3.0.2-0-Z1 (booted not flashed)

**Comment by SimJoSt** [comment]
I dug a bit deeper into the code and found out, that `CalendarStock`, `ExchangeStock` and `KeyboardStock` are not supported for overwrite prevention.
If anyone else supports this statement, I will edit the wiki page to reflect that fact as well as supply a PR to adjust the [mentioned comment](https://github.com/opengapps/opengapps/blob/master/scripts/inc.installer.sh#L1623) to something like:

    We will look for applications from the $default_stock_remove_list prefixed with '+' in your gapps-config to prevent their removal

**Comment by szhu** [comment]
Hi @SimJoSt, I edited the wiki page without looking at the script; I was just trying to interpret the old doc to the best of my ability, and assumed that some keywords were accidentally left out. But, as you pointed out, it looks like those keywords are actually not supported. Thanks for digging into this!

**Comment by SimJoSt** [comment]
@szhu Thanks for clearing that up :-) and no worries.
On the bright side it triggered a conversation with @mfonville, me reading some of the code and getting involved. As soon as there is time, we will see what can be done to properly and cleanly support the apps you mentioned and more.
