### ISSUE TITLE
Allow for optional Google apps installation in Aroma package

### ISSUE THREAD

**Issue by Sparker0i** [opengapps/opengapps#487]
So, browsing through the Google's list of apps in the Play Store, I find some apps that may prove essential for a particular niche of users. Some of these apps include - Google Trips, YouTube Kids, YouTube Go, Areo, Snapseed, PhotoScan.

Inclusion of such apps in the optional category in Opengapps could be a great addition.

Regards.

**Comment by SimJoSt** [comment]
Are those apps restricted to specific devices and/or countries and/or carriers? If not, this probably has a very low priority, as they can be installed from the app store, but I think you are right.  
I like including more apps.

**Comment by Sparker0i** [comment]
No carrier restriction (for the above mentioned apps at least). Not sure about country restriction (Youtube Go was made primarily for India, and other countries with low speeds, but I think it is available everywhere). But having such an option could be indeed a great addition.
