### ISSUE TITLE
Allow gapps-config to be stored in persist partition. 

### ISSUE THREAD

**Issue by bgiesing** [opengapps/opengapps#49]
As seen on TK's xda thread:
http://forum.xda-developers.com/showthread.php?p=61707708
http://forum.xda-developers.com/showthread.php?p=61714439
http://forum.xda-developers.com/showthread.php?p=61716954

**Comment by mfonville** [comment]
Yeah we can do that, it will be trivial to add.

**Comment by bgiesing** [comment]
@mfonville Yeah, I would have did it myself since it is so easy. I am away from my computer though and it is hard to do anything on my phone screen LOL
