### ISSUE TITLE
installing gapps through app doesn't create debug archive

### ISSUE THREAD

**Issue by SimJoSt** [opengapps/opengapps#490]
**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps installation fails:*
- [x] Is the issue reproducible using the latest version of your recovery?
- [x] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

**Issue description:**

I installed the newest version of gapps through the app and for some reason it installed the Google Now launcher, even though I commented it out. Now I cannot debug and find the reason why, because now debug archive was created.

**Reproduction Steps:**

1. install app
2. install gapps through app
3. search for debug archive

**Expected behavior:**

open_gapps_debug_logs.tar.gz should be there

**Observed behavior:**

It isn't.

**Comment by mfonville** [comment]
Was the regular log txt file created or not? Does the debug successfully get created if you manually install the OpenGApps-zip file via TWRP instead?

**Comment by SimJoSt** [comment]
I found my mistake. I forgot, that the config file needs to be in the place where the zip is installing from, which in the case of the app is not sdcard but Downloads/OpenGapps.
Also I installed SuperSU from the official website not the LineageOS one, so it works like a charm now.

Thanks and sorry for the time.
