### ISSUE TITLE
Wrong architecture to set-up Open GApps' pre-bundled busybox

### ISSUE THREAD

**Issue by cyberman9000** [opengapps/opengapps#491]
hi
when i want to install gapps for android 7.1 in my phone i get this error : 
error 64 : Wrong architecture to set-up Open GApps' pre-bundled busybox
but i know i'm use the right package
my phone is wileyfox storm (kipper)
and using lineage os 14.1

**Comment by NicholasBuse** [comment]
Please read the [FAQ ](https://github.com/opengapps/opengapps/wiki/FAQ#2-im-having-a-problem-with-my-open-gapps-install-what-information-do-you-need-to-help-me)and the support instructions mentioned. You need to use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071) for support requests, directly opening GitHub issues is not appreciated.

PS: Please remember to at least include your installation debug log and (if applicable) a logcat when requesting support.

**Comment by seiji619** [comment]
@cyberman9000 did you happen to solve the issue yet?

**Comment by mfonville** [comment]
@cyberman9000 use the xda forum for support requests.

There you should provide your build.prop and any logs

**Comment by orktion** [comment]
Samething Happened to me, when using TWRP Recovery. Issues got resolved when using CWM

**Comment by darkmorpher** [comment]
Known issue on TWRP 3.2.x [#1070](https://github.com/TeamWin/Team-Win-Recovery-Project/issues/1070)
Use 3.0.x

**Comment by darkmorpher** [comment]
[#1070](https://github.com/TeamWin/Team-Win-Recovery-Project/issues/1070) Known issue on TWRP 3.2.x
So use 3.0.x

**Comment by darkmorpher** [comment]
[#1070](https://github.com/TeamWin/Team-Win-Recovery-Project/issues/1070) - Known issue on TWRP 3.2.x
So use 3.0.x

**Comment by ngoquang2708** [comment]
Mount ```/system``` first. The ```updater-binary``` use ```unzip``` command which is on ```/system```.

**Comment by darkmorpher** [comment]
Related #720 #735
