### ISSUE TITLE
Reboot to system not working in Aroma variant

### ISSUE THREAD

**Issue by Sparker0i** [opengapps/opengapps#495]
Phone: Redmi Note 3 Pro
TWRP: 3.1.0
Android 7.1.2-r6

When trying to install OpenGapps via Aroma package, after installation Reboot to System option does not work. It instead redirects back to the TWRP install terminal output.

**Comment by chinmaykunkikar** [comment]
Hi @Sparker0i, can you remove any previous aroma configs and any other aroma related traces present in your `/sdcard` and try reproducing the issue?

**Comment by Sparker0i** [comment]
Hey there, sorry I was a bit busy with personal work. Anyway I've reproduced this again. How do I post the logs (I haven't deleted anything after installation)

**Comment by Sparker0i** [comment]
Seems like it is now working after I did a clean wipe from TWRP.
