### ISSUE TITLE
Setup Wizard Crash after installing 18 May Aroma build

### ISSUE THREAD

**Issue by Sparker0i** [opengapps/opengapps#496]
Device: Redmi Note 3 Pro
Android OS: 7.1.2-r11 , ARM64

Problem:
It seems that when any of the above ROM and OpenGapps are installed from Recovery together, Setup Wizard crashes. It crashes at the step where it asks to start fresh or restore from backup. I am unable to proceed after this step. I've verified this individually on each of the ROMs as well. Should be a OpenGapps bug.

ROMs I've tested this on : Resurrection Remix, Lineage OS, Nitrogen OS, XOSIP, Pure Nexus (unofficial), AOSP Extended

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
