### ISSUE TITLE
several suggestions and cleanup items - especially for the Aroma installer

### ISSUE THREAD

**Issue by jawz101** [opengapps/opengapps#498]
I was wondering if you could add a few notes in the Aroma Gapps screens:

- Device Health Services only works on a Pixel (I'm not even sure it works on a custom ROM in the 1st place so I don't know why it's included.)  Also, I'm guessing the Google Storage Manager works only on a Pixel device because of some of the verbiage in the ui.
- remove Dialer Framework as an option to install.  If it's necessary for Google Dialer, why make it a separate  checkbox?
- Google Apps Device Policy - only relevant if you use Google Apps for Work.  (I'm not even sure if Google Apps for Work technologies even work on an unlocked bootloader so if someone is installing a custom Gapps package it will never work anyways.)
- Gmail won't uninstall the stock email
- Installing Chrome won't uninstall LineageOS's default browser
- Aroma installer doesn't need options to remove junk from a 7.x ROM which aren't even in Android 7.x (Holo Spiral Live Wallpaper, Galaxy Live Wallpaper, Phasebeam, Noisefield, Stock/AOSP Movie Studio, WhisperPush, CyanogenMod Theme Engine, Visualization LWP, etc.)  I couldn't tell you how many others are irrelevant.  It just needs to be scrubbed up.
- Google Storage Manager won't uninstall Stock/AOSP Storage Manager automatically.  If it does, the Aroma installer doesn't note that it does.
- All references to removing/replacing CyanogenMod stuff should be converted to LineageOS packages or scrapped.  CM is dead and it's confusing to know if it's doing LOS changes

**Comment by osm0sis** [comment]
AROMA's a mess, feel free to submit some Pull Requests.
