### ISSUE TITLE
google camera not installed

### ISSUE THREAD

**Issue by mrjayviper** [opengapps/opengapps#499]
not really an issue but more of a question

steps I used

1. install lineage only
2. reboot phone
3. setup phone
4. boot into recovery
5. install opengapps stock (with certain apps removed. see below)

If I do these steps, google camera is not installed. But if I 1 install opengapps right after lineage, the app is installed. Any reason? I had the impression opengapps should still install the app.
Thanks

Here's my gapps-config.txt

Exclude

# Pico+
GoogleTTS              # Install Google Text-to-Speech (Micro+ on 5.0-, Pico+ on 6.0+)

# Nano+
FaceUnlock             # Install FaceUnlock
Hotword
Search                 # Install Google Search (excluding excludes GoogleNow and PixelLauncher)
Speech                 # Install Offline Speech Files

# Micro+
Gmail                  # Install Gmail
ExchangeGoogle         # Install Google Exchange Services
GoogleNow              # Install Google Now Launcher (requires Search)

# Mini+
Maps                   # Install Google Maps
GooglePlus             # Install Google+
Hangouts               # Install Hangouts

# Full+
CloudPrint             # Install Google Cloud Print
Docs                   # Install Google Docs
Drive                  # Install Google Drive
NewsWidget             # Install Google News & Weather
PlayGames              # Install Google Play Games
Movies                 # Install Google Play Movies & TV
NewsStand              # Install Google Play Newsstand
Sheets                 # Install Google Sheets
Slides                 # Install Google Slides
Talkback               # Install Google TalkBack

# Stock+
PixelIcons             # Install Google Pixel Icons
VRService              # Install Google VR Services
PixelLauncher          # Install Pixel Launcher (requires Search and Wallpapers)
PrintServiceGoogle     # Install Print Service Recommendation Service
Wallpapers             # Install Wallpapers

# Super+
#DMAgent                # Install Google Apps Device Policy
#GCS                    # Install Google Connectivity Services (excluding also excludes ProjectFi)
#Earth                  # Install Google Earth
#Indic                  # Install Google Indic Keyboard
#Japanese               # Install Google Japanese Input
#Korean                 # Install Google Korean Input
#Pinyin                 # Install Google Pinyin Input
#Street                 # Install Google Street View
#Translate              # Install Google Translate
#Zhuyin                 # Install Google Zhuyin Input
#ProjectFi              # Install Project Fi by Google

**Comment by nograsswillgrow** [comment]
Please refer to question #7 in the FAQ for an explanation of why this happens: https://github.com/opengapps/opengapps/wiki/FAQ

Google Camera is only installed when the ROM and GApps package are flashed back-to-back as part of a "clean" install.
