### ISSUE TITLE
Add extra (optional) packages:

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#5]
~~/system/app/FitnessPrebuilt -> Should be put in Full+Stock already~~

Add extra options (but not enabled by default)
as found on Nexus:
 /system/priv-app/AndroidForWork
 /system/app/DMAgent (=Device Policy)
 /system/priv-app/GoogleDialer (unsure, and only if we can get it to work)
~~/system/priv-app/TagGoogle (google NFC, com.google.android.tag)~~

possibly useful, but not part of the stock Nexus:
Translate
Inbox
~~Photos -> /system/app/Photos~~
Googles Goggles
Hangouts Dialer

keyboards (are normally found on Nexus):
/system/app/GoogleHindiIME
/system/app/GoogleJapaneseInput
/system/app/GooglePinyinIME
/system/app/iWnnIME
/system/app/KoreanIME

For the future in Android M:
com.google.android.apps.gcs - > /system/priv-app/GCS (google connectivity services)
com.google.android.apps.tycho -> /system/app/Tycho (project fi)

**Comment by mfonville** [comment]
Photos is now implemented

**Comment by mfonville** [comment]
Fitness is now in Full and Stock

**Comment by rapperskull** [comment]
All the apps that are not in the factory images should not be added to the GApps package. Also I'm not really sure about region-specific keyboards, maybe as flashable addons? Android for Work and Device Policy have no utility for any user. I don't think that in an enterprise environment a user can install a custom ROM to flash GApps on. Google Dialer has known problems and it's not on the Play Store, so it's compatible with only a few devices. Google Connectivity Services is also present in Android 5.1.1, but only for the Nexus 6. I don't know about TagGoogle.

**Comment by mfonville** [comment]
The regions-specific keyboards are indeed an issue. I think I would have preference for making them part of the Stock package, but only as optionally installable feature.

Android For Work and Device Policy I am also not sure about what to do with them. To be honest, I think indeed the majority of the users will not have any direct benefit from using them, but there also a lot of users that could. There are plenty of people with their own Google Apps for Business domain while having a custom ROM, or students who also use their Android device in combination with a Google Apps for Education account. Again maybe including them in a Stock install as optional extra?

The other apps are indeed not part of the Nexus image, but are popular, and I suspect that at least Inbox will become a default app on Android M (but it is not there yet).

**Comment by bgiesing** [comment]
Well, as I was the one requesting an Inbox addon for TK's GApps (and he made it), I would love to see Inbox added in some way whether as an Addon or in the main package!

I also got him to add Chrome Dev as an addon, that would be cool too but not necessary,

As for the Region-specific KBs, those are always the first thing I remove on my Nexus, but I do see it being useful for people in other countries.

Hangouts Dialer would be a really good addition!

**Comment by mfonville** [comment]
I studied the work of @Lekensteyn at https://github.com/Lekensteyn/make-gapps-zip

We have some adjustements to make to our current library bundling:
* We should include libgoogle_hotword_jni.so -> if Google Search is going to be installed
* We should include libgoogle_recognizer_jni_l.so  -> if tts and/or ears are going to be installed
* libfilterpack_facedetect.so is not part of FaceUnlock -> It should probably be installed if any kind of package with some media/photo processing is installed (even Hangouts). So maybe part of the 'obligatory' core application set?
* vendor/lib/libfrsdk.so should probably be included to let FaceUnlock work

**Comment by mfonville** [comment]
I just found out that even on 5.1 GoogleHome has been moved to /app from /priv-app, so in the future it will move for all versions (just like it did for talkback)

**Comment by adrman** [comment]
Is there any chance of including Google Connectivity Services in one of the packages? Project Fi wants to see GCS as a system app. I know Fi users are probably a pretty small percentage of the general community, but thought I'd inquire anyway. Thanks.

**Comment by mfonville** [comment]
Maybe we could make GCS and/or AndroidForWork and the other language Keyboards as seperate addons.
Because including them in Stock I do not find very appealing, since they only cater a very small group, but we DO know the file paths that they have within the Nexus filesystem.
I am not sure yet how to make it part of our scripts and build process yet...

**Comment by adrman** [comment]
Because of the limited group(s) that would have interest, I think that would be the best solution.  If you should proceed and I can be of any assistance in testing, please let me know.

**Comment by mfonville** [comment]
Since we now have the Super package, this issue is resolved, and for Marshmallow even more packages will be added the core :-)
