### ISSUE TITLE
report_sources.sh errors

### ISSUE THREAD

**Issue by DJAlik** [opengapps/opengapps#50]
Couple of things I noticed when I run ./report_sources.sh arm-22
For com.google.android.syncadapter.contacts it reports version 4.4.4-1227136
If you run without arguments it reports properly that verison for api 19,21, and 22 are available

The other issue I see if you run it with any arguments at first it throws a ton of errors such as:
awk: run time error: negative field index $-2
 FILENAME="-" FNR=1 NR=1

**Comment by mfonville** [comment]
The errors were because of @rapperskull 's his recent cleanup. I found the cause of those and cleaned it up. The other wrong version report you are right about, and I will try to find a solution for it.

**Comment by mfonville** [comment]
Done, thank you for finding this problem.

**Comment by DJAlik** [comment]
I think there is a similar issue with com.google.android.gsf.login

**Comment by mfonville** [comment]
Yes, I see, that is now because "sort" things that 8 is larger than 21, (because the digit it start with is higher), I will try to fix that too
