### ISSUE TITLE
Clock app is not working

### ISSUE THREAD

**Issue by jeraldsatya2000** [opengapps/opengapps#501]
After installing mini version on my device, the clock app doesn't open

Device : Samsung Galaxy S4 Mini (serranodsdd)
Version : Lineage OS 14.1 (Nougat 7.1.2)

**Comment by artityod** [comment]
issue

**Comment by ChandanShastri** [comment]
Clear the App data of the clock.
Then relaunch it.

If you are facing "unfortunately stopped" issue with your Google Clock.

**Comment by mfonville** [comment]
Please read the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ#2-im-having-a-problem-with-my-open-gapps-install-what-information-do-you-need-to-help-me) and the support instructions mentioned. You need to use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071) for support requests, directly opening GitHub issues is *not* appreciated.

PS: Please remember to at least include your installation debug log and (if applicable) a logcat when requesting support.
