### ISSUE TITLE
AROMA Installer crashes/reboots to TWRP when re-installing

### ISSUE THREAD

**Issue by Enigma0** [opengapps/opengapps#503]
*If Open GApps installation fails:*
- [YES] Is the issue reproducible using the latest version of your recovery?
- [YES] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

**Issue description:**

Crashes/force reboots when performing system space calculations when re-running AROMA installer on top of an existing installation.

**Reproduction Steps:**

1. Install ROM
2. Install AROMA
3. Reboot system/initialize
4. Reboot recovery
5. Install AROMA again

**Expected behavior:**

It should not crash/force reboot TWRP.

**Observed behavior:**

Crashes installer and force reboots system to TWRP recovery.

**Comment by mfonville** [comment]
Aroma is very unreliable and crashes, we are not able to resolve it because the maker of the aroma-lib has ceased development. :-/

**Comment by Enigma0** [comment]
Ah... That sucks. Is there another way to force-enable the Google Assistant functionality in 7+ ?

**Comment by mfonville** [comment]
Use a gapps-config file as described in the wiki documentation

**Comment by dihavt** [comment]
after installing the rom on twrp menu-mount.  check the "system" checkbox and then try to install AROMA. its work for me

**Comment by nikamipara** [comment]
I can Confirm Just followed @dihavt 's advice and its worked.

**Comment by trapicki** [comment]
For me it worked with

1. Booting into TWRP recovery.
2. Choosing `Mount` in main menu
3. **UN**checking "Mount system write protected" (may be called different, my translation from German"
4. Checking = mounting `system`
5. Starting OpenGApps installation in main menu via `Install`

When I did not mounting  `system`, or did not enable writing, OpenGApps installation boiled out at/after 4% system space calculation. Installing with checked `Test` option worked fine.

**Comment by niralnaik** [comment]
not even starting installler just look like it kills recovery and i just see reboot

**Comment by Ed1123** [comment]
> after installing the rom on twrp menu-mount. check the "system" checkbox and then try to install AROMA. its work for me

Worked for me with the same problem.
