### ISSUE TITLE
Provide a tool for generating gapps-config

### ISSUE THREAD

**Issue by noamtamim** [opengapps/opengapps#504]
This can be a web page (preferred as it's easy to update when you add new apps), a shell script, an Android app, or something else I didn't think of (but not a Windows app :-)).

**Comment by noamtamim** [comment]
Thinking about it, a script that interactively generates gapps-config is not good. The experience should be checkbox-based.

**Comment by piyushgarg** [comment]
I think Aroma installer can have the functionality for generate the gapps-config file.

**Comment by richiksc** [comment]
I'm on it, just forked the website

**Comment by chinmaykunkikar** [comment]
I appreciate that @richiksc 👍 
Saw some work on your fork months ago but never got to hear about it from you. What happened?

**Comment by richiksc** [comment]
@chinmaykunkikar Sorry, got busy... haven't worked on it in a while

**Comment by osm0sis** [comment]
Presumably abandoned.
