### ISSUE TITLE
Download via bittorrent would be nice

### ISSUE THREAD

**Issue by guettli** [opengapps/opengapps#505]
- [x ] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)

Download from Germany seems very slow and get interrupted often.

A download via bittorrent would be nice.

**Comment by jsieler** [comment]
By me too. Downloading with 12kb/s is really a joke??

**Comment by mfonville** [comment]
We are hosted by GitHub, if you experience any issues with their service (that is hosted by the Amazon S3 service, see http://opengapps.org/#supportsection) please let their support department know.

We can't provide torrent uploads, the buildbot does not have enough bandwidth and storage to keep all builds around and keep them available for upload.
