### ISSUE TITLE
how to Fix Unfortunately, google play service has stopped.

### ISSUE THREAD

**Issue by afshinnajafi** [opengapps/opengapps#506]
hi 

after install Gapps For ARM64 Platform Type , i faced with below error 
**Unfortunately, google play service has stopped.** 

and i goes to appmanager/google play service / premission 
and check all of premission ! then this error fixed !  but after reset/wipe data factory reset ,  this error comes back ! how to fix this error permanently ?

**Comment by afshinnajafi** [comment]
wating for answer ... 
pls help

**Comment by Nevax07** [comment]
Hi @afshinnajafi, you should consider to include your logcat, it's the minimum

**Comment by mfonville** [comment]
Please read the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ#2-im-having-a-problem-with-my-open-gapps-install-what-information-do-you-need-to-help-me) and the support instructions mentioned. You need to use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071) for support requests, directly opening GitHub issues is *not* appreciated.

PS: Please remember to at least include your installation debug log and (if applicable) a logcat when requesting support.
