### ISSUE TITLE
Legacy Camera Installed on Pixel/Pixel XL Instead of New Camera

### ISSUE THREAD

**Issue by admiralspeedy** [opengapps/opengapps#507]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

**Issue description:**

When installing Open GApps on a device that supports the new camera (Pixel or Pixel XL), the installer is unable to actually determine that the device supports it and installs the legacy camera instead. This means that the libs required for the new camera aren't installed and when the app gets updated from the Play Store to the new camera, it force closes when you open it because the libs are missing. The only way to fix this is to use "forcenewcamera" in gapps-config.txt.

**Reproduction Steps:**

1. Install Open GApps on the Pixel or Pixel XL (I don't know if any other devices support the new camera)
2. Update the camera app with Google Play
3. Try to open the camera

**Expected behavior:**

The new camera should be installed on the Pixel and Pixel XL, not the legacy camera.

**Observed behavior:**

The legacy camera is installed, resulting in force closes after it's updated.

**Comment by richiksc** [comment]
Did you try the `forcenewcamera` keyword in `gapps-config.txt`?

**Comment by admiralspeedy** [comment]
Did you read the report? It literally says forcenewcamera is the only way I could get it to work.

The point of the report is that you shouldn't need to use that to get it to install on the Pixels. According to the Wiki, the installer is supposed to automatically determine if the new camera is supported on the device and install it automatically instead of the legacy one (that's how it sounds anyways).

**Comment by richiksc** [comment]
sorry about that.

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
