### ISSUE TITLE
Parallelizing decompression for faster installation

### ISSUE THREAD

**Issue by arter97** [opengapps/opengapps#511]
Currently, OpenGapps is using slow compression format - lzip.

While some(including me) would argue, using something like zstd would be faster,
it is totally understandable to use lzip to reduce server load and download size.

However, things can definitely be improved.
It's kinda ridiculous that a Gapps installation time takes longer than a ROM installation time(no offense).

We can parallelize the decompression operation since it's very common to have at least 4 cores on devices.

xargs is included in the opengapps' busybox as an applet, so it's relatively easy to achieve this.

I hope someone in OpenGapps can look into this.

Thanks!

**Comment by arter97** [comment]
@mfonville :)

**Comment by jawz101** [comment]
Seems like he's no longer active

**Comment by NicholasBuse** [comment]
GitHub is (almost) always open for business, feel free to submit a pull request.

**Comment by darkmorpher** [comment]
Post on [Gitter](http://gitter.im/opengapps/general) or [XDA](http://forum.xda-developers.com/showthread.php?t=3124506) support pages.

**Comment by osm0sis** [comment]
Presumably abandoned. Feel free to submit a PR if you have an idea how to do this @arter97. :+1:
