### ISSUE TITLE
gapps removal keywords - overdue cleanup needed

### ISSUE THREAD

**Issue by jawz101** [opengapps/opengapps#512]
First,
StorageManagerStock should automatically remove if StorageManagerGoogle is removed.  If it is being removed, the wiki and Aroma Gapps screens should reflect so.

All references to CMxxx stuff needs to be removed.  CyanogenMod is dead and it's confusing.
    
    CMAccount		dead
    CMAudioFX		rename to LAudioFX
    CMBugReport		rename to LBugReport
    CMFileManager		rename to LFileManager
    CMMusic			rename to LMusic
    CMSetupWizard		rename to LSetupWizard
    CMUpdater		rename to LUpdater
    CMWallpapers		I don't know if LineageOS has a wallpaper package?

Also, several of the wiki and Aroma removals are dead in Android Nougat- perhaps even lollipop.

Are these apps still relevant in Nougat and on Nougat-based custom ROMs?  It just makes it look silly.  I don't know why this is even a static list.  You might just want to have OpenGapps support removing by package names, dynamically load a list of what is installed, or something and rather than a hardcoded list of things to remove.
    
    BasicDreams		relevant today?
    DashClock		relevant today?
    FMRadio			?
    Galaxy			Nougat doesn't have this
    HoloSpiral		Nougat doesn't have this
    LiveWallpapers		Nougat doesn't have this
    LockClock		relevant today?
    NoiseField		Nougat doesn't have this
    Phasebeam		Nougat doesn't have this
    PhotoPhase		Nougat does have this thanks @richiksc 
    PhotoTable		Nougat does have this thanks @richiksc 
    Studio			Nougat doesn't have this.  Wasn't this like Android Gingerbread?
    SykoPath		relevant today?
    Themes			LineageOS doesn't have this.  Definitely not Nougat
    VisualizationWallpapers	Nougat doesn't have this
    WhisperPush		No one has this.  Wasn't this like CyanogenMod... Froyo or something?

**Comment by richiksc** [comment]
Ok PhotoTable and PhotoPhase definitely do exist in Nougat. Adding the `LockClock` keyword removes the cLock widget present even on LineageOS 14.1. And yes, LineageOS does have a wallpaper package. LOS has more bloat than you think. But I do agree, a lot of them can be removed, and the `CM` ones should definitely be renamed to `L-`

**Comment by richiksc** [comment]
I removed cLock no problem
