### ISSUE TITLE
Include 'Live Data Wallpapers' and 'Live Earth Wallpapers' APKs in Stock and Super packages

### ISSUE THREAD

**Issue by richiksc** [opengapps/opengapps#514]
Since the Live Data and Live Earth Wallpaper apps are included on new Pixel phones, they should also be included in the stock and super packages.
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))

**Issue description:**

The 'Live Data Wallpapers' and 'Live Earth Wallpapers' APKs should be included in the Stock package because they ship by default on the Google Pixel devices.

**Reproduction Steps:**

1. Install Stock Open GApps after flashing rom.

**Expected behavior:**

There should be Live Earth/Data Wallpapers.

**Observed behavior:**

There are no Live Earth/Data Wallpapers.

**Comment by cydia2020** [comment]
Try [my addons](https://github.com/cydia2020/OpenGAPPS_Addons), it's from PureNexus, which can be included while you're compiling.
