### ISSUE TITLE
Please support +Exchange2 to prevent stock Exchange2 from being removed

### ISSUE THREAD

**Issue by csk1jw** [opengapps/opengapps#515]
Please support +Exchange2 to prevent stock stock Exchange2 from being removed. This will facilitate custom ROMs that provide AOSP/Lineage Email & Exchange with security bypass built-in.
http://forum.xda-developers.com/showpost.php?p=72980654&postcount=4454

**Comment by osm0sis** [comment]
Seems like a fair idea. Make a pull request with the required changes.

**Comment by osm0sis** [comment]
Presumably abandoned.
