### ISSUE TITLE
Is open Gapps app open source

### ISSUE THREAD

**Issue by theScrabi** [opengapps/opengapps#516]
Hi there, is the [open gapps app](http://opengapps.org/app/) open source?

**Comment by AaronM04** [comment]
It's GPLv3 with an "installable zip exception" (see https://raw.githubusercontent.com/opengapps/opengapps/master/LICENSE ), so yes, I would call it open source. The zip files contained closed source programs but I would say they aren't part of the app itself.

**Comment by mfonville** [comment]
The Android OpenGApps.org app (https://github.com/opengapps/opengapps-app-support) is not open source, because it is advertising-supported; the translations are open-source though.

The Open GApps Project scripts are open source as described by AaronM04

**Comment by theScrabi** [comment]
Hm I just had this crazy idea of having some sort of build flavour without ads that can be put into fdroid, but meh.
