### ISSUE TITLE
Arm packages in x86 version

### ISSUE THREAD

**Issue by Rachel030219** [opengapps/opengapps#517]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [X] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [X] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

**Issue description:**
Like I said in the title, why there are arm packages in x86 version?
Please check the screenshots below.
![01](https://img.vim-cn.com/d2/fb25e6905109272c85090a61c7b22b000c6512.jpg)
![02](https://img.vim-cn.com/07/ce6bc2289483a6ec32cdcb7e880c8ab3e26455.jpg)

**Comment by mfonville** [comment]
Please see https://github.com/opengapps/opengapps/wiki/Notes-for-Android-x86
that should answer your question.
