### ISSUE TITLE
Stock camera and gallery

### ISSUE THREAD

**Issue by PR1D3S** [opengapps/opengapps#519]
Stock camera and gallery should not be replaced by gapps because google camera not working properly on lineage os its crashing and galley is very important app of phone....

**Comment by fttx** [comment]
Same problem here.
I basically want to install a "Stock" package but without the camera app

**Comment by NicholasBuse** [comment]
https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options#prevent-automatic-stock-removals

Note: +CameraStock and +Gallery

**Comment by nikamipara** [comment]
Yes, we can override the behavior but the argument is that it should be the default behavior of stock installation.

**Comment by adelra** [comment]
Yes, This is an issue. 

I have installed GApps and now the camera is not working, Does anyone know how to fix it?

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
