### ISSUE TITLE
Calendar Sync adapter

### ISSUE THREAD

**Issue by ale5000-git** [opengapps/opengapps#522]
Hi,
isn't there a more recent Calendar Sync adapter for KitKat and Nougat?

I just see API 15 [here](https://github.com/opengapps/all/tree/master/app/com.google.android.syncadapters.calendar).

**Comment by NicholasBuse** [comment]
I am almost certain that it has not existed since then. Its functionality was rolled into Google Calendar which is supported down to API 16.

**Comment by ale5000-git** [comment]
I found this one for KitKat on a phone:
```
com.google.android.syncadapters.calendar
The internal version number of the application is 17.
The displayed version string of the application is 4.2.2-721232
```
It is more recent but still old.

On newer phones sync adapters are odexed and I don't know how tho deodex them keeping a working signature.

**Comment by NicholasBuse** [comment]
I believe that the one we have in the repo (referenced by you) is newer:

```
The internal version number of the application is 2015080710.
The displayed version string of the application is 5.2.3-99827563-release
```

**Comment by ale5000-git** [comment]
I use 5.2.3 for Android 5+ but the other one for Android <5.

Is there a way deodex an apk with a working sgnature?

**Comment by NicholasBuse** [comment]
The one in repo is SDK 15 which was Ice Cream Sandwhich ([4.0.3 - 4.0.4](https://source.android.com/source/build-numbers))

**Comment by ale5000-git** [comment]
The one that I have have with version 4.2.2-721232 have minsdk 16, I'm a bit confused.

**Comment by NicholasBuse** [comment]
APK VersionName: 4.2.2-721232 does not relate to the SDK 16 (which would be Android v4.1.x)

**Comment by ale5000-git** [comment]
I mean that the newer have minsdk lower than the older that is strange.
