### ISSUE TITLE
Eleven/Music app moved to priv-apps

### ISSUE THREAD

**Issue by KaZo58** [opengapps/opengapps#525]
Eleven is now under priv-apps.
installer.sh needs a small fix.
added priv-apps/Eleven under cmmusic_list for testing and it worked.
[https://review.lineageos.org/#/c/182429/](https://review.lineageos.org/#/c/182429/)

**Comment by osm0sis** [comment]
Yes, that's the correct way to handle it. Can you make a pull request with this change?
