### ISSUE TITLE
scripts/inc.installer.sh partition mounting

### ISSUE THREAD

**Issue by b4r** [opengapps/opengapps#528]
Below I came up with an alternative for my device and the LineageOS recovery in order to properly mount the list in the `for` loop.  I also noticed I had a `recovery.fstab` instead of just `fstab`.  Is it ok at this point to suggest or ask for an updated script to check for both files and perform the mount of those partitions while also populating the `mounts` variable?

    #opengapps/scripts/inc.installer.sh
    mounts=""
    for p in "/cache" "/data" "/persist" "/system" "/vendor"; do
      if [ -d "$p" ] && grep -q "$p" "/etc/recovery.fstab" && ! mountpoint -q "$p"; then
        mounts="$mounts $p"
        dir=$(grep "$p" "/etc/recovery.fstab" | grep -v '#' | awk '{print $1}')
        mount -o rw $dir $p
      fi
    done

**Comment by osm0sis** [comment]
I think this is resolved in the latest mount script.
