### ISSUE TITLE
Security Issue: opengapps.org insecure downloads

### ISSUE THREAD

**Issue by jumper444** [opengapps/opengapps#529]
Users go to opengapps.org in order to select and download the various packages for use/install.
The download links, for example, look like this:
"https://github-production-release-asset-2e65be.s3.amazonaws.com/35777460/3d2e..."
(link truncated. this is just so you can see the first part of it.)

Thus..the download links are HTTPS and secure as far as knowingly coming from those locations specified at AmazonAWS.  (In other words, the downloads couldn't be intercepted/modified/replaced *during* download by malicious router or other party between the user and amazon).

HOWEVER, the entire opengapps.org site itself is NOT https.  It is regular, unsecure http.  Thus the *delivery* of the webpage _including_ the download links themselves (encoded withing the page) is open to injection/interception/modification/replacement by any device between the user and/or/on the internet.  (If such a device was placed at the border of the opengapps webserver to the internet, then ALL downloads by ANYBODY could be switched.)  Opengapps would never know its outgoing pages were modified/switched, and users would never know their incoming pages/downloads were hacked.

Since almost all users of almost all android roms install gapps, the unencrypted (non-https) opengapps home/download site presents a valuable target for any entity that might wish to corrupt one or multiple person's phones.  They simply would place a device somewhere between the user and opengapps.org website...wait for page request...then rewrite the page so links to the original amazonaws downloads (which are secure **IF YOU HAVE THE RIGHT LINK**) point to another source of corrupted/compromised gapps packages.  (The corrupted/compromised gapps package could still come from amazonaws and could still be https encrypted - that doesn't change the risk - they would be encrypted, but *different* files).

(This same commentary applies to the MD5 checksum file as well.  Yes the file is delivered via https from amazonaws, but its source is the same unencrypted non-https website as the packages themselves.  A malicious party simply needs to redirect those (to hacked values) as well.)

SOLUTION: For safety and security, the opengapps.org website needs to receive a certificate and move all access from http to https.

**Comment by NicholasBuse** [comment]
Please see https://github.com/opengapps/opengapps/issues/119 for background...

**Comment by jumper444** [comment]
Oops.  Of course the one time I don't check for previous posts it is already there.  Sorry.  This seemed so obvious that I figured (since it wasn't fixed) that nobody had mentioned it before.

**Comment by jumper444** [comment]
OK. Having reviewed the situation I have a constructive comment based on the thread from 2015.  The opengapps site is clearly not secure, for whatever reason ("github doesn't allow custom domains", etc..).  Fine

A solution presented on that page is to then use:
https://github.com/opengapps/arm/releases
to find and download specific packages.
 
This is VERY valuable information and SUBSTANTIALLY improves the security situation for the downloads.  Github's site is https and therefore these links and their download remain within that enclosure.

However, as a 'normal' user (for a few years now) I never knew this download location existed, it isn't mention on the opengapps.org page (that I can find/see) and it also isn't mentioned on the main project github page - which simply tells people to go to opengapps.org (thus handing them off to insecure site.)

You could dramatically improve security (for those who care about it) by changing the fillowing line on the github project main page:
"..The latest version of pre-built Open GApps can be found at http://opengapps.org and the Open GApps App.."
-TO-
"..The latest version of pre-built Open GApps can be found at http://opengapps.org and the Open GApps App **_or via https download at https://github.com/opengapps/arm/releases.._**"

You could also point out on the opengapps website that the downloads from within it are not from an enclosed secure environment (but of course an entity inserting itself between user and website can just remove that as well.)

Minimally I think the project page should include that additional download option and point out that it's via https.
