### ISSUE TITLE
How to prevent some apps to be installed by using gapps-config?

### ISSUE THREAD

**Issue by Autines** [opengapps/opengapps#530]
I only find the way to install some apps I want. [https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options](url)

**Comment by 211217613** [comment]
I'm not sure how to do it with gapps-config but I open the zip and comment out some of the packages I don't need. Usually works out.
Ex. I don't face unlock so I just look for any reference to face unlock and comment it out.

**Comment by SimJoSt** [comment]
You might want to reread the "Include or Exclude GApps" section: https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options#include-or-exclude-gapps
If you still don't know what to do, write again.

PS: For some reason, the link you posted is not working.

**Comment by Heshyo** [comment]
I'm installing `GApps` at the same time as `LineageOS` through `TWRP`, by passing a zip to both. I read the Advanced Features and Options page and created a `/persist/.gapps-config` file on the internal memory (not SD) using the sample config file, commenting the apps I don't want, making sure i'm using Linux style EOL. I'm still getting everything installed, so I guess I'm not doing things properly.

**Comment by Heshyo** [comment]
It does work when putting the `.gapps-config` next to the GApps zip file. It doesn't seem to work on the other specified locations.
