### ISSUE TITLE
Why opengapps removed fmradio seed ?

### ISSUE THREAD

**Issue by last0tt0man** [opengapps/opengapps#532]
Hi ;

My device is Android One Second generation seed.
I'm install lineageos 14.1 final and updated version and open my phone.Fm radio application is placed.
After installing opengapps nano or pico in TWRP and start fmradio application disappeared.
Why remove opengapps fmradio application and how to appeared again ?

**Comment by SimJoSt** [comment]
Did you uncomment the `FMRadio` line in the gapps config? Or how did you configure your install of opengapps?

**Comment by last0tt0man** [comment]
Normally I never used opengaps-config.I have reviewed make a gapps-config.FMRadio line uncomment already.

I'm solved this problem very different way.

1. Install any file explorer with root access.(e.g. Amaze file manager very well)
2. Go to /system/priv-app/FMRadio.apk click and install.
3. App Management in Amaze Manager & FMRadio remove.

After this process, FMRadio will remain visible and working.

it's ridiculous but it works.

**Comment by mfonville** [comment]
Please attach a debug log so that I can investigate

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
