### ISSUE TITLE
Oreo gapps needed

### ISSUE THREAD

**Issue by thecipherman** [opengapps/opengapps#535]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [ ] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [ ] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [ ] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aissue)

*If Open GApps installation fails:*
- [ ] Is the issue reproducible using the latest version of your recovery?
- [ ] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

*If receiving force closures after Open GApps installation:*
- [ ] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [ ] The issue is reproducible on clean (=wiped ``/data/`` partition) installation
- [ ] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [ ] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**

[Short description of problem here]

**Reproduction Steps:**

1. [First Step]
2. [Second Step]
3. [Other Steps...]

**Expected behavior:**

[Describe expected behavior here]

**Observed behavior:**

[Describe observed behavior here]

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

[Debug log of the Open GApps installation](url)

[A logcat of the moment I receive the force closure (if applicable)](url)

**Comment by SimJoSt** [comment]
As far as I can see you have only entered a title and have not made any modifications to the provided template. Without a further description, you will likely receive no help.

**Comment by Subinsmani** [comment]
When OpenGapps will release oreo, As unofficial Lineage OS release for some devices.

**Comment by thecipherman** [comment]
This is just question so no need to fill all informations

**Comment by SimJoSt** [comment]
You are right, but leaving the template and not deleting it caused me to search for some content in it. It would have been easier to answer if it was more clear.
Also, there is no question. You just stated something in the title. For a more in-depth understanding of what you need and what your problem is, a description would have been very helpful.

**Comment by oscarbg** [comment]
My problem is I can't select Oreo as a Android version in Open Gapps site for downloading it..
so trying Lineageos 15 on gemini I need to find early Oreo Gapps files from other not so trusty sites..

**Comment by christianwico** [comment]
+1 on this. Lots of new Oreo ROMs poppin'. Can't make proper use without GApps.

**Comment by s1awa** [comment]
https://forum.xda-developers.com/android/software/gapps-opengapps-oreo-unofficial-t3681960

**Comment by mfonville** [comment]
Unfortunately I have some things going on in my personal life that severely limit my time to work at OpenGApps, but I have been able to take a look at the Oreo images and will probably provide soon 8.0 builds

**Comment by christianwico** [comment]
@s1awa that would do fine if they also had Intel-based GApps (x86, x64) which are what I need. The author only built for ARM-based archs.

**Comment by s1awa** [comment]
open gapps supports oreo now (beta) http://opengapps.org
