### ISSUE TITLE
CMUpdater/L(ineage)Updater removal bug in GApps when using LineageOS (latest one)

### ISSUE THREAD

**Issue by pr030880** [opengapps/opengapps#536]
In the latest LineageOS (nightly build 08/30/17) the CMUpdater has been replaced with Updater.

https://review.lineageos.org/#/c/180010/

Additionally I found this in the LineageOS changelog:
https://review.lineageos.org/#/c/179646/

Because of that change, the keyword CMUpdater in the Remove section of gapps-config does not work anymore (refers to false/wrong directory).
Can somebody check and verify this? The new folder for the Updater app is:
priv-app/Updater (old one was priv-app/CMUpdater)

As far as what I saw in the installer.sh file, something could be added like:
lupdater (in ' optional_aosp_remove_list=" ')
lupdater_list="
priv-app/Updater"

My gapps-config removal section looks like this:

CMAccount # Remove CM Account
CMBugReport # Remove CM Bug Report
CMAudioFX # Remove CM AudioFX
CMFileManager # Remove CM File Manager
CMMusic # Remove CM Music
CMScreenCast # Remove CM ScreenCast
CMSetupWizard # Remove CM Setup Wizard (see Notes for CMSetupWizard)
CMUpdater # Remove CM Updater
CMWallpapers # Remove CM Wallpapers
CMWeatherProvider # Remove CM Weather Underground

This all worked so far. The Removal of the CMUpdater stopped working since the latest LineageOS Updater package change (introduced in all latest nightlies).

Can somebody please correct this bug, and if corrected - which new keyword must be used for the Removal of the Updater?

**Comment by osm0sis** [comment]
Go ahead and make a PR with the LUpdater keyword.
