### ISSUE TITLE
Keyword 'Include' missing from config section in log file

### ISSUE THREAD

**Issue by hjholtz** [opengapps/opengapps#537]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [ ] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aissue)

*If Open GApps installation fails:*
- [x] Is the issue reproducible using the latest version of your recovery?
- [x] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

*If receiving force closures after Open GApps installation:*
- [ ] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [ ] The issue is reproducible on clean (=wiped ``/data/`` partition) installation
- [ ] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [ ] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**

The installer includes a copy of the config file in the log file. This is especially useful when initially selecting packages with the aroma installer: By saving this section as a .gapps-config file, later versions can be installed with one of the non-interactive installers, but still installing only the initial selection of packages.
Sadly, if include mode is chosen, the keyword "Include" does not get recorded in this section. Therefore,  subsequent installations with a .gapps-config file copied from this section will select very different packages than intended.

**Reproduction Steps:**

1. Use the aroma installer in "Include" mode
2. Create a .gapps-config file by copying the section starting at # Begin User's gapps-config from open_gapps_log.txt
3. Install a later version with the .gapps-config file from step #2 in place

**Expected behavior:**

* The keyword "Include" is present in the log file and thus in the .gapps-config file
* The initial choice of packages is applied also to the subsequent non-interactive installation

**Observed behavior:**

* The keyword "Include" is missing
* The opposite selection of packages gets installed

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

N/A

**Workaround**

1. manually add the keyword "Include" to the .gapps-config file
2. remove /system/addon.d/70-gapps.sh
3. re-flash the ROM itself (will remove gapps)
4. re-flash Gapps (with the fixed config file)

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
