### ISSUE TITLE
Where did PackageInstallerGoogle go?

### ISSUE THREAD

**Issue by Magendanz** [opengapps/opengapps#540]
[Online documentation](https://github.com/opengapps/opengapps/wiki/Pico-Package) still lists PackageInstallerGoogle (a.k.a. GooglePackageInstaller) as component of the Pico package, but it's no longer included in Pico or any superset package.

It is, however, included in TVStock, but it seems less important there because that package also includes TvPackageInstallerGoogle (a.k.a. CanvasPackageInstaller).

Is there a reason this is now omitted?  And if so, we should update the online docs.

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
