### ISSUE TITLE
opengapps-7.1 packages are missing gsf.login and contain some 8.0 packages since a93b82d

### ISSUE THREAD

**Issue by er13** [opengapps/opengapps#541]
opengapps-**7.1** packages are missing **gsf.login** and contain some **8.0** packages (e.g. com.google.android.configupdater) since a93b82d (packages from Oct 4th 2017 are the last proper ones)

Not tested, just from reading, I believe the culprit is in **api26hack** added in a93b82d. Shouldn't it be

if [ "$API" -ge "2**6**" ]; then

or alternatively

if [ "$API" -g**t** "25" ]; then

**Comment by mfonville** [comment]
Thanks for reporting this. Last commits should fix this issue. Please let me know if it will work for you in tomorrow's builds.

**Comment by er13** [comment]
Just for the sake of completeness. There is one more 8.0 package erroneously contained in opengapps-7.1: **com.google.android.apps.turbo**

Shouldn't it also be treated like configupdater in eaff084?

**Comment by mfonville** [comment]
that app should be generic to all android versions (7.1 and up): http://www.androidpolice.com/2017/10/11/google-uploads-device-health-services-system-app-play-store/

**Comment by er13** [comment]
Thanks for the response!

Sorry for being noisy, what about com.google.android.storagemanager (included in the stock variant of opengapps)? Could its 8.0.x version also be used on android-7.1? Thanks!

**Comment by mfonville** [comment]
I believe if the sdk-version is ok, that it should work fine

**Comment by jeffprime** [comment]
Yes
