### ISSUE TITLE
Uninstaller Needed.

### ISSUE THREAD

**Issue by ScrPits** [opengapps/opengapps#542]
I've found no issues rather "annoyances" with googles habits.
Being able to uninstall the gapps reliably based off original source "opengapps" rather then using a system remover and ect. Or a full wipe altogether. 

If we have a choice to install it, We should always have to choice to uninstall.

**Comment by mfonville** [comment]
It is not possible to implement an uninstaller as desired, because some apps get replaced and cannot be put back in case of a uninstall.
There is already a proper solution for uninstalling without losing any data: wiping /system and re-flashing the ROM.
