### ISSUE TITLE
Don't Automatically remove stock/AOSP keyboard

### ISSUE THREAD

**Issue by YandexStudio** [opengapps/opengapps#546]
When I using the aroma package to install Gapps，I choosed installing Google Pinyin，and the log says it didn't removed Stock/AOSP keyboard to prevent no keyboard，and told me if I want remove it I have to use the override mode。

As Google Pinyin have full support of English that can instead of AOSP keyboard，I suggest you add automatically remove AOSP keyboard if Google Pinyin will be installed

**Comment by Kaukov** [comment]
Isn't Pinyin just an input method and not a full keyboard? If you want to replace the Stock/AOSP keyboard, install Google Keyboard/Gboard

**Comment by YandexStudio** [comment]
I think it's a full keyboard, it's differ from Japanese or Korean, It can both input Chinese and English, emojis and symbols, also supports swipe input.

**Comment by Kaukov** [comment]
Hmmm, I see, but I think the AOSP one is left because you are basically left with no other keyboard if you have only the Pinyin one. Why is it an issue to you, by the way? And can't you remove the AOSP keyboard by yourself?
