### ISSUE TITLE
addon.d script generation bug?

### ISSUE THREAD

**Issue by NicholasBuse** [opengapps/opengapps#55]
I usually flash all of my zips (cm caf nightly, opengapps nightly, personal system mods).

1. Wipe System
2. Install CM
3. Install OpenGapps
4. Install personal zip
5. Wipe dalvik/cache

Today for the first time in a while I just used cmupdater to flash only the new nightly. Upon reboot, all Gapps were gone.  I have attached my logs, but it seems that 70-gapps.sh has any empty list in list_files() in both cases.

https://www.dropbox.com/s/97nocqxk2nedt7m/open_gapps_debug_logs20150708.tar.gz?dl=0

**Comment by mfonville** [comment]
I think the generation of bkup_list in our folder_extract() function is broken.
@rapperskull could you have a look at that one? Maybe the wildcard is not processed correctly between the "".

**Comment by mfonville** [comment]
Ok, the fix was trivial, just removing the * in the line :-P

**Comment by mfonville** [comment]
If you can, please confirm that it works now (but 99,9% sure it should).

**Comment by NicholasBuse** [comment]
I have been meaning to try building with cygwin (especially after my changes yesterday).  It is taking a long time, it must be working!

I'll compare to last night's build and try if all looks good. I'll either report and/or try tomorrow's build too.

**Comment by NicholasBuse** [comment]
Made just the change here to the last nightly and re-ran the scenario on my phone.  Attached logs, but all looks good now.

https://www.dropbox.com/s/vhsh3j8gbruo1wl/open_gapps_debug_logs20150709.tar.gz?dl=0
