### ISSUE TITLE
How do I remove OpenGApps after installing it?

### ISSUE THREAD

**Issue by noobfish** [opengapps/opengapps#551]
I've installed Pico package on LineageOS14 ,Thanks for the developers work.
Now I'd like to remove all the APKs and libs installed thus I could fall back to the status before OpenGapps . I've read FAQs and WIKI no answer found.Please help me ,is it possible to uninstallation ?

**Comment by Cyanogen-Mod** [comment]
Actually you could flash the Linage OS again to solve this problem. ☺️

**Comment by noobfish** [comment]
@Cyanogen-Mod Wow man , that's so inconvenience...  
Wo Qu, Tai Ma Fan Le Ba....

**Comment by ildar** [comment]
I guess that addon.d script could be quite easily modified to do that. The file list is already there.

**Comment by ildar** [comment]
Not so easy 🙁
Actually GApps overwrites some files during installation including important libs. So that clear uninstallation isn't possible. 😭

**Comment by T-rex2017** [comment]
There is a way 
'''''''''''''''''''''''''''''''''''''''''
# But for that editing the installer script is needed
# this script detects all libs/files that can't be replaced 
# Usually it delete these 
# So my idea is to move it to a folder rather than deleting
# After this a script with deletion of replaced/added files with re adding of these backup files can be used to revert back
*******Hope this make sense******

**Comment by GongT** [comment]
To remove OpenGapps: 
* boot to recovery
* reformat system partition, reboot to recovery again
* adb shell / twrp shell: `find /data -iname '*google*' -exec rm -rf '{}' \;`
* flash system / restore image
* clear cache and reboot

this will remove all google related apps, I only use this to remove broken install before I actual use my new phone

**Comment by noobfish** [comment]
thank you

**Comment by EvanCarroll** [comment]
@GongT is it not enough to wipe? the system partition must be reformatted?

**Comment by newyork10023** [comment]
GongT, you wrote, "flash system / restore image".  Is this step a choice?  Either flash system (exclusive-) or restore an image of system?  Or, are you referring to some other partition to be flashed?

I am thinking to re-install with just Pico Open Gapps (having initially installed a (much) larger super-set.  Installed Pico on the tablet, and I am much happier with the results.

**Comment by GongT** [comment]
All of these steps is "optional", I use that steps because it can be done without brain 🤣.

**Comment by newyork10023** [comment]
> All of these steps is "optional", I use that steps because it can be done without brain 🤣.

So, it is optional to "flash system / restore image" after the step "reformat system partition, reboot to recovery again"?

Thanks for your reply.

**Comment by GongT** [comment]
@newyork10023 Oh sorry... I forgot your main question...

In fact. It's required in my steps.    
 `3.` step is only removing any google inside `/data` (new version, config, generated data).    
But OpenGapps is inside `/system`, remove them is `Not so easy 🙁`.

**Comment by breversa** [comment]
Not sure if applicable, but I stumbled upon **/d/gapps** recently : https://f-droid.org/fr/packages/org.droidtr.deletegapps/

I haven't used it yet, but you might find it useful.

**Comment by Sne225** [comment]
Removing GApps without losing any data.

1. Boot to TWRP
2. Wipe ART/Dalvik, Cache and System only!
3. Flash the same custom rom again
4. All apps secured. No sign of any google application in your device.

**Comment by curiousrom** [comment]
> Removing GApps without losing any data.
> 
> Boot to TWRP
> Wipe ART/Dalvik, Cache and System only!
> Flash the same custom rom again
> All apps secured. No sign of any google application in your device.

Open GApps normally installs a 70-gapps.sh ROM update or re-flash survival script in the /system/addon.d/ folder so doing what you suggested will not remove Open GApps on ROMs who support addon.d like LineageOS for example.

Delete 70-gapps.sh first then re-flash ROM after wiping System & caches but NOT Data & you will not loose your other apps, data & settings.

**Comment by aaruni96** [comment]
> > Removing GApps without losing any data.
> > Boot to TWRP
> > Wipe ART/Dalvik, Cache and System only!
> > Flash the same custom rom again
> > All apps secured. No sign of any google application in your device.
> 
> Open GApps normally installs a 70-gapps.sh ROM update or re-flash survival script in the /system/addon.d/ folder so doing what you suggested will not remove Open GApps on ROMs who support addon.d like LineageOS for example.
> 
> Delete 70-gapps.sh first then re-flash ROM after wiping System & caches but NOT Data & you will not loose your other apps, data & settings.

But the above post says to wipe /system . wouldn't it work then ?

**Comment by el3mda** [comment]
> إزالة GApps دون فقدان أي بيانات.
> 
> 1. التمهيد إلى TWRP
> 2. امسح ART / Dalvik وذاكرة التخزين المؤقت والنظام فقط!
> 3. وميض نفس rom المخصص مرة أخرى
> 4. جميع التطبيق مؤمنة. لا توجد علامة على أي تطبيق google في جهازك.

**Comment by ilf** [comment]
In LineageOS Recovery, it is *not* sufficient to wipe cache and system.
You also need to do "factory reset" - which, of course, loses all data.
I'd be interested in a way to remove GApps without losing data.

**Comment by s1nistr4** [comment]
Please reopen, this is a major issue that there's no way to do this currently. Fixing this with a simple script/app that removes gapps would allow a lot of people to use custom ROMs that only include gapps so people can use those roms without the google rootkit into their phone

**Comment by StabletulyMigDev** [comment]
there is a way todo that but it requires to have superuser acess
-----------------------
1- Use an terminal emulator that has superuser acess (like termux or lineageOS built-in terminal app)
2- type ```su``` in the terminal
3- type ```cd system/app```
4- than use ```rm -rf <gapp to remove>``` to delete the app files
