### ISSUE TITLE
Add Android TV x86 Oreo 8.1 Gapps

### ISSUE THREAD

**Issue by kyvaith** [opengapps/opengapps#553]
Hi, could You guys add gapps from this image https://dl.google.com/android/repository/sys-img/android-tv/x86-27_r01.zip to yours repo? This is  Android TV x86 Oreo 8.1 emulator image. Especially I need Katniss vr. 3 x86 app, but I have no idea how to merge oat folder with apk. FYI - this apk brings Google Assistant on x86 hardware like Nexus Player. Thanks.

**Comment by kyvaith** [comment]
Please help. I need instruction how to merge vdex and odex files with apk form android 8.1 (api 27). Then I can make a pull request.

**Comment by kyvaith** [comment]
Well, seams to be impossible right now. https://github.com/JesusFreke/smali/issues/565

**Comment by lee2333** [comment]
How to flash the gapps for tv？？
