### ISSUE TITLE
Google dialer change default or close incallui

### ISSUE THREAD

**Issue by MikeShestakov** [opengapps/opengapps#556]
I have 2 issues with google dialer:
1. After installation the google dialer replaced my dialer and set as default and I can use only google dialer. If I begin to use other dialer programms the call doesn't start and also I can't receive calls (no incallui in apps)
2. If in the moment of call I will close the incallui the call will continue and I have no way to return to this window to end the call.

My phone: Nokia 6 
Firmware: stock firmware ta-1000 7.1.1

**Comment by trixter127** [comment]
you can use any dailer you want. just change the default phone app . as you reached here I expect you know how to do that  

the Issue you are facing, occurs if you are trying to use  a non default phone app( dailer app ) for calls

**Comment by MikeShestakov** [comment]
Oh yes, you're right, except one.I've checked now : my call was done without incallui.
