### ISSUE TITLE
TVStock Google Play Music Installs Wrong Version

### ISSUE THREAD

**Issue by npjohnson** [opengapps/opengapps#563]
**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

**Issue description:**

TVStock Packages include the non-leanback Google Play Music.

**Reproduction Steps:**

1. Install TVStock GApps on an ATV build.
2. Note Google Play Music is not the Leanback version

**Expected behavior:**

Google Play Music Leanback is installed.

**Observed behavior:**

Google Play Music Phone/Tablet version is installed.

**Comment by npjohnson** [comment]
So, for Lineage builds on Fugu and Foster (the twos supported ATV devices, we have noted that Google Play Music doesn't seem to install in TV mode (from my understanding its a different APK with the same package name com.google.android.music).

TV: https://www.apkmirror.com/apk/google-inc/google-play-music-android-tv/google-play-music-android-tv-8-5-6561-3-y-release/google-play-music-android-tv-8-5-6561-3-y-android-apk-download/

Tablet/Phone: https://www.apkmirror.com/apk/google-inc/google-play-music/google-play-music-8-6-6626-1-z-release/google-play-music-8-6-6626-1-z-android-apk-download/

**Comment by gabrielgagz** [comment]
I can confirm this also in tvstock  arm package.

**Comment by npjohnson** [comment]
With Lineage now shipping fugu/foster TV builds, this one is gonna become a lot more relevant.

**Comment by npjohnson** [comment]
Due to my limited knowledge of who to tag that is involved in the opegapps project, @mfonville do you have any ideas on this one? Simplest imo would be ifdef'ing in and syncing in both apks (even though they have the same package ID).

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
