### ISSUE TITLE
Tvstock (arm): SetupWraith is missing in latest builds

### ISSUE THREAD

**Issue by gabrielgagz** [opengapps/opengapps#566]
Without SetupWraith.apk the setup process is not sending two important flags: 

secure user_setup_complete 1
global device_provisioned

This breaks several things: Home button, (Voice) Search, Google Play (Install Pending), etc....

**Comment by NicholasBuse** [comment]
Please see https://github.com/opengapps/opengapps/pull/559 and pass it along to your ATV's ROM developer

**Comment by gabrielgagz** [comment]
> Please see #559 and pass it along to your ATV's ROM developer

@NicholasBuse, thanks.
