### ISSUE TITLE
Add Files Go on aroma

### ISSUE THREAD

**Issue by mahmud2011** [opengapps/opengapps#567]
Hello guys, could you please add Files Go by Google (https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.files&hl=en). It's a new file manager, file transfer and cleaner app by Google LLC.

**Comment by NatoBoram** [comment]
I believe that OpenGApps will only produce packages for apps that have been shipped on a Google device before. Unless Pixel 3 ships with Files Go, I don't think they're going to do it.

**Comment by CyclingLand** [comment]
For as far as I know Files Go isn't installed on any device at default

**Comment by mmhyamin** [comment]
Files Go is default on Android Go edition.

**Comment by darkmorpher** [comment]
Related #589

**Comment by NatoBoram** [comment]
Files Go is now default in Android 11.

**Comment by soredake** [comment]
Any progress on this?

**Comment by soredake** [comment]
https://www.reddit.com/r/GooglePixel/comments/ix1yxz/did_the_preloaded_files_app_change_with_android_11/?utm_source=amp&utm_medium=&utm_content=comments_view_all
