### ISSUE TITLE
OpenGApps 8.1

### ISSUE THREAD

**Issue by jawz101** [opengapps/opengapps#570]
Because there's nothing tracking if/when an OpenGApps 8.1 will ever be released on opengapps.org daily downloads page, there needs to be an issue for it.

**Comment by nezorflame** [comment]
Basically 8.1 is already buildable from source (see my PR https://github.com/opengapps/opengapps/pull/560). The only thing left is to update APKs from 8.1.
I'll try to do that ASAP.

**Comment by Hakujou** [comment]
Probably expected, but Face Unlock is broken (absent in 8.1 while enabled in Aroma).

**Comment by nezorflame** [comment]
@Hakujou PR https://github.com/opengapps/opengapps/pull/571 fixes it.

**Comment by gayanper** [comment]
Is this packages are nightlies of 8.1 builds https://builds.nezorfla.me/opengapps/ ?

**Comment by Hakujou** [comment]
Yes they are

**Comment by nezorflame** [comment]
@gayanper yes, I build those until official build server starts producing them.

**Comment by beevelop** [comment]
I can confirm, building 8.1 from the current source is possible and seems to work properly 👍

**Comment by JonSnow9345** [comment]
@nezorflame your link for gapps 8.1 isn't working anymore

**Comment by nezorflame** [comment]
@JonSnow9345 thanks, updated the previous message.

**Comment by szili9992** [comment]
@nezorflame link not working

**Comment by nezorflame** [comment]
@szili9992 thanks, SF VHost service broke.
For now, you use the full link: https://sourceforge.net/projects/unofficial-opengapps-8-1/files/

**Comment by nezorflame** [comment]
Links were updated, SourceForge started working once again.
You can use short link http://opengapps.nezorfla.me in case something breaks again, so I'll make redirects to whatever hosting is used right now.

**Comment by schlimmchen** [comment]
@nezorflame Thanks for your efforts! Sadly, opengapps.nezorfla.me has no DNS entry (as it seems). builds.nezorfla.me is not reachable (at the moment).

Googling "sourceforce nezorfla" helped me out for now (https://sourceforge.net/projects/unofficial-opengapps-8-1/).

**Comment by nezorflame** [comment]
@schlimmchen thanks, fixed opengapps.nezorfla.me.
builds.nezorfla.me will be a self-hosted mirror for SF, not working yet.

**Comment by svelle** [comment]
Any updates on this? Now that the Lineage 15.1 Builds have officially started.

**Comment by nezorflame** [comment]
My builds support LineageOS since today, meaning all necessary apps have been updated to 8.1.0 versions.
Props to @SpasilliumNexus who helped me a lot with this.
PR's can be found here: https://github.com/opengapps/all/pull/16 https://github.com/opengapps/arm/pull/5 https://github.com/opengapps/arm64/pull/3

**Comment by ForsakenHarmony** [comment]
So when are you gonna release?

after those prs are merged?

**Comment by nezorflame** [comment]
@ForsakenHarmony we'll create new PR's with changes from @SpasilliumNexus, and after those are merged, I think builds can be started officially.

**Comment by nezorflame** [comment]
Continues here https://github.com/opengapps/opengapps/pull/580

**Comment by nezorflame** [comment]
Alright, all PR's are merged now.
@NicholasBuse is there anything else to be done for the official 8.1 builds to start rolling out?

**Comment by NicholasBuse** [comment]
@nezorflame,
I'd like to do a couple of test builds and maybe get them tested.

Can you test or do you have some testers?
What build variants would you like uploaded (I'll build all 8.1 locally)?

**Comment by cryptomilk** [comment]
I could test 8.1 arm64 pico

**Comment by nezorflame** [comment]
@NicholasBuse I'm making test builds every day with these changes, built already arm-27 and arm64-27, you can check them out here: https://sourceforge.net/projects/unofficial-opengapps-8-1/files/

**Comment by NicholasBuse** [comment]
@nezorflame thanks for the builds, I just wanted to make sure that the official builds go smoothly tonight before asking for mfonville's time.

@cryptomilk (and all), here is what I've built (only pico uploaded so far): https://androidfilehost.com/?w=files&flid=253259

**Comment by nezorflame** [comment]
Checked the build, works fine for me (dirty flashed though).

**Comment by nezorflame** [comment]
@NicholasBuse @SpasilliumNexus 
Most of the people report success, but for some, Trusted Face FCs:
[2018-03-01-16-44-56.txt](https://github.com/opengapps/opengapps/files/1770963/2018-03-01-16-44-56.txt)
[open_gapps_log.txt](https://github.com/opengapps/opengapps/files/1770964/open_gapps_log.txt)

**Comment by AmolGangadhare** [comment]
So when can we expect official 8.1 on site

**Comment by NicholasBuse** [comment]
There will be builds.

**Comment by nezorflame** [comment]
@crazybenjy9 it's being built. Have some patience.

**Comment by banksio** [comment]
Builds seem to be up and I'm able to download them now, thanks everyone!

**Comment by crazybenjy9** [comment]
@nezorflame I know. Just waiting for arm64 8.1. Good to see the arm ones are up.

**Comment by ForsakenHarmony** [comment]
arm64 is up as well 👌

**Comment by nezorflame** [comment]
Builds are up, time to close this.
