### ISSUE TITLE
Keep stock contacts apk option

### ISSUE THREAD

**Issue by frispete** [opengapps/opengapps#573]
First of all, many thanks for all the work on this immensely useful project.

It allowed me to setup a Lineage OS 14.1 on a (not yet fully supported) SM-T900 in a much appreciated way, that is years beyond the last version of the stock OS on that aging device.

One detail, I've missed so far: +ContactStock 

Is that possible, or do I have to omit GoogleContacts for that?

**Comment by SpasilliumNexus** [comment]
I've had a change for to keep AOSP Contacts, even while installing Google Contacts, in my personal builds a while ago (using +ContactsStock).

I'll get a pull request going in the next day or two.
