### ISSUE TITLE
Getting different MD5 checksum for each download (same file)

### ISSUE THREAD

**Issue by PrinceShaji** [opengapps/opengapps#575]
I've tried downloading several times, and every time, I get a different MD5 cheksum. I read another issue regarding the same, and I understand you are using MD5 just to verify the downloads. If that's the case, them SHA 256 would be the better option. Also, does anyone know why I'm getting different MD5 sums when I download the same file multiple times? I don't know if GitHub supports HTTPS for custom domains, and if that's the case, maybe you could add a link to download the file directly from GitHub.

Thanks a lot.

**Comment by nezorflame** [comment]
This must be some problem from your end, I don't get this problem on my side.

**Comment by PrinceShaji** [comment]
I tested this with other websites and they're all working fine. So everything on my end is working fine. Can you provide direct links to GitHub on the website for individual files? That's gonna be super useful.
