### ISSUE TITLE
Error git

### ISSUE THREAD

**Issue by thenoobt** [opengapps/opengapps#576]
I have an error after adding an "apk" the error is this, error: Can not pull with rebase: You have unstaged changes.
Stopping at 'sources / all'; script returned non-zero status.

WHAT I CAN DO TO FIX IT

**Comment by nezorflame** [comment]
@thenoobt don't write in Caps, and learn how to use Git first.
1. The error speaks for itself: "Can not pull with rebase: You have unstaged changes". Commit your changes before doing anything.
2. Learn how to use Git commands, e.g. from here: https://product.hubspot.com/blog/git-and-github-tutorial-for-beginners
