### ISSUE TITLE
Face unlock not working (Android 8.1 arm)

### ISSUE THREAD

**Issue by CyclingLand** [opengapps/opengapps#577]
**Issue description:**

The Face unlock in Smart Lock (Trusted Face) doesn't work anymore.

**Reproduction Steps:**

1. Flashed AOSPExtended 5.1 (android 8.1) on my Motorola Moto g4 play
2. Flashed OpenGapps arm mini for Android 8.1
3. Set everything thing up
4. Tried to set up Face Unlock

**Expected behavior:**

Face Unlock just working like normal

**Observed behavior:**

It didn't show up in the Smart Lock settings

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

[Debug log of the Open GApps installation](url)

[A logcat of the moment I receive the force closure (if applicable)](url)

**Comment by nezorflame** [comment]
@CyclingLand what version did you use?

**Comment by nezorflame** [comment]
Also ping @SpasilliumNexus

**Comment by nezorflame** [comment]
@CyclingLand also your links are broken.

**Comment by SpasilliumNexus** [comment]
Thanks @nezorflame

@CyclingLand please post a link to the thread/ROM and I'll see what's going on inside of it.

**Comment by allstargaurav** [comment]
@CyclingLand Its because OpenGapps now ships with the 64 bit libfacenet.so in ARM  version thats why it crashes

**Comment by CyclingLand** [comment]
@nezorflame I got the open_gapps-arm-8.1-mini-20180205.zip but It's not a huge deal anymore because I got a new phone right now, but maybe other people are still having this issue

**Comment by CyclingLand** [comment]
and my links are broken because I don't have these files

**Comment by CyclingLand** [comment]
@SpasilliumNexus this is the used rom: https://downloads.aospextended.com/changelog/harpia/AospExtended-v5.1-harpia-20180128-1534-OFFICIAL.zip/

**Comment by SpasilliumNexus** [comment]
Unless the issue of 64-bit libs being in OpenGapps, causing Face Unlock to not show up under security, the permission (android.hardware.camera.front.xml) is in the ROM, under /system/vendor/etc/permissions/.

This is one of the new paths (in my pull request: https://github.com/opengapps/opengapps/pull/571) that OpenGapps searches for. OpenGapps doesn't have this fix officially in their repo, however, @nezorflame has been building unofficial OpenGapps packages, which are the same as the official variants, except his packages has fixes such as this fix applied to them: https://forum.xda-developers.com/android/apps-games/arm-unofficial-opengapps-builds-android-t3743495

On top of the G4 Play being an ARM device, 64-bit libs won't work on that phone. You will need another fix which installs the proper libraries here: https://github.com/opengapps/opengapps/issues/555#issuecomment-356595517

Finally, you can verify if Face Unlock is installed by looking for "FaceUnlock" in /system/app/

**Comment by nezorflame** [comment]
I'll check if I can incorporate his fix into my builds as well.

**Comment by CyclingLand** [comment]
@SpalilliumNexus
Thnx for the info

@nezorflame if you need a tester just contact me because I probably don't really use my g4 anyways

**Comment by nezorflame** [comment]
Fix is live now (since 25th of February), please tell me if there are any issues left.

**Comment by CyclingLand** [comment]
can I just flash the new .zip without wiping anything?

**Comment by SpasilliumNexus** [comment]
Just flash the newest. Also, this issue can be closed. It has no purpose anymore.
