### ISSUE TITLE
Problem about Pixel Launcher in Aroma

### ISSUE THREAD

**Issue by Villardhzq** [opengapps/opengapps#578]
Pixel Launcher didn't install properly in Aroma version. I have tried many daily build in different devices, but it still can't be installed. So I use the stock version. Very appreciate for your work~

**Comment by CyclingLand** [comment]
You can also download it from here: https://www.apkmirror.com/apk/google-inc/pixel-launcher/
And just install the apk

**Comment by Skaronator** [comment]
@CyclingLand 
It must be a system app so the Google Search Bar works correctly. The Aroma version was the easiest way to do this.

**Comment by KyonLi** [comment]
Oreo 8.1 2018.3.3 build version, same issue.

**Comment by CyclingLand** [comment]
@Skaronator I installed it on my new phone without root and the bar works just fine and the swipe for google now as well

**Comment by CyclingLand** [comment]
*Update*
I got it from this link: https://www.xda-developers.com/rootless-pixel-launcher-google-feed/

**Comment by Skaronator** [comment]
Yeah this one works right now and it works without being a system app.

About 1 year ago the Google APK must be a system app to have the weather and the swipe to the left working. (but not true anymore for those forks)

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
