### ISSUE TITLE
SetupWizard Pixel 2(Walleye)

### ISSUE THREAD

**Issue by TresReinosDeLeche** [opengapps/opengapps#587]
SetupWizard FC's Everytime when trying to restore from cloud.

This forces the user to setup fresh account to continue.

**Comment by darkmorpher** [comment]
Post on (https://gitter.im/opengapps/general)[Gitter] or (http://forum.xda-developers.com/showthread.php?t=3124506)[XDA] support pages.

**Comment by darkmorpher** [comment]
Post on [https://gitter.im/opengapps/general](Gitter) or (http://forum.xda-developers.com/showthread.php?t=3124506)[XDA] support pages.

**Comment by darkmorpher** [comment]
Post on (https://gitter.im/opengapps/general)[Gitter] or (http://forum.xda-developers.com/showthread.php?t=3124506)[XDA] support pages.

**Comment by darkmorpher** [comment]
Post on [Gitter](http://gitter.im/opengapps/general) or [XDA](http://forum.xda-developers.com/showthread.php?t=3124506) support pages.
