### ISSUE TITLE
Suggestion: Check for Pixel Launcher Before Installing

### ISSUE THREAD

**Issue by FayneAldan** [opengapps/opengapps#596]
The installer should check if Pixel Launcher is already installed before installing since Resurrection Remix (Nougat) comes with Pixel Launcher 2, but Open GApps ends up replacing it with Pixel Launcher 1.

**Comment by SpasilliumNexus** [comment]
That's weird... I've updated Pixel Launcher to 8.1.0-4429924 in this commit https://github.com/opengapps/all/commit/115ee0ffeb92fab24ce8d3d16e76387877219195

The updated Pixel Launcher located here: https://github.com/opengapps/all/tree/master/priv-app/com.google.android.apps.nexuslauncher/21/nodpi

It is the same version as the one included in RR: https://github.com/ResurrectionRemix/android_vendor_resurrection/tree/nougat/prebuilt/common/app

Where is the launcher located in /system?
When you say Pixel Launcher 1, do you mean the Google Now Launcher?
Are you using `pixellauncher` as the keyword for installation and not `googlenow`?

I'm just trying to narrow things down here.
I'll take a look at this in the morning.

**Comment by FayneAldan** [comment]
It's located in `/system/app/NexusLauncher`
As for keywords, I'm just using the stock package.

**Comment by FayneAldan** [comment]
Seems to be fixed in 20180304
