### ISSUE TITLE
Fix #585 doesn't fix Google Phone being "not supported" in the Play Store in arm 7.1 build 0303

### ISSUE THREAD

**Issue by ripee** [opengapps/opengapps#597]
I'm afraid this doesn't fix Google Phone being unsupported in the Play Store. Wiping system and flashing arm pico 7.1 build 0303 deletes the 3 files in this commit (dialer_experience.xml, com.google.android.dialer.support.jar, and com.google.android.dialer.support.xml) from their corresponding folders on my Samsung Galaxy Note 4 N910F running LineageOS 14.1.

Only manually restoring them from a backup, setting the appropriate permissions, clearing cache in Google Play store and Google Play services, and rebooting, brings it back.

This happens each and every time the system partition is wiped in TWRP and arm pico 7.1 build 0303 is flashed immediately following flashing of the rom.

Edit: This occurs with stock arm 7.1 build 0303 as well.

**Comment by FayneAldan** [comment]
Did you try a clean flash?

**Comment by ripee** [comment]
No, and that will be my next course of action. But in all fairness, why would a clean flash be necessary to preserve 3 files which the build script has included for API 25 anyway in the builds preceeding 0303? I'd also like to point out that including "forceclean" in .gapps-config didn't make any difference either, pico or stock.

I will flash 0305 and report on it.
