### ISSUE TITLE
Pixel Laucher Is Not Being Installed No Matter What!

### ISSUE THREAD

**Issue by varunagarwal1** [opengapps/opengapps#598]
Clean re-installation of LineageOS [previously was also installed] on Moto X Play, 16 GB, OpenGapps Stock Version to find Pixel Launcher was not installed. Below Configuration script was saved in same folder as zip file with file name - "gapps-config.txt". Script has not changed since 6 months and when used 6 months ago, Pixel Launcher was installed.
```
Exclude

Fitness                # Install Google Fit
Movies                 # Install Google Play Movies & TV
Photos                 # Install Google Photos
GooglePlus             # Install Google+
CameraGoogle           # Install Google Camera
Indic                  # Install Google Indic Keyboard
Japanese               # Install Google Japanese Input
Korean                 # Install Google Korean Input
Pinyin                 # Install Google Pinyin Input
ProjectFi              # Install Project Fi by Google
Zhuyin                 # Install Google Zhuyin Input

+CameraStock
+Gallery

GoogleAssistant
```
Second attempt with Clean reinstallation with Super Version and above script with same result.

Third attempt with Clean reinstallation with Aroma Version and above script with same result.

Fourth attempt with Clean reinstallation with Aroma Version and no script with same result.

Below is log for your kind review.
[open_gapps_log.txt](https://github.com/opengapps/opengapps/files/1778672/open_gapps_log.txt)

**Comment by FayneAldan** [comment]
#595 should've fixed it. Either 20180304 didn't include the changes or the changes didn't work.

**Comment by FayneAldan** [comment]
20180305 now includes the fix. This issue can be closed.

**Comment by varunagarwal1** [comment]
Pixel Launcher is now installed in 20180305. Thanks @FayneAldan for all your help and fixes.
