### ISSUE TITLE
Some devices have no TWRP available

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#60]
Some devices only have CWM available, this are often relatively old devices.
Maybe we could consider to also publish builds of micro, pico and nano without the .xz compression for the 'arm' platforms and keep a 'compatibility' mode for them.

We could also use that compatability code for the aroma builds of issue #56 

@rapperskull do you think that would be maintainable, code-wise?

Update: another solution could be to bundle an arm build of xz in a special cwm-compatibility version of those builds.

**Comment by mfonville** [comment]
I compiled the extremly lightweight static xzdec for xz decompression on arm platforms: http://mallorea.student.utwente.nl/files/xzdec

It can be used like: ./xzdec gmscore.tar.xz -> gmscore.tar

the original file .xz will be kept, so it will have to be deleted afterwards.

**Comment by rapperskull** [comment]
Since xzdec always prints the output to stdout, we can pass the output to tar (is it present in CWM?) and extract the file without saving the uncompressed tar file.

**Comment by mfonville** [comment]
Yup, good improvement. Was already thinking about that (but had it not yet implemented).

**Comment by mfonville** [comment]
I have now a test build available of the micro package @ https://www.dropbox.com/s/6miz6kfcv87gq5c/open_gapps-arm-5.1-micro-test2.zip?dl=0

**Comment by mfonville** [comment]
btw, we should file a bug with CWM (and/or Philz) etc to please ask them to update the busybox (if applicable). I just don't know where...

**Comment by mfonville** [comment]
You guys are not going to believe, this but this also fixes #56 Apparently tar's build in xz decompression uses much more memory than our bundled one. So for AROMA we should enable this *always*.

**Comment by MWP** [comment]
I had the tar/xz issue when trying to install current open gapps on a fresh cyanogenmod nightly install.
The above open_gapps-arm-5.1-micro-test2.zip fixed the problem.
