### ISSUE TITLE
Camera Google Legacy is not installed

### ISSUE THREAD

**Issue by gargullia** [opengapps/opengapps#600]
Device: Nexus 7 2013
[open_gapps_debug_logs.tar.gz](https://github.com/opengapps/opengapps/files/1781045/open_gapps_debug_logs.tar.gz)
[open_gapps_log.txt](https://github.com/opengapps/opengapps/files/1781046/open_gapps_log.txt)

**Comment by FayneAldan** [comment]
"WARNING: Google Camera has/will not be installed as requested. Google Camera
can only be installed during a Clean Install or as an update to an existing
GApps Installation."
Read the log. ;)
