### ISSUE TITLE
Import New Google ATV Certificates and Packages

### ISSUE THREAD

**Issue by webgeek1234** [opengapps/opengapps#601]
There are some new packages for ATV in O. Two such are TVLauncher and TVRecommendations. These are available on the store and thus the apk mirrors. However, they use a new certificate, thus the scripts won't let me import them for local testing. Can one of the more experienced maintainers look into updating ATV sources from fugu and the scraper?

**Comment by NicholasBuse** [comment]
Are these the 2 you are talking about?
[TVLauncher](https://www.apkmirror.com/apk/google-inc/android-tv-home-android-tv/android-tv-home-android-tv-1-1-11-100-4504100-release/android-tv-home-android-tv-1-1-11-100-4504100-android-apk-download/)
and
[TVRecommendations](https://www.apkmirror.com/apk/google-inc/android-tv-core-services-android-tv/android-tv-core-services-android-tv-1-1-11-100-4505063-release/android-tv-core-services-android-tv-1-1-11-100-4505063-android-apk-download/)

**Comment by webgeek1234** [comment]
Yes, those are correct. And LeanbackLauncher needs updated from somewhere as well. I believe that is not on the store and needs pulled from a fugu image. In N, it was the launcher itself; in O, it's dependency for TVLauncher.

**Comment by webgeek1234** [comment]
Thanks for adding these. Working on a PR with ATV updates now, but this part is complete. Closing.
