### ISSUE TITLE
Request Update Device Health Services 1.1.0.185711861 (arm64) (Android 8.0+)

### ISSUE THREAD

**Issue by nasbdh9** [opengapps/opengapps#602]
Request Update Device Health Services 1.1.0.185711861 (arm64) (Android 8.0+)

https://www.apkmirror.com/apk/google-inc/device-health-services/device-health-services-1-1-0-185711861-release/

This is different from the previous update, it seems that only supports arm64？

**Comment by NicholasBuse** [comment]
https://github.com/opengapps/all/commit/c761f0d256b3df7a9023ccb016267eaeb2bfa828

**Comment by NicholasBuse** [comment]
whoops, didn't notice it was arm64 only...will revert for now...
