### ISSUE TITLE
Google play services has stopped LeEco Le Pro 3 X727

### ISSUE THREAD

**Issue by szamuka** [opengapps/opengapps#606]
Google play services doesn't work on this phone. I tried on LineageOS and AICP

**Comment by NicholasBuse** [comment]
Please read the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ#2-im-having-a-problem-with-my-open-gapps-install-what-information-do-you-need-to-help-me) and the support instructions mentioned. You need to use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071) for support requests, directly opening GitHub issues is not appreciated.

PS: Please remember to at least include your installation debug log and (if applicable) a logcat when requesting support.
