### ISSUE TITLE
aosp6.0.1_r62  with force close

### ISSUE THREAD

**Issue by YaphetsH** [opengapps/opengapps#607]
I build aosp6.0.1_r62  and flash into my nexus6p,and use twrp recovery  to get gapps(version is arm64-6.0stock-20180321). I  already give all permission to google paly services,but it still force close when I launch any gapps with account.
Here is my err log:
```
com.google.android.gms.persistent E/Auth: [DataBlockManagerHelper] Failed to read data from DataBlockManager.
 java.lang.SecurityException: uid 10012 not allowed to access PST
com.google.android.gms.ui E/WebViewFactory: Chromium WebView package does not exist                                                           android.webkit.WebViewFactory$MissingWebViewPackageException: 

com.google.android.gms.ui E/DeviceDoctorHandler: FATAL EXCEPTION: main
                                                                                Process: com.google.android.gms.ui, PID: 19965
                                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/com.google.android.gms.auth.uiflows.minutemaid.MinuteMaidActivity}: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: android.content.pm.PackageManager$NameNotFoundException: com.android.webview
```
Anyone can help me?

**Comment by SpasilliumNexus** [comment]
This is not a GApps issue, but it is pretty clear:

> Chromium WebView package does not exist 

Which means you either
- Didn't build AOSP WebView
or
- You've built the ROM without patches to allow use of an alternative WebView such as Google WebView, and in the process, removed AOSP WebView with OpenGapps, leading to FC issues.

You will need to go through another ROM's vendor repo such as Lineage or Omni to find and cherry-pick the commit.

**Comment by YaphetsH** [comment]
thanks,I  know it.
