### ISSUE TITLE
OpenGAPPPS App doesnt recognize Android8 Oreo

### ISSUE THREAD

**Issue by DSDV** [opengapps/opengapps#609]
Hello Folks,
i today upgraded to an Oreo Rom and noticed that the website offers 8.0 opengapps but the app doenst and even automaticly detects 7.0! which is false version and maybe even can cause damage in rare cases?

with best +DS_DV+

PS: is the app recommended by the dev staff?

**Comment by ripee** [comment]
I can confirm that this also occurs when running LineageOS-15.1. It "detects" and selects 7.0, not even 7.1, although 7.1 is the highest version in the list.

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
