### ISSUE TITLE
When WallpaperPickerGooglePrebuilt is installed, /system/app/WallpaperPicker should be removed

### ISSUE THREAD

**Issue by VincentJoshuaET** [opengapps/opengapps#614]
Google Wallpapers can be used by launchers as their wallpaper picker app, making the stock/AOSP one unnecessary.

_Sent from my ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by SpasilliumNexus** [comment]
Will look into it. In the meantime, close these please:
https://github.com/opengapps/opengapps/issues/564, https://github.com/opengapps/opengapps/issues/565, https://github.com/opengapps/opengapps/issues/590, https://github.com/opengapps/opengapps/issues/591
There is no reason for these to still be open as they all have been fixed.

**Comment by VincentJoshuaET** [comment]
Thanks, closed.

**Comment by VincentJoshuaET** [comment]
Any update on this? I had to add (WallpaperPicker) to my .gapps-config
