### ISSUE TITLE
[QUESTION] What happened to GApps Daily Build?

### ISSUE THREAD

**Issue by TH3L0N3C0D3R** [opengapps/opengapps#616]
There is no update since 1 April. What happened to GApps Daily Build on [OpenGapps](http://opengapps.org/)?

**Comment by pehlm** [comment]
+1

**Comment by NicholasBuse** [comment]
Please see my comments on this [XDA Post](https://forum.xda-developers.com/showpost.php?p=76186383&postcount=5261). Also arm did get uploaded last night: [arm releases of 13 April 2018](https://github.com/opengapps/arm/releases/tag/20180413)

These are just informational comments, but as always:

---
Please read the [FAQ ](https://github.com/opengapps/opengapps/wiki/FAQ#2-im-having-a-problem-with-my-open-gapps-install-what-information-do-you-need-to-help-me)and the support instructions mentioned. You need to use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071) for support requests, directly opening GitHub issues is not appreciated.
