### ISSUE TITLE
build.prop should be rw------- on Oreo

### ISSUE THREAD

**Issue by VincentJoshuaET** [opengapps/opengapps#620]
This is the last part of the addon.d script produced by Open GApps:

```
for i in $(list_files); do
    chown root:root "/system/$i"
    chmod 644 "/system/$i"
    chmod 755 "$(dirname "/system/$i")"
done
```

On Oreo, this line should be added:

```
chmod 600 /system/build.prop
```

_Sent from my ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by SpasilliumNexus** [comment]
Hopefully it will work when I get around to testing tonight: https://github.com/SpasilliumNexus/opengapps-main/commit/fd14c90f5214fd21fd1eb10cdb6e1f8763999139

If all is good I'll submit a pull, [among others](https://github.com/SpasilliumNexus/opengapps-main/commits/testing-builds).
