### ISSUE TITLE
Chrome Beta Support

### ISSUE THREAD

**Issue by dontobi** [opengapps/opengapps#621]
would it be possible to support Chrome Beta?

**Comment by VincentJoshuaET** [comment]
I suggested for add-on zips  for beta versions years ago, they still haven't done anything. I guess they have no plans for it.

**Comment by dontobi** [comment]
I have already tried to integrate myself, but without success.

**Comment by vwvtkxjobkvpqszygxmjvgaavwvfju** [comment]
Those are not on devices themselves though, only on the Play Store.
