### ISSUE TITLE
Gapps for LOS 15.1 Nexus Player

### ISSUE THREAD

**Issue by manusalgam** [opengapps/opengapps#623]
Hi, please check my post in XDA about the new Apr. 14 TV Gapps:

https://forum.xda-developers.com/nexus-player/orig-development/official-lineage-os-15-1-tv-t3765985/post76236737#post76236737

Note: tested with April 9 LOS build

**Comment by osm0sis** [comment]
Yeah we work with the Lineage guys. Should be resolved or getting better.
