### ISSUE TITLE
What happend to the 8.1 ARM64 tvstock package?

### ISSUE THREAD

**Issue by Skaronator** [opengapps/opengapps#624]
The Android 8.1 (ARM64) version of the tvstock is no longer available? When youu look on the releases here: https://github.com/opengapps/arm64/releases

You can see the latest available version is `open_gapps-arm64-8.1-tvstock-20180409.zip` but they are gone since `arm64 releases of 14 April 2018`.

**Comment by NicholasBuse** [comment]
I have replied to this [this XDA post](https://forum.xda-developers.com/showpost.php?p=76249045&postcount=5275)

{Begin standard reply}...

Please read the [FAQ ](https://github.com/opengapps/opengapps/wiki/FAQ#2-im-having-a-problem-with-my-open-gapps-install-what-information-do-you-need-to-help-me)and the support instructions mentioned. You need to use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071) for support requests, directly opening GitHub issues is not appreciated.

PS: Please remember to at least include your installation debug log and (if applicable) a logcat when requesting support.
