### ISSUE TITLE
What would be the way to install gmscore only?

### ISSUE THREAD

**Issue by ArchangeGabriel** [opengapps/opengapps#632]
I don’t care about anything else (gsf, vendor, etc.). Could you guide me in building such a “Femto” flavour? Thanks!

**Comment by Wesley-Chan** [comment]
Riding your thread. Sorry, OP.
Also asking for the possibility to build `FaceUnlock`-only package. I don't care about anything else. What can be removed in `Nano` without affecting `FaceUnlock`? Thanks.

**Comment by Sandmonster** [comment]
With new foss stores such as [F-Droid](https://f-droid.org) and [Aurora Store](https://auroraoss.com/) having Play Store on your phone is no longer a need. The only reason to have any Google related software installed is a working Firebase notifications. So, I want to complement this thread with idea for more bare bones package which only supports Firebase notifications.

**Comment by ArchangeGabriel** [comment]
@Sandmonster I would just use microG for this. My issue was SafetyNet, but if you only care about push notifications, microG will do.

**Comment by sandboiii** [comment]
@ArchangeGabriel There is also applications which use google maps which I personally would prefer to be original, not the microG's implementation. In my experience microG is prone to crashing in many ways. So, I want to stick with original google services. I would like to see something like zipable headless Google Services without Google Play.

**Comment by ArchangeGabriel** [comment]
microG maps implementation used to have a lot of issues indeed, but there has been a huge change in the implementation some time ago, and I’ve never had issue since. However YMMV because my use case might not be representative.

However regarding Google Play Services without Google Play Store that’s not possible AFAIK, even μG implementation has to implement a fake Google Play Store.
