### ISSUE TITLE
instantapps FC

### ISSUE THREAD

**Issue by alviteri** [opengapps/opengapps#634]
05-22 09:21:55.809  6471  6471 E AndroidRuntime: FATAL EXCEPTION: main
05-22 09:21:55.809  6471  6471 E AndroidRuntime: Process: com.google.android.instantapps.supervisor, PID: 6471
05-22 09:21:55.809  6471  6471 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver com.google.android.instantapps.supervisor.ExperimentUpdateReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.instantapps.REGISTER_AND_SYNC_PHENOTYPE cmp=com.google.android.instantapps.supervisor/.ExperimentUpdateService }: app is in background uid UidRecord{2333195 u0a76 RCVR idle change:uncached procs:1 seq(0,0,0)}
05-22 09:21:55.809  6471  6471 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3194)
05-22 09:21:55.809  6471  6471 E AndroidRuntime: 	at android.app.ActivityThread.-wrap17(Unknown Source:0)
05-22 09:21:55.809  6471  6471 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
05-22 09:21:55.809  6471  6471 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-22 09:21:55.809  6471  6471 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
05-22 09:21:55.809  6471  6471 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
05-22 09:21:55.809  6471  6471 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-22 09:21:55.809  6471  6471 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
05-22 09:21:55.809  6471  6471 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
05-22 09:21:55.809  6471  6471 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.instantapps.REGISTER_AND_SYNC_PHENOTYPE cmp=com.google.android.instantapps.supervisor/.ExperimentUpdateService }: app is in background uid UidRecord{2333195 u0a76 RCVR idle change:uncached procs:1 seq(0,0,0)}
05-22 09:21:55.809  6471  6471 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
05-22 09:21:55.809  6471  6471 E AndroidRuntime: 	at android.app.ContextImpl.startService(ContextImpl.java:1477)
05-22 09:21:55.809  6471  6471 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:650)
05-22 09:21:55.809  6471  6471 E AndroidRuntime: 	at bjp.a(PG:34)
05-22 09:21:55.809  6471  6471 E AndroidRuntime: 	at com.google.android.instantapps.supervisor.ExperimentUpdateReceiver.onReceive(PG:1)
05-22 09:21:55.809  6471  6471 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3187)
05-22 09:21:55.809  6471  6471 E AndroidRuntime: 	... 8 more

**Comment by SpasilliumNexus** [comment]
Google's problem. Fixed in 3.00-release-197609801 https://www.apkmirror.com/apk/google-inc/google-play-services-for-instant-apps/google-play-services-for-instant-apps-3-00-release-197609801-release/
