### ISSUE TITLE
Not Available By Design?... 

### ISSUE THREAD

**Issue by Ibuprophen** [opengapps/opengapps#636]
Hello Everyone! :-) 

I am just curious as to why the following OpenGApps Packages are not available for both Oreo 8.0 & 8.1? 

ARM - Missing Full & Stock 
ARM64 - Missing Stock 
x86 - Missing Stock 
x86_64 - Missing Stock

Is this by design (will never be available)? 

OR for another reason not stated elsewhere & why? 

Thank you very much for your time and understanding with this! 

~Ibuprophen

**Comment by ibuprophen1** [comment]
Thank you very much for your clarification @NicholasBuse!
