### ISSUE TITLE
Explore open source friendly download mirrors/bittorrent?

### ISSUE THREAD

**Issue by AdityaAnand1** [opengapps/opengapps#637]
I know this has been bought up several times, but there are [hundreds](https://opengapps.org/blog/post/2016/03/18/the-no-mirror-policy/)(see the number of comments) of people who literally cannot download OpenGapps binaries because of how unreliable and slow large github release downloads are, probably more who never bothered to complain and just gave up. This needs to be addressed and not shrugged off as "tell github to do something about it".

The "no-mirror policy" raises some good arguments but all of them can be solved. Uploading to mirrors can be a part of the build process.

I know this is FOSS and nobody has any money to put into this. I, and I'm sure most others, would be more than happy to give away spare bandwidth through bittorrent. 

If not, bandwidth is cheap. We can get 1TB for $5/month (last I checked), perhaps we can figure out some estimates and see how much it would cost and if it is at all feasible given the popularity of OpenGapps.

If not even that, perhaps we can seek some sponsors, VPS providers or file hosts, who'd be willing to provide a mirror for putting a small plug on the website.

**Comment by gongyuchong** [comment]
Hello,
  First, I am not the developer. I am the one who just want to answer your questions.
  Now in this project, every daily build is automatically built by the program. And because of the updating speed, it is difficult to set a bit-torrent server to provide the files so that everyone can download in a fast speed. Wish you can understand the situations.

**Comment by AdityaAnand1** [comment]
If I get a go-ahead by the actual developers, I'd be more than willing to build a simple automated script that could handle that.

And anyways, you've only addressed one single proposal. What about the rest? @gongyuchong

**Comment by gongyuchong** [comment]
Actually, bandwidth is not a big problem. But I think seek for a sponsors may cause a lot trouble to the developers, for commercial or legal  problems also play a important role in running this project. Anyway ,I am not the original founder of this project. I just want to express my own point of view and wish I can help you.

**Comment by mkg20001** [comment]
I decided to do something about this and set up my own "mirror" (it hosts self-built opengapps zips, hope that's ok).
https://opengapps.mkg20001.io/ (note: the missmatching "last updated" date is because writing the html generator took quite a while)
:tada: 
If I can do this in a few days, a bunch of skilled devs that have been doing this for more than a year can set up something rock-solid in a week

**Comment by vomw** [comment]
Bandwidth is a problem now. #719

**Comment by nezorflame** [comment]
Technically my buildserver serves as the mirror since I have a Telegram bot  for this.
You can find them here: https://github.com/opengapps/opengapps/issues/719#issuecomment-462135816

**Comment by nezorflame** [comment]
> Bandwidth is a problem now. #719

It's not the bandwidth, it's the GitHub policy for the repo itself.
It's not common to store APKs inside GitHub repo...

**Comment by thezeroth** [comment]
I am in US East coast with Gigabit optical connection, can't download any of releases, with or without a download manager, 3 hours wasted, i am wondering how stupid and ignorant and stubborn is the person who doesn't allow torrent mirroring of these files. whats the point of maintaining these packages when people literary cant download them. i strongly suggest planning a better distribution channel for releases.

**Comment by nezorflame** [comment]
@thezeroth well, you're in bad luck, I guess. Thanks to Amazon providing a good hosting for US citizens.
Regarding to the mirrors, I can't say why this whole "no mirrors" thing exists, but I can say that soon we'll be moving releases from Github to another hosting, and the situation may become better soon. Stay tuned for a blog post.
