### ISSUE TITLE
AOSP Build system

### ISSUE THREAD

**Issue by MatthewBooth** [opengapps/opengapps#64]
Would you be open to working this into the AOSP/CM build system?

Such that I could use this script to to put GApps into my AOSP ROM manually and they be 100% up to date as of the download time?

This si something I'd be happy to try myself if you guys would accept any pull requests on the subject

**Comment by mfonville** [comment]
Hey,

of course we can look at this. Could you maybe enlighten us how the AOSP/CM build system works and what would be necessary to adjust it to make it work?

You'll have to be careful btw in a legal sense about including GApps in your ROM, because when CM did this in the past, Google did not like it and asked them to separate GApps from the ROM itself. So you'd have to carefully approach this if you would want to distribute your ROM.

We can pull requests, but best would be to development first in a seperate branch and think of a proper way to organize and structure (depending on the changes that would be necessary)

**Comment by Bracket-** [comment]
Not sure I understood your last paragraph, @mfonville. It would probably still be easier for him to open a PR so it can be reviewed, commented and worked on, and if it's decided at the end not to merge it, the PR can be closed. A PR is usually already done on a separate branch from a fork of one of upstream's branches (usually master, though it doesn't have to be).

**Comment by MatthewBooth** [comment]
Hi guys,

Great that you'd be willing to look at this. 

I think for smaller ROMs and developers, it wouldn't attract much attention from Google. Some developers already do this with their ROMs, this would be just automating it. And, of course, you'd only be providing the ability to do this, but wouldn't fall in foul of any restrictions yourselves (any more than having a repository like this, or apkmirror already might be?).

As far as the AOSP build system works. You would create an Android.mk file in the repository which contains some information. The most important part is a Module name (for this) which would you perhaps call "OpenGapps" or soemthing like that.

Then a developer would include in their configuration files a "package" and use the above name.

AFAIK, and I will have to experiment, but the rest of the makefile would be something like:

```bash
PRODUCT_COPY_FILES += \
external/opengapps/${ARCH}/GooglePhotos/GooglePhotos.apk:system/app/GooglePhotos/GooglePhotos.apk \
external/opengapps/${ARCH}/GooglePhotos/lib/arm/libconsumerphotoeditor_native.so:system/app/GooglePhotos/lib/arm/libconsumerphotoeditor_native.so \
```

And so on. Just a case of reading the intended DPI and CPU architecture from the config files

**Comment by mfonville** [comment]
Ok, I think legally then it should be ok, it is indeed the responsibility of the ROM developers to adhere to Google's policies. We only provide a toolset.

OpenGApps (notice the capitals) should be indeed a proper module name.

So, best would be if our to-be-developed build script should produce a filesystem hierarcharchy that could directly be put on the /system/ partition of the ROM?
e.g.:
```
/app/Photos/Photos.apk
/app/Photos/lib/arm/somelib.so
```
and then generate a makefile that instructs to copy that whole fileset?

And as input a developer should be able to select which packages to include, which CPU, which DPI...

**Comment by MatthewBooth** [comment]
For the layout the "PRODUCT_COPY_FILES" has two parts

```bash
external/opengapps/${ARCH}/GooglePhotos/GooglePhotos.apk : system/app/GooglePhotos/GooglePhotos.apk \
```

The first part (external/opengapps/....) is the location of the repository in the AOSP tree. This should generally be in external/NAMEHERE. The rest of that part can be however you choose to lay it out in your repository.

Separating the two parts is a : 

The second part (system/app/GooglePhotos/GooglePhotos.apk) should be the the exact layout on the phone.

The \ just denotes a new line. The last entry won't have a \

As for selecting the CPU arch and DPI, they will be (or should be, AFAIK) generated by the device build files (this is at least the case for the [CPU architecture](https://github.com/AOSP-Shamu/platform_device_moto_shamu/blob/lollipop/BoardConfig.mk#L17))

**Comment by MatthewBooth** [comment]
It might be a case that you put in the README to declare the DPI somewhere using a variable of your choosing (I will look at CyanogenMod shortly as I believe they have a method of doing this)

**Comment by mfonville** [comment]
the DPI should also be in the build.prop, so it has to be generated/available somewhere.

About the PRODUCT_COPY_FILES, most easy would of course be if those hierarchies would be the same, since that keeps it simple, and our script already knows where everything should go.

I think I will be able to fork or modify build_gapps.sh for this new purpose, and will need some small adjustments to the buildhelper to reflect that new hierarchy. I will start those modifications, and then you can take it from there to integrate it properly with the AOSP build system.

**Comment by MatthewBooth** [comment]
Yeah, I'm trying to track it out. There may need to be some evaluation going on in the makefile (and I don't know if it should be doing that) to determine, because, for example, my Nexus 6's DPI is larger than 480 (but obviously the 480 is the one that would apply). I also think that all the product copy files commands are done before the build, so that may well be before the build.prop is generated.

**Comment by mfonville** [comment]
I am currently playing around a bit with the code, trying to hack something together. But one particular hard thing will be that we kind of have to merge the 'build' and the 'execute' part of the scripts. So I am still trying to find out what is the best (maintainable) way to do this.

**Comment by mfonville** [comment]
I have now a prototype that can generate a simpel file hierarchy (no symlinks and such yet) for all apps and configs as they should be on /system/.
The code is very static and ugly though, so I will now use this knowledge and prototype to refactor it in a nice way into the current normal scripts.

**Comment by AdFad666** [comment]
Hopefully you can work it so that we add something simple to the device repo, like:

$(call inherit-product-if-exists, vendor/opengapps//stock-xxhdpi.mk)

**Comment by MatthewBooth** [comment]
That would actually be a better than what i had in mind. Great idea!

**Comment by mfonville** [comment]
It looks btw that @JustArchi has already written a re-package script of his own at https://github.com/ArchiDroid/ArchiDroid/blob/master-cm/__build/gapps.sh
So for those who can't wait for this AOSP build system integration to be finished could maybe take a look at that.

**Comment by JustArchi** [comment]
Indeed I wrote a script to be used with my AD ROM, which nicely integrates available packages provided by lovely contributors of OpenGApps project.

As you can see from the script, it's just a really simple version of extract & replace, with respect of values found in build.prop. I have two major branches in AD - master-cm branch, and device branch. Master branch is the main core of all AD variants and includes generic build (arm, nodpi, 5.1), which should work properly with all device variants, but in addition to that, I can execute the same script from device branch (with build.prop available), which will then update master GAPPS with respect of values used by particular device. So far I noticed that only 2 packages I use include device-based combinations -> GMS Core and Messenger.

It works great for my own purpose, as I include core GAPPS + some extra optional GAPPS during flashing of AD. Extra GAPPS are provided there to replace stock AOSP packages, so users can choose what exactly they want to replace, and what not (similar to OpenGApps AROMA package).

It's however nice to note that I only include the GAPPS and not anything else "next" to it, such as custom updater-script and so. The whole purpose of my script is to update binary files (APKs + dependencies) and nothing else.

However, sure, if somebody wants to safe his time by writing a similar script which downloads latest OpenGApps and includes it, go ahead.

**Comment by JustArchi** [comment]
Personally I don't think that AOSP integration will be any useful, as GAPPS should not be treated as the part of build process. Also without proper flexibility, which is impossible, users won't be able to actually CHOOSE what GAPPS they want to install, and what not. Therefore, personally I don't need, and I'd suggest to not waste time on any AOSP integration, as it's direct hit to the freedom of installing exactly what user wants, and I can't find any advantage of doing so.

**Comment by JustArchi** [comment]
Advanced ROMs similar to AD will always find the way to do everything as needed, but if you take closer look at AD, you'll see that I build my own variation of CyanogenMod, then it's merged with everything else what I have in AD, and in similar way, GAPPS are merged too. Everything is automated so I don't wante time doing repetitive tasks.

```
bash gapps.sh
git commit -m "OpenGApps update"
git push origin master-cm
git checkout i9300-cm-experimental
git pull origin master-cm
bash adbuild.sh clean
git commit -m "Updated sources"
bash gapps.sh --update
git commit -m "i9300-specific GAPPS update"
git push origin i9300-cm-experimental
```

I'm satisfied the way it works now, as it's physically impossible to integrate my AD backend with AOSP build process, so I'm not even trying.

Leave AOSP build process alone, it should generate working base ROM and nothing else. Instead, make your own script for integration of such AOSP ROM with the rest of your ROM components, and everything will be better.

**Comment by MatthewBooth** [comment]
I'm 99% sure the guys at @PureNexus wil will want this script if they get wind of it. There is a usecase for having GApps integrated into the AOSP build system, for sure.

**Comment by JustArchi** [comment]
There is not because AOSP system doesn't offer any flexibility in terms of choice.

You tell it to include packages X, Y, Z, and it does include these pakcages.

And I dare you to integrate AROMA with AOSP before you ask friendly folks here to waste their time on that shit :+1:

**Comment by MatthewBooth** [comment]
The guys at Pure Nexus don't offer a choice either ;) Like I said, there is a usecase.

**Comment by JustArchi** [comment]
Whatever, I don't care anyway. I just can't see a point why friendly folks here should waste their time for something as useless as hardcoding list of packages to be included during building of AOSP.

**Comment by AdFad666** [comment]
I don't think it's useless, 'stock gapps' is the most popular (at least in my circles) followed by something completely minimal. If complete customization is desired then the user always needs to do some work, whether integrating or flashing a zip.

There are already eight variants that offer enough customization for most.

Making available some mk files to include in a device repo seems the easiest solution. If done properly, They even allow to override building certain packages, so you don't need to build the launcher if you're including Google Now launcher, for example.

It could be as simple as including something like:
$(call inherit-product-if-exists, vendor/opengapps/stock-xxhdpi.mk)
or
$(call inherit-product-if-exists, vendor/opengapps/micro-hdpi.mk)

**Comment by Blystad** [comment]
Any updates to this?

**Comment by mfonville** [comment]
I had some protyping done for it in a fork, but still had to implement it neatly. It is currently having a low priority on our list. Getting Marshmallow and our Android TV packages ready e.g. takes a lot of our effort at the moment.

**Comment by Blystad** [comment]
Understandable. Do you have a path to the fork? I might be able to help out :)

**Comment by mfonville** [comment]
It is only here on my local system, since I wouldn't dare to put that ugly prototype in the daylight :-P

In general it boils down that buildhelper.sh needs to be extended with some code that is currently found within update-binary.sh for selection of the best matching DPI apk.
Ad the targetlocation has to be simplified, dropping the 'keyword' and 'common' and '$dpi' from the target path.

**Comment by mfonville** [comment]
@Blystad I see you are forking and working on the AOSP build system (but not be merged yet). Does everything go well for that? If you need any help or feedback don't be afraid to e.g. add me on Hangouts :-)

**Comment by Blystad** [comment]
Yep :) It's going well. I originally went the route of code generation, based on the existing shell script system. But Android doesn't really like to first generate Android.mk files, and then add them. Android prefers to scan all Android.mk files and then do stuff afterwards. This resulted in having to run `make opengapps` and then `make`.

So, what I'm looking into now is to have a very simple Android.mk for each module. E.g. this is Chrome:

```
LOCAL_PATH := .
include $(CLEAR_VARS)
LOCAL_MODULE := Chrome
LOCAL_PACKAGE_NAME := com.android.chrome
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/system/app

include $(BUILD_GAPPS_PREBUILT_APK)
```

and then put all these in a repository, and use a hook in the AOSP build system that Google is using (they import stuff from `vendor/google/build/config.mk` before loading makefiles. This makes it possible for me to setup the `BUILD_GAPPS_PREBUILT_APK` target).

The `BUILD_GAPPS_PREBUILT_APK` target will take care of setting the remaining necessary parameters, point to the correct architecture dependent APK, and extract the required libraries.

**Comment by Blystad** [comment]
Just a update from my end:

I now have a working AOSP based build system on https://github.com/Blystad/opengapps_aosp_build/tree/initial_version for Android version 5.1. I have used it to build a ROM with the Micro variant.

The system is capable of enabling/disabling features, libraries, etc. based on both version selected (`GAPPS_VARIANT` property) and `PLATFORM_SDK_VERSION`.

I have generated and configured `Android.mk` files for most projects.

Main remaining piece is documentation & overrides. I will setup overrides up to and including Micro (since that is what I plan on using). It's not a lot of work to setup overrides, but I am quite busy this week :) See [Chrome/Android.mk](https://github.com/Blystad/opengapps_aosp_build/blob/initial_version/modules/Chrome/Android.mk#L8-L10) for an example.

I'm also a little bit sceptical about something the AOSP build system does to Chrome.apk: it deletes ALL .so files inside the apk, while your script seems to include crazy.*.so in the APK (I think?)...What is the reason behind letting crazy.*.so stay in the APK?

**Comment by mfonville** [comment]
I will check out your code when I'll have the time (probably in the weekend).
I do like your whole 'new' modular approach, it seems well thought through and designed :-) .

The crazy libs are not allowed to be extracted from the APK. It is a silly recent (Chrome v43 or so) development from the Chrome/ium team, that use an alternative linker. Their 'normally' bundled .so libs are only a pre-loader and the real lib stays within the APK. The lib inside the APK in not compressed and 'aligned' which allows them to use it.
So the AOSP build system would have to be updated to adapt to this specific situation.

**Comment by Blystad** [comment]
Alright, I'll find a way :) 

I merged stuff into my master branch now after having added GPLv3 license (just using same as on opengapps/opengapps), and basic documentation.

**Comment by mfonville** [comment]
Ok, very nice. If you want, we could look at how we could upstream/combine this code somehow, to make it more maintainable in the long run, or whether it would be best to keep it separate.

I see e.g. the function in core/find_apk.sh, which has a copied function, but maybe could benefit from an include instead.

It would definately need some planning and refactoring though and add maybe some automatic testing to check if commits don't break any build.

**Comment by Blystad** [comment]
My first suggestion is that we move the code from `Blystad/opengapps_aosp_build` to `opengapps/aosp` or something. I would like to retain contributor rights, as I plan on fixing more overrides and eventual issues in the near future.

Regarding if it's best to merge the two, or keep them seperate, it really boils down to complexity. I think I would prefer keeping them seperate, and here is why:
If we were to merge them, then I think we would have to look at creating a data structure containing all the apps, and their configuration options (module name, package name, overrides, shared libraries etc), and then generate ota.zip, aroma packages and AOSP Android.mk modules from this data structure.

This data structure would need to account for a lot of configuration options, and it would end up quite complex in my opinion. While Android.mk module name and package name is easy, the overrides is a bit difficult. Take Chrome for example which should replace the browser on stock or higher.

This complexity is also why I dropped the code generation route.

There's a flipside, and that is to use the existing AOSP build system + OpenGapps AOSP build system to create the ota.zip, but the AOSP build system doesn't really work that way. It could generate the zip files, but it would have trouble with deleting APKs out of the box. Support could be added, but the AOSP build system is a bit of a mess to be honest. I know Google is working on replacing it. (based on issues in their public bug tracker).

Currently the OpenGapps AOSP based build system is like 150-200 LoC, and then just Android.mk files for all the Google apps packages. Creating an Android.mk file is fairly easy: copy a existing Android.mk and substitute module name and package name. Changing the build system is also fairly easy. E.g. in Marshmallow we don't need to copy the system libraries, so we can add a condition around [core/prebuilt_apk.mk](https://github.com/Blystad/opengapps_aosp_build/blob/e043b08c02c4df967abc00f6031549e537fb7ea5/core/prebuilt_apk.mk#L12-L20) saying "if version < 23 ... extract libs"

--

With that being said, I think we could do one improvement that make the two systems play nicer with eachother: 

Remove the "nodpi", "240", etc folder, and move all packages up one level. Then, name the nodpi version just ModuleName.apk (e.g. Chrome.apk). This one should always exist (e.g. youtube which is only available in one DPI should contain YouTube.apk)

Then, for the DPI specific versions, these should follow the standard Android DPI naming scheme (e.g. hdpi, xhdpi, etc), with APKs named e.g. Chrome.apk, Chrome_hdpi.apk, Chrome_xhpdi.apk

**Comment by mfonville** [comment]
Keeping it separate and e.g. it hosting in a repo like ```opengapps/aosp ``` seems good to me. Is there a better name for the Android Build system than just 'aosp' that could be more descriptive?

About the dpi-naming scheme, I wish we could use hdpi, xhdpi etc, but unfortunately we can't, because the APKs actually don't stick to it at all :-(
Their ordering is not adhering those names, sometimes they are combined, and actually in the Android documentation (but don't have the link quickly available for you) they added in sdk23 even *more* possible DPIs that dont carry a 'name'.

Also we rely on the number to do comparing when installing the packages from recovery, so having the number 'ready' is useful for us.

But thinking in solutions, maybe we could use some kind of overlay or script? The 'numbers' behind hdpi, xhdpi and such are known, so 'calculating' the dpi that closest matches for a given 'name' should be possible, I think.

**Comment by Blystad** [comment]
Maybe `opengapps/aosp_build`? 

Seems I can get the display DPI from the property `ro.sf.lcd_density` in build.prop and if it isn't specified it should be default to mdpi (160) ( https://github.com/android/platform_frameworks_base/blob/master/core/java/android/util/DisplayMetrics.java ).

Should be fairly simple to sort based on that, and I can get that property from `PRODUCT_PROPERTY_OVERRIDES `.

**Comment by Blystad** [comment]
To transfer the project to opengapps/* we have two options.

Either I need to have admin rights to opengapps (ref: https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization ). But I'm fully understanding if that is a bit difficult :)

Or, you create a repo, and just clone my repo (not fork via the UI). Then everything should be fine. All work is on the master branch anyways.

**Comment by mfonville** [comment]
@Blystad alright, all done :-)
You are in charge of the team and the repo

I now declare this bug "closed" haha ;-)

**Comment by Blystad** [comment]
Thanks :)

**Comment by mfonville** [comment]
Thank you, for your hard work :)
Do you have btw an XDA-handle ? Then I could highlight your efforts on the Open GApps OP.

**Comment by Blystad** [comment]
I had one with a nickname that was cool when I was 14 :) I registered a new account with the name `blystad`

**Comment by mfonville** [comment]
Lol. I am still going strong with the 14-year one as you can see (not on github luckily)
