### ISSUE TITLE
Where does APK's coming from?

### ISSUE THREAD

**Issue by TerkiKerel** [opengapps/opengapps#640]
Hi,

Google's products (most of them) are closed source. some of them not available on google-play.

So how OpenGapps finds the APK's? There is this source?

Thank you

**Comment by hathlife** [comment]
They're pull from a pixel device with latest updated APK.

**Comment by TerkiKerel** [comment]
@hathlife i did not get it :/ Where do you pull from? You connect a pixel device and get the packages from inside the filesystem? 

A pixel device have not "google now launcher". it has "google pixel launcher". but gapps offers "google now launcher"? how this is possible?

**Comment by SpasilliumNexus** [comment]
Yes. You pull them via ADB (with root) or through custom recovery. 

Google Now Launcher? That's where Nexus devices come in, which have Google Now Launcher.

On top of that, if for some reason no one can pull from a Nexus or Pixel, there's the factory images: https://developers.google.com/android/images

**Comment by TerkiKerel** [comment]
Thank you :)
