### ISSUE TITLE
F2FS support for /system partition

### ISSUE THREAD

**Issue by giaur500** [opengapps/opengapps#641]
LineageOS already supports f2fs for /system partition. Lineage detects correctly f2fs file system and performs installation with success.

Unfortunately, OpenGapps install script never checks which file system is there and always tries to mount /system as ext4, so installation fails if /system is formatted as f2fs.

To fix: add filesystem check and mount /system correctly to allow gapps installation on f2fs

**Comment by osm0sis** [comment]
Should be resolved. The latest mount scripts use -t auto (i.e. auto type detection) for partition mounting.
