### ISSUE TITLE
Package Comparison page has broken HTML

### ISSUE THREAD

**Issue by jumper444** [opengapps/opengapps#643]
The package comparison page here for this project (screenshot attached) has busted HTML which appears fixed width and will not work on reasonably sized machines.  The screenshot is from a 1280 width display and half the packages run off the right side of the table and are unviewable.  Can this be fixed?
![screenshot_2018-06-28 opengapps opengapps](https://user-images.githubusercontent.com/1995883/42057154-70480552-7aea-11e8-97e4-9c7b8aa723cd.png)

**Comment by jumper444** [comment]
https://github.com/opengapps/opengapps/wiki/Package-Comparison
This is the page in question.

**Comment by jumper444** [comment]
What about just making the heading of "Super" "Stock "Full" "Mini"... for each column in VERTICAL single letter text (meaning put a <br> after each letter....s<br>u<br>p<br>e<br>r..etc)

**Comment by jumper444** [comment]
I went ahead and changed the page myself as described to vertical columns.  Fits screen now and I think everything is ok.  If somebody disagrees then revert it back.

**Comment by NicholasBuse** [comment]
You lost the URL to each package type that was part of the header. Other than that I am ok with the changes.

**Comment by NicholasBuse** [comment]
I added the url to each letter of your formatting

**Comment by iamsubhranil** [comment]
i recently modified the page a bit for a little nicer experience. in the table, i listed apps from pico first, which has the least number of apps, and then it goes up to super, which has the max.
is the broken name style really required now though? it looks pretty ugly and users have a hard time understanding the name of each column (i personally do).

**Comment by iamsubhranil** [comment]
Does this looks better?

![TestWiki](https://i.imgur.com/szMQAB2.png)
