### ISSUE TITLE
Apps such as Greenify and Poweramp unable to verify purchase with 280618 build of gapps

### ISSUE THREAD

**Issue by gwiqu** [opengapps/opengapps#644]
using redmi 5 plus on Havoc OS

**Comment by SpasilliumNexus** [comment]
Probably a Play Store issue.
See if [Google Play Store 10.7.18](https://www.apkmirror.com/apk/google-inc/google-play-store/google-play-store-10-7-18-release/), posted on APKMirror a few minutes ago, fixes it.

**Comment by HybridAir** [comment]
I can also confirm that I am having the same problem, even after updating the Play Store.

**Comment by eliaspizarro** [comment]
Confirm, also materialistik, titanium backup and kernel auditor

**Comment by SpasilliumNexus** [comment]
Reinstall [10.6.30](https://drive.google.com/file/d/1dEmTIiqpTte8O24WszR3QqpLziz3MJwY/view?usp=sharing).
10.7.17 and 10.7.18 has a licensing issue, and should be reported via help and feedback, if you haven't done that already.

**Comment by SpasilliumNexus** [comment]
https://www.xda-developers.com/latest-play-store-breaks-license-verification-paid-apps/

**Comment by NicholasBuse** [comment]
Is the consensus that I revert to last play store version? (probably
forcing all to wipe play store data...)

**Comment by SpasilliumNexus** [comment]
I for one recommend reverting it. Google is currently looking into it, but who knows how long it'll take for them to push out an update to fix this mess.

**Comment by SpasilliumNexus** [comment]
Update: 10.7.19 has the issue fixed. Tested with a few apps with licensing checks.

**Comment by NicholasBuse** [comment]
10.7.19 has been in the repo since shortly after @SpasilliumNexus tested. Has this issue been resolved?

**Comment by NicholasBuse** [comment]
10.7.19 has been in the repo since shortly after @SpasilliumNexus tested. Has this issue been resolved?

**Comment by NicholasBuse** [comment]
Equating lack of complaints to issue resolution.
