### ISSUE TITLE
Google Phone Does Not Ring nor Vibrate

### ISSUE THREAD

**Issue by johnmarkcausin** [opengapps/opengapps#645]
I am installing the gapps on a AOSP Android 6.0. Everything goes well after I update most of the apps in Google Play. BUT Google Phone doesn't seem to ring nor vibrate when someone is calling. It can make outbound calls and accept inbound calls but the phone would not ring and/or vibrate when someone is calling.

Please help.

Thank you.

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
