### ISSUE TITLE
logs are not saved with "adb sideload"

### ISSUE THREAD

**Issue by jamuir** [opengapps/opengapps#646]
**Issue description:**

logs are not saved when installing via `adb sideload`.

**Reproduction Steps:**

Install an open gapps zip using twrp and `adb sideload`, then notice that the tar.gz archive of debug logs cannot be found (I hit this when trying to install `open_gapps-arm64-8.1-nano-20180705.zip`).

The logs below come from twrp's recovery log:
```
cp: can't create '/sideload/open_gapps_log.txt': Read-only file system
- Installation complete!
 
cp: can't stat '': No such file or directory
unknown fuse request opcode 17
df: /sideload: Function not implemented
cp: can't stat '/sideload/open_gapps_log.txt': No such file or directory
cp: can't stat '/system/default.prop': No such file or directory
cp: can't stat '/data/local.prop': No such file or directory
cp: can't stat '/build.prop': No such file or directory
logcat read failure
tar: can't open '/sideload/open_gapps_debug_logs.tar.gz': Read-only file system
- Unmounting  /system /vendor
```
The install script doesn't seem to set the variable `TMP`.  Perhaps the script expects that to be set by the environment.

**Expected behavior:**

I'm not sure.  Maybe debug logs could be written to `/cache`, or maybe they could be written to the system partition.

**Comment by jamuir** [comment]
The behaviour I see may be due to the fact that my userdata partition has FBE enabled.

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
