### ISSUE TITLE
No updates since July 6th

### ISSUE THREAD

**Issue by nezorflame** [opengapps/opengapps#647]
@NicholasBuse @osm0sis guys, any news on the current state of the project?
People are worried about the lack of updates...

**Comment by NicholasBuse** [comment]
Latest: https://forum.xda-developers.com/showpost.php?p=77086427&postcount=5529

I could check with @mfonville if he'd be willing (and have time) to setup the build on someone else's server, but we would have to find a server that has ~500GB free disk space (maybe more?) and the connectivity to upload ~65GB of builds a day (or night).

Please read the [FAQ ](https://github.com/opengapps/opengapps/wiki/FAQ#2-im-having-a-problem-with-my-open-gapps-install-what-information-do-you-need-to-help-me)and the support instructions mentioned. You need to use [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071) for support requests, directly opening GitHub issues is not appreciated.

PS: Please remember to at least include your installation debug log and (if applicable) a logcat when requesting support.

**Comment by osm0sis** [comment]
Again, I'm not a team member of Open GApps, I only contribute fixes/features once in a while.

**Comment by harbing3r1** [comment]
A weekly GApps release would ease the load on build server. (reduce the 65GB per day)

**Comment by mfonville** [comment]
Currently the machine hosting the buildbot has a hardware failure.
We expect it to be online again at the end of July and hope that the current latest release will suffice for this very moment.

**Comment by NicholasBuse** [comment]
Thanks @ties!!!
