### ISSUE TITLE
Negative storage space while restoring from cloud

### ISSUE THREAD

**Issue by Granat1** [opengapps/opengapps#648]
**System Info:**

Device: OPPO Find 7
System: LineageOS
LineageOS version: 15.1
Android version: 8.1.0
Gapps version: ARM-8.1-20180724
(I've updated from the 20180722 because I was hoping it will fix the issue)

**Reproduction Steps:**

1. I've entered a "device setup" and it doesn't matter if this was just after the instalation or from settings menu
2. I used mobile network for connection but WIFI has the same outcome
3. I choosed "Backup from the cloud" and selected device backup file

**Expected behavior:**

I've expected any positive storage space at this point, this was newly installed system so about 2gb

**Observed behavior:**

My space had negative value, 
In the time I've generated a bug report this value was -1,8GB but it was different on the first boot, It was -575MB

I was unable to get the logcat file (tar.gz)

[open_gapps_log.txt](https://github.com/opengapps/opengapps/files/2224266/open_gapps_log.txt)

**Comment by Granat1** [comment]
I have logcat.txt tho, I'll post it in this comment

[logcat.txt](https://github.com/opengapps/opengapps/files/2224317/logcat.txt)

**Comment by osm0sis** [comment]
We can't fix Google's bugs, so not sure what you expect here.
