### ISSUE TITLE
Photos crashes in 7/15 4am CST build

### ISSUE THREAD

**Issue by DJAlik** [opengapps/opengapps#65]
Not sure if it is opengapps related but I started having Photos crash in the latest manual build. Here's the crash log

**Comment by DJAlik** [comment]
java.lang.RuntimeException: Must be called on the UI thread
	at b.r(PG:53833)
	at knt.d(PG:184)
	at hml.onError(PG:23898)
	at hlm.onError(PG:513)
	at hlm.a(PG:657)
	at hli.a(PG:1645)
	at kca.e(PG:277)
	at kca.f(PG:292)
	at kcq.run(PG:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by mfonville** [comment]
Probably indeed not Open GApps related, since we don't change the apk apart from stripping it from its libraries. Also this logcat doesn't give any (useful) information. You need to provide a longer logcat.
For now I will mark this as invalid.

**Comment by mfonville** [comment]
@DJAlik does the problem still occur?

**Comment by DJAlik** [comment]
I can only reproduce it when I try to open a photo/video when there is a
connection issue. Most likely a Google bug. You can close this issue

On Thu, Jul 16, 2015 at 6:12 AM, mfonville <notifications@github.com> wrote:

> @DJAlik <https://github.com/DJAlik> does the problem still occur?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opengapps/opengapps/issues/65#issuecomment-121927896>.
>



-- 
<http://www.facebook.com/djalik>  <http://twitter.com/#!/DJAlik>
<http://www.linkedin.com/in/alexrusinov>
<http://plus.google.com/114580313768137070684>
<http://www.mixcloud.com/djalik/>
<http://psnprofiles.com/DJAlik>

**Comment by mfonville** [comment]
Ok, I will close the issue :-)
You can use maybe the "Feedback" function to notify Google of this error.
