### ISSUE TITLE
TVStock GApps Issues in Android 6.0 ARM

### ISSUE THREAD

**Issue by islem19** [opengapps/opengapps#651]
I installed GApps (TVStock) into TV ARM architecture Android 6.0 ( i pushed them using ADB) 
I have couple issues:
1- Google Play service crashes and keeps stopping
2- Can't access play Store ( Log in Service keeps stopping )

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
