### ISSUE TITLE
All the apps are very unstable and keep on crashing. Used the Gapps for 8.1 for Arm64 on Lineage 15.1

### ISSUE THREAD

**Issue by thekeviv** [opengapps/opengapps#655]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [ ] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [ ] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [ ] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aissue)

*If Open GApps installation fails:*
- [ ] Is the issue reproducible using the latest version of your recovery?
- [ ] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

*If receiving force closures after Open GApps installation:*
- [ ] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [ ] The issue is reproducible on clean (=wiped ``/data/`` partition) installation
- [ ] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [ ] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**

[Short description of problem here]

**Reproduction Steps:**

1. [First Step]
2. [Second Step]
3. [Other Steps...]

**Expected behavior:**

[Describe expected behavior here]

**Observed behavior:**

[Describe observed behavior here]

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

[Debug log of the Open GApps installation](url)

[A logcat of the moment I receive the force closure (if applicable)](url)

**Comment by jimisan** [comment]
same here. 7 hours of eye red.

**Comment by jimisan** [comment]
1. install google play from app mirror
2. install gapps pico via twrp
3. suffer
4. do factory reset via twrp
5. profit

**Comment by thekeviv** [comment]
I tried flashing it a few times. On turning the phone on, Google play services keep on crashing, same for maps, play store would start but not open. So I have decided to wait until it becomes stable and have flashed the Yalp store for getting the essential apps(excluding Google ones).

**Comment by heindrix** [comment]
i once encounter this, after i deleted the related folder and files in the /data/app directory, and reflashed the GAPPS, it's all good.

**Comment by jimisan** [comment]
nice.

**Comment by 865301007** [comment]
i tried flash it  in android8.1 device.but always popup "device is not certified ", how to solve it.
thank you.

**Comment by lbdroid** [comment]
@865301007 
Go to this website and follow instructions: https://www.google.com/android/uncertified/

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
