### ISSUE TITLE
dialer - not correct api installed 

### ISSUE THREAD

**Issue by TheIsotopes** [opengapps/opengapps#658]
@NicholasBuse pls can you check this
since https://github.com/opengapps/arm/commit/4e623797531d12c2f48f695563df3e32a5bc7d3d the wrong dialer (api23) is installed on api24 and above

**Comment by NicholasBuse** [comment]
I guess I misunderstood the APK selection process...

The project had a hack in place for other instances like this, so I extended the feature: https://github.com/opengapps/opengapps/commit/591f704555b5851a0a58e6d8466b889046ee3499

I tested the fix locally, and it will execute on tonight's builds.

Thanks for pointing this out!
