### ISSUE TITLE
can't sideload on pine64 rockpro64 stock android rom 7.1 or 8.1

### ISSUE THREAD

**Issue by Firesped** [opengapps/opengapps#662]
The stock android rom for the rockpro64 by Pine64 does not include the google apps. I have been trying to sideload this in but it always fails. it also fails if I put it on the SD card. I don't have any special recovery, just the normal one.

do I need to compile this with the rockpro64 SDK?

**Comment by yurikoles** [comment]
@Firesped opengapps may be installed only on supported rom, e.g. LineageOS-based, maybe some others.
