### ISSUE TITLE
google play services - not correct api installed

### ISSUE THREAD

**Issue by TheIsotopes** [opengapps/opengapps#663]
@NicholasBuse found another incorrect api install ... pls can you fix this
install of google play services higher then api23 have also probs ... we have api26 and api28 in the code list but it was installed api23 on api26 and higher

**Comment by okatomyhanjaya** [comment]
could u send "open_gapps_logs.txt" ?

**Comment by okatomyhanjaya** [comment]
please give screenshot

**Comment by NicholasBuse** [comment]
I have this...
