### ISSUE TITLE
Google Play services on apkmirror but not in package ... why

### ISSUE THREAD

**Issue by TheIsotopes** [opengapps/opengapps#667]
since a few days the Google Play services 480dpi for Android Pie are on [apkmirror](https://www.apkmirror.com/apk/google-inc/google-play-services/google-play-services-13-2-80-release/google-play-services-13-2-80-100308-211705629-android-apk-download/) but not in gapps package

**Comment by TheIsotopes** [comment]
fixed now in `34e116b` ... closed

**Comment by NicholasBuse** [comment]
Thanks for pointing this out. 13.2.81 stalled and the crawler doesn't grab "old" versions. I'll double check the rest of the 13.2.80 versions on Monday.
