### ISSUE TITLE
GooglePlayServices ForceClose

### ISSUE THREAD

**Issue by HemanthJabalpuri** [opengapps/opengapps#668]
[2018-09-27_10.15.zip](https://github.com/opengapps/opengapps/files/2422597/2018-09-27_10.15.zip)
sir I am on stock touchwiz 4.4.2 rom...
Google play services force closes on setup wizard...
Attached logcat produced by SysLog app..
But it works fine for 2018 September 4th build Gapps..

I used pico GApps

**Comment by curiousrom** [comment]
> I am on stock touchwiz 4.4.2 rom...

But stock Samsung Touchwiz firmware already includes Play Store & several Google apps so why would you need to install Open GApps on top of it?

**Comment by HemanthJabalpuri** [comment]
> > I am on stock touchwiz 4.4.2 rom...
> 
> But stock Samsung Touchwiz firmware already includes Play Store & several Google apps so why would you need to install Open GApps on top of it?

Sorry for late reply...

I use a stock rom lite named rom, which is debloated with GApps too...
So I have to flash GApps after rom..

Thanks

**Comment by HemanthJabalpuri** [comment]
I tried newer pivo gapps for 4.4 from Nov 13th 2018..
and issue gone..
