### ISSUE TITLE
Touchscreen and graphics orientations mismatched on Aroma on SM-T813 (gts210vewifi)

### ISSUE THREAD

**Issue by ericonr** [opengapps/opengapps#673]
After using TWRP to install LineageOS, launching Aroma made it appear in landscape orientation on the screen, but the touchscreen acted as if the device was in portrait orientation (so if I clicked the left side of the screen, it was understood as clicking the top of the screen).

The opengapps version that was used was arm64, Android 8.1, 2018-09-29.

**Comment by tofof** [comment]
Confirmed and still present open_gapps-arm64-9.0-aroma-20190608

**Comment by osm0sis** [comment]
Development of AROMA itself is dead, so not sure what's to be done here other than stop building it entirely.

**Comment by Spartelfant** [comment]
Today I encountered this issue as well on my SM-T810 (gts210wifi) while installing `open_gapps-arm-10.0-aroma-20220215`. A quick search landed me here and I decided to leave this comment, hoping it may prove useful to others:

I was able to control the GApps Aroma installer by using the volume up and volume down buttons to select items on the screen and by using the power button to "click" on the selected item.
