### ISSUE TITLE
privapp permissions

### ISSUE THREAD

**Issue by darkobas** [opengapps/opengapps#674]
could u start updating also privapp-permissions-google xml not just packages. every sane 9.0 device enforces privapp permission check and if permissions are missing device doesnt boot up.

**Comment by darkobas** [comment]
try setting ro.control_privapp_permissions enforce
or ro.control_privapp_permissions log   (this will actually boot, and you can grep for it)

i know at least manage_users is missing from pixelmigrate
thats in nano package

**Comment by SpasilliumNexus** [comment]
Huge thanks for that tip! I'm now on a Pie ROM, so I'll be able to try keeping Google's privapp updated beyond what they've provided.

I've would've switched to a Pie ROM sooner, but I was waiting for OmniROM 9 on OnePlus 3T, and refused to switch to another ROM.

Now I'm on one that is running without enforced privapp permissions, but can use `ro.control_privapp_permissions=log` prop at will to see such entries for any Google ones

- `10-28 07:24:59.571  1190  1190 W PackageManager: Privileged permission android.permission.INTERACT_ACROSS_USERS for package com.qualcomm.qcrilmsgtunnel - not in privapp-permissions whitelist`
- `10-28 07:24:59.572  1190  1190 W PackageManager: Privileged permission android.permission.INTERACT_ACROSS_USERS for package com.qti.dpmserviceapp - not in privapp-permissions whitelist`
- `10-28 07:24:59.573  1190  1190 W PackageManager: Privileged permission android.permission.INTERACT_ACROSS_USERS for package com.android.dialer - not in privapp-permissions whitelist`
- `10-28 07:24:59.573  1190  1190 W PackageManager: Privileged permission android.permission.CAPTURE_AUDIO_OUTPUT for package com.android.dialer - not in privapp-permissions whitelist`
