### ISSUE TITLE
Missing language files for some apps

### ISSUE THREAD

**Issue by KyonLi** [opengapps/opengapps#675]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

**Issue description:**

On Android Pie some new Gapps have **separated language files**, like Google Photos 4.3.0.216626853, Google news 5.5.0

**Reproduction Steps:**

1. [First Step]
Install Google Photos 4.3.0.216626853 from OpenGapps 9.0 2018.10.16, this app can only display as English and **not following system language settings**.
2. [Second Step]
Install Google Photos 4.3.0.216626853 from play store, language is the same as system language settings (zh-cn).
3. [Other Steps...]
I found that in the app data directory, there are separated language apk files, `split_config.en.apk` `split_config.zh.apk`

![image](https://user-images.githubusercontent.com/7446107/47095451-e0338900-d25f-11e8-940a-fba37279a706.png)

`base.apk` has the same SHA1 with the one from OpenGapps.

**Expected behavior:**

Gapps with full language support.

**Observed behavior:**

Only English works.

**Comment by yurikoles** [comment]
I can confirm this on Pie/ARM64, LiquidRemix/Xiami Mi A1 (tissot)

**Comment by yurikoles** [comment]
Google Photos seems to be fixed as for 1st November.

**Comment by nplatis** [comment]
I have witnessed this in Google Maps as well, also in Android Oreo.
Could we possibly have a notice about this problem, it is at least frustrating.

**Comment by fersnake** [comment]
im having this issue too. but my phone is in spanish and the photo app and news are in english. any fix?

**Comment by michael55910** [comment]
I've got the same issue - stock Android 5.1, latest Open GApps 22 Dec. Local language is not working in Maps and Photos.

**Comment by tulioliveira** [comment]
Same issue here too. Maps and Photos stuck in english even if system is configured to Portuguese

**Comment by mrror** [comment]
Now (open_gapps-arm-7.1-aroma-20190125) also Google Maps is in english only.

**Comment by daviduco** [comment]
I'm too facing this. No news about it?

**Comment by runekock** [comment]
For me, the language corrects itself when the app gets updated from the play store. So a workaround would be to put an older version in the gapps package. Though that would annoy some users too.

**Comment by stucki** [comment]
This problem still exists but there's no update in almost 6 months. Is anybody working on this?

**Comment by stucki** [comment]
@NicholasBuse @mfonville Are you aware of this problem? New installations have no translations included. Users need to wait for the first update before they see apps e.g. Chrome in their local language. (If this is not easy to fix then it should probably be mentioned in the FAQ.)

**Comment by mfonville** [comment]
There is not much we can do about it, with the exception of being more picky which APKs we include in our repository. Making language-specific version of the GApps package is not feasible with current infrastructure (the amount of possible combinations for packages would grow exponentially)

**Comment by stucki** [comment]
@mfonville Hmm, are there any drawbacks when installing an old release? Is there anything that won't be updated via Play Store? If not, why not recommend using a release from e.g. 2 months ago?

I know, this is not a perfect solution, but it could work...

**Comment by yurikoles** [comment]
The most obvious and simple solution is to exclude installation of apps that you really need in your language. Just read advanced features in wiki. I do this myself for Chrome, so it's always installed from Google Play. Most of the apps have no problems with language, so you can keep them.
