### ISSUE TITLE
“gsflogin-all.tar.lz” is missing in arm-4.4-pico package

### ISSUE THREAD

**Issue by Hanmoshi** [opengapps/opengapps#677]
**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

**Issue description:**

File“gsflogin-all.tar.lz” is missing in arm-4.4-pico package and this situation has been going on for a month at least

**Reproduction Steps:**

![20181018160059](https://user-images.githubusercontent.com/29530999/47139705-08b69400-d2ef-11e8-9d58-a0d29af8ed99.jpg)

**Comment by shujarafi** [comment]
Yes..............................
