### ISSUE TITLE
How to build a custom package?

### ISSUE THREAD

**Issue by matifali** [opengapps/opengapps#679]
**Issue description:**

[How to build a custom package with apps of our own choice]
I know we can do that in aosp build environment and include the extra packages as we want. But how to do that while building standalone flashable zip package.

**Comment by BAProductions** [comment]
Same here

**Comment by BAProductions** [comment]
Same here

**Comment by matifali** [comment]
I know we can add the extra packages of our choice in aosp build environment.
But I don't know how can we do that if we are building Gapps standalone flashable zip package.

**Comment by BAProductions** [comment]
> I know we can add the extra packages of our choice in aosp build environment.
> But I don't know how can we do that if we are building Gapps standalone flashable zip package.

Same here

**Comment by jamuir** [comment]
One thing you could try is to download a "super" variant (i.e. download one of the pre-built zip packages).  Then you can edit the zip file by throwing out the things (i.e. packages) you don't need.  Would that work for you?

**Comment by matifali** [comment]
I don't think if this is the right way.

**Comment by BAProductions** [comment]
Will do
