### ISSUE TITLE
Per Device Config File Changes

### ISSUE THREAD

**Issue by bgiesing** [opengapps/opengapps#68]
I have been thinking about this for a while...

Some devices that are still supported by companies (like 2013 Nexus 7), can't fit the whole stock GApps package anymore. Even with a config file, if you have multiple devices, it's really hard to decide what you want to remove or add as maybe you want something to be installed but you can't put it into the config cause one of your devices doesn't have enough space. Ideally, you would still want to install those on the device that does have space.

My idea is to allow device specific configs. This could be done two ways:

- Use an IF block in your existing file.

This would be the preferred solution. It would use all the file entries but prefer changes made in the block based on device. A config might like like this (not real code):
```shell
Include
Chrome
etc.

if [ $device_name = flo ]; then
    Exclude
    Chrome
endif
```
- Allow people to make `.gapps-config-$device_name` files

This would use a normal config file first but look at the device one to modify. This would probably be worse. A way to look for one in the build script could be where it finds the config file, add an option for one with the device name using the $device_name variable.

**Comment by mfonville** [comment]
The idea for using if-then-end situations would be REALLY hard, since we don't use any 'grammar' for the config file, we just process each line as a keyword.

The second idea, to use some extra addendum to the configfile should be easy to implement though.

I am just wondering though, could you maybe sketch the scenario where this is an issue? Because in my perception most people don't share/move their configfile between the various devices? Or am I mistaken?

Having btw a device-specific addendum, could allow btw someone to set-up a git repository with some 'sane' defaults for specific devices, that mimick the original stock configuration of that time. E.g. no docs/slides/sheets on many nexus devices (they used to only have a stub, because of lack of space on the system partition).

**Comment by bgiesing** [comment]
@mfonville I have my GApps packages and config file on an OTG Flash Drive. When I need to install, I reboot to TWRP, plug in the drive, and install. Since the config file is in the same folder as the GApps on the OTG Drive, it uses it on every device.

As far as being an issue, the 2013 Nexus 7 doesn't have enough space, even after removing everything I can without having my other device "suffer" from the choices when I would want it in system if possible. A good example is since Launcher3 uses less space then GNow, I could make a sacrifice to not put GNow on my Tablet but still have it on my phone.

**Comment by mfonville** [comment]
Ok, I understand your scenario, then it makes indeed perfect sense to have a .gapps-config-$device_name take precedence over other configs.
We can do implement this in the next development cycle (I hope to launch stable tomorrow, if all scripts work :-P ).

**Comment by mfonville** [comment]
@bgiesing I made a version in branch https://github.com/opengapps/opengapps/tree/perdeviceconfig that should implement this feature, with .gapps-config-devicename taking precedence over a normal config.

I would like you to test this version, using various scenarios (so e.g. not having that deviceconfig file there, or having both a normal and a deviceconfig etc) so we can make sure it works properly. If it works, we will merge into mainline.

**Comment by bgiesing** [comment]
@mfonville I am testing now, I had a problem making a zip originally because I switched from Linux to Windows 10. 

Will report back shortly with Logs

**Comment by bgiesing** [comment]
@mfonville Here's the logs: https://gist.github.com/bgiesing/6e29159f689e762b01e4

It worked fine! One thing I will say is maybe we can tag the log files with the device name if a per-device config is used?

**Comment by mfonville** [comment]
I added one more bit of code, because I did see your falcon's devicename is not recognized (because of a faulty build.prop) so I added one more fallback instruction, that should give your falcon 'eos_falcon' as devicename. Could you also please confirm whether this change works correctly?

**Comment by bgiesing** [comment]
@mfonville Here's the updated logs: https://gist.github.com/bgiesing/6e29159f689e762b01e4

It works fine.

**Comment by mfonville** [comment]
Ok, great. Then I will merge it into the master branch. I did look into adjusting the output log file's name, but that is not easy to (reliable) achieve so I will forfeit that part.

@bgiesing Would you maybe be willing (as native speaker) to write something about this new feature at https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options#the-gapps-config-file ?

**Comment by bgiesing** [comment]
@mfonville Done! https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options#config-files-per-device

I put it into a section right beneath so it could be directly linked to.

**Comment by mfonville** [comment]
Thank you :)
