### ISSUE TITLE
Google News & Weather is deprecated.

### ISSUE THREAD

**Issue by yurikoles** [opengapps/opengapps#680]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If receiving force closures after Open GApps installation:*
- [x] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [x] The issue is reproducible on clean (=wiped ``/data/`` partition) installation
- [x] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [x] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**

OpenGapps should not ship Google News & Weather

**Reproduction Steps:**

1. Install GApps (checked in super)

**Expected behavior:**

Only new `Google News` app is installed. 

**Observed behavior:**

`Google News & Weather` is installed alongside with new `Google News`.

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

Not required.

**Comment by NicholasBuse** [comment]
Yes, thank you for linking.
