### ISSUE TITLE
minAPI26 and Problematic Messages "Dark Mode" (with fix)

### ISSUE THREAD

**Issue by SpasilliumNexus** [opengapps/opengapps#681]
It seems that Android 8.0+ (minAPI26) versions of Messages don't have a functioning Dark Mode when the user attempts to switch to it.

Since the minAPI of them are 26, they affect devices running Android 8.0 and newer.

I've tried getting in contact with someone on APKMirror to find out where the submitter are getting them from, but I've gotten no response for almost a week.

The workaround I have for my personal builds of OpenGApps is to completely remove folder "26" from all architectures, which will make the installer install the correct minAPI21 versions of Messages.

To confirm, downloading Messages from the Play Store with and without having a current installation of the Messages app, also installs a minAPI25 (nodpi) version on my device, in which the Dark Mode option works fine.

I'm not sure how to manipulate the crawler to not pick up minAPI26 for a pull submission unfortunately.

**Comment by NicholasBuse** [comment]
Thanks for the heads up. I'll contact apkmirror, and see about a near term fix. Keep you posted.

**Comment by NicholasBuse** [comment]
Ah, they are Android One...
```sh
aapt d badging <any_apk> | grep "uses-feature: name='android.hardware.ram.low'"
```

**Comment by NicholasBuse** [comment]
"Ricardo" was getting a dpi 320 for awhile too...

I have purged all 6 variants: 
- https://github.com/opengapps/arm/commit/833d62331b919429b6072667c6c99ccc99d604a4
- https://github.com/opengapps/arm64/commit/12a06348757002aae43e4de79f95c7c1799272db
- https://github.com/opengapps/x86/commit/9938d00

**Comment by SpasilliumNexus** [comment]
Thanks! I figured that's what they were, given the low DPIs on them all and being the only ones for Oreo+.
