### ISSUE TITLE
Running latest opengapps however updates still available

### ISSUE THREAD

**Issue by DJAlik** [opengapps/opengapps#688]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [ ] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [x] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aissue)

*If Open GApps installation fails:*
- [x] Is the issue reproducible using the latest version of your recovery?
- [x] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

*If receiving force closures after Open GApps installation:*
- [x] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [ ] The issue is reproducible on clean (=wiped ``/data/`` partition) installation
- [ ] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [ ] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**

I've been updating daily however the following updates are still offered everyday:
Maps
Android System WebView
Google Street View
Phone
Gboard

I am on "osprey" Moto G3 arm-320 device running latest lineageos 14.1 20181103

**Reproduction Steps:**

1. [First Step]
2. [Second Step]
3. [Other Steps...]

**Expected behavior:**

[Describe expected behavior here]

**Observed behavior:**

[Describe observed behavior here]

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

[Debug log of the Open GApps installation](url)

[A logcat of the moment I receive the force closure (if applicable)](url)

**Comment by NicholasBuse** [comment]
If you want to get those versions and upload them to APKMirror, crawlers will get them (unless they are already there?)

**Comment by DJAlik** [comment]
I think they are already there. Here's my currently installed versions for those 5 apps:

Gboard 7.7.10.219587609
Maps 10.2.2
Phone 24.0.216196427
Streetview 2.0.0.218515229
WebView 66.0.3359.158

Aren't all of these already in the opengapps repo?

**Comment by DJAlik** [comment]
@NicholasBuse I uploaded the 320arm of Phone to apkmirror but on the opengapps repository only nondpi versions are present eventhough apkmirror has various dpi versions present. Streetview apk was already on apkmirror and the same as opengapps so not sure what the issue is. Webview on opengapps is much newer, I have chrome installed but for some reason it still wants to update it. Maps is probably going to be fixed tonight. Gboard I was a member of the beta, once I left the update no longer shows.

**Comment by NicholasBuse** [comment]
I saw your phone and added it last night. Some of the other ones seem up-to-date in our repo:
Gboard 7.7.10.219587609 -->7.7.12.219989447-release-armeabi-v7a (just got it this morning, but 7.7.10 was latest until then)
Maps 10.2.2 --> 10.3.1 (for arm-320 specifically)
Phone 24.0.216196427 --> Updated last night
Streetview 2.0.0.218515229 --> 2.0.0.218515229 (same)
WebView 66.0.3359.158 --> 70.0.3538.80

If you have logs maybe you are out of space to load new ones? 
I assume you are "dirty" flashing.

Odd. WebView 66.0.3359.158 has not been current for arm since May 31, 2018 (https://github.com/opengapps/arm/commits/master/app/com.google.android.webview/21/nodpi)

**Comment by NicholasBuse** [comment]
Sorry, Repos have all the Phones that APK Mirror does: [Phone 24.0.216196427 Search](https://github.com/search?q=Phone+24.0.216196427+repo%3Aopengapps%2Fall+repo%3Aopengapps%2Farm+repo%3Aopengapps%2Farm64+repo%3Aopengapps%2Fx86+repo%3Aopengapps%2Fx86_64&type=Commits&utf8=%E2%9C%93) (I also confirmed the source report and version log from the build releases)

Streetview puzzles me.
(See webview above)
Let me know on maps
Gboard did update last night, but the betas are typically newer versions (new releases are still behind older betas...)

**Comment by NicholasBuse** [comment]
(mis-click on close...)

**Comment by DJAlik** [comment]
Flashed last nights built. This morning the following still show.

Streetview
Webview. 

I think it's putting in the stub instead of the full webview. https://github.com/opengapps/all/blob/master/app/com.google.android.webview.stub/24/nodpi/336015805.apk

**Comment by SpasilliumNexus** [comment]
Nougat or later, WebViewStub gets installed if Chrome will be too.

Use override to force non-stub WebView to install: https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options#protection-from-stupidity
