### ISSUE TITLE
Automation of apk extraction from Nexus factory images

### ISSUE THREAD

**Issue by Lekensteyn** [opengapps/opengapps#70]
This how to lists some manual steps to extract files from a factory image: https://github.com/opengapps/all/blob/master/HOWTO

> Extract the image-xxxxx-xxxxxx.zip from from the tgz archive
> Extract the system.img from the image-xxxxx-xxxxxx.zip
> Get sig2img [sic] from https://github.com/anestisb/android-simg2img
> Convert the system.img from a sparse android file to a disk-image file using android-simg2img: simg2img system.img system.raw.img
> Open the system.raw.img using a disk-mount application

All of these steps can be automated. From my notes, the steps to download an image, verify its integrity, extract the system image from the zip file and expand it to an ext4 filesystem image:

``` bash
# get proprietary files (install android-tools-fsutils on Ubuntu for simg2img)
wget https://dl.google.com/dl/android/aosp/hammerhead-lmy48b-factory-596bb9c1.tgz
sha1sum -c <<<596bb9c125525ce5baf4762a1cac6f5880c50cbc\ \ hammerhead-lmy48b-factory-596bb9c1.tgz
tar xOf hammerhead-lmy48b-factory-596bb9c1.tgz hammerhead-lmy48b/image-hammerhead-lmy48b.zip |
bsdtar -xf- system.img
simg2img system.img system.ext4; rm system.img
```

Here is another uncut piece from my notes which I use to extract a set of files (each line from `$files`) from `system.ext4` to `$outdir` (again with some integrity checking):

``` bash
# Continue extracting the files (51 MiB)
outdir=/tmp/pfiles/system
files=$(awk '/^[-\/]/{sub("^-?/system/","");print}' ~/android/system/device/lge/hammerhead/proprietary-blobs.txt)
mkdir -p $(<<<"$files" sed -e 's,/[^/]*$,,' -e "s,^,$outdir/," | sort -u)
<<<"$files" sed "s,.*,dump & $outdir/&," | debugfs system.ext4 2>/tmp/other
cat /tmp/other
# Grab other files from cm-12.1 (d8c1b0b9b8f9d10d48f8ccd77907231b509c3a36)
for f in $(grep -Eo 'vendor/[^:]+' /tmp/other); do
    wget -O "$outdir/$f" https://github.com/TheMuppets/proprietary_vendor_lge/raw/cm-12.1/hammerhead/proprietary/$f
done
(cd "$outdir" && sha1sum -c) <<EOF
ce1f2999b12d02d187eed6479d185a210526657c  vendor/lib/libqc-opt.so
760739ac471ab004458542939cfd853503aabf92  vendor/lib/libQSEEComAPI.so
781920631d0c44d07aeb12c1f05020397acd14a4  vendor/lib/soundfx/libqcbassboost.so
4b117e02bf34fa8252640ba4d09566179c3258b8  vendor/lib/soundfx/libqcreverb.so
8ad9079658e50b3b3c72f3891d4e19218aa2e90a  vendor/lib/soundfx/libqcvirt.so
EOF
```

Hopefully it can be of some use.

Aside,
I have tried to [document](https://github.com/Lekensteyn/make-gapps-zip) the differences between AOSP and the Nexus images with the ultimate goal to have reproducible/automatable steps for generating the gapps from a system image. Unfortunately I have not managed to handle the aot-optimized apk files which have no classes.dex file inside. Where did you get these APKs from? Can you document this in the commit messages in the future?

**Comment by mfonville** [comment]
Yes, I know these steps could be automated, but it never had priority (because nexus images are not released that often).
So thank you for the code, we can use this to (partially) automate the process.

About regenerating the APKs from the image I use this tool: http://forum.xda-developers.com/galaxy-s5/general/tool-deodex-tool-android-l-t2972025/post57471606#post57471606 
Unfortunately it is Windows-only :-(

**Comment by Lekensteyn** [comment]
That tool looks like a frontend to https://github.com/testwhat/SmaliEx which is a fork of smali. The inability to handle oat-optimized files is tracked in https://github.com/JesusFreke/smali/issues/269. I have not studied @testwhat's code yet, but hope it is possible to integrate in the upstream repo after review.

**Comment by Lekensteyn** [comment]
Alright, I finally managed to make a reproducible gapps package from the factory images. Assuming that the APK files and framework folders are somehow available (extracted from system.img, from a device, whatever), it can be used to create an APK that will always be the same.

This tool (odex2apk.py) can be found in my repo at https://github.com/Lekensteyn/make-gapps-zip. There is also a make-update-zip.py script that can handle a set of APKs and files with a very simple update-binary script (I like it simple, easy to audit and verify). Since it is written in Python, it is not just limited to Linux, but can also work on Windows and OS X.

This should be a step towards fully reproducible builds for Open GApps (in the truly open, transparent sense). Your feedback is welcome :-)

**Comment by mfonville** [comment]
I am currently on holidays, so sorry for lack of initial response on some of your input. But I think this is awesome :-) probably it would be great/best to make this part of the apk-crawler? So that one could extract apks from both online sources as from (locally available) images, and export them easily to the opengapps scripts.

**Comment by Lekensteyn** [comment]
Feel free to use it in apkcrawler (MIT is compatible with GPLv3), the best is to keep this functionality in a separate file (module) though. The apk crawler code is already monolithic. (For clarity, I mean to keep it in a separate file, possibly next to apkcrawler.py.)

And for someone on holidays you are pretty fast. In the coming weeks I will most likely be very less responsive as I have been neglected my inbox and procrastinated replies ;-)

**Comment by mfonville** [comment]
@Lekensteyn does your script and (bak)smali also support x86 images/applications?

**Comment by Lekensteyn** [comment]
It (odex2apk.py) should handle those as the only difference is in the naming of the folders (x86 or x86_64 vs. arm). (bak)smali should not be much different in that regard, I assume that the (o)dex files are independent of the architecture.

**Comment by mfonville** [comment]
I do get the error when trying to deodex the Nexus Player image (which is x86):

odex2apk: Processing boot directory, may take a minute...
Traceback (most recent call last):
  File "./make-update-zip.py", line 197, in <module>
    main()
  File "./make-update-zip.py", line 168, in main
    odex2apk.process_boot(boot_odex_path)
  File "/home/maarten/Development/make-gapps-zip/odex2apk.py", line 160, in process_boot
    raise RuntimeError("Failed to deoptimize boot.oat")
RuntimeError: Failed to deoptimize boot.oat

So I fear odex2apk cannot handle x86 :-/

**Comment by mfonville** [comment]
A notice: on Android One images most APKs are not odexed, so you can get fully signed APKs straight from Google :-)

**Comment by osm0sis** [comment]
Abandoned.
