### ISSUE TITLE
Google Services FC

### ISSUE THREAD

**Issue by DeVviL** [opengapps/opengapps#702]
Hello, please help! Google Services Force Close.
Device - Meizu M2 mini, ARM64, android 7.1 custom ROM
Install OpenGapps ARM64 7.1 nano

**Reproduction Steps:**

1. Install Lineage 14.1 (or other ROM)
2. Install gapps
3. Reboot
4. Force Close immediately after the first boot

[system_log.txt](https://github.com/opengapps/opengapps/files/2649636/system_log.txt)
[open_gapps_debug_logs.tar.gz](https://github.com/opengapps/opengapps/files/2649641/open_gapps_debug_logs.tar.gz)

**Comment by TomasMFranco** [comment]
Try installing an apk of the newest google services and clearing the cache of every google app.
