### ISSUE TITLE
Pushbullet Updates

### ISSUE THREAD

**Issue by NicholasBuse** [opengapps/opengapps#71]
I believe that Pushbullet needs to be updated (maybe per architecture channels?). Just noticed that it has not update since 20150716 (last release in opengapps/opengapps).

**Comment by mfonville** [comment]
It is a problem on pushbullet's side in processing our new RSS feed. I am contact with them about it.

**Comment by mfonville** [comment]
Pushbullet resolved their issue, so coming night everything should go smooth. So I will close the bug now, if it will still be broken it can be reopened.
