### ISSUE TITLE
Can not open camera and problem with android auto

### ISSUE THREAD

**Issue by duypp1820** [opengapps/opengapps#712]
I was installed LineageOS 15.1 with Gapps 8.1 stock version 
(https://github.com/opengapps/opengapps/files/2735358/open_gapps-arm64-8.1-stock-20190108.versionlog.txt)
I am selling leeco le s3 x522 us version. ( it also call leeco le 2 qualcomm version ) on ebay with LineageOS installed on device because chinese stock rom from leeco le s3 is stuck, so i installed LineageOS 15.1 and sell the phone. My customer keep complain me about google camera is not working and android auto is not working so i decide to take 2 leeco phones and see what happen, i recognize that it really not working. My solution is install Footej camera premium version and block gapps from being install android auto. But my customer keep complain me about android auto that they download from google play is not working. Please help me i have no idea to fix this problem.

**### #The issues i'm facing right now is i can not open camera, every time i open camera it just say camera has stop. I try to fix that by clear cache, force stop app, reboot phone but nothing change. Another problem i am facing right now is android auto keep say google play service is not working, i looked on online and following their steps like reboot, clear cache on google play service, reset phone, update google play service and force Android auto. Please help me**

**Comment by viggy96** [comment]
I've experienced the Android Auto not working on my device as well and have reported it (#710). As for the Google Camera, you might want to not flash it via OpenGApps, and instead install it as a user app. [This](https://www.celsoazevedo.com/files/android/google-camera/) is a good place to download a Google Camera app. I use the apks from that site myself, for my Moto X4.

**Comment by duypp1820** [comment]
I know but if you install google camera as user app then you have to log in to able to install it on google play

**Comment by duypp1820** [comment]
Also i have to complete setup to able install it so when my customer power on the phone they will not see setup screen

**Comment by duypp1820** [comment]
If you have patch zip can you share it

**Comment by viggy96** [comment]
@duypp1820 What? Just go to the website I linked and download the apk directly. There are plenty of versions there to try if one doesn't work on your device. This process doesn't involve the Play Store at all.

**Comment by duypp1820** [comment]
i tried abuot 15 diff camera app all not working, there is one app that work the rear camera but not work the front camera. Front camera have green color when it take picture, rear camera is great, that app is CaMMera

**Comment by duypp1820** [comment]
i think app CaMMera have bug with front camera if it fix then it will be great

**Comment by viggy96** [comment]
You can also try to find the stock camera app for Leeco phones online, and install that. There's probably something weird that Leeco is doing on its phones with regard to the camera that the Google Camera doesn't deal with.

**Comment by viggy96** [comment]
OpenGApps appears to have broken the auto API necessary for Android Auto, so there's nothing for us to do but wait for a fix. I have submitted #710 to alert the OpenGApps team. There has been no reply yet.
