### ISSUE TITLE
How to Uninstall opengapps

### ISSUE THREAD

**Issue by joesdu** [opengapps/opengapps#715]
How to Uninstall opengapps?Can you release an uninstall package?

**Comment by YandexStudio** [comment]
I think their wiki said clearly that there's NO WAY to uninstall, the only way to “remove” is wipe /system and re-flash your ROM.

BUT, if your ROM zip contains /data, your /data will also overwrite and you may lose your data.

**Comment by qssq** [comment]
I'm also looking for ways to uninstall gapps，flashing gapps causes many strange problems, such as invalid desktop uninstall applications, automatic reply after restart, magisk does not pop up authorization prompts, and so on.

**Comment by nezorflame** [comment]
Pretty sure there won't be an uninstaller anytime soon (or even never).

**Comment by amosbird** [comment]
If it's MIUI, you can reinstall current rom using system update. It will fail but also get rid of gapps.

**Comment by DJCrashdummy** [comment]
FWIW: there are some tips at #551.

**Comment by Melechtna** [comment]
> FWIW: there are some tips at #551.

None of the tips here are useful anymore as wiping system isn't an option anymore

**Comment by osm0sis** [comment]
On a device and ROM where GApps are possible formatting system in a custom recovery is absolutely is still a thing.
