### ISSUE TITLE
Play Service don't install with no error in log

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [opengapps/opengapps#717]
I tried to install the open_gapps-arm64-8.0-builds from 2019-01-26 on my Samsung Galaxy S7.
These build don't install the Google Play Service on my/this device.
And there was no error message in the logs.
I downloaded later an arm64-v8a-build of the apk from apkmirror.com.
Only the apks for arm64-v8a install on my/this device.

So I guess that in the builds...
- Are only apks for arm64-v7a
- It isn't mentioned on the homepage
- There is no version check (v7a/v8a) in the installer
- There got no error logged

Is this possible?

**Comment by Tobias-B-Besemer** [comment]
Setting the option "ForceClean" solved the issue with reboot.
I attach the logs.
[open_gapps_log.txt](https://github.com/opengapps/opengapps/files/2826294/open_gapps_log.txt)
[open_gapps_debug_logs.tar.gz](https://github.com/opengapps/opengapps/files/2826295/open_gapps_debug_logs.tar.gz)

**Comment by Tobias-B-Besemer** [comment]
I made now several tries with the super-/stock-/full- & mini-editions.
I always had a reboot during install.
The point were the installer reboots vary.
It isn't a temperature problem, because TWRP says my temp. is ~25C.
But the reboot happens earlier if I e.g. have the storage mounted before in TWRP.
So it locks a little like a memory (OOM) problem to me... Maybe from TWRP...
I'm using TWRP v3.2.3-0.
Only the mirco-edition was small enough to be installed before the problem happens.

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
