### ISSUE TITLE
Soundpicker - New APK

### ISSUE THREAD

**Issue by dontobi** [opengapps/opengapps#718]
There is an update for the App Soundpicker. This update has not been commited yet. here the link to the APK:

https://www.apkmirror.com/apk/google-inc/sounds/sounds-2-0-1-226190645-release/

**Comment by SpasilliumNexus** [comment]
Having the crawler find this app, since Google has published it to the Play Store, is on my to-do list (among others) once the migration completes.

**Comment by Crescendo-BLYAT** [comment]
its is included already on Stock version of GApps...

**Comment by NicholasBuse** [comment]
Added to APKCrawler: https://github.com/opengapps/apkcrawler/commit/d20c99af54cdb9e76c59b9c0e834416b010a5e12

Committed latest apk: https://gitlab.nezorfla.me/opengapps/arm/commit/7f4b0e5113f97d6d6c2c4216e29dd55b52a07464
