### ISSUE TITLE
ZIP Logo cut off

### ISSUE THREAD

**Issue by bgiesing** [opengapps/opengapps#72]
This is no where near important, but just mentioning that at least on my Moto G, the ASCII Logo is cut off from being too wide.

Doesn't need to be fixed but I just thought I would bring it up!
![Just Sayin](http://1.bp.blogspot.com/-3r_1e3wGhH0/VAJRkU9LHjI/AAAAAAAAGjs/d_KF_AG-Do4/s1600/tumblr_n5bbfnF7nx1s8wvgro1_400.gif)

**Comment by mfonville** [comment]
Could you give me the line length of your device? (so how many characters fit on one line)

**Comment by mfonville** [comment]
And could you test if maybe this would fit on your screen?
```
   ___                    ___   _                
  / _ \ _ __  ___ _ _    / __| /_\  _ __ _ __ ___
 | (_) | '_ \/ -_) ' \  | (_ |/ _ \| '_ \ '_ (_-<
  \___/| .__/\___|_||_|  \___/_/ \_\ .__/ .__/__/
       |_|                         |_|  |_|      
```

**Comment by bgiesing** [comment]
Looks like it works!

On Wed, Jul 22, 2015, 5:28 AM mfonville <notifications@github.com> wrote:

> And could you test if maybe this would fit on your screen?
>
>    ___                    ___   _
>   / _ \ _ __  ___ _ _    / __| /_\  _ __ _ __ ___
>  | (_) | '_ \/ -_) ' \  | (_ |/ _ \| '_ \ '_ (_-<
>   \___/| .__/\___|_||_|  \___/_/ \_\ .__/ .__/__/
>        |_|                         |_|  |_|
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opengapps/opengapps/issues/72#issuecomment-123655248>.
>
> unsubscribe
> <http://email.giesing.cf/u/eJxNyzESwiAQQNHTQOmEBVZSUNh4jwWWhBkJjJD7a6xs_rzmJ49IEWTxrfOxUe9DwPPfZYyTL9zhGwUarQXjhFm2Mvcz3GKrcvfMCVG7rEKk4BSHkC2lJeOaDDNb-fapzUpHoajX665UXr95egGPD8kxK3I>
>



To unsubscribe click: <http://email.giesing.cf/u/eJwljrtuwkAQAL_G7oJ29_ZehQs7gSKgPIoEkSa6u70zVrAgCEciXx_kTDHlaKQxJiSqh-a-XU9H-_W2enkdv917pR66z83u6VrWH8-0lJ_HX97Gk8gWZQO6ok7d9VPXVgxjGA6LfnY6jvW-EZEQhYou3gA7itEqziVziC4QYn1uzvl0uN4iANZZH2yAiEEzMWEWNtorpyNYC1JSKcalRBYysadU4B9ETFaR1p4CGp8y6ASGI96W5vyiHy77Kc5Tl6ai9g_2yEUp>

**Comment by mfonville** [comment]
So that would mean we are only a single character too long at the moment...?

**Comment by mfonville** [comment]
I pushed a shorter logo to the mainline, @bgiesing could you test if that works for you?

**Comment by bgiesing** [comment]
Okay, I must of messed up when I checked the first time because we are still too long by 2-3 characters. @mfonville

**Comment by mfonville** [comment]
Ok, then check tomorrow's build, it will be fixed now for sure (it is only 2x something chars now)
