### ISSUE TITLE
Repositories at https://gitlab.nezorfla.me/ have disappeared

### ISSUE THREAD

**Issue by gentoo-root** [opengapps/opengapps#722]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [x] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aissue)

*If Open GApps installation fails:*
- [ ] Is the issue reproducible using the latest version of your recovery?
- [ ] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

*If receiving force closures after Open GApps installation:*
- [ ] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [ ] The issue is reproducible on clean (=wiped ``/data/`` partition) installation
- [ ] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [ ] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**

I'm building my custom builds of Android with OpenGApps included. After the repositories with apks had been removed from github, I switched to https://gitlab.nezorfla.me/. However, it looks like short time ago this server stopped working, e.g., https://gitlab.nezorfla.me/opengapps/arm64 says that the repository doesn't exist, although it shows in the list. These repositories are still in .gitmodules of this one.

**Reproduction Steps:**

1. `git clone https://gitlab.nezorfla.me/opengapps/arm64`

**Expected behavior:**

The repository with apks is cloned.

**Observed behavior:**

```
remote: A repository for this project does not exist yet.
fatal: repository 'https://gitlab.nezorfla.me/opengapps/arm64/' not found
```

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

[Debug log of the Open GApps installation](url)

[A logcat of the moment I receive the force closure (if applicable)](url)

**Comment by nezorflame** [comment]
@gentoo-root hi, thanks for the issue. What you've experienced is that you got in the middle of the server upgrade, while I was transferring the data to the new server. Everything should be OK now (and a lot faster). Please try again and let me know if there are any issues.

**Comment by gentoo-root** [comment]
Hi, I'm glad to see everything works again now. However, I wouldn't say it's faster than before — I didn't have enough patience to clone the repository:

```
$ git clone https://gitlab.nezorfla.me/opengapps/arm64
Cloning into 'arm64'...
warning: redirecting to https://gitlab.nezorfla.me/opengapps/arm64.git/
remote: Enumerating objects: 35688, done.
remote: Counting objects: 100% (35688/35688), done.
remote: Compressing objects:  10% (1109/10712)
```

It was way too slow, doing a little progress once in a few minutes, and I stopped. Fortunately, I have them cloned, and all I need is fetch, but github was much, much faster.

**Comment by nezorflame** [comment]
By faster I meant more like a server state :)
Also you'd probably want to make a shallow clone, since having all the history locally is usually not required.

**Comment by gentoo-root** [comment]
Yes, you're right, `--depth=1` is what I want (BTW, that's what happens when I run `repo sync -c`), but the server is still unusably slow:

```
$ time git clone https://gitlab.nezorfla.me/opengapps/arm64 --depth=1
Cloning into 'arm64'...
warning: redirecting to https://gitlab.nezorfla.me/opengapps/arm64.git/
remote: Enumerating objects: 463, done.
remote: Counting objects: 100% (463/463), done.
remote: Compressing objects: 100% (226/226), done.
error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Command exited with non-zero status 128
0.01user 0.05system 27:58.41elapsed 0%CPU (0avgtext+0avgdata 4436maxresident)k
32inputs+0outputs (0major+312minor)pagefaults 0swaps
```

It has been running for 28 minutes and failed. When the download itself finally started, it was at 4 KB/s.

**Comment by nezorflame** [comment]
Since it's using HTTPS, one of this fixes for the error is setting this:

`git config --global https.postBuffer 524288000`

**Comment by nezorflame** [comment]
I'll be optimizing this even further.
Also cloning by SSH doesn't seem to have this issue, so I'll probably enable registration in the near future.

**Comment by nezorflame** [comment]
@gentoo-root I've enabled registration.
Registration will allow to create issues, snippets. You won't be able to fork a repo or create a new one though.
Please try creating a new account, adding SSH key and pulling the repo through SSH instead.

**Comment by gentoo-root** [comment]
OK, my results:

HTTPS + setting https.postBuffer: download speed improved a lot (up to a few MB/s), but "Counting objects" and "Compressing objects" stages take about 15 minutes even with `--depth=1`.

SSH: "Counting objects" is immediate, "Compressing objects" takes 10 minutes, and the download speed is good, although it sometimes drops to a few hundred KB/s (it happens with HTTPS as well).

To be honest, I don't know how you do the whole thing in 3 minutes if "Compressing objects" takes 10 minutes and doesn't involve any data transmission over the network.

BTW, the confirmation emails from gitlab get into spam.

**Comment by nezorflame** [comment]
@gentoo-root it really depends on the location, since the server is based in Germany.

**Comment by gentoo-root** [comment]
Sorry, can you elaborate more? How does it depend on the location how much time "Compressing objects" takes? I expect that the download speed may be lower than yours, but not the server-side steps.

**Comment by nezorflame** [comment]
Yeah, I was speaking only about the DL speed.
About the confirmation letter - yeah, I know, will try to fix that.

**Comment by nezorflame** [comment]
If you want, try pulling the repos once again. Should be a bit better now.

**Comment by NicholasBuse** [comment]
I think this was just poor communication/timing. Server is good after upgrade.

**Comment by gentoo-root** [comment]
Yes, I confirm, the speed is good now both over HTTPS and SSH. Thanks!

**Comment by Split7fire** [comment]
Again same problem:
`fatal: unable to access 'http://gitlab.nezorfla.me/opengapps/arm64/': Could not resolve host: gitlab.nezorfla.me`

**Comment by nezorflame** [comment]
@Split7fire we've changed the hostname of the server a long time ago - you're gonna need to replace `gitlab.nezorfla.me` to `gitlab.opengapps.org`.

**Comment by Split7fire** [comment]
@nezorflame, yep I have discovered it and already replaced. Thanks for answering!
