### ISSUE TITLE
chrome arm64 apk 368302057.apk.lz:  "Requires development platform Q but this is a release platform."

### ISSUE THREAD

**Issue by jamuir** [opengapps/opengapps#725]
**Issue description:**

https://gitlab.nezorfla.me/opengapps/arm64/commit/0d55fd7437c7e98d4f6d6eb50c4ce9789df30da8

The latest update to the Chrome apk does not install in ~"user"~ oreo builds:

```
02-04 22:47:57.787 W/PackageManager(  911): Failed to parse /system/app/Chrome: /system/app/Chrome/Chrome.apk (at Binary XML file line #3): Requires development platform Q but this is a release platform.
```

**Reproduction Steps:**

Try to install app/com.android.chrome/24/nodpi/368302057.apk.lz in an ~"user"~ oreo build.

**Comment by jamuir** [comment]
edit:  correction. I see this in both "user" and "userdebug" builds (it is not specific to "user" builds).

**Comment by jamuir** [comment]
@NicholasBuse :  I think commit 0d55fd74 needs to be reverted.

https://gitlab.nezorfla.me/opengapps/arm64/commit/0d55fd7437c7e98d4f6d6eb50c4ce9789df30da8

**Comment by NicholasBuse** [comment]
Done, thanks I'll start watching for Q apks!
