### ISSUE TITLE
Automated Upload Script

### ISSUE THREAD

**Issue by bgiesing** [opengapps/opengapps#73]
Maybe we can add a simple bash script (maybe `./upload.sh`?) that would automatically cd into the source directory, add the files, commit with a common format, and push.
```
cd sources/$arch &&
git add . &&
git commit -am'$AppName $VersionName ($DPI)' &&
git push origin HEAD:master &&
cd ../../
```

To explain:

1. The `cd` command would cd into the appropriate source dir.
2. Add to Staged
3. Commit with $AppName being either the keyword, package name, or the Play Store name; $VersionName and $DPI coming from the `./add_sourceapp.sh` command variables.
4. This is interesting, but when you clone and run `./download-sources.sh`, it doesn't set the branch of the modules to master, so this version of the command would take what you just added (HEAD) and push it to origin/master.
5. Take you back to the main directory.

If we have multiple files added at the same time, then we could do two things:

- Add to one commit (with the name being altered to show `$AppName $VersionName ($DPI) and more` (Or something similar)
- Add to one commit and put all the `$AppName $VersionName ($DPI)` on a line each.
- Make seperate commits for each APK of different name (aka multiple GMS versions would still be one commit with the name having multiple DPIs, but Play Store and Chrome would still be seperate commits)

Any thoughts or anybody want to implement?

**Comment by NicholasBuse** [comment]
+1

**Comment by DJAlik** [comment]
+1

On Wed, Jul 22, 2015 at 5:30 PM, Nicholas Buse <notifications@github.com>
wrote:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opengapps/opengapps/issues/73#issuecomment-123889818>.
>



-- 
<http://www.facebook.com/djalik>  <http://twitter.com/#!/DJAlik>
<http://www.linkedin.com/in/alexrusinov>
<http://plus.google.com/114580313768137070684>
<http://www.mixcloud.com/djalik/>
<http://psnprofiles.com/DJAlik>

**Comment by bgiesing** [comment]
@mfonville Can you look at my initial script? Been a while since I have done shell so I want to make sure I am on track:

```sh
#!/bin/sh
#This file is part of The Open GApps script of @mfonville.
#
#    The Open GApps scripts are free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    These scripts are distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#

source add_sourceapp.sh
cd sources/$architectures
git add .
git commit -am'$name $versionname ($dpis)'
git push origin HEAD:master
cd ../../
```

**Comment by mfonville** [comment]
'source' is not POSIX-compliant, you should use ./
$architectures can be a multitude of architectures, not a single value.

But in general I think it'd be better to take a different approach for not attachting it to add_sourceapp.sh.

* I think the best thing you could do, is write a separate script that iterates over the directories in sources (e.g. from my apkcompetition-script, some ugly and non-compliant code:
```
TOP="$(realpath .)"
SOURCES="$TOP/sources"
for arch in $(ls "$SOURCES"); do
	cd "$SOURCES/$arch"
	***DO STUFF**
done
```
* per architecture check with e.g. git status if something has changed in the second-level directory (e.g. app/com.android.chrome) since that indicates a package, and we want seperate commits per package (don't we?) (hint: check out --format for the git commands)
* Then, if something has changed for such a package's directory, find out for which subfolders (those give you the sdk level) and subsubfolder (that gives you the dpi).
* Add for the package's folder the proper git add and git rm to indicate what has to be added and removed for the commit
* Write the commit, with a nice message with the info you have
* Go to the next package, and make more commits if necessary
* At the end show which commits would be pushed, and ask the user if he really wants to push those to the repository. Gracefully handle a possible fail to push, if somebody else has pushed some packages earlier than you...

**Comment by bgiesing** [comment]
@mfonville This is where i'm at currently:
```sh
TOP="$(realpath .)"
SOURCES="$TOP/sources"
APK=$(git status -suall | cut -c4-)

upload () {
git add $APK
git commit -am'$name $versionname ($dpis)'
git push origin HEAD:master
cd ../../
}

for arch in $(ls "$SOURCES"); do
    cd "$SOURCES/$arch"
    upload
done
```

The $APK output looks like this (note I added a random APK from APKMirror so I can test.):
```
app/com.asus.camera/19/nodpi/210020370.apk
```

Right now, I am trying to figure out:

1. How to one read the first line and come back afterwards
2. Best way to extract the info from the $APK command (grep?)

**Comment by mfonville** [comment]
Read the first line is: ```head -n1```
To get the best info from any git command, use the --format option for git. (Look at man git)

**Comment by bgiesing** [comment]
@mfonville I can't find the --format option in the man pages at all.

**Comment by bgiesing** [comment]
@mfonville @rapperskull Here's where I am at now:

```sh
#!/bin/sh
#This file is part of The Open GApps script of @mfonville.
#
#    The Open GApps scripts are free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    These scripts are distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#

TOP="$(realpath .)"
SOURCES="$TOP/sources"
arch="'all' 'arm' 'arm64' 'x86' 'x86_64'"

command -v aapt >/dev/null 2>&1 || { echo "aapt is required but it's not installed.  Aborting." >&2; exit 1; }
command -v install >/dev/null 2>&1 || { echo "coreutils is required but it's not installed.  Aborting." >&2; exit 1; }
#coreutils also contains the basename command

getapkproperties(){
        apkproperties="$(aapt dump badging "$1" 2>/dev/null)"
        name="$(echo "$apkproperties" | grep "application-label:" | sed 's/application-label://g' | sed "s/'//g")"
}

getinfo () {
APK=$(git status -suall | cut -c4- | head -n1)
versionname=$(basename ${APK} .apk)
dpis=$(${APK} | awk -F/ '{print $(NF-1)}')
}

upload () {
git add $APK
git commit -am'$name $versionname ($dpis)'
# git push origin HEAD:master
cd ../../
}

for arch in $(ls "$SOURCES"); do
    cd "$SOURCES/$arch"
    getinfo
    getapkproperties
    upload
done
```

I am getting this error: `Syntax error: word unexpected (expecting ")")`

**Comment by mfonville** [comment]
Try this:
```
TOP="$(realpath .)"
SOURCES="$TOP/sources"

command -v aapt >/dev/null 2>&1 || { echo "aapt is required but it's not installed.  Aborting." >&2; exit 1; }
command -v basename >/dev/null 2>&1 || { echo "coreutils is required but it's not installed.  Aborting." >&2; exit 1; }

getapkproperties(){
        apkproperties="$(aapt dump badging "$1" 2>/dev/null)"
        name="$(echo "$apkproperties" | grep "application-label:" | sed 's/application-label://g' | sed "s/'//g")"
}

getinfo () {
APK="$(git status -suall | cut -c4- | head -n1)"
versionname="$(basename "$APK" .apk)"
dpis="$(printf "$APK" | awk -F/ '{print $(NF-1)}')"
}

upload () {
git add "$APK"
git commit -am"$name $versionname ($dpis)"
# git push origin HEAD:master ## commented out to not push (will later)
cd "$TOP"
}

for arch in $(ls "$SOURCES"); do
    cd "$SOURCES/$arch"
    getinfo
    getapkproperties
    upload
done
```

**Comment by bgiesing** [comment]
Better, but it isn't getting the App Name from aapt. (Even though that's your code LOL)

**Comment by mfonville** [comment]
because your $1 is empty, you don't pass anything to the getapkproperties functions.

Maybe a good read/manual for the basics: http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html

**Comment by bgiesing** [comment]
PR submitted! @mfonville

**Comment by mfonville** [comment]
Please test carefully (it does not commit automatically yet) the upload_sources.sh script that can be found in the uploadscript branch.
It would first need some testing (especially for edge-cases) before I want to enable the automatic committing, and putting it in master.

**Comment by mfonville** [comment]
I now added the handling for multiple APKs, since it was trivial.

**Comment by bgiesing** [comment]
@mfonville I would test, but there's nothing to test on! LOL

**Comment by bgiesing** [comment]
@mfonville Seems there's an error:
```
commit a5cc4011c6dbd9de4585e3dcf18608ed0a10b738
Author: Brandon Giesing <brandon@giesing.cf>
Date:   Fri Jul 24 16:52:13 2015 -0500

    Google Play services 7.8.93 (nodpi)

diff --git a/priv-app/com.google.android.gms/21/nodpi/7893440.apk b/priv-app/com.google.android.gms/21/nodpi/7893440.apk
new file mode 100755
index 0000000..95f637e
Binary files /dev/null and b/priv-app/com.google.android.gms/21/nodpi/7893440.apk differ

commit 526d19a084d8f85aa6fd1c408e9ab8a3e5d59298
Author: Brandon Giesing <brandon@giesing.cf>
Date:   Fri Jul 24 16:51:59 2015 -0500

      (nodpi)

diff --git a/priv-app/com.google.android.gms/21/nodpi/7892440.apk b/priv-app/com.google.android.gms/21/nodpi/7892440.apk
deleted file mode 100644
index 37b6407..0000000
Binary files a/priv-app/com.google.android.gms/21/nodpi/7892440.apk and /dev/null differ
```

It generates two commits with one including /dev/null

Here's the output of the script itself:
```shell

rm 'priv-app/com.google.android.gms/21/nodpi/7892440.apk'
fatal: pathspec 'priv-app/com.google.android.gms/21/nodpi/7892440.apk' did not match any files
[detached HEAD 526d19a]   (nodpi)
 1 file changed, 0 insertions(+), 0 deletions(-)
 delete mode 100644 priv-app/com.google.android.gms/21/nodpi/7892440.apk
[detached HEAD a5cc401] Google Play services 7.8.93 (nodpi)
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100755 priv-app/com.google.android.gms/21/nodpi/7893440.apk
```

**Comment by mfonville** [comment]
Please try again with the updated script

**Comment by bgiesing** [comment]
@mfonville Aaaannnnndddd... it works!

![Epic Win](http://stream1.gifsoup.com/webroot/animatedgifs2/2043309_o.gif)

**Comment by mfonville** [comment]
Ok, please keep testing it more, maybe try to make some crazy scenarios and see if it performs well, only then we can merge it safely.

**Comment by bgiesing** [comment]
@mfonville I can't think of much other scenarios. You either do a first upload or upload a new file. Both worked (in fact, since the all the apps are up to date, I added the last version of Inbox and and then updated to the latest.) I even tried a non Google app.

I think, we actually need more than just me (and you) testing. Calling all @opengapps/packagers!

**Comment by mfonville** [comment]
Well, what if you do some manual changes in the lib-folders for example. Or what if the sdk level has changed etc. That are really some cases to should be covered in that it doesn't do anything weird.

**Comment by mfonville** [comment]
I reckon we should also add the architecture to the commit message to make them readable on Twitter

**Comment by mfonville** [comment]
I updated the script again. It now asks before each commit, whether the commit should be added/created, and after each architecture has been processed, it will ask whether to push or not.

**Comment by bgiesing** [comment]
@mfonville I would make a slight alteration to the confirm steps to add `[Y/n]` like other confirm steps in linux commands.

**Comment by mfonville** [comment]
Ok, I have done that. I will now merge it into master, for everyone to use.

**Comment by mfonville** [comment]
I uploaded some Chrome versions today. That uploadscript was really a good idea, it makes it really a breeze to add these new APKs to the repo :-)

**Comment by bgiesing** [comment]
:D No problem!

On Sat, Aug 1, 2015, 3:17 AM mfonville <notifications@github.com> wrote:

> I uploaded some Chrome versions today. That uploadscript was really a good
> idea, it makes it really a breeze to add these new APKs to the repo :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opengapps/opengapps/issues/73#issuecomment-126882850>.
>



To unsubscribe click: <http://email.giesing.cf/u/eJwljrtuwkAQRb_GLtHOzD6LLUgikDBFIoRSRuPxLrYCNrIgCfn6rJxbnOZKR6eL1rJgPcTndXOf3OexopfQbyp8mg_fx2mk99-v7RaGh-WPH0OvQOXCQwFtdk0z7sf9W6XVhYfz6rRQpkvdR9EUkmEnXhybDNmiOGWcxhyssKvnOKfr-VFESjnvAjsUzdiSyZJbAGUsUPIC6IvG6JQTWdYIKqBk9T8A6LRGHwIy2CBJGSHoulySFv3qNNz6e7tE3WKF6z84PkVc>
