### ISSUE TITLE
Missing WearableManageSpaceActivity in GMS Core.

### ISSUE THREAD

**Issue by YandexStudio** [opengapps/opengapps#734]
exception ClassName:
android.content.ActivityNotFoundException
exception Message: Unable to find explicit activity class com.google.android.gms/com.google android.gms.wearable.ui.WearableManageSpaceActivity); have you declared this activity in your AndroidManifest.xml? throwFileName: Instrumentation. java
throwClassName: android app. Instrumentation
throwMethodName: checkStartActivityResult

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
