### ISSUE TITLE
Timeout on download

### ISSUE THREAD

**Issue by minhperry** [opengapps/opengapps#739]
When I download a version from either the website or github, the link always expire in 300 secs or 5 mins and I'll never be able to finish my download on my slow internet speed because of it. Please don't say me to upgrade my internet, I can't

**Comment by daman5202** [comment]
Thats not your Internet, thats the bad server. I have a 100Mbps connection and the speed of the opengapps file is 20-30kbps which also fails after 30MB, I have never been successful in downloading opengapps package. I don't know why don't they host the files somewhere else.

**Comment by thezeroth** [comment]
I am in US East coast with Gigabit optical connection,have the same problem, cant download any of their releases, with or without a download manager, 3 hours wasted, i am wondering how stupid is the person who doesn't allow torrent mirroring of these files.
