### ISSUE TITLE
Cleanup of local git repository

### ISSUE THREAD

**Issue by DJAlik** [opengapps/opengapps#74]
With daily apk changes my VM is crying for space. How do we reduce the size of opengapps/.git/modules/sources ? I am currently sitting at 6.1 gigs!

The opengapps/sources is only 3.7 gigs

**Comment by mfonville** [comment]
Run ```git gc``` to garbage collect your git repository.
Smaller than that, we won't be able to make it without losing history...

**Comment by mfonville** [comment]
Addendum: run the command within the repository of the submodules, so in sources/arm, sources/arm64 etc.

**Comment by DJAlik** [comment]
how much history do we need to keep on the APKs?

**Comment by mfonville** [comment]
All, for now at least.
I also did look into removing history, but it would be a enormous effort that would have to be well-coordinated (everybody would have to clear their own git repo at the same time, before pushing in new APKs).
So for now we will just keep going like this. If Google e.g. does change something again in how they handle APKs (like we had wit the DPIs), that would be a possible moment to revise our apk history.
Btw, it is actually nice I think, that we have so many versions of all APKs available, we might soon outgrow apkmirror ;-)

**Comment by DJAlik** [comment]
sidebar question. Do you know if there is a way to increase the size of my VM? I am using Virtualbox 5

**Comment by mfonville** [comment]
First resize the virtual disk of your VM via the windows commandline, then increase the size of the partition on the disk by booting of a virtual USB disk with gparted, then use resize2fs to enlarge the filesystem to the partitionsize. A good starting point: https://forums.virtualbox.org/viewtopic.php?f=35&t=50661
