### ISSUE TITLE
Gapps 5.1 full not available doesn't build

### ISSUE THREAD

**Issue by callihn** [opengapps/opengapps#741]
ARM 5.1 full is not available and hasn't built in over a year now. Although one can easily cope with this by adding FullGApps in .gapps-config it is wasting some bandwidth on both ends and storage space on the user end. In any case if this is intentional please say so and if so it might make sense to remove the option from the download page.

**Comment by darkmorpher** [comment]
Please close. Last checked, new builds are pushed.

**Comment by callihn** [comment]
How many years ago was that?
No FULL build for 5.1. has shown up for diwnload on opengapps.org for at
least a year.

This screenshot is from today!

**Comment by Mattwmaster58** [comment]
The amount of people using Android 5.1 and using OpenGapps.org is a very small subset of people. It's likely that this is the reason builds haven't been made recently. It's likely not worth the maintenance burden.

**Comment by callihn** [comment]
Where are you getting these statistics? Considering the issues/greater
risks with root carrying forward from 5.1 and the smaller number of devices
that can even be attempted due to locked boot loaders, the opengapps build
process being automated and that 5.1 is available just not in full I have
doubts on that one.

**Comment by nezorflame** [comment]
Website doesn't change package selection, it simply greys out the unavailable options.
E.g. we only build `pico`, `nano`, `stock`, `tvstock` and `aroma` for every architecture for Android 5.1, hence why other options are greyed out.

**Comment by nezorflame** [comment]
You can check the `LATEST.json` file in the respective repo to see which variants are being built for every Android version.
For example, for ARM: https://github.com/opengapps/arm/blob/master/LATEST.json

**Comment by nezorflame** [comment]
As for the "why" it was removed - I don't know, probably due to previous bandwidth  issues with Github. @NicholasBuse @mfonville do you remember the reason?

**Comment by callihn** [comment]
Hence "doesn't build".
So you're saying the build was disabled on purpose? If so why not just drop
all full builds since it's obviously not going to be something we can
depend on in the future?

Full and stock are the only ones worth building for most people I'd venture
to guess since all others remove any apps not installed by them. While
stock obviously is more if a waste since very few phones use that. Better
option would be a package that just installs play services since that's the
only app that can't be moved to the system after upgrading with numerous
available apps that do so (link2sd, titanium, etc.).

Really not much thought process going on with this project.

**Comment by nezorflame** [comment]
You're wrong in assumption `Full and stock are the only ones worth building for most people`. Take a look, for example, at one of the recent ARM64 releases here: https://sourceforge.net/projects/opengapps/files/arm64/20191123/
Android 9.0 has all of the packages being built for it, and `full` is the **least** downloaded package (except for `tvstock` which is a special snowflake and can be ignored).

**Comment by nezorflame** [comment]
> So you're saying the build was disabled on purpose? If so why not just drop
all full builds since it's obviously not going to be something we can
depend on in the future
I personally agree that this list should be reviewed and changed since we've moved to the SourceForge as a hosting, but that's up to @mfonville.

> Better option would be a package that just installs play services since that's the only app that can't be moved to the system after upgrading with numerous available apps that do so
1. There's already `pico` package with the same purpose
2. In modern Android versions people don't usually move apps to `/system` since we have systemless solutions (Magisk) which don't break SafetyNet, and the general trend is to avoid touching the `/system` at all.

> Really not much thought process going on with this project.
The main "thought" process and logic was mostly done by the team a few years ago.
Nowadays we're only trying to resolve bugs and prepare for new Android releases since we can't commit as much time as we were able to previously.
While it's not a contemporary solution and we're not very active, this project still works for us and a few hundred thousand people per month.
In any case, we can't please everyone. If you think that this project doesn't satisfy your needs and you don't like it, feel free to pick some other solution that works for you. Or make your own.

**Comment by callihn** [comment]
No because you're forgetting all of this requires root, thus I can easily
uninstall any gapps I don't want and install any I do want using the
playstore and move them or their updates to the system or not, I really
don't need a package like nano or pico to do that, though granted the
automation of the script may make it faster there is to my knowledge no way
to prevent those packages from uninstalling all other gapps installed. As
for full and stock they are pretty self explanatory and as far as I know
only Google's phones ship with stock. I only use gapps for updating play
services really as everything else can be managed with other apps that can
move the updates to the system, but they can not move play services
correctly since it involves other files. I can of course use stock and set
it to full but that's really wasting bandwidth since I'm not needing it all
but there's a good chance that's what many are doing because they have seen
that they can not rely on the full build as evidenced by 5.1. That being
said you can buy a new phone or tablet today from major retailers that are
running 5.1 so it's going to be awhile before it dies and again with things
like forced encrypting, dm-verity and many locked boot loaders with never
devices not to mention the severe lag time with cwm and twrp these devices
are a more sure bet for those needing root.

**Comment by callihn** [comment]
And if course safetynet, lets not forget that major pita. Pico will
uninstall all gapps that pico does not contain which makes it pointless for
updating/upgrading play services because it removes all of your already
installed and updated gapps.
