### ISSUE TITLE
Android Auto Connectivity Broken

### ISSUE THREAD

**Issue by Alex9001** [opengapps/opengapps#742]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [X] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [X] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [X] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aissue)

*If Open GApps installation fails:*
- [X] Is the issue reproducible using the latest version of your recovery?
- [X] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

*If receiving force closures after Open GApps installation:*
- [X] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [X] The issue is reproducible on clean (=wiped ``/data/`` partition) installation
- [X] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [X] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**
When I plug my phone into my car's Android Auto dash it doesn't work and says "Please unplug, wait a moment and re-plug your device." Running LineageOS 16 for Payton and opengapps (latest builds). Works fine with a rooted stock build.

**Reproduction Steps:**

1. Install lineage + twrp + opengapps
2. Boot phone, complete setup, install Android Auto and Google Maps
3. Connect phone to automobile with wire
4. Android Auto crashes

**Expected behavior:**

Connecting phone to car's dashboard should launch android auto instead of an error.

**Observed behavior:**

Android Auto won't work with OpenGApps and MindTheGApps regardless of what rom is used (I've tested Oreo and Pie roms). It will work just fine with stock device builds. It is not  because the cable is bad. Android Auto application launches just fine on the device, but it does not work tethered to an automobile's dashboard.

[2019-05-26-21-02-00.zip](https://github.com/opengapps/opengapps/files/3235084/2019-05-26-21-02-00.zip)

**Comment by pascalwhoop** [comment]
What version of the app are you using? I've got a Xiaomi mi 8 with 4.7.59... of Android Auto and I can open it and use it, however my display turns black when disconnecting and stays that way. Ppl on Reddit are reporting similar issues [here](https://www.reddit.com/r/AndroidAuto/comments/9r5jeu/screen_flickering/).

I'll try what happens when I set a timer with Tasker to kill the Android auto app as it may force my display to be off while driving or something and then that service doesn't get killed. Will report back

**Comment by Alex9001** [comment]
This was done with the version of gapps was latest on May 29, and those preceding it.

As explained in OP Android Auto never works. 

Quoted from linked reddit post "Android Auto keeps working".

These are two separate issues.

Further addendum to OP:

I believe this may be a device specific issue for Moto X4

**Comment by wsmithjr1** [comment]
I don't know that this is a gapps issue, I think this is a LineageOS issue on the x4. I cannot enable the file transfer mode for the USB interface, which seems to be required. I have an identical x4 that's stock, and it works fine.

**Comment by skythian** [comment]
Same issue with LOS 17 and One Plus 7 Pro.

**Comment by lubica81** [comment]
Same issue on my Samsung J4+. Any news to fix this problem?

**Comment by Mr-Dilkington** [comment]
Still an issue.  Here are my observations on this using different phones with stock/LineageOS:

Mi A1  - Official LineageOS 16 - Doesn't work.  I can't even force the phone to use USB tethering.  Worked fine until a LineageOS update back in Oct/Nov (can't recall the one that broke it).
Mi A1 - Stock - Works.
Umidigi F1 Play - Eragon v1 - Works.
Umidigi F1 Play - LineageOS 17.x GSI - Doesn't work.  Plugging phone into head unit literally crashes the phone and forces reboot.
Umidigi F1 Play - AOSP Quack Phh-Treble  - Doesn't work.  Plugging in phone doesn't result in crash but head unit doesn't react to phone being plugged in.
LG V20 US996 - Unofficial Lineage 16 - Works!  This one surprised me.  Tested it just now.

**Comment by Alex9001** [comment]
Also didn't work with unofficial LOS 17 for pixel 3a "sargo"

**Comment by ffaauusstt** [comment]
Not working on LOS 16 official on Xiaomi A1, on crDroid 5 (all of them are using latest opengapps nano).

**Comment by Mr-Dilkington** [comment]
I also tested again today on Umidigi F1 Play using the latest version of the LineageOS 17 GSI and FlameGApps.  Same problem.  Android Auto causes the entire phone to lock up and reboots.

**Comment by aenertia** [comment]
Confirm - blank screen on head unit on Mitsubishi Outlander 2020 model and Oneplus5 running lineage 17 .Was working fine on Lineage16 and same device combination. Now I get a hard lock up on the phone requiring a reset (still some vibration responses from nav keys in crashed state).

Using gapps nano from this week (January update) from the opengapps site.

**Comment by mgclabs** [comment]
Same Issue - LG v20 H990DS LineageOS 17.1 Nano Gapps

**Comment by SoHardToFindAFreeUsername** [comment]
Hi,

My issue seems to be the same : Android Auto error message : " Android auto requires one or more Google Play services that are not currently available. Please contact the developer for assistance. "
![image](https://user-images.githubusercontent.com/61167032/74689066-095c8480-51da-11ea-9fa8-f4178e315b26.png)
Not working because of OpenGapps. 
With MindTheGApps (I know that is an old version : MindTheGapps-8.1.0-arm-20180808_153837) Android Auto is working well. But with OpenGApps recent download (open_gapps-arm-8.1-pico-20200212 or open_gapps-arm-8.1-stock-20200212) AA never launch.

(But with MindTheGapps : Netflix couldn't be installed).

Does anybody have advice to fix AA with OpenGApps ?

Bye

**Comment by nobl** [comment]
Same issue here. First with crdroid and it worked well (even better than crdroid) on pixelexperience (februar build) but latest build broke it now.

**Comment by jslawler** [comment]
Hi,

I'm also experiencing this issue. Logs can be found on [this LOS 17.1 GitLab issue](https://gitlab.com/LineageOS/issues/android/-/issues/1759).

**Comment by alishchytovych** [comment]
The same here - Android Auto works fine on the phone but does not work with car radio. (Samsung S8, LineageOS 17.1, GApps stock)
Please fix.

**Comment by voldor** [comment]
Same here with a Galaxy s8+ with Lineage OS 17.1 (july 15th update)
ans Open gapps micro

**Comment by hkalman** [comment]
I have the same issue with SakuraProject where I've got this answer: https://github.com/ProjectSakura/Bug_Tracker/issues/5

**Comment by umute97** [comment]
Same here (HavocOS 3.9, dreamlte)

**Comment by m0ddixx** [comment]
I got issues on Android 11 with Android Auto installed from Playstore with OpenGapps Nano.
I think the way permissions are accquired in later Android versions are requiring some settings in either packages.xml
or i need to manually flash it as priv-app or something. But whenever i manually edit these files, they get resetted.

`[11-13 15:03:12.273 12148:12148 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: com.google.android.projection.gearhead:car, PID: 12148
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.projection.gearhead/com.google.android.apps.auto.carservice.gmscorecompat.FirstActivityImpl}: java.lang.SecurityException: Neither user 10299 nor current process has android.permission.MANAGE_USB.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.SecurityException: Neither user 10299 nor current process has android.permission.MANAGE_USB.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.hardware.usb.IUsbManager$Stub$Proxy.getPorts(IUsbManager.java:1706)
	at android.hardware.usb.UsbManager.getPorts(UsbManager.java:875)
	at com.google.android.gms.car.usb.SystemUsbStatusProvider.a(SourceFile:4)
	at knu.a(SourceFile:9)
	at knu.a(SourceFile:51)
	at kmu.a(SourceFile:31)
	at com.google.android.gms.carsetup.FirstActivityImpl.onCreate(SourceFile:89)
	at android.app.Activity.performCreate(Activity.java:8000)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
	... 11 more
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:2018)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2046)
	at com.android.server.usb.UsbService.getPorts(UsbService.java:655)
	at android.hardware.usb.IUsbManager$Stub.onTransact(IUsbManager.java:828)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
`

**Comment by Cysioland** [comment]
Got this error on `stock` arm64 GApps from 5 December 2020.

```
12-05 22:43:43.623 19267 19291 E GmsClient: unable to connect to service: com.google.android.gms.car.service.START on com.google.android.gms
12-05 22:43:43.630 19267 19287 E GH.CAR  : getCarService failed
12-05 22:43:43.630 19267 19287 E GH.CAR  : java.lang.IllegalStateException: Failed to get the delegate car service.
12-05 22:43:43.630 19267 19287 E GH.CAR  : 	at byn.k(SourceFile:25)
12-05 22:43:43.630 19267 19287 E GH.CAR  : 	at cco.k(SourceFile:2)
12-05 22:43:43.630 19267 19287 E GH.CAR  : 	at cbr.a(Unknown Source:5)
12-05 22:43:43.630 19267 19287 E GH.CAR  : 	at com.google.android.apps.auto.carservice.service.impl.GearheadCarStartupService.e(SourceFile:1)
12-05 22:43:43.630 19267 19287 E GH.CAR  : 	at cco.j(SourceFile:2)
12-05 22:43:43.630 19267 19287 E GH.CAR  : 	at com.google.android.gms.car.startup.IStartup$Stub.dispatchTransaction(SourceFile:69)
12-05 22:43:43.630 19267 19287 E GH.CAR  : 	at brw.onTransact(SourceFile:2)
12-05 22:43:43.630 19267 19287 E GH.CAR  : 	at android.os.Binder.execTransactInternal(Binder.java:1021)
12-05 22:43:43.630 19267 19287 E GH.CAR  : 	at android.os.Binder.execTransact(Binder.java:994)
12-05 22:43:43.630 19267 19287 E GH.CAR  : Caused by: com.google.android.gms.common.api.ApiException: 17: API: Car.API is not available on this device. Connection failed with: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
12-05 22:43:43.630 19267 19287 E GH.CAR  : 	at lpm.c(SourceFile:1)
12-05 22:43:43.630 19267 19287 E GH.CAR  : 	at com.google.android.gms.common.api.internal.GoogleApiManager$ClientConnection.s(SourceFile:7)
12-05 22:43:43.630 19267 19287 E GH.CAR  : 	at com.google.android.gms.common.api.internal.GoogleApiManager$ClientConnection.k(SourceFile:2)
12-05 22:43:43.630 19267 19287 E GH.CAR  : 	at com.google.android.gms.common.api.internal.GoogleApiManager$ClientConnection.f(SourceFile:21)
12-05 22:43:43.630 19267 19287 E GH.CAR  : 	at com.google.android.gms.common.api.internal.GoogleApiManager$ClientConnection.dM(SourceFile:1)
12-05 22:43:43.630 19267 19287 E GH.CAR  : 	at lqw.run(SourceFile:10)
12-05 22:43:43.630 19267 19287 E GH.CAR  : 	at android.os.Handler.handleCallback(Handler.java:883)
12-05 22:43:43.630 19267 19287 E GH.CAR  : 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-05 22:43:43.630 19267 19287 E GH.CAR  : 	at android.os.Looper.loop(Looper.java:214)
12-05 22:43:43.630 19267 19287 E GH.CAR  : 	at android.os.HandlerThread.run(HandlerThread.java:67)
12-05 22:43:43.631 19267 19481 E GH.CAR  : getCarService failed
12-05 22:43:43.631 19267 19481 E GH.CAR  : java.lang.IllegalStateException: Failed to get the delegate car service.
12-05 22:43:43.631 19267 19481 E GH.CAR  : 	at byn.k(SourceFile:25)
12-05 22:43:43.631 19267 19481 E GH.CAR  : 	at cco.k(SourceFile:2)
12-05 22:43:43.631 19267 19481 E GH.CAR  : 	at cbr.a(Unknown Source:5)
12-05 22:43:43.631 19267 19481 E GH.CAR  : 	at com.google.android.apps.auto.carservice.service.impl.GearheadCarStartupService.e(SourceFile:1)
12-05 22:43:43.631 19267 19481 E GH.CAR  : 	at cco.j(SourceFile:2)
12-05 22:43:43.631 19267 19481 E GH.CAR  : 	at com.google.android.gms.car.startup.IStartup$Stub.dispatchTransaction(SourceFile:69)
12-05 22:43:43.631 19267 19481 E GH.CAR  : 	at brw.onTransact(SourceFile:2)
12-05 22:43:43.631 19267 19481 E GH.CAR  : 	at android.os.Binder.execTransactInternal(Binder.java:1021)
12-05 22:43:43.631 19267 19481 E GH.CAR  : 	at android.os.Binder.execTransact(Binder.java:994)
12-05 22:43:43.631 19267 19481 E GH.CAR  : Caused by: com.google.android.gms.common.api.ApiException: 17: API: Car.API is not available on this device. Connection failed with: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
12-05 22:43:43.631 19267 19481 E GH.CAR  : 	at lpm.c(SourceFile:1)
12-05 22:43:43.631 19267 19481 E GH.CAR  : 	at com.google.android.gms.common.api.internal.GoogleApiManager$ClientConnection.s(SourceFile:7)
12-05 22:43:43.631 19267 19481 E GH.CAR  : 	at com.google.android.gms.common.api.internal.GoogleApiManager$ClientConnection.k(SourceFile:2)
12-05 22:43:43.631 19267 19481 E GH.CAR  : 	at com.google.android.gms.common.api.internal.GoogleApiManager$ClientConnection.f(SourceFile:21)
12-05 22:43:43.631 19267 19481 E GH.CAR  : 	at com.google.android.gms.common.api.internal.GoogleApiManager$ClientConnection.dM(SourceFile:1)
12-05 22:43:43.631 19267 19481 E GH.CAR  : 	at lqw.run(SourceFile:10)
12-05 22:43:43.631 19267 19481 E GH.CAR  : 	at android.os.Handler.handleCallback(Handler.java:883)
12-05 22:43:43.631 19267 19481 E GH.CAR  : 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-05 22:43:43.631 19267 19481 E GH.CAR  : 	at android.os.Looper.loop(Looper.java:214)
12-05 22:43:43.631 19267 19481 E GH.CAR  : 	at android.os.HandlerThread.run(HandlerThread.java:67)
12-05 22:43:43.644 19267 19291 E GmsClient: unable to connect to service: com.google.android.gms.car.service.START on com.google.android.gms
```

**Comment by epsilontheta** [comment]
Installed newest LOS 17.1 and newest OpenGapps (open_gapps-arm64-10.0-nano-20201205.zip). Same issue.

**Comment by huw0** [comment]
From the linked issue by @m0ddixx it seems that the MANAGE_USB permission is missing, at least on my device.
I found [this](https://forum.xda-developers.com/t/gapps-daily-open-gapps-for-android-all-android-versions-devices.3098071/post-83971915) XDA post, which suggested moving the app to priv-apps combined with a permissions file may help.

I now longer get a blank screen in the car, but do know get a big red Android error screen. Communications Error.....

**Comment by epsilontheta** [comment]
I could solve it by reinstalling the Android Auto app in the play store.
Can you verify if that also works for you?

**Comment by Cysioland** [comment]
It fixed itself when Google pushed a Google Play Services update.

**Comment by huw0** [comment]
I'm still seeing a Communications Error screen.

In my case the OpenGApps version used originally did not include Android Auto. I've used magisk systemizer to make it a system app but potentially this is not enough.

If it was broken but is now broken please can you confirm...

* Android Version
* Android Auto Version
* System app status of android auto
* Play Services Version
* OpenGapps Version

**Comment by osm0sis** [comment]
That permission is present already: https://gitlab.opengapps.org/opengapps/all/-/blob/master/etc/permissions/privapp-permissions-google.xml#L679

**Comment by epsilontheta** [comment]
Broken again after upgrading to LOS 18.1 and `open_gapps-arm64-11.0-nano-20210712.zip`. Tried to fix by installing `open_gapps-arm64-11.0-nano-20210713.zip`, but no improvement.

**Comment by bananafunction** [comment]
> 
> 
> Broken again after upgrading to LOS 18.1 and `open_gapps-arm64-11.0-nano-20210712.zip`. Tried to fix by installing `open_gapps-arm64-11.0-nano-20210713.zip`, but no improvement.

I am running an unofficial LOS 18.1 on my Sony Xperia XZ1 compact with `open_gapps-arm64-11.0-nano-20210713.zip` flashed and for me, on my ROM, AndroidAuto is also broken. Not sure whether it is a problem of my device tree, LOS 18.1 or even a combination. I will upload logs later this day :-)

**Comment by rks-technik** [comment]
same here. LOS 18.1 and open_gapps-arm64-11.0-pico-20210724.zip on my 8t.
on the phone AA is working on with usb i get a black screen or an error that there is an app missing

**Comment by Kampfwurst** [comment]
same here. LOS 18.1 and open_gapps-arm64-11.0-pico-20210724.zip on my 8t.
on the phone AA is working on with usb i get a black screen or an error that there is an app missing

**Comment by mbo99** [comment]
I make a try, when install AndroidAutoStubPrebuilt.apk as system priv app Android auto works fine.
First I remove /system/app/AndroidAutoPrebuiltStub/AndroidAutoStubPrebuilt.apk
Then I use systemizer module from Magsik to install AndroidAutoStubPrebuilt.apk as priv-app. 
Last step is to update Android Auto from play store. 

So it should work, when AndroidAutoStubPrebuilt.apk is packed to priv-app.
