### ISSUE TITLE
Photos installs to wrong directory.

### ISSUE THREAD

**Issue by callihn** [opengapps/opengapps#743]
ARM 5.1 Stock
Possibly others will have this issue.

Photos is being installed to /system/app where it will not run from. Tested with todays OpenGapps and latest version of Photos. Photos will run from /system/priv-app and /data/app just fine as tested but regardless of how it gets installed to /system/app it will not run from that location so the install script needs this changed. Something has changed resently as this has not been an issue before, so either Photos has changed in some way to cause this or the install script has changed in OpenGaps.

**Comment by megapro17** [comment]
Also have this problem on arm64 9.0... no one fixing problems here, opengapps is dead

**Comment by callihn** [comment]
Apparently.

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.

**Comment by megapro17** [comment]
Purging issues instead of fixing

**Comment by osm0sis** [comment]
You're welcome to make a Pull Request any time, smart guy.
