### ISSUE TITLE
Suggestion: Config option to override device architecture check

### ISSUE THREAD

**Issue by Mattwmaster58** [opengapps/opengapps#745]
With some devices like the Redmi Note 7 (lavender), custom ROMs seem to be ARM64 based, while the stock ROM is ARM based. For that reason, only specially modified (ie, the installer script's device architecture check is bypassed) gapps packages (usually created by the ROM creator) can be installed, which means that the choices for gapps packages are limited by what the ROM creator feels like modifying and are usually out of date.

Related to #738

**Comment by osm0sis** [comment]
Smarter would be fixing it to detect the architecture of the currently installed ROM rather than what TWRP reports.

**Comment by osm0sis** [comment]
Better yet, it might already be fixed. Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
