### ISSUE TITLE
Wear OS is stuck.

### ISSUE THREAD

**Issue by ImNotDeadNoMore** [opengapps/opengapps#746]
I have a LG G3 with Lineage OS installed. I installed the Nano OpenGapps Zip. No Matter what I try Wear OS will not get past the splash screen/logo. It seems like it needs something more from Google Play Services to open fully.

**Comment by lazerl0rd** [comment]
@ImNotDeadNoMore did you find a solution to your problem?

**Comment by awb95** [comment]
I had d same issue - Installed Lineage OS, OpenGapps and Magisk. Alle Google Apps worked well but Wear OS wich got installed through PlayStore Stuck on Splash Screen.
I could fix it for me through downloading and installing the latest Google Play Services apk from Apkmirror.

**Comment by livagit** [comment]
Please look here 
https://forum.xda-developers.com/t/rom-official-lineageos-17-1-weeklies-for-xiaomi-mi-mix-2s.3974661/post-84541185

**Comment by rk-zero** [comment]
You need the Google App from Playstore, thats usually missing in Pico/Nano.  https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox

**Comment by kdvalin** [comment]
I am having the same issue, tried numerous things, none of the following have worked:
- Different variants
    - Nano
    - Micro
    - Mini
    - Full
-  Cleared cache in
    - Google App
    - Wear OS App
    - Google Play Services
- Re-flashed LineageOS

Have no idea where to go from here..
<details><summary>Full Details</summary>

- Phone: Moto X4 (payton)
- ROM: Lineage OS 17.1 2021/02/23
- Relevant App Versions:
    - Google App: 12.4.9.29
    - Google Play Services: 21.02.14
    - Wear OS App: 2.44.0.353846678
</details>

**Comment by livagit** [comment]
https://github.com/opengapps/opengapps/issues/910#issue-814024369

**Comment by rk-zero** [comment]
@kdvalin reset your watch. When prompted for connection pair the watch over bluetooth settings, not the wear os app.
When you do that a notification will pop up prompting you to setup a near device. click it, it skips the hanging splash screen. After setup of watch wear os app will work normally (you still need google search app and play services).
