### ISSUE TITLE
Core GApps Explanation

### ISSUE THREAD

**Issue by jslawler** [opengapps/opengapps#747]
Hi guys,

This isn't a demand by any means, it's more a fishing request for information I can't find too much about online pertaining to the Open GApps Project.

A few of these core GApps I don't personally require, such as the ones relating to backup. I'm fine with removing these from the script.

What I was wondering was whether anyone has any insight into what each core GApp does or relates too in the most vague of terms and whether you think it is required.
Any information helps.

```
defaultetc #Permissions for Open GApps

defaultframework #Maps/Media effects framework/permissions

googlebackuptransport #Google backup sync service (Required for Google Backup)

googlecontactssync #Google contracts sync service (Required for Google Contact sync)

googlefeedback #Google Analytics for crashes (Is this required for anything but reporting crashes to Google?)

googleonetimeinitializer #Google setup upon first boot (Not required if you plan on setting up device via settings)

googlepartnersetup #Links GApps to other GApps, e.g. GCal > Gmail integration (Unknown to what extent this is used)

gmscore #Google Mobile Services core (Basically required for anything Google AFAIK)

gsfcore  #Google Services Framework. Helper utility that interacts with GmsCore. (How deep the integration with GmsCore and it's necessity is unknown to me)

vending #PlayStore (Required if you use the PlayStore)

setupwizarddefault #Google account setup wizard for mobile (Required if you use a Google account on a mobile)

setupwizardtablet #Google account setup wizard for mobile  (Required if you use a Google account on a tablet)

configupdater #(Unknown what use this has)

extservicesgoogle #(Unknown what use this has but is required to boot)

extsharedgoogle #(Unknown what use this has but is required to boot)

carriersetup #(Unknown what use this has)

gmssetup #Google Mobile Services setup (Unknown what use this has)

backuprestore #Restores Google backup (Not required if you don't use Google Backup services)

soundpicker #Google sound settings (Not required if your own device has sound settings I imagine)
```

**Comment by lbdroid** [comment]
If I'm not mistaken, "core" refers to those that are not possible to install from playstore.

**Comment by jslawler** [comment]
> If I'm not mistaken, "core" refers to those that are not possible to install from playstore.

Well that would make a lot more sense as opposed to core meaning "not operable without".

I was able to get Google's basic services operable with just 3 of the selections.

Thanks for the information.

**Comment by Ks89** [comment]
Also, does "core" add play services by default?
Is there a way to install gapps without play services and then install play services from apk manually?

**Comment by darkmorpher** [comment]
So you want MicroG?

**Comment by Ks89** [comment]
@darkmorphes yes without play services.

**Comment by jslawler** [comment]
@ks89 - You can use Aurora/Yalp store to access the Play Store apps, however without a Google drop-in replacement such as microG, you won't be able to use most of them.
The Play Store also cannot be used without Play Services, unless using such a drop-in replacement like microG - Unless using shadow53's version which MAY work, however you'd still run into the no Play Services issue.

**Comment by Ks89** [comment]
Is it possible to install play service as an apk after installing microG without issues?

**Comment by jslawler** [comment]
> Is it possible to install play service as an apk after installing microG without issues?

I recommend reading up about microG.

microG isn't a replacement for GApps, it's essentially a range of libraries and utilities to act in the place for some of the background Google services required to run a GApp system.
If you were to install Google Play Services after installing microG, you'd simply have a Google system again, negating the use for microG all together.

What are you trying to achieve exactly, then we might be able to assist you further.

**Comment by Ks89** [comment]
Last year I had some experiments on a older android device with the latest linageOS Rom. However I didn't downgrade play services to the versione that I wanted because it was not possible uninstalling updates of that app. So I thought if there was a solution to install the Rom without play services and installing it next via apk downloaded from the Web.
It was only for research, not for a real use case. 

When I saw this issue I thought to try to ask it.

**Comment by Rupurudu** [comment]
#821 moves soundpicker out of Core to GApps, you can remove it if you want.
