### ISSUE TITLE
Dialer doesn't have correct permission

### ISSUE THREAD

**Issue by Crescendo-BLYAT** [opengapps/opengapps#748]
It lacked this 2 permissions that will make the phone bootlooped.

**android.permission.CONNECTIVITY_USE_RESTRICTED_NETWORKS, android.permission.READ_PRIVILEGED_PHONE_STATE**

Logcat:
06-09 12:11:33.901   956   956 E AndroidRuntime: java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.google.android.dialer: android.permission.CONNECTIVITY_USE_RESTRICTED_NETWORKS, com.google.android.dialer: android.permission.READ_PRIVILEGED_PHONE_STATE}

**Comment by Crescendo-BLYAT** [comment]
https://github.com/opengapps/opengapps/issues/674

**Comment by NicholasBuse** [comment]
https://gitlab.nezorfla.me/opengapps/all/commit/c0219c58ebca10a4d1cc3a87320ddf7c7619df9f

(NOTE: our gitlab is not showing diffs of the file properly, but the two permissions were added)

**Comment by Crescendo-BLYAT** [comment]
@NicholasBuse  still missing this: android.permission.READ_PRIVILEGED_PHONE_STATE

**Comment by NicholasBuse** [comment]
Sorry about that, must have got distracted yesterday...

https://gitlab.nezorfla.me/opengapps/all/commit/d9eda0df5484a47a5b0cc28021c165e2f9431cf4

**Comment by Crescendo-BLYAT** [comment]
it's OK... thanks for fixing this one...

it's preventing boot when secure startup is used...

**Comment by Crescendo-BLYAT** [comment]
@NicholasBuse and you doubled those permission... lol...

```xml
    <privapp-permissions package="com.google.android.dialer">
        <permission name="android.permission.ALLOW_ANY_CODEC_FOR_PLAYBACK"/>
        <permission name="android.permission.CAPTURE_AUDIO_OUTPUT"/>
        **<permission name="android.permission.CONNECTIVITY_USE_RESTRICTED_NETWORKS"/>**
        <permission name="android.permission.CONTROL_INCALL_EXPERIENCE"/>
        <permission name="android.permission.GET_ACCOUNTS_PRIVILEGED"/>
        <permission name="android.permission.INTERACT_ACROSS_USERS"/>
        <permission name="android.permission.MODIFY_AUDIO_ROUTING"/>
        <permission name="android.permission.MODIFY_PHONE_STATE"/>
        **<permission name="android.permission.CONNECTIVITY_USE_RESTRICTED_NETWORKS"/>**
        <permission name="android.permission.READ_PRIVILEGED_PHONE_STATE"/>
        <permission name="android.permission.REGISTER_CONNECTION_MANAGER"/>
        <permission name="android.permission.STATUS_BAR"/>
        <permission name="android.permission.STOP_APP_SWITCHES"/>
        <permission name="com.android.voicemail.permission.READ_VOICEMAIL"/>
        <permission name="com.android.voicemail.permission.WRITE_VOICEMAIL"/>
    </privapp-permissions>
```

**Comment by curiousrom** [comment]
> Sorry about that, must have got distracted yesterday...
> https://gitlab.nezorfla.me/opengapps/all/commit/d9eda0df5484a47a5b0cc28021c165e2f9431cf4

When I try to follow that link on Windows 10 & Edge I get:

> This site is not secure
> 
> This might mean that someone’s trying to fool you or steal any info you send to the server. You should close this site immediately.
> 
> Details 
> The hostname in the website’s security certificate differs from the website you are trying to visit.
> Error Code: DLG_FLAGS_SEC_CERT_CN_INVALID
> 
> Because this site uses HTTP Strict Transport Security, you can’t continue to this site at this time.

**Comment by NicholasBuse** [comment]
Server updated. Replace nezorflame.me with opengapps.org

**Comment by curiousrom** [comment]
> Server updated. Replace nezorflame.me with opengapps.org

@NicholasBuse - Now when trying the link you edited above: https://gitlab.opengapps.org/opengapps/all/commit/d9eda0df5484a47a5b0cc28021c165e2f9431cf4

I get:

>  404 
> Git Resource Not found

The reason I was trying to see that permission fix commit is all the users reporting failing to boot with Open GApps built 2019-09, 10, 11, 12 & probably 13 here in the [XDA Open GApps thread](https://forum.xda-developers.com/android/software/pa-gapps-continuation-t3098071/page624)

XDA user modpunk posted [here](https://forum.xda-developers.com/showpost.php?p=80488715&postcount=6246) the probable privapp-permissions-google.xml bug & proposed a solution.
