### ISSUE TITLE
Invalid Signature for Google Play Services

### ISSUE THREAD

**Issue by 8monochrome** [opengapps/opengapps#752]
**Issue description:**

After installation, google play services detected as not installed. Logcat shows Google Play Services invalid signature. 
Same goes for Play Store, Google contact sync, Google calendar sync etc.

Used APK-Info v1.33 to review PreBuiltCoreGMSPi.apk from latest gapps (nodpi) vs the one from apkmirror - Opengapps one indicates Signature does not verify. Apkmirror one is fine.

**Reproduction Steps:**

1. Flash Rom (I used https://sourceforge.net/projects/havoc-os/files/enchilada/Havoc-OS-v2.6-20190623-enchilada-Official.zip/download)
2. Flash TWRP 
3. Reboot Recovery
4. Flash Gapps
5. Flash magisk v19.3
6. Reboot

**Expected behavior:**

Google play services not installed. Eg unable to verify safetynet check in magisk manager - Prompt to show google play services not supported

**Comment by 8monochrome** [comment]
https://imgur.com/a/TzIOfWO

Screenshots

**Comment by alexa-v2** [comment]
All signatures will pass using v1 verification, I believe it says that that v2 and beyond won't pass any other

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
