### ISSUE TITLE
Support flashable-zip_microG

### ISSUE THREAD

**Issue by zaoqi** [opengapps/opengapps#753]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

**Issue description:**

Add support for https://github.com/WeAreFairphone/flashable-zip_microG
https://github.com/opengapps/opengapps/issues/215

**Comment by darkmorpher** [comment]
MicroG is a different project. Do you mean opengapps micro package?
