### ISSUE TITLE
Some improvement suggestions to stock package.

### ISSUE THREAD

**Issue by Crescendo-BLYAT** [opengapps/opengapps#754]
Please include Action Services, ARcore, & Lens in stock package as its working perfectly.
If possible, remove any other launchers (like LOS' Trebuchet) on stock installation.

Also enable **quickstep** for Pixel Launcher by default.

**Comment by darkmorpher** [comment]
[Action Services are only part of super and aroma packages.](https://github.com/opengapps/opengapps/wiki/Package-Comparison)
The new Lens is part of Google Assistant feature.
ARcore is device specific and will take major install-script rewrite to detect correct supported device.

**Comment by Crescendo-BLYAT** [comment]
> [Action Services are only part of super and aroma packages.](https://github.com/opengapps/opengapps/wiki/Package-Comparison)
> The new Lens is part of Google Assistant feature.
> ARcore is device specific and will take major install-script rewrite to detect correct supported device.

As for **Action Services** - I suggest to move it to Stock as Pixel stock got it pre-installed already.

As for **ARcore** -  It includes **all the Google Apps that come standard** on the latest Nexus (now Pixel) Phone. Make it so.

As for LOS default Dialer & Trebuchet, remove it automatically when installing Stock.
Set the Pixel Launcher as the default QuickStep recent provider. 
People installing this stock package already knows what to expect anyway.

@NicholasBuse  Please comment on this. Thank you.

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
