### ISSUE TITLE
Can I install Open gApps file to a MediaTek phone by using ADB Fastboot?

### ISSUE THREAD

**Issue by thewebinarts** [opengapps/opengapps#756]
Hello everyone,

I have a Infinix Smart 2 X5515, I actually download the Open gApps file mini.
Could I install it with the ADB Fastboot from my MacBook Pro?

If yes, what is the proccess? Becuse actually my phone does not start until the main menu.
When the logo Infinix displays, he restart again.

Best regards,
Arnold K.

**Comment by nezorflame** [comment]
No, you're gonna need a custom recovery for that. Go to XDA Forums for your device (or general forum for Mediatek devices) and ask around.

@mfonville this can be closed.
