### ISSUE TITLE
7/23 and 7/24 builds fail to install

### ISSUE THREAD

**Issue by DJAlik** [opengapps/opengapps#76]
Getting the following error when tried to install my own 7/23 built (built around 8pm CST) and same error with just downloaded 7/24 built from the opengapps site:

E:Error executing updater binary in zip '/external_sd/open_gapps-arm-5.1-stock-20150724.zip'

No opengapps log written

**Comment by DJAlik** [comment]
![screenshot_2015-07-24-00-47-34 1](https://cloud.githubusercontent.com/assets/12225343/8868428/e61b38ec-319d-11e5-81c7-8b1693d2b355.png)

**Comment by mfonville** [comment]
I can reproduce it here too, I removed the releases of 24th till we sort out this issue.

**Comment by mfonville** [comment]
I fixed it, the ASCII art was evil, and the ui_print implementation in update-binary was not nice.
