### ISSUE TITLE
Gitlab Sync Problem

### ISSUE THREAD

**Issue by alviteri** [opengapps/opengapps#760]
Since some days there is not possibility to sync gitlab sources 

fatal: unable to access 'https://gitlab.nezorfla.me/opengapps/all/': SSL: cer
tificate subject name (api.opengapps.org) does not match target host name 'gi
tlab.nezorfla.me'
fatal: unable to access 'https://gitlab.nezorfla.me/opengapps/arm64/': SSL: c
ertificate subject name (api.opengapps.org) does not match target host name '
gitlab.nezorfla.me'
fatal: unable to access 'https://gitlab.nezorfla.me/opengapps/arm/': SSL: cer
tificate subject name (api.opengapps.org) does not match target host name 'gi
tlab.nezorfla.me'
error: Cannot fetch arm64 from https://gitlab.nezorfla.me/opengapps/arm64
error: Cannot fetch all from https://gitlab.nezorfla.me/opengapps/all
error: Cannot fetch arm from https://gitlab.nezorfla.me/opengapps/arm

error: Exited sync due to fetch errors

**Comment by alviteri** [comment]
@mfonville @NicholasBuse

**Comment by mfonville** [comment]
@alviteri you an update the your git links to match the host https://gitlab.opengapps.org ? that should fix it

**Comment by alviteri** [comment]
Thanks I will try later
