### ISSUE TITLE
Problems with "ALL" resources

### ISSUE THREAD

**Issue by rodger-rulez** [opengapps/opengapps#763]
Hi! I've decided today to build a package for myself, but ran into a problem. For some reason, ALL resources are not compiled. In the log, this error:

 all-28 com.google.android.backuptransport                                                                              [/home/rodger-rulez/opengapps/build/arm64/28/aroma/Core/googlebackuptransport-all/nodpi/priv-app/GoogleBackupTransport/GoogleBackupTransport.apk]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
note:  /home/rodger-rulez/opengapps/build/arm64/28/aroma/Core/googlebackuptransport-all/nodpi/priv-app/GoogleBackupTransport/GoogleBackupTransport.apk may be a plain executable, not an archive
 nodpi
   all-28 com.google.android.syncadapters.contacts                                                                        [/home/rodger-rulez/opengapps/build/arm64/28/aroma/Core/googlecontactssync-all/nodpi/app/GoogleContactsSyncAdapter/GoogleContactsSyncAdapter.apk]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
note:  /home/rodger-rulez/opengapps/build/arm64/28/aroma/Core/googlecontactssync-all/nodpi/app/GoogleContactsSyncAdapter/GoogleContactsSyncAdapter.apk may be a plain executable, not an archive
 nodpi
   all-28 com.google.android.feedback                                                                                     [/home/rodger-rulez/opengapps/build/arm64/28/aroma/Core/googlefeedback-all/nodpi/priv-app/GoogleFeedback/GoogleFeedback.apk]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
note:  /home/rodger-rulez/opengapps/build/arm64/28/aroma/Core/googlefeedback-all/nodpi/priv-app/GoogleFeedback/GoogleFeedback.apk may be a plain executable, not an archive
 nodpi
   all-28 com.google.android.onetimeinitializer                                                                           [/home/rodger-rulez/opengapps/build/arm64/28/aroma/Core/googleonetimeinitializer-all/nodpi/priv-app/GoogleOneTimeInitializer/GoogleOneTimeInitializer.apk]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
note:  /home/rodger-rulez/opengapps/build/arm64/28/aroma/Core/googleonetimeinitializer-all/nodpi/priv-app/GoogleOneTimeInitializer/GoogleOneTimeInitializer.apk may be a plain executable, not an archive
 nodpi
   all-28 com.google.android.partnersetup                                                                                 [/home/rodger-rulez/opengapps/build/arm64/28/aroma/Core/googlepartnersetup-all/nodpi/priv-app/GooglePartnerSetup/GooglePartnerSetup.apk]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
note:  /home/rodger-rulez/opengapps/build/arm64/28/aroma/Core/googlepartnersetup-all/nodpi/priv-app/GooglePartnerSetup/GooglePartnerSetup.apk may be a plain executable, not an archive
 nodpi

**Comment by nezorflame** [comment]
Hi @rodger-rulez. Thanks for the report.
This is the drawback of transferring our /all repo to Git LFS. We'll rollback the changes soon, I'll update this issue once it's resolved.

**Comment by nezorflame** [comment]
@rodger-rulez should be fine now, we've restored the /all state. Please check it out and let me know if there're any issues left.

**Comment by rodger-rulez** [comment]
@nezorflame every is fine now, thanks)
