### ISSUE TITLE
Markup permissions should be fixed

### ISSUE THREAD

**Issue by aviraxp** [opengapps/opengapps#764]
Google markup does not handle permission request well when it is called through content URI without opening it for the first time. So we need to grant permission to it, or it will crash in some cases.

```
    <exception package="com.google.android.markup">
        <permission name="android.permission.READ_EXTERNAL_STORAGE" fixed="false"/>
        <permission name="android.permission.WRITE_EXTERNAL_STORAGE" fixed="false"/>
    </exception>
````

**Comment by nezorflame** [comment]
@aviraxp good job, wanna make a PR with this change?

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
