### ISSUE TITLE
com.google.android.googlequicksearchbox

### ISSUE THREAD

**Issue by alviteri** [opengapps/opengapps#765]
@NicholasBuse, @jamuir, @mfonville or anyone can add this to gitlab ... I can't because I have not gitlab account

<code>permission name="android.permission.MANAGE_USB"</code> in <code>privapp-permissions package="com.google.android.googlequicksearchbox"</code>

since it breaks boot in some msm8998 sony and probably others ... thanks

there is the log

<code>
09-04 07:47:18.329  3719  3719 E System  : ******************************************
09-04 07:47:18.329  3719  3719 E System  : ************ Failure starting system services
09-04 07:47:18.329  3719  3719 E System  : java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.google.android.googlequicksearchbox: android.permission.MANAGE_USB}
09-04 07:47:18.329  3719  3719 E System  : 	at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:2005)
09-04 07:47:18.329  3719  3719 E System  : 	at com.android.server.pm.permission.PermissionManagerService.access$100(PermissionManagerService.java:89)
09-04 07:47:18.329  3719  3719 E System  : 	at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.systemReady(PermissionManagerService.java:2052)
09-04 07:47:18.329  3719  3719 E System  : 	at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21286)
09-04 07:47:18.329  3719  3719 E System  : 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:1711)
09-04 07:47:18.329  3719  3719 E System  : 	at com.android.server.SystemServer.run(SystemServer.java:437)
09-04 07:47:18.329  3719  3719 E System  : 	at com.android.server.SystemServer.main(SystemServer.java:296)
09-04 07:47:18.329  3719  3719 E System  : 	at java.lang.reflect.Method.invoke(Native Method)
09-04 07:47:18.329  3719  3719 E System  : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
09-04 07:47:18.329  3719  3719 E System  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:838)
09-04 07:47:18.330  3719  3719 D SystemServerTiming: MakePackageManagerServiceReady took to complete: 519ms
09-04 07:47:18.330  3719  3719 E Zygote  : System zygote died with exception
09-04 07:47:18.330  3719  3719 E Zygote  : java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.google.android.googlequicksearchbox: android.permission.MANAGE_USB}
09-04 07:47:18.330  3719  3719 E Zygote  : 	at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:2005)
09-04 07:47:18.330  3719  3719 E Zygote  : 	at com.android.server.pm.permission.PermissionManagerService.access$100(PermissionManagerService.java:89)
09-04 07:47:18.330  3719  3719 E Zygote  : 	at com.android.server.pm.permission.PermissionManagerService$PermissionManagerInternalImpl.systemReady(PermissionManagerService.java:2052)
09-04 07:47:18.330  3719  3719 E Zygote  : 	at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21286)
09-04 07:47:18.330  3719  3719 E Zygote  : 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:1711)
09-04 07:47:18.330  3719  3719 E Zygote  : 	at com.android.server.SystemServer.run(SystemServer.java:437)
09-04 07:47:18.330  3719  3719 E Zygote  : 	at com.android.server.SystemServer.main(SystemServer.java:296)
09-04 07:47:18.330  3719  3719 E Zygote  : 	at java.lang.reflect.Method.invoke(Native Method)
09-04 07:47:18.330  3719  3719 E Zygote  : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
09-04 07:47:18.330  3719  3719 E Zygote  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:838)
09-04 07:47:18.331  3719  3719 D AndroidRuntime: Shutting down VM
</code>

**Comment by NicholasBuse** [comment]
https://gitlab.opengapps.org/opengapps/all/commit/7a6668f8fb8c8df32eb491807ae93eeff0b59ad1

look right @alviteri ?

**Comment by alviteri** [comment]
Thank you @NicholasBuse
