### ISSUE TITLE
"What's on my screen" missing in Google Assistant

### ISSUE THREAD

**Issue by viggy96** [opengapps/opengapps#766]
The "what's on my screen" button does not appear in the Google Assistant, even when the feature is enabled in the settings. 

ROM: LineageOS 16.0
Device: Moto X4

**Comment by viggy96** [comment]
Is there any update on this?

**Comment by viggy96** [comment]
Anyone able to replicate this issue?

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.

**Comment by viggy96** [comment]
I can still reproduce this issue on the September 1 release of OpenGApps. I'm using the nano version. My phone is a Moto X4, running LineageOS 17.1.

**Comment by osm0sis** [comment]
Provide some logs please. Install log and logcat from when you go to do "what's on my screen".

**Comment by viggy96** [comment]
Here's a log. I have tried asking "what's on my screen" verbally, as well as just waiting for the button to appear. I have enabled all permissions to the Google app, and allowed it to use my screen context.
[opengapps.log](https://github.com/opengapps/opengapps/files/5213165/opengapps.log)

**Comment by methuselahin** [comment]
I also have got issues on honor 5x the latest build of lineageOS 16. I had flashed nano version from 10th of sept. Disabling google app makes issue go away! In case of log i need to install matlog if that is required!

**Comment by osm0sis** [comment]
Honestly it doesn't work on my OnePlus 7T and I'm on stock ROM, so I think this isn't really an Open GApps problem.

I ask it "what's on my screen" and it acts like it doesn't have permission, but "use screen context" is already enabled in settings.
![Screenshot_20200914-110527](https://user-images.githubusercontent.com/2858716/93096200-7bb31b80-f67a-11ea-91f4-b3726d83413c.jpg)

**Comment by osm0sis** [comment]
Nevermind, finally got it to work but I had to trigger Assistant repeatedly until it suggested the option itself. Perhaps that will work for you too?

**Comment by viggy96** [comment]
@osm0sis Nope, that doesn't help. I've tried triggering the assistant repeatedly.

**Comment by viggy96** [comment]
Okay, I've noticed another quirk. If I activate the assistant with my voice, the "what's on my screen" button appears. However, it does NOT appear, when activating the assistant by holding my home button.
[opengapps_button.log](https://github.com/opengapps/opengapps/files/5314068/opengapps_button.log)
[opengapps_voice.log](https://github.com/opengapps/opengapps/files/5314069/opengapps_voice.log)

**Comment by osm0sis** [comment]
Yeah that's what I was saying before, I think a good part of this is just Google being Google and A/B tests and such.

**Comment by osm0sis** [comment]
The latest clarification from Google:
![Screenshot_20210219-090420](https://user-images.githubusercontent.com/2858716/108508186-ccfeb100-7291-11eb-8412-02e9c02d58e6.jpg)

I think we'll close this now. It's Google being Google, i.e. inconsistent, and not Open GApps' fault.
