### ISSUE TITLE
"Google Sounds" included in Super?

### ISSUE THREAD

**Issue by mrjayviper** [opengapps/opengapps#767]
as above. The apps is listed in the "Links to Google Apps" but there's no entry on the default gapps-config.txt

Thanks

**Comment by curiousrom** [comment]
You can't prevent the installation of Sounds (com.google.android.soundpicker) with gapps-config because it's bundled in the core package for some reason.

So there are not keywords for Sounds applicable to the gapps-config @ the present.

As you can see in https://github.com/opengapps/opengapps/blob/master/scripts/inc.buildtarget.sh

`soundpicker)  packagetype="Core"; packagename="com.google.android.soundpicker"; packagetarget="app/SoundPickerPrebuilt"`

I wonder if @NicholasBuse is aware of that as he made the initial commit to add that app AFAIK and also the most recent one: https://gitlab.opengapps.org/opengapps/all/commit/1cfe395a2ae126ddb5fb12d43e3ba8467ca6654b

Sounds is fluff IMO as all ROMs have a Media storage or a file explorer to pick sounds and those do not have 4 services like Sounds & do not try to connect to the web.

It should be removed from core so Pico does not include it IMO.

**Comment by mrjayviper** [comment]
Update: I installed super and Google sounds was NOT included. I didn't exclude it using gapps-config

**Comment by curiousrom** [comment]
> Update: I installed super and Google sounds was NOT included. I didn't exclude it using gapps-config

Are you running Android 9.0 & up? From https://github.com/opengapps/opengapps/wiki/Super-Package

> For 9.0+ also:
> Google Sounds

Check in Settings > Apps > show system app > Sounds.

**Comment by mrjayviper** [comment]
Yes. I'm on lineage 16 (or whatever is the version for Android 9)

**Comment by curiousrom** [comment]
> Yes. I'm on lineage 16 (or whatever is the version for Android 9)

That's weird as Sounds was installed on Galaxy S5 G900M LineageOS 16.0 klte build 2019-09-02 + Open GApps Pico + LineageOS AddonSU.

Cold you attach your open_gapps_log.txt to a reply?

**Comment by mrjayviper** [comment]
updated 1st post with setup info. sorry for forgetting that
--------
contents of open_gapps_log.txt

# Begin Open GApps Install Log
------------------------------------------------------------------
            ROM Android version | 9
                   ROM Build ID | lineage_dipper-userdebug 9 PQ3A.190801.002 eng.root.20190817.084025 test-keys
          ROM Version increment | eng.root.20190817.084025
                ROM SDK version | 28
        ROM/Recovery modversion | 16.0-20190817-UNOFFICIAL-dipper
                Device Recovery | TWRP 3.3.1-0-0ccd76fc-dirty
                    Device Name | dipper
                   Device Model | MI 8
                    Device Type | phone
                     Device CPU | arm64-v8a,armeabi-v7a,armeabi
          Device A/B-partitions | false
             Installer Platform | arm
                   ROM Platform | arm64
           Display Density Used | 440
                   Install Type | Clean[Data Wiped]
             Smart ART Pre-ODEX | false
Google Camera already installed | Clean
          FaceUnlock Compatible | true
              VRMode Compatible | false
       Google Camera Compatible | true
      New Camera API Compatible | false
          Google Pixel Features | false
          Current GApps Version | No GApps Installed
          Google Camera version | Legacy
       Installing GApps Zipfile | /usb_otg/open_gapps-arm64-9.0-super-20190904.zip
       Installing GApps Version | 20190904
          Installing GApps Type | super
                    Config Type | include
             Using gapps-config | /usb_otg/gapps-config.txt
      Remove Stock/AOSP Browser | true[default]
       Remove Stock/AOSP Camera | false[NO_CameraGoogle]
       Remove Stock/AOSP Dialer | true[default]
        Remove Stock/AOSP Email | true[default]
      Remove Stock/AOSP Gallery | true[default]
     Remove Stock/AOSP Launcher | false[NO_GoogleNow/PixelLauncher]
      Remove Stock/AOSP MMS App | true[default]
     Remove Stock/AOSP Pico TTS | false[NO_GoogleTTS]
         Ignore Google Contacts | false
           Ignore Google Dialer | false[DialerGoogle]
         Ignore Google Keyboard | false
Ignore Google Package Installer | false
          Ignore Google NFC Tag | false
          Ignore Google WebView | false
         Total System Size (KB) | 3096336
         Used System Space (KB) | 1240880
        Current Free Space (KB) | 1839072
   Post Install Free Space (KB) | 1004268   << See Calculations Below
------------------------------------------------------------------
# End Open GApps Install Log

NOTE: Stub WebView was installed instead of Google WebView because your device
has already Chrome installed as WebViewProvider. If you still want Google WebView,
you can add 'Override' to your gapps-config to override this redundancy protection.

# Begin GApps Size Calculations
------------------------------------------------------------------
  TYPE  |         DESCRIPTION        |      SIZE |   TOTAL
        |         Current Free Space |   1839072 | 1839072
 Remove |             Existing GApps | +       0 | 1839072
 Remove |             Obsolete Files | +       0 | 1839072
 Remove |                    browser | +    1644 | 1840716
 Remove |            calculatorstock | +     952 | 1841668
 Remove |              calendarstock | +    2484 | 1844152
 Remove |                 clockstock | +    4864 | 1849016
 Remove |              cmsetupwizard | +       0 | 1849016
 Remove |              contactsstock | +   10184 | 1859200
 Remove |                dialerstock | +       0 | 1859200
 Remove |                      email | +    6540 | 1865740
 Remove |           extservicesstock | +      52 | 1865792
 Remove |             extsharedstock | +      24 | 1865816
 Remove |                    gallery | +   11584 | 1877400
 Remove |              keyboardstock | +   49424 | 1926824
 Remove |                        mms | +    8108 | 1934932
 Remove |      packageinstallerstock | +    8684 | 1943616
 Remove |          printservicestock | +     396 | 1944012
 Remove |                  provision | +       0 | 1944012
 Remove |        storagemanagerstock | +    6128 | 1950140
 Remove |                   tagstock | +    1084 | 1951224
 Remove |              webviewgoogle | +       0 | 1951224
 Remove |               webviewstock | +  120020 | 2071244
Install |                       Core | -  178264 | 1892980
Install |               batteryusage | -   11176 | 1881804
Install |                      books | -   14180 | 1867624
Install |           calculatorgoogle | -    2648 | 1864976
Install |             calendargoogle | -   20876 | 1844100
Install |            carrierservices | -   13968 | 1830132
Install |                     chrome | -  124788 | 1705344
Install |                clockgoogle | -    6172 | 1699172
Install |                 cloudprint | -    3840 | 1695332
Install |             contactsgoogle | -    9188 | 1686144
Install |            dialerframework | -      12 | 1686132
Install |               dialergoogle | -   25564 | 1660568
Install |                      drive | -   39964 | 1620604
Install |                 facedetect | -    2584 | 1618020
Install |                 faceunlock | -   19148 | 1598872
Install |                    fitness | -   11360 | 1587512
Install |                      gmail | -   26508 | 1561004
Install |                  googlepay | -   18460 | 1542544
Install |                       keep | -   17908 | 1524636
Install |             keyboardgoogle | -   62140 | 1462496
Install |                       maps | -   93232 | 1369264
Install |                     markup | -    7004 | 1362260
Install |                  messenger | -   49080 | 1313180
Install |                      music | -   15884 | 1297296
Install |     packageinstallergoogle | -    8340 | 1288956
Install |                     photos | -   48716 | 1240240
Install |         printservicegoogle | -      32 | 1240208
Install |                     search | -  110624 | 1129584
Install |                     speech | -   39128 | 1090456
Install |       storagemanagergoogle | -    7284 | 1083172
Install |                  taggoogle | -    1116 | 1082056
Install |                webviewstub | -     396 | 1081660
Install |                  wellbeing | -    7120 | 1074540
Install |                    youtube | -   61056 | 1013484
        |               Buffer Space | -    9216 | 1004268
------------------------------------------------------------------
                        Post Install Free Space | 1004268
------------------------------------------------------------------

# End GApps Size Calculations

# Begin User's gapps-config
CalSync
DialerFramework
PackageInstallerGoogle
BatteryUsage
FaceDetect
FaceUnlock
Markup
Search
Speech
Wellbeing
CalendarGoogle
Gmail
CalculatorGoogle
CarrierServices
ClockGoogle
Maps
Messenger
Photos
TagGoogle
YouTube
Books
Chrome
CloudPrint
Drive
Keep
Music
ContactsGoogle
DialerGoogle
GooglePay
KeyboardGoogle
PrintServiceGoogle
StorageManagerGoogle
WebViewGoogle
WebViewStub
Fitness

# End User's gapps-config
