### ISSUE TITLE
Misc website design stuff

### ISSUE THREAD

**Issue by bgiesing** [opengapps/opengapps#77]
Since we have a new logo, we should update the website for consistency. Also, while we are at it, maybe a little bit of beautification? Those buttons are a little ugly to be honest.

**Comment by mfonville** [comment]
There is a new website in development by @raulx222 and me, but some JQuery issues still have to be worked out. So please have some patience :-)

**Comment by mfonville** [comment]
The website is btw not perfect, some issues on mobile and so, but @raulx222 and me will sort that out by ourselves.
