### ISSUE TITLE
Aroma installer: Detection and removal support for OmniROM stock apps

### ISSUE THREAD

**Issue by darkmorpher** [opengapps/opengapps#770]
Default `acr.browser.lightning`  app not removed when [stock browser removal is checked](https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options#remove-stock-apps) on Aroma package. No problem on normal opengapps package when `gapps-config` is used.

For Aroma installer, Please add [support for removal](https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options#remove-stock-apps) of 

OmniROM stock apps Full list:

acr.browser.lightning
acr.browser.barebones
org.omnirom.omnibrain
org.omnirom.omnichange
org.omnirom.deskclock
org.omnirom.gramophone
com.kabouzeid.gramophone
org.omnirom.omnirecord
org.omnirom.torch

Omni App Switcher (org.omnirom.omniswitch) and MatLog (org.omnirom.logcat) [already listed](https://github.com/opengapps/opengapps/wiki/Advanced-Features-and-Options#remove-stock-apps).

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
