### ISSUE TITLE
com.google.android.apps.restore doesn't have the correct permissions

### ISSUE THREAD

**Issue by Demon000** [opengapps/opengapps#777]
10-11 19:09:37.099  4097  4097 W PackageManager: Privileged permission android.permission.READ_PRIVILEGED_PHONE_STATE for package com.google.android.apps.restore - not in privapp-permissions whitelist
10-11 19:09:37.099  4097  4097 W PackageManager: Privileged permission android.permission.WRITE_EMBEDDED_SUBSCRIPTIONS for package com.google.android.apps.restore - not in privapp-permissions whitelist

Causes the device to bootloop.

**Comment by rocketeer231** [comment]
Agreed

**Comment by nezorflame** [comment]
It's been fixed and is present now in the `privapp-permissions-google.xml`: https://gitlab.opengapps.org/opengapps/all/blob/master/etc/permissions/privapp-permissions-google.xml#L165
