### ISSUE TITLE
Gboard has different name with one from play store and force closed when open preferences

### ISSUE THREAD

**Issue by denikris** [opengapps/opengapps#778]
**Issue description:**

The one installed on android 5.1 is com.android.inputmethod.latin from built open_gapps-arm-5.1-stock-20191017 but on play store is com.google.android.inputmethod.latin, sometimes when open its setting, gboard force close

**Reproduction Steps:**

1. Open settings
2. Language & input
3. Keyboard setting
4. Gboard setting
5. Preference

**Expected behavior:**

the app should listed in play store like google search or gmail

**Observed behavior:**

try to install again with play store but it failed

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

[Debug log of the Open GApps inst
[open_gapps_debug_logs.tar.gz](https://github.com/opengapps/opengapps/files/3753948/open_gapps_debug_logs.tar.gz)
allation](url)

**Comment by Aiti-Aemes** [comment]
happening now with 5 Mar 2020 build....

**Comment by osm0sis** [comment]
That's your ROM's keyboard package name..
