### ISSUE TITLE
Nano package description page missing on Wiki since update done 29/10/2019

### ISSUE THREAD

**Issue by conceptrat** [opengapps/opengapps#780]
It appears that someone removed the Nano package description page in an edit on the 29/10/2019.

See this Wayback Machine reference [[https://web.archive.org/web/20191029043606/https://github.com/opengapps/opengapps/wiki/](https://web.archive.org/web/20191029043606/https://github.com/opengapps/opengapps/wiki/)].  You can see that the link to the Nano package description page is missing "Red" on this main page.  This is the previous capture for the main page [[https://web.archive.org/web/20190808193417/https://github.com/opengapps/opengapps/wiki](https://web.archive.org/web/20190808193417/https://github.com/opengapps/opengapps/wiki)] shows it is there.  And the previous WBM snapshot [[https://web.archive.org/web/20190805054533/https://github.com/opengapps/opengapps/wiki/Nano-Package](https://web.archive.org/web/20190805054533/https://github.com/opengapps/opengapps/wiki/Nano-Package)] shows how it used to look.

I'd also like to point out that at the same time as this happened someone, perhaps the same person who removed the Nano package page, added some text "Yu &" to the footer area which shows on every Wiki page.  Hopefully this is just an error by an editor and not some attempted hack. Refer to the current Wiki [[https://github.com/opengapps/opengapps/wiki](https://github.com/opengapps/opengapps/wiki)] and the first link above to see what I mean about this little modification.

**Comment by curiousrom** [comment]
Thanks for the detailed report & links.

Hopefully there is a recent backup of those pages that can be restored.

**Comment by NicholasBuse** [comment]
Thanks @curiousrom , In the future, the wiki changes are kept a git repo.  If you are done restoring, I'll got ahead and make additional reverts etc.

I've blocked the user in question.

**Comment by NicholasBuse** [comment]
Ok, I've finished up my additional cleanup. Thanks for bringing it to our attention

**Comment by conceptrat** [comment]
I know this is closed now and it's been corrected/reverted.  However I was intrigued by the fact that this GitHub user created only recently could have the ability to alter/remove content in the Wiki.

Is this a standard feature of GitHub?

Or was this something done at a repo level and somehow it was accepted as a commit?

If so then it seems a little too permissive as I'd have only expected the project adminsitrators/editors to have this sort of access.

That user wouldn't have had commits accepted to the actual codebase of OpenGapps right?
