### ISSUE TITLE
Error on installing Open Gapps 8.1 on Carbon ROM 6.1 on Z3C

### ISSUE THREAD

**Issue by armanshahrisa** [opengapps/opengapps#781]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [X ] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [X ] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [X ] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aissue)

*If Open GApps installation fails:*
- [X ] Is the issue reproducible using the latest version of your recovery?
- [X] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

*If receiving force closures after Open GApps installation:*
- [X] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [X] The issue is reproducible on clean (=wiped ``/data/`` partition) installation
- [X] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [X] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**

Error on installing Open Gapps 8.1 on Carbon ROM 6.1.  

**Reproduction Steps:**

1. Flash CARBON-CR-6.1-NOCT-RELEASE-z3c-20191011-0237.zip on Z3C.
2. Flash Open Gapps nano (latest version) on Z3C.

**Expected behavior:**

Installing the open GApps 8.1 pico on carbon rom 6.1

**Observed behavior:**

It mistakenly assumes my CARBON-CR-6.1-NOCT-RELEASE-z3c-20191011-0237.zip rom contins android 9.

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

# Begin Open GApps Install Log
------------------------------------------------------------------
------------------------------------------------------------------
# End Open GApps Install Log

INSTALLATION FAILURE: This GApps package can only be installed on a 8.1.x ROM.

# Begin User's gapps-config

# End User's gapps-config

**Comment by nezorflame** [comment]
This should be fixed after the Android 10 https://github.com/opengapps/opengapps/pull/773 PR merge since we'll fix the issue with the version detection there.
