### ISSUE TITLE
YouTube app is not getting update.

### ISSUE THREAD

**Issue by rahbar11** [opengapps/opengapps#784]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [x] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aissue)

*If Open GApps installation fails:*
- [x] Is the issue reproducible using the latest version of your recovery?
- [x] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

*If receiving force closures after Open GApps installation:*
- [ ] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [ ] The issue is reproducible on clean (=wiped ``/data/`` partition) installation
- [ ] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [ ] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**

YouTube app is not getting update in my Samsung galaxy S5 (SM-G900F). Using nano package of android 9.0 for arm architecture. Used every custom rom of android 9.0. My device is getting all the latest builds of YouTube app when running official firmware but when i flash custom rom with open gapps the playstore is giving me July's build of YouTube app.

**Reproduction Steps:**

1. Download YouTube app.
2. See the last updated information.
Other android 9 phones got updates in November but i am not getting updates and the app is saying to update it.

**Expected behavior:**

YouTube app is getting updates. It should also be shown in Play Store and there should be an option to update it.

**Observed behavior:**

YouTube app is no longer supported for updates. When we open the app it says to update it but there is no option to update it in Play Store but the app is getting normal updates in other android 9 phones.

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

[Debug log of the Open GApps installation](url)

[A logcat of the moment I receive the force closure (if applicable)](url)

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
