### ISSUE TITLE
android 10 gapps?

### ISSUE THREAD

**Issue by Justart2** [opengapps/opengapps#785]
why dont have android 10 gapps? I want to flush to pixel of aosp system.

**Comment by NicholasBuse** [comment]
**DON'T ASK FOR ETAs...**
https://sourceforge.net/projects/opengapps/files/README.md/download

**Comment by KaKi87** [comment]
Just because it's FOSS, users shouldn't be able to ask for ETAs. That's really ridiculous and I'm really getting bored by this fucking no-complain rule.
He's just asking because it's the first time ever that GApps are not ready to use while Android ROMS are.
Why being so rude ?
