### ISSUE TITLE
keyboard FC

### ISSUE THREAD

**Issue by USBhost** [opengapps/opengapps#79]
Nexus 9
ARM64
Android 5.1.1
Pico/Nano Package

any ROM and/or Kernel

tried 7/25 and 7/28 build

E/JniUtils( 2607): Could not load native library jni_latinime
E/JniUtils( 2607): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/app/LatinIME/LatinIME.apk"],nativeLibraryDirectories=[/system/app/LatinIME/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libjni_latinime.so" i think this is the problem.

I/OpenGLRenderer(  543): Initialized EGL, version 1.4
I/ActivityManager(  543): Process com.android.inputmethod.latin (pid 2607) has died
V/ActivityManager(  543): killProcessGroupAsync took 0 ms for PID 2607 on thread 17
W/ActivityManager(  543): Scheduling restart of crashed service com.android.inputmethod.latin/.LatinIME in 1000ms
W/InputMethodManagerService(  543): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@3010bbdb attribute=null, token = android.os.BinderProxy@16e750a4
I/ActivityManager(  543): Start proc 2635:com.android.inputmethod.latin/u0a43 for service com.android.inputmethod.latin/.LatinIME
E/JniUtils( 2635): Could not load native library jni_latinime
E/JniUtils( 2635): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/app/LatinIME/LatinIME.apk"],nativeLibraryDirectories=[/system/app/LatinIME/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libjni_latinime.so"
E/JniUtils( 2635): 	at java.lang.Runtime.loadLibrary(Runtime.java:366)
E/JniUtils( 2635): 	at java.lang.System.loadLibrary(System.java:988)
E/JniUtils( 2635): 	at com.android.inputmethod.latin.utils.JniUtils.<clinit>(JniUtils.java:33)
E/JniUtils( 2635): 	at com.android.inputmethod.latin.utils.JniUtils.loadNativeLibrary(JniUtils.java:46)
E/JniUtils( 2635): 	at com.android.inputmethod.latin.LatinIME.<clinit>(LatinIME.java:513)
E/JniUtils( 2635): 	at java.lang.reflect.Constructor.newInstance(Native Method)
E/JniUtils( 2635): 	at java.lang.Class.newInstance(Class.java:1606)
E/JniUtils( 2635): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2786)
E/JniUtils( 2635): 	at android.app.ActivityThread.access$1900(ActivityThread.java:154)
E/JniUtils( 2635): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1404)
E/JniUtils( 2635): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/JniUtils( 2635): 	at android.os.Looper.loop(Looper.java:135)
E/JniUtils( 2635): 	at android.app.ActivityThread.main(ActivityThread.java:5305)
E/JniUtils( 2635): 	at java.lang.reflect.Method.invoke(Native Method)
E/JniUtils( 2635): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/JniUtils( 2635): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/JniUtils( 2635): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
I/LatinIME( 2635): Hardware accelerated drawing: true
W/SubtypeLocaleUtils( 2635): KeyboardLayoutSet not found, use QWERTY: locale=en_AU extraValue=TrySuppressingImeSwitcher,AsciiCapable,SupportTouchPositionCorrection,EmojiCapable
W/InputAttributes( 2635): No editor info for this field. Bug?
E/art     ( 2635): No implementation found for long com.android.inputmethod.latin.BinaryDictionary.createOnMemoryNative(long, java.lang.String, java.lang.String[], java.lang.String[]) (tried Java_com_android_inputmethod_latin_BinaryDictionary_createOnMemoryNative and Java_com_android_inputmethod_latin_BinaryDictionary_createOnMemoryNative__JLjava_lang_String_2_3Ljava_lang_String_2_3Ljava_lang_String_2)
E/AndroidRuntime( 2635): FATAL EXCEPTION: Executor - UserHistoryDictionary.en_US
E/AndroidRuntime( 2635): Process: com.android.inputmethod.latin, PID: 2635
E/AndroidRuntime( 2635): java.lang.UnsatisfiedLinkError: No implementation found for long com.android.inputmethod.latin.BinaryDictionary.createOnMemoryNative(long, java.lang.String, java.lang.String[], java.lang.String[]) (tried Java_com_android_inputmethod_latin_BinaryDictionary_createOnMemoryNative and Java_com_android_inputmethod_latin_BinaryDictionary_createOnMemoryNative__JLjava_lang_String_2_3Ljava_lang_String_2_3Ljava_lang_String_2)
E/AndroidRuntime( 2635): 	at com.android.inputmethod.latin.BinaryDictionary.createOnMemoryNative(Native Method)
E/AndroidRuntime( 2635): 	at com.android.inputmethod.latin.BinaryDictionary.<init>(BinaryDictionary.java:157)
E/AndroidRuntime( 2635): 	at com.android.inputmethod.latin.ExpandableBinaryDictionary.createOnMemoryBinaryDictionaryLocked(ExpandableBinaryDictionary.java:260)
E/AndroidRuntime( 2635): 	at com.android.inputmethod.latin.ExpandableBinaryDictionary.createNewDictionaryLocked(ExpandableBinaryDictionary.java:561)
E/AndroidRuntime( 2635): 	at com.android.inputmethod.latin.ExpandableBinaryDictionary.access$700(ExpandableBinaryDictionary.java:53)
E/AndroidRuntime( 2635): 	at com.android.inputmethod.latin.ExpandableBinaryDictionary$12.run(ExpandableBinaryDictionary.java:605)
E/AndroidRuntime( 2635): 	at com.android.inputmethod.latin.ExpandableBinaryDictionary$1.run(ExpandableBinaryDictionary.java:194)
E/AndroidRuntime( 2635): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 2635): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 2635): 	at java.lang.Thread.run(Thread.java:818)
E/art     ( 2635): No implementation found for long com.android.inputmethod.latin.BinaryDictionary.createOnMemoryNative(long, java.lang.String, java.lang.String[], java.lang.String[]) (tried Java_com_android_inputmethod_latin_BinaryDictionary_createOnMemoryNative and Java_com_android_inputmethod_latin_BinaryDictionary_createOnMemoryNative__JLjava_lang_String_2_3Ljava_lang_String_2_3Ljava_lang_String_2)
I/Process ( 2635): Sending signal. PID: 2635 SIG: 9
I/ActivityManager(  543): Process com.android.inputmethod.latin (pid 2635) has died
W/ActivityManager(  543): Service crashed 2 times, stopping: ServiceRecord{2bcd62a9 u0 com.android.inputmethod.latin/.LatinIME}
I/OpenGLRenderer(  543): Initialized EGL, version 1.4
V/ActivityManager(  543): killProcessGroupAsync took 39 ms for PID 2635 on thread 17
W/InputMethodManagerService(  543): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@3cf451cb attribute=null, token = android.os.BinderProxy@16e750a4

**Comment by mfonville** [comment]
Could you add the installation debug log? It should be a tar-file. I will need that to further investigate.

**Comment by USBhost** [comment]
https://copy.com/gdmphYCe4J4w1sTX

**Comment by mfonville** [comment]
This reinstall was on a dirty /system partition, or not?
Because it seems that for some reason the google variation of the lib was already installed... so it was on the ROM, or it was a previous gapps flash.
Anyhow, the end-state of libraries is inconsistent, I will need some time to figure out why, find a fix and we should do tests before it goes into the mainline.

**Comment by mfonville** [comment]
@USBhost could you try this build (preferably on a clean install) and check if the problem has been resolved? https://www.dropbox.com/s/1cjaamdnp03a9er/open_gapps-arm64-5.1-nano-20150804.zip?dl=0

**Comment by mfonville** [comment]
This should be fixed in today's build.
So I will close the bug, if problems still arise, please comment and we will re-open it.

**Comment by zcwfeng** [comment]
Fatal Exception: java.lang.UnsatisfiedLinkError: Native method not found: com.android.inputmethod.latin.BinaryDictionary.createOnMemoryNative:(JLjava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)J
       at com.android.inputmethod.latin.BinaryDictionary.createOnMemoryNative(BinaryDictionary.java)
       at com.android.inputmethod.latin.BinaryDictionary.(BinaryDictionary.java)
       at com.android.inputmethod.latin.ExpandableBinaryDictionary.createOnMemoryBinaryDictionaryLocked(ExpandableBinaryDictionary.java:262)
       at com.android.inputmethod.latin.ExpandableBinaryDictionary.createNewDictionaryLocked(ExpandableBinaryDictionary.java:561)
       at com.android.inputmethod.latin.ExpandableBinaryDictionary.access$700(ExpandableBinaryDictionary.java:53)
       at com.android.inputmethod.latin.ExpandableBinaryDictionary$12.run(ExpandableBinaryDictionary.java:605)
       at com.android.inputmethod.latin.ExpandableBinaryDictionary$1.run(ExpandableBinaryDictionary.java:194)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:848)
