### ISSUE TITLE
OpenGapps 10 Beta install fails with error 25 - No build.prop or equivalent 

### ISSUE THREAD

**Issue by HonoluluHenk** [opengapps/opengapps#792]
**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope

*If Open GApps installation fails:*
- [x] Is the issue reproducible using the latest version of your recovery?
- [x] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

**Issue description:**

Installation on my Xiaomi Mi A2 fails with error code 25
OpenGapps: open_gapps-arm64-10.0-micro-20200115-BETA.zip 

**Reproduction Steps:**

1. Install custom ROM as per instructions
2. Reboot into recovery
3. Install OpenGapps

**Expected behavior:**

OpenGapps installed

**Observed behavior:**

Error 25

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

N/A

After digging around in `install.sh`, I found (just below get_file_prop() near line 956):
```
if [ ! "$(getprop 2>/dev/null)" ]; then
...
elif [ ! "$(getprop ro.build.type 2>/dev/null)" ]; then
...
fi
```

On my device, both if-branches fail so lateron there's no get_prop() function defined.
When I add the following, everything works as expected:

```
else
  get_prop() {
    getprop "$1"
  }
```

**Comment by iamsdx** [comment]
the same
Xiaomi MIX2S Mokee Android 10.0

**Comment by nezorflame** [comment]
Thanks, that's a valid point, I'll try that out in my fork.

**Comment by nezorflame** [comment]
@HonoluluHenk this should've worked since 16 January release. Were you able to check it?

**Comment by nezorflame** [comment]
Please check on the new builds from January 31 to see if the issue is resolved.
