### ISSUE TITLE
android Q --Youtube Music can not get music from sd card(as protable storage)

### ISSUE THREAD

**Issue by StefanLyj** [opengapps/opengapps#795]
1. [First Step]
device with sd card . sd card as protable storage.there is music in sd card
2. [Second Step]
open ytmusic ,click song to view music in device

**Expected behavior:**
ytmusic can get music from sd card

**Observed behavior:**
ytmusic can not get music from sd card,but with android p gms version,it can

is ytmusic not support in android Q??

**Comment by nezorflame** [comment]
Works fine here with nano package on a Q ROM. I suggest you to contact your ROM's developer.

**Comment by StefanLyj** [comment]
Thks,it's work fine when i use version 3.45.54
