### ISSUE TITLE
9.0 TV-Stock Boot Loop

### ISSUE THREAD

**Issue by ArnauBG** [opengapps/opengapps#811]
Hi, @nezorflame I'm having trouble with my OpenGApps installation, and I think that you could help me.

**Checklist**

- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*
- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)

**Issue description:**

After installing my build of OppenGApps, I experience boot loop

**UPDATE:** The problem is related to TV-Stock package, since I installed Pico package without problems.

**Reproduction Steps:**

1. [Build OpenGapps with the following config: `arm-28-tvstock`]
2. [Install the build with TWRP Recovery v. 3.3.1-0]
3. [Wipe Dalvik]
4. [Factory Reset]
5. [Reboot]

**Expected behavior:**

[I excepted that Android boots up with AndroidTV.]

**Observed behavior:**

[It keeps stuck in the boot animation.]

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

[Debug log of the Open GApps installation](https://gist.github.com/ArnauBG/57c16a485a84eea7821bdb2918f9a805)
[tar.gz File](https://drive.google.com/file/d/1ZURBvVp1OKP5bJYYJAaKvhh0GOZD8QXP/view?usp=sharing)
[LogCat](https://gist.github.com/ArnauBG/bbf92fa291f815214a3e631b9e9cd057)

# Thanks in  advantage.

**Comment by meponderR** [comment]
I am having the same problem as you are with tvstock

**Comment by rtm516** [comment]
I worked out a fix to this, you need to change your build.prop to have the `ro.build.characteristics` set to `tv` this can be done by mounting the system partition and running [this script](https://gist.github.com/rtm516/cbd4b685d227b2f8134a21d9dc85d48e). But before you can install apps you need to expand the system partition using something like gparted, then gapps will install fine.

It then fails to sign in or discover so cant be setup, if you get past this let me know.

**Comment by Harald321** [comment]
Seems like this is a common issue. I'm using a rasperry pi 4b. Also having a bootloop after installing open_gapps-arm-9.0-tvstock-20200711.

**Comment by kkshinichi** [comment]
> I worked out a fix to this, you need to change your build.prop to have the `ro.build.characteristics` set to `tv` this can be done by mounting the system partition and running [this script](https://gist.github.com/rtm516/cbd4b685d227b2f8134a21d9dc85d48e). But before you can install apps you need to expand the system partition using something like gparted, then gapps will install fine.
> 
> It then fails to sign in or discover so cant be setup, if you get past this let me know.

Tried doing this on my end, but I'm still stuck on a bootloop. Details to be given upon request.

**Comment by rtm516** [comment]
> Tried doing this on my end, but I'm still stuck on a bootloop. Details to be given upon request.

You might have to wipe the device so when you do this it is the first install of gapps, as that's what worked for me.

**Comment by kkshinichi** [comment]
> > Tried doing this on my end, but I'm still stuck on a bootloop. Details to be given upon request.
> 
> You might have to wipe the device so when you do this it is the first install of gapps, as that's what worked for me.

Still isn't working on my end.

Here's what I did:
1. Install Lineage OS on MicroSD card through Etcher
2. Boot up, enable root access and local terminal, reboot to system to enable terminal
3. Reboot to TWRP
4. Wipe Dalvik data, and Factory Reset
5. Install opengapps tvstock
6. Mount Boot, System, Data Partitions
7. Execute [this script](https://gist.github.com/rtm516/cbd4b685d227b2f8134a21d9dc85d48e)
8. Reboot back to system
9. Bootloop

**Comment by fredthedoggy** [comment]
Has Anyone found a fix for this? I have the exact same problem, and I did use the script provided.

**Comment by josemarilumanlan** [comment]
Have the same issue. 

Using rpi3 b+ stuck at bootloop after installing tv-stock.

**Comment by sapbasis2016** [comment]
I am using rpi4 with tv stock but it stuck in boot loop.
Can someone any stable version of tv stock?

**Comment by nezorflame** [comment]
> > > Tried doing this on my end, but I'm still stuck on a bootloop. Details to be given upon request.
> > 
> > 
> > You might have to wipe the device so when you do this it is the first install of gapps, as that's what worked for me.
> 
> Still isn't working on my end.
> 
> Here's what I did:
> 
> 1. Install Lineage OS on MicroSD card through Etcher
> 2. Boot up, enable root access and local terminal, reboot to system to enable terminal
> 3. Reboot to TWRP
> 4. Wipe Dalvik data, and Factory Reset
> 5. Install opengapps tvstock
> 6. Mount Boot, System, Data Partitions
> 7. Execute [this script](https://gist.github.com/rtm516/cbd4b685d227b2f8134a21d9dc85d48e)
> 8. Reboot back to system
> 9. Bootloop

The script mentioned by @kkshinichi checks for the presence of the `ro.build.characteristics` prop, and if present, replaces it to TV, but ONLY if it was present and had the `tablet` value.

This script needs to be changed to account for other cases:
- there can be a `phone` value instead of the `tablet`
- there can be no `ro.build.characteristics` prop at all - it needs to be created then
