### ISSUE TITLE
the problem of installing GAAPS ont the device with small system partition

### ISSUE THREAD

**Issue by radmir1948** [opengapps/opengapps#812]
Dear Sirs,
I got the Samsung Galaxy Tab 10.1 and tried to install Open-Gaaps, but found the size (578 mb) of the system partition on my tablet is insufficient to install Gaaps.
So I installed using nano package without support speed and sound search. But I think, there is a lack of some other Gaaps item,...
Really I don't know which product I need to install. I tried to install  one time more changing gaaps-config.txt removing comments previously set and adding new ones on what I want to install. 
But I found the install script is removing previously installed items and install the new items. In calculus of necessary memory they add  the memory for all items including to be removed items, and installing news. As a result I failed.
The questions are:

- May I install the package in several steps by parts - I mean may I control the order of installing by changing the lists in install.sh and/or gaaps-config.txt? Can you give more details and samples how to change the lists for installing or saving installed items?
- May you rewrite install.sh so, that it can do what I want or give some advice what I may do for that? 
- The tablet's memory is enough and would be good if one can add items necessary for most apps. So, google chrome browser gives an Error message and doesn't work, Your tube application doesn't work and so on.
- Now some products give at every start unpleasant message like "Error: google speech service not installed" (application "Adobe pdf reader")
- The advice to install absent services from play market forced me to be patient and collect  information of what did lack for every application despite the fact I don't know where and how I may find what I need, what version I need and would it work on my old tablet? If you think everybody may cope with such a small task, thanks, you have  very high estimation of my abilities.

Yours,
Radmir

**Comment by khanhtranngoccva** [comment]
Just resize the system partition with "parted" binary for TWRP (from XDA) then format all touched partitions with mke2fs -t ext4 command. Be careful not to touch recovery or any other partitions on the left, or you destroy the bootloader and hard-brick the tablet. On Samsung devices, system, cache, hidden and userdata partitions are on the far right, so resizing is not much of a problem.

**Comment by khanhtranngoccva** [comment]
If you do not resize partition to have at least 200MB free after installation, some APKs will be missing. I had the same problem as well.

**Comment by radmir1948** [comment]
Hello, khanhtranngoccva,
but the problem is more complex, the program "parted" gives an error on the main partition mmcblk0. The msg says it has no label?
Yes it is wright, but if I try to use command mklabel, I got the warning all data may be removed. I have no tools to define mmcblk0's label, I suspect it has no label. I found another solution, and if interested, I'll give the full information and send you the link where you may read it.
Yours,
Radmir

**Comment by khanhtranngoccva** [comment]
Why don't you use the name and setflags command in parted tool?

Vào 00:04, T.5, 19 Th3, 2020 Turmukhambetov Radmir N. <
notifications@github.com> đã viết:
