### ISSUE TITLE
I use twrp flash open_gapps-arm64-10.0-nano-20200311.zip to pixel, but nothing after reboot device.

### ISSUE THREAD

**Issue by Justart2** [opengapps/opengapps#818]
I already use twrp flash into pixel device, but nothing after reboot. why?

Gapps version is open_gapps-arm64-10.0-nano-20200311.zip

**Comment by Justart2** [comment]
please help me resolve. thanks

**Comment by killruana** [comment]
Same problem here with LineageOS 17.1 (lineage-17.1-20200401-nightly-FP2-signed.zip) on my Fairphone 2 and gapps open_gapps-arm-10.0-pico-20200401.zip
