### ISSUE TITLE
Binary release hosting

### ISSUE THREAD

**Issue by hemanth7787** [opengapps/opengapps#819]
Sourceforge is insanely slow  

This file downloads for around 30-70 KBps
https://nchc.dl.sourceforge.net/project/opengapps/x86_64/20200322/open_gapps-x86_64-7.1-pico-20200322.zip

Is it feasible to host release binary somewhere else ?

**Comment by hemanth7787** [comment]
can we look towards BitTorrent or something?

**Comment by osm0sis** [comment]
BitTorrent for a daily release schedule? Good luck getting seeders. No. Hosting is what it is, read the Blog for reasons.
