### ISSUE TITLE
libwebviewchromium.so is actually in /system/lib/

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#82]
libwebviewchromium.so of the AOSP ROM is actually not stored in /app/webview/lib/ but is stored in /system/lib/.
When deleting stock webview this library should also be removed. Current testing indicates that no replacement symlink has to be provided beteen /system/lib/ and /system/app/WebViewGoogle/lib/arm/, but it needs to be confirmed by others.

**Comment by dnle71** [comment]
I've posted that bug coz I remember when tk-gapps first introduced WebviewGoogle and there it goes. It's libwebviewchromium.so is stored in /system/lib/ and linked to the app lib folder.

After deleting the lib as requested, chrome seems to work fine, tried a few webview test apps from play store and it's still working.

**Comment by mfonville** [comment]
I also checked now filesystem layout on an original Nexus device, and they also work with the symlink. So I will check how we might mimick this in a nice reliable manner. Doing this will imply though that a WebViewGoogle installation will always have to enforce a WebViewStock purge, which is allowed to be bypassed at the moment.

So for now I will just push a non-invasive patch, and those symlink and other changes will be at a later moment.

**Comment by mfonville** [comment]
I have done quite some invasive code changes. On my phone it works, but if some other @opengapps/general that are able to build their own package could confirm that the 'webviewsystemlib' branch also works for them, I dare to merge this into master.

**Comment by bgiesing** [comment]
@mfonville Did you forget to close this issue? You mentioned in the PR that it closes this.

**Comment by mfonville** [comment]
@bgiesing yup, I should have closed it. Thought the PR would do that for me :-P
