### ISSUE TITLE
Website crashes in ADM

### ISSUE THREAD

**Issue by bgiesing** [opengapps/opengapps#83]
The website loads but then redirects to nothing in ADM Download Manager for Android. 

Video: https://goo.gl/photos/4PiDgud3QMGc4xVS6

**Comment by mfonville** [comment]
Are you sure that the url it is visiting is really http://opengapps.org and no extra parameters are included? And maybe ADM is not compatible with GetMDL? You could test that by visiting other GetMDL (Material Design Lite) generated websites.

**Comment by bgiesing** [comment]
@mfonville looks like other mdl sites are affected too... Definitely their end.

**Comment by mfonville** [comment]
I will put this on a 'wontfix' then from our side. I suggest you contact the GetMDL devs and the ADM devs and let their battle commence who should fix their stuff ;-)
