### ISSUE TITLE
Additional overlays for setting default Google apps

### ISSUE THREAD

**Issue by VincentJoshuaET** [opengapps/opengapps#839]
```
<!-- Screenshot editing default activity.  Must handle ACTION_EDIT image/png intents.
         Blank sends the user to the Chooser first.
         This name is in the ComponentName flattened format (package/class)  -->
<string name="config_screenshotEditor">com.google.android.markup/com.google.android.markup.AnnotateActivity</string>
```

**Comment by VincentJoshuaET** [comment]
<string name="launcher_overlayable_package">com.google.android.apps.nexuslauncher</string>


<string name="themepicker_overlayable_package">com.google.android.apps.wallpaper</string>

**Comment by VincentJoshuaET** [comment]
https://github.com/PixelExperience/vendor_pixelstyle/blob/ten/overlay/frameworks/base/core/res/res/values/config.xml

**Comment by curiousrom** [comment]
What's up with the OP of this bug report?

Where is the description in plain English?
