### ISSUE TITLE
Can't view src

### ISSUE THREAD

**Issue by VitaliPom** [opengapps/opengapps#849]
Hi, why I can't view sources and how do I view source of the swipe jni library? And can I install it just in my project at AndroidStudio or I must put it inside /system and be root for that? Please help it's 2020 and people want to progress with new software. I have a cool keyboard with novice idea that worth having swipe and people are actually asking for that from me.
Many thanks,
Vitali

**Comment by nezorflame** [comment]
Hi. All of the APKs are stored at our Gitlab server: https://gitlab.opengapps.org/opengapps/

**Comment by VitaliPom** [comment]
Hi,
Thanks for your fast reply.
Where do I look for source code of arm/lib/19?
In here I cannot view it. And the link has only compiled library.
Thanks,
Vitali

**Comment by nezorflame** [comment]
Like I've already mentioned, these libs abd APKs come from Google's factory images directly as is, we do not have the code for them and we do not compile these apps.
