### ISSUE TITLE
Google Play games has error -505 permissions problems, if not initially installed on /system/

### ISSUE THREAD

**Issue by mfonville** [opengapps/opengapps#85]
XDA user OverlordQ experiences the issue that Google Play Games cannot be installed from the Google Play Store, if it was not initially installed on /system/.
Permission error -505 is then shown by the Play Store.
Check posts (and earlier responds to it) of http://forum.xda-developers.com/showpost.php?p=62156317&postcount=64

We should test if this applies to more/all devices and ROMs:
- [x] OverlordQ should try to use a gapps-config file to install Google Play Games on /system/ (and make some space by deselecting some other packages) and see if then everything works properly on his device
- [ ] ~~Please @opengapps/general who have devices they can test on, try an installation without Google Play Games installed on /system/ and see if you experience the same Play Store problem~~ -> Gives no issues
- [ ] ~~If both above are true, we will reconsider the content of the 'mini' package.~~ -> Forfeit

**Comment by NicholasBuse** [comment]
I was able to install, run, and login Games on my N5 with CM 12.1 CAF. I'm almost certain I've always excluded games in my gapps-config

**Comment by mfonville** [comment]
The weird thing is also, that an android application should be allowed to redeclare the same permissions as long as it is signed with the same keys as the conflicting application. In this situation both are signed by Google Inc., so they should not conflict.
Maybe this specific CM ROM misses (or includes) a patch that breaks this behaviour... :-/

**Comment by OverlordQ** [comment]
Installed Play Games using gapps-config.txt using micro-20150803. Any further debugging wrt package signatures, let me know.

**Comment by OverlordQ** [comment]
Installed a Micro+PlayGames using full package and this for a gapps-config.txt:
```
Include
Speech
FaceDetect
FaceUnlock
ExchangeGoogle
CalSync
Search
CalendarGoogle
GoogleNow
GoogleTTS
Gmail
PlayGames
```

New LogFiles: 

https://www.dropbox.com/s/esc12bgznid9yen/open_gapps_log.txt?dl=0
https://www.dropbox.com/s/2c0yjdi84qfo9lp/open_gapps_debug_logs.tar.gz?dl=0

Let me know if any additional debugging can be done on my end.

**Comment by mfonville** [comment]
@OverlordQ and now Google Play Games works correctly?

**Comment by OverlordQ** [comment]
It loads and games stopped prompting with the 'game requires latest Google Play Games' message.

So if there's anything you need me to do to debug on why it wont install from the play store let me know.

**Comment by mfonville** [comment]
@NicholasBuse what was the latest time you tried this? at the moment you did write that message, or sometime in the past?

**Comment by mfonville** [comment]
@OverlordQ if you have any android app developing experience, it might be very useful to write 2 stub applications, and let them claim the same permission, and sign those apps with the same key.
Install those apps then on your ROM, and see if they also give the same trouble. If so, we could identify it as problem with the ROM...

**Comment by NicholasBuse** [comment]
@mfonville , at the time of the comment.  I don't use PlayGames, but I saw the issue,  tried and reported.

**Comment by mfonville** [comment]
@OverlordQ does this problem still happen with the latest packages, that have updated Play Games and Google Play Services?

**Comment by OverlordQ** [comment]
Still noticing it, even with other GApps packages, so it's going to probably be something with CM 12.1. That, coupled with other platform bugs in 12.1 I've downgraded back to 4.4

**Comment by mfonville** [comment]
@OverlordQ thank you for the feedback.
So then probably indeed something with CM 12.1
Personally, I would expect there is something wrong with their crypto algorithms or certificates, that it can't match up those keys. I will close the bug here, since we can't do anything about it. But I would suggest to at least notify the CM developers of this bug.
