### ISSUE TITLE
Missing permission

### ISSUE THREAD

**Issue by neobuddy89** [opengapps/opengapps#857]
18th July - Open Gapps Micro Arm64 for Android 10 fails to boot. Below is the error:

07-20 05:34:53.640  3292  3292 E System  : ******************************************
07-20 05:34:53.640  3292  3292 E System  : ************ Failure starting system services
07-20 05:34:53.640  3292  3292 E System  : java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.google.android.googlequicksearchbox: android.permission.BLUETOOTH_PRIVILEGED}
07-20 05:34:53.640  3292  3292 E System  : 	at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:2984)
07-20 05:34:53.640  3292  3292 E System  : 	at com.android.server.pm.permission.PermissionManagerService.access$100(PermissionManagerService.java:123)
07-20 05:34:53.640  3292  3292 E System  : 	at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.systemReady(PermissionManagerService.java:3045)
07-20 05:34:53.640  3292  3292 E System  : 	at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21962)
07-20 05:34:53.640  3292  3292 E System  : 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:2068)
07-20 05:34:53.640  3292  3292 E System  : 	at com.android.server.SystemServer.run(SystemServer.java:537)
07-20 05:34:53.640  3292  3292 E System  : 	at com.android.server.SystemServer.main(SystemServer.java:364)
07-20 05:34:53.640  3292  3292 E System  : 	at java.lang.reflect.Method.invoke(Native Method)
07-20 05:34:53.640  3292  3292 E System  : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-20 05:34:53.640  3292  3292 E System  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:918)

**Comment by YandexStudio** [comment]
I've also tested with aroma installer on some other device, looks like it's not related with arch and android version.
on my arm android 9 device also have the same issue.
When include Google Search App, it cause bootloop.
I'm inconvenient to post my logcat, but I guess it's the same reason.

**Comment by S-trace** [comment]
Yes, my device also bootlooped with the same issue.
I added this permission to /system/etc/permissions/privapp-permissions-google.xml and the tablet now works fine.

**Comment by razorloves** [comment]
https://gitlab.opengapps.org/opengapps/all/-/merge_requests/24

**Comment by vpnsade** [comment]
Open
