### ISSUE TITLE
missing file metadata

### ISSUE THREAD

**Issue by ETACSDecoder** [opengapps/opengapps#859]
Hello.
I have board on AllWinner QuadCore A40i with And7.1
-Download open_gapps-arm-7.1-pico-20200722
-Enter in Recovery mode
-Select "Apply update from TFCard or USB"
and I get error
"E: Failed to find META-INF/com/android/metadata in update package"
"E: Error in /sideload/package.zip"
(Status 255)

Where can I get this file "metadata"?

**Comment by strazzere** [comment]
It should be bundled in the zip file. Can you provide a listing of what is in the zip file?

On linux/macos it would be something like this, `unzip -l open_gapps-arm-7.1-pico-20200722.zip`
