### ISSUE TITLE
Looking for a home for a new tool

### ISSUE THREAD

**Issue by NicholasBuse** [opengapps/opengapps#86]
@mfonville and @opengapps/packagers,

I have written a new tool (in python) that I am calling apkmirror_crawler. It is nearly ready for prime time (I used to to pull the two new GMS that I uploaded today).

- By default (no command line parameters) it pulls all **current** APK versions of each application that we care about.
- You can pass in one or more of the OpenGApps config file keywords to reduce the scope (books, gmscore, etc.)
- If the identified APK to download already exists in your directory, it will not be re-downloaded
- It could be easily extended as we support more applications (Inbox, etc.)

An example (at the time I'm writing this) for **current** versions, running:
```
python apkmirror_crawler.py gmscore
```
will identify the current version of 7.8.99 and download:
- com.google.android.gms-7.8.99_(2134222-438)-7899438-minAPI21.apk
- com.google.android.gms-7.8.99_(2134222-448)-7899448-minAPI21.apk

Older 7.8.95 ones are ignored...

Does this have a place in our project, or should I keep it in my own GitHub account?

**Comment by NicholasBuse** [comment]
Also, my plan is to extend or mirror this functionality into a "playstore_crawler" tool, but didn't want to bite off the auth issues that we still have as a TBD...

**Comment by mfonville** [comment]
Wow, sounds awesome Nick :-)
I am sure we can embed this tool as part of the project. Probably best as a seperate repository, I think, since crawling the internet for APKs and building GApps packages are two different things. And posix shell != python :-)

Make sure that to directly include a good LICENSE (and/or NOTICE) file about how you think this tool should be used and to which (and whose) terms a user of the tool agrees to (especially when expanded to include the Play Store).

**Comment by mfonville** [comment]
@NicholasBuse Should I go forward and create the repository for you?
How about the generic name "apkcrawler"? Or rather "apk_crawler"? Or something completely different?

**Comment by NicholasBuse** [comment]
Let's go with "apkcrawler". I'll probably have some questions or need some recommendations on Licensing...

**Comment by mfonville** [comment]
You can now push to git@github.com:opengapps/apkcrawler.git
```
git init
git remote add origin git@github.com:opengapps/apkcrawler.git
git push -u origin master
```
Don't forget to also make a README.md and a .gitignore file.

About LICENSE and NOTICE, I am no legal expert, but I think a good thing would be to start out with e.g. the GPLv3 for your own work.
Look at some existing licenses for applications that are able to handle copyrighted 3rd party content like bittorrent (http://www.bittorrent.com/legal/eula) and see which general 'rules' could/should be reapplied to the usage of the crawler. In general you want to let the user be responsible for the usage and that is their own responsibility to stick to the user license agreement of the crawled source (especially concerning the Play Store).
It might also be good to let a users set-up e.g. their own credentials or URLs when using the tool.
