### ISSUE TITLE
Missing libsbcdecoder_jni.so in Google Search App

### ISSUE THREAD

**Issue by YandexStudio** [opengapps/opengapps#860]
When I press Google Assistant Button on my headphones, my phone shows Google App Crashed.
Here's the logcat.

`logcat -b crash
07-23 19:10:39.820 31937 31968 E AndroidRuntime: FATAL EXCEPTION: BG Thread #0
07-23 19:10:39.820 31937 31968 E AndroidRuntime: Process: com.google.android.googlequicksearchbox:interactor, PID: 31937
07-23 19:10:39.820 31937 31968 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/priv-app/Velvet/Velvet.apk!/lib/arm64-v8a/libsbcdecoder_jni.so" not found
07-23 19:10:39.820 31937 31968 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
07-23 19:10:39.820 31937 31968 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1669)
07-23 19:10:39.820 31937 31968 E AndroidRuntime:        at com.google.android.apps.gsa.staticplugins.bisto.l.bd.run(Unknown Source:118)
07-23 19:10:39.820 31937 31968 E AndroidRuntime:        at com.google.android.apps.gsa.staticplugins.bisto.l.bj.run(Unknown Source:2)
07-23 19:10:39.820 31937 31968 E AndroidRuntime:        at com.google.android.libraries.gsa.m.a.l.call(Unknown Source:8)
07-23 19:10:39.820 31937 31968 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-23 19:10:39.820 31937 31968 E AndroidRuntime:        at com.google.apps.tiktok.concurrent.aq.run(SourceFile:1)
07-23 19:10:39.820 31937 31968 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-23 19:10:39.820 31937 31968 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-23 19:10:39.820 31937 31968 E AndroidRuntime:        at com.google.apps.tiktok.concurrent.f.run(Unknown Source:24)
07-23 19:10:39.820 31937 31968 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
07-23 19:10:39.820 31937 31968 E AndroidRuntime:        Suppressed: com.google.android.apps.gsa.shared.util.c.a.bz: Unchecked exception happened while running task: al[audio-decoder]
07-23 19:10:39.820 31937 31968 E AndroidRuntime:                at com.google.android.apps.gsa.shared.util.c.a.ca.run(SourceFile:6)
07-23 19:10:39.820 31937 31968 E AndroidRuntime:                ... 5 more`

**Comment by osm0sis** [comment]
Is this still an issue with the latest build? Looks like the lib is supposed to be INSIDE Velvet (Google App).

**Comment by nezorflame** [comment]
Seems more like an issue with outdated Velvet inside of the opengapps package. Should've been resolved by an update.

**Comment by osm0sis** [comment]
No response, so will consider this abandoned.
