### ISSUE TITLE
Gapps contains virus?

### ISSUE THREAD

**Issue by jakey1995abc** [opengapps/opengapps#861]
The latest version of Arm64, Android 10, aroma package (open_gapps-arm64-10.0-aroma-20200723.zip) contains some sort of virus. I downloaded it on Windows 10 from the official site, and now I can't open the file in any programs without them crashing (including winrar, 7zip, file explorer), and I am also unable to right click, delete, or copy the file to another location without explorer.exe crashing.

**Comment by osm0sis** [comment]
Laughable. No.
