### ISSUE TITLE
Android 10 ARM builds of Full, Stock, Super, Aroma & TVStock variants missing

### ISSUE THREAD

**Issue by Magendanz** [opengapps/opengapps#866]
Many of the Android 10 ARM variants have been missing since July 14 (last build).  Includes the following:

- Full
- Stock
- Aroma
- TVStock

Is this an error or this packages are gone for good?  I can find no information in the blog or wiki explaining their absence.

**Comment by deltabravozulu** [comment]
I was looking for aroma as the updates were being [uploaded](https://sourceforge.net/p/opengapps/activity/) this afternoon. I waited on the . I saw Pico...then Nano...then Micro...then Mini...then...arm64. Indeed, [14 July 2020](https://sourceforge.net/projects/opengapps/files/arm/20200714/) was the last day of updates thus far. Before then it was completely regular for update builds to contain all of them.

**Comment by TheGame455** [comment]
It also seems that builds for ARM64 past that date have the voice model broken, it never finishes downloading and the initial Google Assistant setup will fail.

**Comment by nezorflame** [comment]
Will be fixed soon, that's a problem with a build script.

**Comment by nezorflame** [comment]
@TheGame455 this has already been fixed in the August 14 build and later.

**Comment by Magendanz** [comment]
Looks like the August 15th build never got past Android 9.0 on ARM.  Even pico, nano, micro and mini weren't built.

**Comment by nezorflame** [comment]
@Magendanz yeah. @mfonville some other issue with the buildserver?

**Comment by mfonville** [comment]
It seems the server got a reboot during the build/upload process :-/

**Comment by Magendanz** [comment]
So, are ARM 10.0 builds going to be without Chrome for the foreseeable future?  Can we still install that manually?

**Comment by nezorflame** [comment]
@Magendanz no, I've just published a PR to fix that, so the next official build should contain all the variants once again.
These Chrome builds will use the old implementation though, since I've yet to find a working one with TrichromeLibrary for ARM. But I'll keep looking.

**Comment by ipdev99** [comment]
> @Magendanz no, I've just published a PR to fix that, so the next official build should contain all the variants once again.
> These Chrome builds will use the old implementation though, since I've yet to find a working one with TrichromeLibrary for ARM. But I'll keep looking.

Not sure if it will help.
I do not use chrome browser.
I use Brave and/or Chrome Dev browser(s).

On my daily use Nexus 7 (2013) WiFi running an Android 10 rom.
Unofficial aex rom, I do not update the rom (or magisk) that often but, I keep PlayStore updates current.
My testing account is signed up for Google Beta(s) so, Play services and WebView are from the beta channel for me.
_Along with Phone, Messages, gBoard, Google and maybe some I forgot about._

Brave Browser is 1.12.113
Chrome Dev is 86.0.4230.2
WebView and Trichrome are both 84.0.4147.125

I checked on another Nexus 7 (2013) LTE (unofficial aex build) that I have not updated I updated in awhile.
_Also logged into my testing account._
Brave Browser is 1.11.105
No Chrome or Chrome Dev browser installed.
WebView and Trichrome are both 84.0.4147.111

Disclosure:
Neither of these devices used OpenGapps as an initial install.
Both were initially setup using a bare-minimum Gapps package.
Then signed into to Google and PlayStore took over to update (upgrade/downgrade) and install.

**Comment by TheGame455** [comment]
> @TheGame455 this has already been fixed in the August 14 build and later.

Thank you for replying, I will now update my GApps knowing that this has been fixed

**Comment by nezorflame** [comment]
@ipdev well, depends on what you're talking about.
My PR was only to enable building the variants with Chrome, but the actual APK used there is for SDK24+. Same goes for the Webview - both of them are still using the old scheme (without the TrichromeLibrary). We may have to stay this way for quite some time.
Updating Chrome/Webview from the Store will also download the TrichromeLibrary required to run those, and for the non-updated experience you should be fine with the older versions anyway.

I'm not sure for Brave, but both Chrome Dev and the beta Webview must use TrichromeLibrary under the hood, so it gets downloaded as well from the Play Store.
