### ISSUE TITLE
Bootloop on Pixel 3a Android 10 with opengapps (pico) embedded during AOSP build

### ISSUE THREAD

**Issue by ConradGyllenhaal** [opengapps/opengapps#878]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [ ] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aissue)

*If Open GApps installation fails:*
- [ ] Is the issue reproducible using the latest version of your recovery?
- [ ] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

*If receiving force closures after Open GApps installation:*
- [ ] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [ ] The issue is reproducible on clean (=wiped ``/data/`` partition) installation
- [ ] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [ ] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**

Using your aosp_build repo/project, everything is fine during AOSP compilation, but I got bootloop.
I don't get bootloop when I don't add opengapps.

**Reproduction Steps:**

1. Build AOSP and use aosp_build project/repo
2. Flash AOSP image
3. Boot...
4. ...loop (stay infinitely on animated Android logo)

**Expected behavior:**

The device should boot normally.

**Observed behavior:**

Switching from release to debug build, I was able to get a no-auth root adb access during the bootloop. I can see that zygote and every services are killed every few seconds, and the boot sequence start again.

It seems to be linked to priv-app permissions whitelisting since I see:

`08-11 12:37:54.748  1337  1337 E System  : ******************************************
08-11 12:37:54.748  1337  1337 E System  : ************ Failure starting system services
08-11 12:37:54.748  1337  1337 E System  : java.lang.IllegalStateException: Signature|privileged permissions not in privapp-permissions whitelist: {com.google.android.euicc: android.permission.WRITE_EMBEDDED_SUBSCRIPTIONS, com.android.sdm.plugins.dcmo: android.permission.MODIFY_PHONE_STATE, com.google.android.euicc: android.permission.WRITE_SECURE_SETTINGS, com.verizon.llkagent: android.permission.GET_ACCOUNTS_PRIVILEGED, com.google.intelligence.sense: android.permission.SUBSTITUTE_NOTIFICATION_APP_NAME, com.google.android.euicc: android.permission.MODIFY_PHONE_STATE, com.google.android.euicc: android.permission.START_ACTIVITIES_FROM_BACKGROUND, com.google.android.euicc: android.permission.READ_PRIVILEGED_PHONE_STATE, com.android.sdm.plugins.dcmo: android.permission.READ_PRIVILEGED_PHONE_STATE, com.google.euiccpixel: android.permission.READ_PRIVILEGED_PHONE_STATE, com.android.hotwordenrollment.xgoogle: android.permission.MANAGE_VOICE_KEYPHRASES, com.android.sdm.plugins.diagmon: android.permission.READ_PRIVILEGED_PHONE_STATE, com.verizon.llkagent: android.permission.MANAGE_USERS, com.android.hotwordenrollment.okgoogle: android.permission.MANAGE_VOICE_KEYPHRASES, com.google.intelligence.sense: android.permission.LOCATION_HARDWARE, com.google.android.euicc: android.permission.CHANGE_COMPONENT_ENABLED_STATE, com.google.intelligence.sense: android.permission.CAPTURE_AUDIO_HOTWORD, com.google.intelligence.sense: android.permission.WRITE_SECURE_SETTINGS, com.google.euiccpixel: android.permission.MODIFY_PHONE_STATE, com.google.euiccpixel: android.permission.REBOOT, com.google.android.euicc: com.android.permission.INSTALL_EXISTING_PACKAGES, com.google.android.euicc: android.permission.REBOOT, com.google.intelligence.sense: android.permission.MANAGE_SOUND_TRIGGER}
08-11 12:37:54.748  1337  1337 E System  : 	at com.android.server.pm.permission.PermissionManagerService.systemReady(PermissionManagerService.java:2970)
08-11 12:37:54.748  1337  1337 E System  : 	at com.android.server.pm.permission.PermissionManagerService.access$100(PermissionManagerService.java:122)
08-11 12:37:54.748  1337  1337 E System  : 	at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.systemReady(PermissionManagerService.java:3031)
08-11 12:37:54.748  1337  1337 E System  : 	at com.android.server.pm.PackageManagerService.systemReady(PackageManagerService.java:21785)
08-11 12:37:54.748  1337  1337 E System  : 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:1993)
08-11 12:37:54.748  1337  1337 E System  : 	at com.android.server.SystemServer.run(SystemServer.java:513)
08-11 12:37:54.748  1337  1337 E System  : 	at com.android.server.SystemServer.main(SystemServer.java:350)
08-11 12:37:54.748  1337  1337 E System  : 	at java.lang.reflect.Method.invoke(Native Method)
08-11 12:37:54.748  1337  1337 E System  : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
08-11 12:37:54.748  1337  1337 E System  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:908)
08-11 12:37:54.748  1337  1337 D SystemServerTiming: MakePackageManagerServiceReady took to complete: 574ms
08-11 12:37:54.748  1337  1337 E Zygote  : System zygote died with exception`

Since my build also include Magisk (https://github.com/CaseyBakey/chaosp), I'm able to change (with the Magisk resetprop command) the _ro.control_privapp_permissions_ property to _permissive_. When doing this, the device instantly boot OK, the UI is started etc.

But, strangely, the quoted permissions are properly declared in the '/system/etc/permissions/privapp-permissions-google.xml' file on the device.

Typically:

```
sargo:/ # cat /system/etc/permissions/privapp-permissions-google.xml |grep -i -A10 euicc                                                                                                                                                 
    <privapp-permissions package="com.google.android.euicc">
        <permission name="android.permission.CHANGE_COMPONENT_ENABLED_STATE" />
        <permission name="android.permission.MODIFY_PHONE_STATE" />
        <permission name="android.permission.READ_PRIVILEGED_PHONE_STATE" />
        <permission name="android.permission.REBOOT" />
        <permission name="android.permission.START_ACTIVITIES_FROM_BACKGROUND" />
        <permission name="android.permission.WRITE_SECURE_SETTINGS" />
        <permission name="android.permission.WRITE_EMBEDDED_SUBSCRIPTIONS" />
        <permission name="com.android.permission.INSTALL_EXISTING_PACKAGES" />
        <permission name="com.android.permission.WRITE_EMBEDDED_SUBSCRIPTIONS" />
        <permission name="com.google.android.permission.USE_GRIL" />
--
    <privapp-permissions package="com.google.euiccpixel">
        <permission name="android.permission.MODIFY_PHONE_STATE" />
        <permission name="android.permission.READ_PRIVILEGED_PHONE_STATE" />
        <permission name="android.permission.REBOOT" />
    </privapp-permissions>
--
```

So we can see that, clearly, the package com.google.android.euicc has the android.permission.WRITE_SECURE_SETTINGS permission.

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

[A logcat of the moment I receive the bootloop](https://paste.ofcode.org/7JH3jiKkjpx4KCBcDSDGpX)

**Comment by osm0sis** [comment]
Please open this issue on the aosp_build repo instead.
