### ISSUE TITLE
Device Specific SetupWizard

### ISSUE THREAD

**Issue by bgiesing** [opengapps/opengapps#88]
Currently, Tablets and Phones have two different Setup Wizards. Should we support both like TK? I think this might fix a bug that some (me included) have had, where the SetupWizard would crash Play services when skipping Tap N' Go as I haven't had an issue with the stock Nexus 7 2013's wizard which is what TK is offering.

## To integrate:
- [ ] Change Folder structure to accommodate both.
- [ ] Add `./add_sourceapp.sh` support to recognize these separate APKs.
- [ ] Upload both variants
- [ ] Add to update-binary to install them

@mfonville @rapperskull @raulx222 @NicholasBuse @JustArchi

**Comment by rapperskull** [comment]
If no one can work on it before, I can assign myself to this issue, but I will not be able to work on it until September.

**Comment by bgiesing** [comment]
@rapperskull Well, I know @mfonville can't work on it till at least August 28th. I don't know about anybody else though.

**Comment by mfonville** [comment]
Please use the original bugreport for this issue (the mysteries of setupwizard). Because detection of both variants is not trivial.

**Comment by bgiesing** [comment]
@mfonville There isn't any other bug report with setup wizard in it...

**Comment by bgiesing** [comment]
Duplicate of #7
