### ISSUE TITLE
Ok Google speech recognition not working

### ISSUE THREAD

**Issue by rahbar11** [opengapps/opengapps#883]
**Issue description:**
Voice match for Ok Google is not working and a notification is shown up randomly saying ok Google model update + Download failed. Because of this assistant doesn't appear when we say ok Google or hey Google.

**Reproduction Steps:**

1. Complete the setup wizard and at the end when it comes to assistant, It says "Problem while connecting" 'Check your connection and try again' even in setup wizard
2. The notification appears randomly. Most of the time while using Google apps
3. Go to Google app , then tap more, then settings, then voice, then voice match and finally try to enable ok Google. It will give you the same error with notification.

**Expected behavior:**

It should ask for voice match or say that your voice is recognised already in the setup wizard instead of giving error and voice match should work properly.

**Observed behavior:**

As described above in the issue description...

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

[Debug log of the Open GApps installation](url)

[A logcat of the moment I receive the force closure (if applicable)](url)

**Comment by osm0sis** [comment]
Any luck on latest build? Is it only your device or are others seeing this too?

**Comment by rahbar11** [comment]
I'm using 17 September build and it's not fixed. I will try latest version and let you know + I don't really know about other devices... But I think it's happening with every arm devices...

**Comment by esgwpl** [comment]
I'm also seeing this on my phone.
Zenfone Max Pro M1 ARM64 LineageOS 16 (Android 9) using micro version that I downgraded to nano.

**Comment by methuselahin** [comment]
LineageOs  16.1 kiwi same issue

**Comment by mantan18** [comment]
I also found the Google lens can't be opened

**Comment by rahbar11** [comment]
> I also found the Google lens can't be opened

It's working for me

**Comment by mantan18** [comment]
> > I also found the Google lens can't be opened
> 
> It's working for me



> > I also found the Google lens can't be opened
> 
> It's working for me

I use the micro gapps Google lens it can't appear Google's statement keeps stopping

**Comment by hypernova7** [comment]
I have the same issue on LineageOS 17.1

**Comment by ShreyanshShrivastava** [comment]
Using opengapps mini package for arm64 having same problem

**Comment by hypernova7** [comment]
> 
> 
> Using opengapps mini package for arm64 having same problem

My phone only support ARM

**Comment by ShreyanshShrivastava** [comment]
[UPDATE]
This issue solves automatically after you get an update for google app.
I got an update today and it started working.  :)

**Comment by aljazzair** [comment]
Same issue on LineageOS 16 / Samsung Tab S2 /Gapps 12/23/2020

**Comment by CaptainTimothy** [comment]
Same here.

Xiaomi 8 Pro (equuleus) with LineageOS 17.1 and gapps stock,
"OK Google" not working anywhere but "Google Lens" works fine.

Installed latest version (stock-20201223) with no luck,
Tried earlier version (stock-20200705) then update from play store, still not working.

**Comment by osm0sis** [comment]
I don't think there's anything to be done here.
