### ISSUE TITLE
Live Captions is crashing on Pixel 3 XL Android 10

### ISSUE THREAD

**Issue by ConradGyllenhaal** [opengapps/opengapps#887]
Hello there,

I'm using crosshatch device (Pixel 3 XL) with API-29 (Android 10), with the nano package.
I'm getting crash when starting Live Captions.

Looking at adb logcat I can see:

> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: FATAL EXCEPTION: main
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: Process: com.google.android.as:captions, PID: 12161
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.google.android.apps.miphone.aiai.AiaiApplication: java.lang.SecurityException: Permission denial: reading from settings requires:android.permission.READ_DEVICE_CONFIG
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6465)
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission denial: reading from settings requires:android.permission.READ_DEVICE_CONFIG
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: 	at android.provider.DeviceConfig.enforceReadPermission(DeviceConfig.java:806)
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: 	at android.provider.DeviceConfig.addOnPropertiesChangedListener(DeviceConfig.java:623)
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: 	at brw.<init>(PG:5)
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: 	at btq.a(Unknown Source:10)
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: 	at bxg.a(PG:4)
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: 	at jdo.a(PG:5)
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: 	at aeq.a(PG:8)
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: 	at aex.onCreate(Unknown Source:9)
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: 	at com.google.android.apps.miphone.aiai.AiaiApplication.onCreate(PG:1)
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
> 10-05 16:24:22.456 12161 12161 E AndroidRuntime: 	... 8 more

I tried to grant this permission to the package by using:

> adb shell pm grant com.google.android.as android.permission.READ_DEVICE_CONFIG

but I got this error:
`Security exception: Permission android.permission.READ_DEVICE_CONFIG requested by com.google.android.as is not a changeable permission type
`

Do you have an idea why I get this error?

**Comment by osm0sis** [comment]
Looks like another priv-app permission issue. @NicholasBuse.

**Comment by osm0sis** [comment]
Still broken @ConradGyllenhaal?

**Comment by NicholasBuse** [comment]
https://gitlab.opengapps.org/opengapps/all/-/commit/03fd4d4d0ed908c2a181d10b4a2975f45eb8a21d

**Comment by ConradGyllenhaal** [comment]
I'm gonna take a look at this next week. I have to prepare a new build setup first.

**Comment by osm0sis** [comment]
Looks resolved
