### ISSUE TITLE
Official Signing Certificates?

### ISSUE THREAD

**Issue by dushankw** [opengapps/opengapps#888]
**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [X] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

**Issue description:**

It is not obvious where one can obtain the official OpenGapps signing certificates/fingerprints in order to validate the various artifacts signed by them.

NOTE: I am raising the issue here as I believe it is within scope of the build tooling and not the pre-built packages (even though said packages are the artefacts that are signed).

**Reproduction Steps:**

```
$ keytool -printcert -jarfile ~/Downloads/open_gapps-arm64-9.0-pico-20201017.zip 
Signer #1:

Signature:

Owner: CN=opengapps.org, OU=Buildbot, O=Open GApps, L=Virtual, ST=UTC, C=EU
Issuer: CN=opengapps.org, OU=Buildbot, O=Open GApps, L=Virtual, ST=UTC, C=EU
Serial number: c8af387b5028b9fc
Valid from: Fri May 05 19:06:56 AEST 2017 until: Tue Sep 20 19:06:56 AEST 2044
Certificate fingerprints:
	 SHA1: A8:22:97:D2:96:DD:9B:1C:02:0A:EF:F7:98:10:1A:02:F0:00:3C:2E
	 SHA256: 07:64:B6:43:15:96:FA:94:5C:68:E5:BD:D8:A8:30:5E:2F:2C:97:78:90:C1:CC:87:DB:E5:4A:90:0E:B2:61:12
Signature algorithm name: SHA1withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 1
```

**Expected behavior:**

Some official list of certificates and their SHA256 fingerprints, served from a https domain and ideally signed by one or more of the developers GPG keys (which can be uploaded to GitHub then recovered via https://github.com/USERNAME.gpg) that can be used as a root of trust to verify signed packages against.

**Observed behavior:**

As above.

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

N/A

**Comment by dushankw** [comment]
I would also observe in terms of your signatures that SHA1 is a broken algorithm and it would be worthwhile transitioning to something stronger such as SHA256/SHA512.

Also, thanks for your efforts in this project!

**Comment by nezorflame** [comment]
That's a task for the @mfonville

**Comment by mfonville** [comment]
Hi, this is unfortunately not something we can resolve. The signing algorithm (and even the key!) are dictated by what is supported by TWRP to support the feature of having a signed-zip for installation.

The only thing we do can control and try to offer to end-users is that we use is this custom certificate. If the zip has this certificate, it indicates that it was build by the OpenGApps.org buildbot. Custom-made builds don't carry this certificate. But it is not impossible to mimic it. So you can't treat it as a guarantee, but you can use it the other way around: if a zip doesn't have this certificate is is definitely not an official OpenGApps.org build.

It is a pity we can't do anything more about this, but it is just the situation as-is when it comes to custom ROM/GApps flashing.

**Comment by dushankw** [comment]
Thanks for the comment and I am sorry for such a delayed reply.

@mfonville I understand your reply, however I would still suggest that it would be good to have this fingerprint listed somewhere prominently (perhaps in the `README.md`).

You can (and should) explain the caveats you mentioned around what the signature does/does not prove, but irrespective, so long as the builds are being signed and thus carry *some* level of guarantee, it is important to be able to easily verify the signature, and in my case, I found locating the official key/fingerprint quite difficult.

A one-liner command for end users to perform the validation would also be great :+1:

**Comment by dushankw** [comment]
If you welcome such a change, I would be happy to make a PR, though it really needs to be a maintainer, as opposed to an outsider who defines the fingerprint.

**Comment by mfonville** [comment]
A PR would certainly be welcome. Also it could be documented in the wiki.
