### ISSUE TITLE
Only tvstock/tvmini builds available for Android 8.0(missing pico+others)

### ISSUE THREAD

**Issue by ubergeek42** [opengapps/opengapps#889]
I'm only seeing tvstock/tvmini builds for 8.0(I need pico on x86, but they seem to be missing for arm as well). The last build of x86/pico I could find was from June 30.

I saw #862 , but it was closed as resolved.

**Comment by nezorflame** [comment]
Thanks for the report! It was due to a bug in the build script, should be fixed when the PR mentioned above is merged.

**Comment by nezorflame** [comment]
Since this has been fixed, I'm closing this.
