### ISSUE TITLE
Issue when following build instructions (download_sources.sh does not pull from git lfs)

### ISSUE THREAD

**Issue by alyssadev** [opengapps/opengapps#890]
**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [x] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aissue)

**Issue description:**

The issue is that compilation doesn't "fail"; it appears to succeed, but the resulting .zip is only 19MB. It appears that download_sources.sh doesn't actually download artifacts from Git LFS on gitlab; this step has to be run manually after clone, or added to download-sources.sh as below:

```diff
diff --git a/download_sources.sh b/download_sources.sh
index 4855321b..346affa5 100755
--- a/download_sources.sh
+++ b/download_sources.sh
@@ -66,5 +66,5 @@ for module in $modules; do
     exit 1
   fi
 done
-git submodule foreach -q 'branch="$(git config -f "$toplevel/.gitmodules" "submodule.$name.branch")"; git checkout -q "$branch"; git pull -q $depth --rebase'
+git submodule foreach -q 'branch="$(git config -f "$toplevel/.gitmodules" "submodule.$name.branch")"; git checkout -q "$branch"; git pull -q $depth --rebase; git lfs pull'
 popd > /dev/null
```

**Reproduction Steps:**

1. No existing clone of the repo (I used a DO droplet with ample CPU and RAM and the beevelop/android docker package for testing)
2. Added ssh key from container to my github account
3. `apt install build-essential lzip git zip git-lfs bc`
4. `git clone git@github.com:opengapps/opengapps.git; cd opengapps`
5. `./download_sources --shallow arm64`
6. `make arm64-29-micro`

**Expected behavior:**

A .zip containing a full micro android 10.0 opengapps package (>200MB) produced in out/

**Observed behavior:**

Many errors regarding invalid zip file contents are printed, the process appears to complete but the resulting zip is only 19MB

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

No log file is produced, but I piped the output of make to gzip and attached it to this issue.
[make-arm64-29-micro.log.gz](https://github.com/opengapps/opengapps/files/5542561/make-arm64-29-micro.log.gz)

I've also attached the output zip. 
[badopengapps.zip](https://github.com/opengapps/opengapps/files/5542563/badopengapps.zip)

**To fix:**

1. After step 4 (cloning the repository): `curl https://github.com/opengapps/opengapps/commit/f45c00cd0433583257c26947a8e6809e1b2a8ba0.diff | git apply`

https://github.com/opengapps/opengapps/compare/master...alyssadev:patch-1

After performing that step and running `make arm64-29-micro`, I got a zip of size 256M which I'm about to try writing to my tablet.

**Comment by alyssadev** [comment]
https://github.com/alyssadev/opengapps-build made a cloud init script and tool to deploy to digitalocean and download a custom build

**Comment by WrekLess** [comment]
Hi @alyssadev ,

I used this to do a full repo sync that pulls from git lfs:

`repo forall -r '.*opengapps.*' -c 'git lfs fetch && git lfs checkout'
`
Regards.

**Comment by osm0sis** [comment]
So submit a Pull Request please.
