### ISSUE TITLE
Can't sign in with google accounts in AOSP 7.1.2 with opengapps (tvstock,tvmini)

### ISSUE THREAD

**Issue by hanspark74** [opengapps/opengapps#892]
I am working on AOSP 7.1.2 for Android TV, and build the opengapps as "tvstock" or "tvmini".
After build completed, GApps seem work properly. But I couldn't sign in with my google accounts for "Play Store" and "Add account".
An error saying that your username and password don't match, even if I have entered the correct information. My google account security options are okay to sign in.

11-25 05:56:51.458  5756  5756 I CreateOrAddAccountActivity: onPageComplete: EXISTING_PASSWORD
11-25 05:56:51.458  5756  5756 D CreateOrAddAccountActivity: Displaying: VERIFY_USERNAME_PASSWORD with error: null
11-25 05:56:51.459  5756  5756 D CreateOrAddAccountActivity: user does not exist: xxx@gmail.com
11-25 05:56:51.461  3573  3573 I PhenotypeExperimentConf: refreshConfiguration() : Force = false : UpdateAvailable = false : Age = 40 minutes : MaxAge = 720 minutes
11-25 05:56:51.461  3573  3573 I AndroidIME: PasswordIme.onDeactivate()
11-25 05:56:51.479  3573  3573 W InputMethodService: Window size has been changed. This may cause jankiness of resizing window: -1 -> -2
11-25 05:56:51.706  5756  6562 D AuthTaskThreadFactory: ensure background task delay
11-25 05:56:52.465  5756  5756 D AccountSignInFragment: Log-in failed, detailed reason: null
11-25 05:56:52.465  5756  5756 I CreateOrAddAccountActivity: onPageComplete: VERIFY_USERNAME_PASSWORD
11-25 05:56:52.465  5756  5756 D CreateOrAddAccountActivity: Displaying: VERIFY_USERNAME_PASSWORD_FAILURE with error: null

Thanks.

**Comment by osm0sis** [comment]
Can you test again on latest builds and report back?

**Comment by JuanCarlosM1** [comment]
I had the same problrm with the Android 9.0 version. I fix it replacing with Bitgapps packages after flash the OpenGapps.
