### ISSUE TITLE
GApps crashing

### ISSUE THREAD

**Issue by MattoDeg** [opengapps/opengapps#895]
GAPPs not working after Lineage OS update.
I had GAPPs since April 2020 and Lineage 17.x since the first release and everything worked perfect until two weeks ago, when I updated my device. Since then, none of the GApps I have (installed via play store or directly from GAPPs packge) doesn't work. I open them, they load succefully for some seconds and then quit without any error provided. I'm currently using Gmail, Google, Google Opinion Rewards. Maps is not currently giving any error.

**Comment by osm0sis** [comment]
Super vague. You blatantly ignored the issue template and haven't uploaded any useful information about your device or any logs.

**Comment by MattoDeg** [comment]
Actually I posted a _step to reproduce the error_, if you look carefully. Thanks anyway for answering. I resolved by formatting and installing again. About phone and log, yeah you are right.

Thanks again and keep up the good work.
