### ISSUE TITLE
Android 11 Support?

### ISSUE THREAD

**Issue by dragonBall561** [opengapps/opengapps#896]
I am wondering if (or when) Gapps will get Android 11 support. If possible, can I make my own android 11 gapps?

**Comment by ShreyanshShrivastava** [comment]
Yeah you can make your own opengapps but you should name it differently so as to avoid confusion but that is all up to you 😉😉

**Comment by osm0sis** [comment]
You can follow along in the xda thread and here while it's being developed: https://github.com/opengapps/opengapps/pull/885
