### ISSUE TITLE
Builds older than 2020 missing from sourceforge

### ISSUE THREAD

**Issue by Aura-Mancer** [opengapps/opengapps#897]
Hi there, I wanted to download an OpenGapps package built before 2020, but they are missing from sourceforge. For example, [https://sourceforge.net/projects/opengapps/files/arm/20190928/](url) doesen't work.

Is there a reason for this?

**Comment by osm0sis** [comment]
I mean, they don't have unlimited resources and they had to switch hosts last year to SourceForge, so yeah, I'd say there's a reason. There was a blog post about it all, feel free to check it out.
