### ISSUE TITLE
 google play services still not working

### ISSUE THREAD

**Issue by julolosvalles26** [opengapps/opengapps#904]
I have been using gaaps for years but it has been months since I have switched to nickgapps because they give many bugs

My mobile is a one plus 3 I use lineageos 17.1 and gapps aroma 64 bits and I can't get past the setup wizard since google services constantly fail and it doesn't let go of there or skipping the process or skipping the wifi I try to upload a photo

![IMG_20210112_151907](https://user-images.githubusercontent.com/51278544/104596437-43493b80-5674-11eb-9af6-a0e72e9430b5.jpg)

I have bypassed the wifi and took out the sim to see if I can bypass the configuration but it gets stuck in for a second

![IMG_20210112_153139](https://user-images.githubusercontent.com/51278544/104596764-b5ba1b80-5674-11eb-89bc-9bf7e6481513.jpg)

**Comment by osm0sis** [comment]
We'll carry on tracking this in your original issue (#876) where you've now uploaded logs. :+1:
