### ISSUE TITLE
No logs option

### ISSUE THREAD

**Issue by soredake** [opengapps/opengapps#906]
Would be nice to have option to disable logs entirely, e.g. not create `open_gapps_log.txt`.

**Comment by osm0sis** [comment]
NoDebug already exists, is that not enough?

**Comment by soredake** [comment]
open_gapps_log.txt is created even with nodebug option

**Comment by osm0sis** [comment]
I don't think this will be accepted either way since it's hard enough getting users to upload logs as it is. 😉

**Comment by soredake** [comment]
> I don't think this will be accepted either way since it's hard enough getting users to upload logs as it is. wink

I don't how it's connected, for users who don't want to share logs this option does not change anything, they will not do logs anyway, but for users like me who just don't need logs this option will be useful.

**Comment by osm0sis** [comment]
It's pretty integral to the install process, for example if you didn't have enough space for the GApps chosen, so again, this won't be implemented.
