### ISSUE TITLE
How to achieve Replaces stock/AOSP 

### ISSUE THREAD

**Issue by luffr** [opengapps/opengapps#91]
Hello, I want a special Gapps.
In this package include:
Google system base
Gmail (replaces stock/AOSP Email)
Google Calendar (replaces stock/AOSP Calendar)
Google Camera (replaces stock/AOSP Camera)
Photos (replaces stock/AOSP Gallery)

I have try many time to delete some APP that I do not need based on Stock Package.
Could you help me?
My email is wshop@163.com.
Thank you.

**Comment by mfonville** [comment]
You can take a look at scripts/inc.buildtarget.sh and adjust it to your news. But please post support requests like this in the XDA forum, and not as bugreports.
