### ISSUE TITLE
How do I Install OpenGapps on a Work Profile (Shelter)?

### ISSUE THREAD

**Issue by powline99** [opengapps/opengapps#916]
Searching for a solution to install OpenGapps on the work profile (I Installed Shelter/Island).

Any ideas?:

I found this but don't know how to fastboot boot a Work Profile.

adb push android.apk /data/local/tmp

adb shell pm install --user 10 /data/local/tmp/android.apk

My settings:

Users:

UserInfo{0:Owner:c13} running

UserInfo{10:Work profile:1030} running

Would Installing Magisk work and the opengapps module for it. If so How do I flash Magisk for a work profile

**Comment by nafarinha** [comment]
I'd also like to be able to do this

**Comment by osm0sis** [comment]
Open GApps are just system apps, they don't belong to a particular user.
