### ISSUE TITLE
Add Google Files to android r package

### ISSUE THREAD

**Issue by soredake** [opengapps/opengapps#919]
It's default file manager in a11.

And it's added in nikgapps already https://nikgapps.com/

https://www.androidpolice.com/2020/06/17/files-app-on-android-11-now-includes-storage-from-other-apps/

**Comment by NicholasBuse** [comment]
https://github.com/opengapps/apkcrawler/commit/b5972bb1b780a95d14edc9c5c28bcefc5ed36287 added Files to the APKMirror crawler, also pushing variants (arm, arm64, x86 and x86_64) to APK Repos.

Still need scripting support to get them added to builds...

**Comment by soredake** [comment]
https://github.com/nikgapps/build/commit/18c4c41e95eff57a1c18f082f39abe5d46c74b1b

**Comment by tenzap** [comment]
FilesGoogle is added in this PR that adds support for Go edition apps #948

**Comment by osm0sis** [comment]
Looks resolved!
