### ISSUE TITLE
Avoid installing Google Package Installer for LineageOS

### ISSUE THREAD

**Issue by Flamefire** [opengapps/opengapps#921]
**Issue description:**

Using the Google Package Installer uninstalling an app like WhatsApp fails with an exception: `java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.packageinstaller/com.android.packageinstaller.UninstallerActivity}: java.lang.IllegalArgumentException: Invalid UUID string: CD28-EB81`

IIRC this is due to a "bug" in the framework that returns those short UUIDs for SD cards which are not valid UUIDs (for the functions used)

LOS has fixed that with https://github.com/LineageOS/android_frameworks_base/commit/6d687f055a32430c09ddbde8ef3075bc429b51ad but the OpenGapps doesn't seem to have the fix so it still crashes.

I've seen that the Google Package Installer gets installed after https://github.com/opengapps/opengapps/issues/591 so maybe it would be better to not do that for certain ROMs?  Maybe via some ROM option?

**Reproduction Steps:**

1. Install OpenGapps
2. Click on uninstall for e.g. WhatsApp (most packages work fine)

**Expected behavior:**

Uninstall confirmation dialog opens

**Observed behavior:**

Uninstaller crashes

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

```
05-31 23:05:30.314 20881 20881 E AndroidRuntime: FATAL EXCEPTION: main
05-31 23:05:30.314 20881 20881 E AndroidRuntime: Process: com.google.android.packageinstaller, PID: 20881
05-31 23:05:30.314 20881 20881 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.packageinstaller/com.android.packageinstaller.UninstallerActivity}: java.lang.IllegalArgumentException: Invalid UUID string: CD28-EB81
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Invalid UUID string: CD28-EB81
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at java.util.UUID.fromString(UUID.java:194)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.os.storage.StorageManager.convert(StorageManager.java:2290)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at com.android.packageinstaller.handheld.UninstallAlertDialogFragment.getAppDataSizeForUser(UninstallAlertDialogFragment.java:78)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at com.android.packageinstaller.handheld.UninstallAlertDialogFragment.getAppDataSize(UninstallAlertDialogFragment.java:114)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at com.android.packageinstaller.handheld.UninstallAlertDialogFragment.onCreateDialog(UninstallAlertDialogFragment.java:179)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:417)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.app.Fragment.performGetLayoutInflater(Fragment.java:1351)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1303)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3057)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3004)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:184)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7831)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7813)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
05-31 23:05:30.314 20881 20881 E AndroidRuntime: 	... 11 more
```

**Comment by nezorflame** [comment]
Well, since we provide unmodified framework and app files, this will be fixed only once Google fixes this.
We can add a way to exclude GPI through a config keyword though.

@mfonville @osm0sis any thoughts on this?

**Comment by Flamefire** [comment]
>  We can add a way to exclude GPI through a config keyword though.

That was my idea too. I think the best would be to have the ROM have some property like "I have a fixed GPI" so OpenGApps defaults to not installing it (with the user maybe being able to still install it)

**Comment by mfonville** [comment]
If Google marked it as fixed for an upcoming release in May 2020, I wonder why we don't have the fix yet in Google's app. Are we sure to be on one of the latest versions of  `com.google.android.packageinstaller`? (is the fix not in recent monthly security update images?)

If Google has not released their fixed version, we should indeed refrain from replacing the one from the ROM.
Preferred option would be if we could detect it ourselves if the patch has been applied, but probably not feasible. So instead go with a keyword, and a property would be good. If the LineageOS folks would be willing to supply that, we could add it in the script. Worst case we have to maintain an allow/block list ourselves.

**Comment by Flamefire** [comment]
>  If the LineageOS folks would be willing to supply that

Not sure how to request that and it even applies to e.g. HavocOs and more (I think). So maybe just read a property `ro.google_package_installer.version` and check that and if a ROM maintainer includes that property, then fine.
So basically create that ROM-side customization point and wait for them to pick it up instead of waiting first for them to introduce something

**Comment by nasbdh9** [comment]
Have you tried a new version of Google Package Installer, such as https://www.apkmirror.com/apk/google-inc/package-installer/package-installer-11-7276604-release/
If there is no problem with the new version, may be able to update to this

**Comment by Flamefire** [comment]
@nasbdh9 Sorry for getting back so late. I just tried 10-7029319 (using LOS 17.1, Android 10) and that worked.

**Comment by osm0sis** [comment]
Sounds resolved!
