### ISSUE TITLE
opengapps for 11 stock does not delete built-in gallery after ota

### ISSUE THREAD

**Issue by soredake** [opengapps/opengapps#923]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [x] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aissue)

*If Open GApps installation fails:*
- [] Is the issue reproducible using the latest version of your recovery?
- [] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

*If receiving force closures after Open GApps installation:*
- [x] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [ ] The issue is reproducible on clean (=wiped ``/data/`` partition) installation
- [ ] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [ ] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**

I flashed stock version of arm64 11 gapps, after crdroid (my rom) ota built-in gallery (`com.android.gallery3d`) that is replaced with google photos earlier is installed again.

**Reproduction Steps:**

1. Flash crdroid on your phone.
2. Flash open_gapps-arm64-11.0-stock-20210513-TEST.zip
3. Do ota upgrade.
4. Obverse that built-gallery is back.

**Expected behavior:**
Built-in gallery should not comeback.

**Observed behavior:**
Gallery installed again.

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

[Debug log of the Open GApps installation](url)

[A logcat of the moment I receive the force closure (if applicable)](url)

**Comment by osm0sis** [comment]
Sounds like a bug with the addon.d script generation in the installer.

**Comment by soredake** [comment]
> Sounds like a bug with the addon.d script generation in the installer. Last I checked there were still some inconsistencies post-OTA of various GApps files, this gallery issue is new though. What's the package name of your stock gallery?

com.android.gallery3d

**Comment by soredake** [comment]
Not only gallery is back after ota, but stock (`com.android.launcher3`) crdroid home launcher is back.

**Comment by soredake** [comment]
Maybe this commits will help https://github.com/opengapps/opengapps/commit/227c33a6c7430649f3db3369518921eee5644ba7 https://github.com/opengapps/opengapps/commit/3901263dc610622259e30a517553bc034b4a00ec

**Comment by soredake** [comment]
`com.android.dialer` is back too

**Comment by z3DD3r** [comment]
@soredake,
Can you please check latest test build? Test builds are shared in telegram group. Here is the direct link to latest test builds:
https://drive.google.com/drive/u/0/folders/1CvN4tZH_VWX17dI2Hlevgy-HfQolOTTW

**Comment by soredake** [comment]
Flashed new build, i'll wait for new ota.

**Comment by josephcsible** [comment]
This problem is still happening to me in the 15 February 2022 build. The directory in question is `/system/system_ext/priv-app/Gallery2`. It's on a OnePlus 6T running LineageOS 18.1, if that matters.

**Comment by osm0sis** [comment]
Fixed?

**Comment by osm0sis** [comment]
Fixed?

**Comment by soredake** [comment]
No, i just stopped using opengapps a long time ago.

**Comment by osm0sis** [comment]
Cool, well if it's still an issue then this should stay open.

**Comment by soredake** [comment]
Can someone confirm this is still happening?

**Comment by osm0sis** [comment]
You've confirmed it no longer happens?
