### ISSUE TITLE
Open GApps for Android 11 installation fails claiming "Insufficient storage space"

### ISSUE THREAD

**Issue by adrianer** [opengapps/opengapps#930]
*If Open GApps installation fails:*
- [x] Is the issue reproducible using the latest version of your recovery?
- [ ] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery?::: TWRP 3.5.x is not available for OnePlus 8 Pro (even not an unofficial one, unfortunately)

Phone Information: OnePlus 8 Pro (instantnoodlep)

Android version: lineage-18.1-20210808-nightly-instantnoodlep-signed.zip
Recovery version: lineage-18.1-20210808-recovery-instantnoodlep.img

open_gapps-arm64-11.0-nano-20210813.zip and open_gapps-arm64-11.0-nano-20210807.zip:

    Insufficient storage space available in System partition. You may want to use a smaller Open GApps package or consider removing some apps using gapps-config.
    See:"/sdcard/open_gapps_log.txt for complete details and information.

Though after booting to the system, /sdcard/open_gapps_log.txt could not be found anymore.

Same story as in #925: the pico gapps work, but as the phone has an internal storage of 256GB it is unlikely, that there is not enough space for the nano version, so there must be a bug in the way opengapps calculate free space (on Android 11 and OnePlus devices?).

**Comment by alex-robbins** [comment]
I had this same problem with OnePlus 8T (kebab) and the LineageOS recovery. Unlike here and in #925, neither pico nor nano worked for me.

I have [open_gapps_log.txt](https://github.com/opengapps/opengapps/files/7028696/open_gapps_log.txt). You can see these lines
```
         Total System Size (KB) | Filesystem
         Used System Space (KB) | 1K-blocks
        Current Free Space (KB) | Used
```
made by this code
```sh
# Read and save system partition size details
df=$(df -k /system | tail -n 1)
case $df in
  /dev/block/*) df=$(echo "$df" | awk '{ print substr($0, index($0,$2)) }');;
esac
total_system_size_kb=$(echo "$df" | awk '{ print $1 }')
used_system_size_kb=$(echo "$df" | awk '{ print $2 }')
free_system_size_kb=$(echo "$df" | awk '{ print $3 }')
log "Total System Size (KB)" "$total_system_size_kb"
log "Used System Space (KB)" "$used_system_size_kb"
log "Current Free Space (KB)" "$free_system_size_kb"
```

So it looks like the script is taking the header line of the `df` output instead of the actual results. I read the code though and I don't see why this would be the case. In #789 something similar was happening, and [apparently](https://github.com/opengapps/opengapps/issues/789#issuecomment-570099731) it was due to something regarding SAR. The workaround suggested there doesn't seem relevant to the current version of the script though, as far as I can tell.

I can't do a lot more testing, because I'm not sure how to interact with the environment in which the script runs. (If I get an adb shell in recovery, partitions aren't mounted, I don't have ash or awk on my PATH, etc.)

Anyway, MindTheGapps worked for me, so I'm not very motivated here.

**Comment by jmpxy** [comment]
I've had this issue earlier today trying to sideload it with adb sideload in recovery. All I did was reboot and tried again. It magically worked again.

**Comment by alex-robbins** [comment]
Pretty sure I tried that. Did you sideload both times? What recovery were you using?

**Comment by glasserc** [comment]
I just hit this today. I'm trying to install on a OnePlus 8 non-pro (`instantnoodle`).

My [open_gapps_log.txt](https://github.com/opengapps/opengapps/files/7575567/open_gapps_log.txt) does not contain the delightful lines @alex-robbins posted. The equivalent from my log is:

```
         Total System Size (KB) | 1564464
         Used System Space (KB) | 951536
        Current Free Space (KB) | 596544
```

If I `Mount/unmount system` and then do `df` on the device, these sizes correspond to the size of the partition:

```
OnePlus8:/ # df
Filesystem      1K-blocks   Used Available Use% Mounted on
rootfs            3645788  22148   3623640   1% /
tmpfs             3832312   1228   3831084   1% /dev
tmpfs             3832312      0   3832312   0% /mnt
tmpfs             3832312      0   3832312   0% /apex
tmpfs             3832312      4   3832308   1% /linkerconfig
tmpfs             3832312     72   3832240   1% /tmp
tmpfs             3832312      0   3832312   0% /storage
/dev/block/dm-6   1564464 951536    612928  61% /mnt/system
```

**Comment by osm0sis** [comment]
Still an issue?

**Comment by tayron1** [comment]
> Still an issue?

Yes, for me


```# Begin Open GApps Install Log
------------------------------------------------------------------
            ROM Android version | 11
                   ROM Build ID | lineage_bacon-userdebug 11 RQ3A.211001.001 e40b95eefe
          ROM Version increment | e40b95eefe
                ROM SDK version | 30
        ROM/Recovery modversion | 18.1-20230315-NIGHTLY-bacon
                Device Recovery | TWRP 3.6.2_9-0-a95e1927
                    Device Name | A0001
                   Device Model | A0001
                    Device Type | phone
                     Device CPU | armeabi-v7a,armeabi
          Device A/B-partitions | false
             Installer Platform | arm
                   ROM Platform | arm
           Display Density Used | 480
                   Install Type | Dirty[Data NOT Wiped]
Google Camera already installed | false
              VRMode Compatible | false
       Google Camera Compatible | true
      New Camera API Compatible | false[force_api]
          Google Pixel Features | false
          Current GApps Version | No GApps Installed
          Google Camera version | Legacy
       Installing GApps Zipfile | /sdcard/open_gapps-arm-11.0-pico-20220215.zip
       Installing GApps Version | 20220215
          Installing GApps Type | pico
                    Config Type | 
             Using gapps-config | Not Used
      Remove Stock/AOSP Browser | false[NO_Chrome]
       Remove Stock/AOSP Camera | false[NO_CameraGoogle]
       Remove Stock/AOSP Dialer | false[NO_DialerGoogle]
        Remove Stock/AOSP Email | false[NO_Gmail]
      Remove Stock/AOSP Gallery | false[NO_Photos]
     Remove Stock/AOSP Launcher | false[NO_GoogleNow/PixelLauncher]
      Remove Stock/AOSP MMS App | false[NO_Messenger]
     Remove Stock/AOSP Pico TTS | false[default]
         Ignore Google Contacts | false
           Ignore Google Dialer | true[NoRemove]
         Ignore Google Keyboard | false
Ignore Google Package Installer | false
          Ignore Google NFC Tag | false
          Ignore Google WebView | false
         Total System Size (KB) | 1334432
         Used System Space (KB) | 1094200
        Current Free Space (KB) | 240232
 Additional Space Required (KB) | 27488   << See Calculations Below
------------------------------------------------------------------
# End Open GApps Install Log

INSTALLATION FAILURE: Your device does not have sufficient space available in
the system partition to install this GApps package as currently configured.
You will need to switch to a smaller GApps package or use gapps-config to
reduce the installed size.

NOTE: The Stock/AOSP Dialer is not available on your
ROM (anymore), the Google equivalent will not be removed.
# Begin GApps Size Calculations
------------------------------------------------------------------
  TYPE  |         DESCRIPTION        |      SIZE |   TOTAL
        |         Current Free Space |    240232 |  240232
 Remove |             Existing GApps | +       0 |  240232
 Remove |             Obsolete Files | +       0 |  240232
 Remove |                androidauto | +       0 |  240232
 Remove |              cmsetupwizard | +       0 |  240232
 Remove |           extservicesstock | +       0 |  240232
 Remove |             extsharedstock | +      52 |  240284
 Remove |      packageinstallerstock | +    3108 |  243392
 Remove |                  provision | +       0 |  243392
Install |                       Core | -  206356 |   37036
Install |                    calsync | -    2396 |   34640
Install |            dialerframework | -      12 |   34628
Install |               gearheadstub | -    3168 |   31460
Install |                  googletts | -   46588 |  -15128
Install |     packageinstallergoogle | -    3144 |  -18272
        |               Buffer Space | -    9216 |  -27488
------------------------------------------------------------------
                      Additional Space Required |   27488
------------------------------------------------------------------

# End GApps Size Calculations

# Begin User's gapps-config

# End User's gapps-config
```

This is my Log. I have 50 GB free and nothing works

**Comment by scubbx** [comment]
I'm also stuck at this while trying to reactivate my old Nexus 7. There is not enough space even for the pico variant.

**Comment by AlexLJordan** [comment]
@taynotfound I had the same issue, same device same opengapps version, the whole shebang. I switched to BiTGapps Core https://bitgapps.io/ And it worked fine!
