### ISSUE TITLE
adding an fdroid repo to opengapps

### ISSUE THREAD

**Issue by fdroid-anyone** [opengapps/opengapps#936]
- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

**Issue description:**

I want to implement alternative install channels for opengapps based on F-Droid.  If the maintainers agree with this idea, I'll implement it in these collections of scripts and submit it via merge requests.  The core of the idea is to generate the _fdroid_ index file for the existing files, then users with the F-Droid client app can add opengapps as an _fdroid_ repo.  Then F-Droid can automatically get opengapps updates, and even streamline the whole install process.

Also, I've written lots of POSIX shell scripts, since I've been using UNIX since 1994.  I'm also a fan of clean git histories.

**Comment by osm0sis** [comment]
@mfonville @nezorflame @NicholasBuse

**Comment by mfonville** [comment]
Thanks for your proposal. It certainly sounds interesting!

I have not used f-droid repositories before, could you elaborate how the repository would work? Would the index contain the apk files that are in our repositories, or do they list the installable-zips that we publish on opengapps.org?

**Comment by fdroid-anyone** [comment]
I think this project can be done in two stages:

* First, include a repo index file for the files that are already published, 
that seems to be the installable-zips.  I didn't see any direct download links 
for APKs.

* Second, figure out where the plain APKs should be hosted, then add those to 
the repo index.

**Comment by fdroid-anyone** [comment]
I guess I should add: an fdroid repo is a lot like an RSS feed.  It a standard 
format that clients can subscribe to, then the files/apps in the index will show 
up in the app store UI.

**Comment by mfonville** [comment]
Let's just keep it to the installable-zips. My question about the APKs was just to check how it works.

Probably @nezorflame can publish a RSS feed using the API he already developed to publish our most recent releases to the opengapps.org website. (the source of the tool is here: https://github.com/opengapps/package-api )

**Comment by fdroid-anyone** [comment]
Maarten Fonville:
> Let's just keep it to the installable-zips. My question about the APKs was just to check how it works.

An install procedure will need to be defined installable-zips.  F-Droid already 
has one for OTA ZIPs: it installs it into a private dir on /data that the 
recovery can access to directly flash it.  I imagine these installable-zips 
would be similar.

> Probably @nezorflame can publish a RSS feed using the API he already developed to publish our most recent releases to the opengapps.org website. (the source of the tool is here: https://github.com/opengapps/package-api )

An fdroid repo is only like an RSS feed, it actually uses a totally different 
JSON format, and it is required to be in a signed JAR.  Does opengapps do any 
kind of release signing now?

**Comment by mfonville** [comment]
> An fdroid repo is only like an RSS feed, it actually uses a totally different JSON format, and it is required to be in a signed JAR. Does opengapps do any kind of release signing now?
We do sign releases with the test-key, because that is the only key that TWRP (and probably also other recoveries) allow to verify the installable-zip. (we do have our own certificate for the zip though)

**Comment by fdroid-anyone** [comment]
Maarten Fonville:
>> An fdroid repo is only like an RSS feed, it actually uses a totally different JSON format, and it is required to be in a signed JAR. Does opengapps do any kind of release signing now?
> 
> We do sign releases with the test-key, because that is the only key that TWRP (and probably also other recoveries) allow to verify the installable-zip. (we do have our own certificate for the zip though)

So an fdroid repo is always signed.  Then the client app remembers the signing 
key on first use (TOFU).  Then all other downloads of the index and files in the 
index will be fully verified based on that key.  It seems that the fdroid repo 
signing key would most easily live on the machine that publishes to sourceforge.

**Comment by osm0sis** [comment]
Would the fdroid app handle choosing the right architecture and Android version?

**Comment by nezorflame** [comment]
I like the idea.

AFAIK, the actual repo index needs to be hosted as well (there's some predefined route that's expected from F-Droid and its forks).

As for the APKs - right now they are present in full only on https://gitlab.opengapps.org/opengapps. To make this happen, we need to host both the APKs and the repo index somewhere (preferably within the same domain we use).

**Comment by nezorflame** [comment]
> Would the fdroid app handle choosing the right architecture and Android version?

It should, but we're gonna need to test that.

**Comment by osm0sis** [comment]
Yeah F-Droid serving the packages would be a good replacement for the long-dead official Open GApps app.

**Comment by fdroid-anyone** [comment]
If it is possible to get the URLs to the files on the SourceForge mirrors, and 
they are static, then the fdroid repo index file could be hosted on something 
like https://opengapps.org/fdroid/repo, but the files would be served from the 
SourceForge mirrors.  F-Droid has automatic mirror handling, so if it doesn't 
find the file on the main site, it will automatically try the next mirror until 
it finds the file.  The repo can declare official mirrors in the index, and 
users can add mirrors in the client.

As for the APKs, they could be served directly out of gitlab.opengapps.org "raw" 
URLs, e.g.
https://gitlab.opengapps.org/opengapps/arm64/-/raw/master/app/com.google.android.apps.docs.editors.docs/24/640/213420546.apk

But I don't know if you want that kind of load on your gitlab server.  A plain 
webserver or cloud services like Amazon AWS S3 also are easy possibilities for 
repo hosting.

**Comment by fdroid-anyone** [comment]
Also, fdroid is already built around all the APK metadata, but it also handles 
any file.  It is possible to put a version code in the filename, and then fdroid 
has some concept of version for the file.  If there is some standard metadata in 
the installable ZIPs, then support for parsing that and mapping it to APK-style 
metadata would not be too hard.

**Comment by nezorflame** [comment]
I don't see any practical reason to serve the actual installable ZIPs in the F-Droid. How would the user install them? Or is it purely for discovery reason?

As for the APKs - true, it should be better to serve them from the additional server which holds blobless self-updated clone (by Gitlab hooks) of the repo to minimize the size.

**Comment by fdroid-anyone** [comment]
If the user can mount the /data partition in recovery, then the installable ZIP 
can be read from a private directory where F-Droid can securely manage it.  This 
gives a secure download and install path that is hopefully more automated. 
F-Droid could also use /sdcard or external storage for an easier setup via recovery.

**Comment by mfonville** [comment]
Let's not serve the APKs, because it would indeed overload our gitlab instance and we don't have the budget for AWS.

The links to sourceforge are updated every day with the newest releases. @nezorflame already made an API that serves our homepage, you can see the output at: https://api.opengapps.org/list

Something similar can probably be crafted for the repo index. The filenames of the packages are consistent/predictable so that you can get architecture + android version + variant + date from the filename.

**Comment by osm0sis** [comment]
Seems abandoned?
