### ISSUE TITLE
Open GApps Android 11 Nano Builds 20210928 and 20210929 Bootloop!

### ISSUE THREAD

**Issue by curiousrom** [opengapps/opengapps#938]
Multiple LineageOS 18.1 users are reporting bootloop on clean install in this post & below it for open_gapps-arm64-11.0-nano-20210928 and 20210929: https://forum.xda-developers.com/t/gapps-daily-open-gapps-for-android-all-android-versions-devices.3098071/post-85703249

One user reported no issues with build 20210925.

**Comment by rominator1983** [comment]
I can confirm that 20210928 loops with the logo whereas 20210925 is working properly.
I only tested nano.

**Comment by farukr1** [comment]
my stock variant unofficial build as of today also bootloops, LineageOS 18.1

**Comment by osm0sis** [comment]
@rominator1983, can you confirm if it's fixed? And if not, provide logs.

**Comment by curiousrom** [comment]
Broken builds were removed from the servers so closing the issue.

**Comment by 0x15f2d** [comment]
I'm still having this issue as of 20220514 with the build open_gapps-arm-11.0-pico-20220215. fortuna3g los18.1 armv7a.

**Comment by curiousrom** [comment]
> I'm still having this issue as of 20220514 with the build open_gapps-arm-11.0-pico-20220215. fortuna3g los18.1 armv7a.

Could you please report it in the XDA thread: https://forum.xda-developers.com/t/gapps-daily-open-gapps-for-android-all-android-versions-devices.3098071/page-367
