### ISSUE TITLE
Support gapps-config in persist folder

### ISSUE THREAD

**Issue by jawz101** [opengapps/opengapps#94]
This would be really handy to avoid accidentally deleting my config file

http://forum.xda-developers.com/showthread.php?p=61901221

**Comment by jawz101** [comment]
Oops.. Wrong link
http://forum.xda-developers.com/showpost.php?p=61901221&postcount=12

**Comment by bgiesing** [comment]
Already supported.

**Comment by mfonville** [comment]
Yup. We already have this, so I'll close this issue.

**Comment by jawz101** [comment]
Thanks.  My derp.  Love your work
