### ISSUE TITLE
Broken compatibility with CrDroid 7.12 (olive)

### ISSUE THREAD

**Issue by poqdavid** [opengapps/opengapps#941]
**Issue description:**

Installs fine without any errors but the phone refuses to boot when installing nano-20211109

**Reproduction Steps:**

1. Wipe System, Data, Cache
2. Flash crDroidAndroid-11.0-20211108-olive-v7.12
3. Flash open_gapps-arm64-11.0-nano-20211109.zip

**Expected behavior:**

Like how `open_gapps-arm64-11.0-nano-20210924.zip` version worked just fine I was expecting that to also work fine

**Observed behavior:**

The device just gets stuck on the loading screen and never gets to the OS even after 40min

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

Unfortunately I don't have any logs since I had to get the device running but here is some information that might help
https://sourceforge.net/projects/crdroid/files/olive/7.x/crDroidAndroid-11.0-20211108-olive-v7.12.zip/download
https://github.com/crdroidandroid/android_device_xiaomi_olive
https://github.com/crdroidandroid/proprietary_vendor_xiaomi_olive
https://github.com/Xiaomi-SDM439-Development/android_kernel_xiaomi_sdm439

The problem happened somewhere between `open_gapps-arm64-11.0-nano-20210924.zip` and `open_gapps-arm64-11.0-nano-20211109.zip`

**Comment by Suffie42** [comment]
I've hit the exact same issue, booting takes for every, eventually it gives up boots recovery with an error messages, something is corrupt with the option to wipe stuff. Doesn't do any good afterwards same thing.

I've ran into this on a Sony Xperia XZ2 compact with an official lineageos [lineage-18.1-20211105-nightly-xz2c-signed.zip](https://mirrorbits.lineageos.org/full/xz2c/20211105/lineage-18.1-20211105-nightly-xz2c-signed.zip) opengaps open_gapps-arm64-11.0-mini-20211109.zip. I first tried to upgrade from Lineage 17.1 that failed, tried again wiped all same thing, changed to Lineageos without opengaps, boots, again with open_gapps-arm64-11.0-nano-20211109.zip same thing. Also tried [open_gapps-arm64-11.0-nano-20211111.zip](https://sourceforge.net/projects/opengapps/files/arm64/20211112/open_gapps-arm64-11.0-nano-20211112.zip/download). Only got it to work by reverting to an old opengaps open_gapps-arm64-11.0-nano-20210712.zip which did it.

So I assume something in more recent opengapps is broken. Right now my phone works so can't provide any more logs, got my phone to work, but still wanted to report the issue.

**Comment by fricy** [comment]
Can confirm. I softbricked my phone trying to install open_gapps-arm64-11.0-mini-20211203.zip with crDroidAndroid v7.12 on a OnePlus 3T. Reverting to open_gapps-arm64-11.0-mini-20211030.zip I had on hand fixed the bootloop for me.

Judging from the dates above something broke between oct 30 and nov 09.

**Comment by poqdavid** [comment]
@Suffie42 and @fricy Just noticed `open_gapps-arm64-11.0-nano-20211217.zip` works fine on my phone might want to test it

**Comment by osm0sis** [comment]
Still broken with the latest package?

**Comment by poqdavid** [comment]
Not sure I haven't flashed gapps for a while now, I would have tested it but right now I only got one device.

**Comment by osm0sis** [comment]
Well, either way the issue template states:

> Only issues related to the code of The Open GApps Project scripts themselves
>
> If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers forum thread: http://forum.xda-developers.com/android/software/Open-GApps-t3098071
