### ISSUE TITLE
setupwizarddefault-x86_64 is accessing a deleted field `isCarrierAp` of apex package `android.net.wifi`

### ISSUE THREAD

**Issue by yujincheng08** [opengapps/opengapps#945]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
- [ ] The issue is not a [duplicate](https://github.com/opengapps/opengapps/issues?q=is%3Aissue)

*If Open GApps installation fails:*
- [ ] Is the issue reproducible using the latest version of your recovery?
- [ ] Is the issue reproducible with (the latest) [TWRP](https://twrp.me) recovery? *(other recoveries are only best-effort)*

*If receiving force closures after Open GApps installation:*
- [x] The issue is **NOT** an error within one of the bundled Google applications itself *(verify by e.g. installing the application from the Play Store instead)*
- [x] The issue is reproducible on clean (=wiped ``/data/`` partition) installation
- [x] The affected ROM includes the necessary patches and functionality as noted for [Android versions](https://github.com/opengapps/opengapps/wiki#notes-for-android-versions) and [Platforms](https://github.com/opengapps/opengapps/wiki#notes-for-platforms)
- [x] No non-AOSP hacks like privacy guards' permission restrictions etcetera are applied

**Issue description:**

`setupwizarddefault-x86_64` is accessing a deleted field `isCarrierAp` of `android.net.wifi.ScanResult` and crashes. Since this package (`com.android.wifi`) is apex so it will be updated by Google automatically and EVERY x86_64 Android 11 device with openGApps installed will crash (bootloop) by this issue after `com.android.wifi` is updated by oepnGApps itself.
FYI, This field is removed in this commit: https://cs.android.com/android/_/android/platform/packages/modules/Wifi/+/c50556db869a1caefab533c64ab640a6ba1ae934

**Reproduction Steps:**

1. Setup [MagiskOnWSA](https://github.com/LSPosed/MagiskOnWSA) which is basically Android 11
2. Launch it
3. Modify the shared preference `SetupWizardLocalPrefs` of `com.google.android.setupwizard` (DeviceProtectedStorageContext) with `lifecycleName=pre-deferred` (`default` and `deferred` should also trigger the crash).

**Expected behavior:**

`setupwizarddefault-x86_64` should not access this field and startups normally.

**Observed behavior:**

`setupwizarddefault-x86_64` is accessing an obsolete field and crashes unexpectedly.

**Upload the installation debug log (=tar.gz file) and logcat of Force Closure:**

```
11-25 17:52:43.284 14145 14145 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.google.android.setupwizard.SetupWizardApplication: java.lang.RuntimeException: java.lang.NoSuchFieldException: No field isCarrierAp in class Landroid/net/wifi/ScanResult; (declaration of 'android.net.wifi.ScanResult' appears in /apex/com.android.wifi/javalib/framework-wifi.jar)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6724)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:237)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: No field isCarrierAp in class Landroid/net/wifi/ScanResult; (declaration of 'android.net.wifi.ScanResult' appears in /apex/com.android.wifi/javalib/framework-wifi.jar)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	at mm.a(PG:318)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	at lr.l(PG:292)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	at lr.a(PG:206)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	at lr.<init>(PG:112)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	at mc.a(PG:141)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	at mc.d(PG:50)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	at mc.b(PG:79)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	at ate.a(PG:36)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	at aqz.a(PG:31)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	at com.google.android.setupwizard.SetupWizardApplication.onCreate(PG:11)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6719)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	... 8 more

11-25 17:52:43.284 14145 14145 E AndroidRuntime: Caused by: java.lang.NoSuchFieldException: No field isCarrierAp in class Landroid/net/wifi/ScanResult; (declaration of 'android.net.wifi.ScanResult' appears in /apex/com.android.wifi/javalib/framework-wifi.jar)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	at java.lang.Class.getDeclaredField(Native Method)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	at mm.a(PG:316)

11-25 17:52:43.284 14145 14145 E AndroidRuntime: 	... 19 more
```

**Comment by fjohn123** [comment]
Same.
