### ISSUE TITLE
Screen saver doesn't kick in automatically

### ISSUE THREAD

**Issue by benjani85** [opengapps/opengapps#946]
Issue description:

The screen saver from the Open Gapps build "open_gapps-arm64-11.0-tvstock-20211217" does not start after the period of inactivity. I have tried changing the screen saver type (including 3rd party apps) and the inactivity period but it never kicks in. I have only got it to work by clicking the "Start Now" button.

Reproduction Steps:

1. Install Lineage 18.1 build from this image: lineage-18.1-20211123-UNOFFICIAL-KonstaKANG-rpi4-atv.img onto Raspberry Pi 4.
2. Flash Open Apps: open_gapps-arm64-11.0-tvstock-20211217.zip
3. Turn off "Stay Awake" in developer options
4. Set screen saver type to "Backdrop" and inactivity period to 5 minutes

Expected behavior:

Screen saver should kick in after 5 minutes of inactivity.

Observed behavior:

Screen saver does not kick in.

Upload the installation debug log (=tar.gz file) and logcat of Force Closure:

Unable to locate the debug log from the file system.

**Comment by osm0sis** [comment]
Still an issue? Not much we can do without a log or a test device, Lineage contributors had been keeping the ATV builds afloat.
