### ISSUE TITLE
Infinite loop in installer when trying to skip Google voice activation setup on LineageOS

### ISSUE THREAD

**Issue by briaguya-ai** [opengapps/opengapps#947]
**Only issues related to the code of The Open GApps Project scripts themselves**

If you have found an issue with a pre-built OpenGApps.org package please use the XDA-Developers [forum thread](http://forum.xda-developers.com/android/software/Open-GApps-t3098071)

**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] **(i think so?)** The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

*If Open GApps compilation fails:*
* it didn't

*If Open GApps installation fails:*
* it didn't

*If receiving force closures after Open GApps installation:*
* i didn't

**Issue description:**
from [this issue on the LineageOS repo](https://gitlab.com/LineageOS/issues/android/-/issues/3438)

> When going through the setup questions at the start, clicking "skip" in either of the "enable voice activation" or "say OK google" screens causes it to jump back to an earlier page.
From this earlier page I can only go forward... as far as the voice activation setup, which then puts me in the same loop again.
The only workaround was to accept voice activation and say "OK google" a bunch of times.

**Reproduction Steps:**

1. Install LineageOS 18.1
2. Install opengapps pico (i used `open_gapps-arm64-11.0-pico-20211217`)
3. Try to skip "OK Google" setup

**Expected behavior:**

3. Try to skip "OK Google" setup
4. Successfully skip "OK Google" setup

**Observed behavior:**

3. Try to skip "OK Google" setup
4. Get thrown back to passcode page
5. Repeat 3 & 4 until you give up and say "OK Google" then go into settings and delete your voice profile data

**Comment by OverlordMarkus** [comment]
I observed this as well.

You can circumvent this by doing back to connectivity and selecting "offline configuration".

**Comment by briaguya-ai** [comment]
> I observed this as well.
> 
> You can circumvent this by doing back to connectivity and selecting "offline configuration".

if you go online after doing offline setup, you'll end up with a "finish setting up your phone" notification which brings you back into the guided setup. If I recall correctly, dismissing the notification is only a temporary fix, as it will reappear after a reboot. The only way to get the notification to stop appearing is to complete the setup, which has the same unskippable OK Google issue

**Comment by osm0sis** [comment]
This still an issue?
