### ISSUE TITLE
Merge Stock and ForNexus package

### ISSUE THREAD

**Issue by bgiesing** [opengapps/opengapps#95]
Since they are 99% similar, can't we make one package and use the config file to apply the differences? 

So if we add the `fornexus` keyword to the config file, it will do what the current package does. 

@rapperskull @mfonville

**Comment by mfonville** [comment]
It is a design choice. I will leave this decision to @rapperskull

**Comment by bgiesing** [comment]
@mfonville Even if they are still two separate packages, we could do like we have to change a package using the config. (ex. Stock to Pico by including the word.)

So we would still have a separately downloadable one that just works, but we could use turn Stock into For Nexus with a keyword.

That way, it's still easy for people who don't use the config; but people who do know how only have to have one file downloaded.

**Comment by bgiesing** [comment]
My reasoning is because I barely have space left, and I have to have both the stock and fornexus packages along with the previous release of each just in case.

**Comment by Tobyskernel** [comment]
I like this idea. It's just what TKruzze did in PA-GAPPS.

**Comment by rapperskull** [comment]
There's no problem, and no keyword needed. AFAIK the fornexus package can be installed on custom ROMs without problems. There will be issues if ROMs already included some GApps: in that case the fornexus package would skip the check and lead to problems. Anyway when I come back from vacation I'll take a further look to the code and see what can be done.

**Comment by mfonville** [comment]
The more I think about this idea, the more I like it.
I think a great way to check if a device is still stock/nexus style, and not having other custom gapps on them, is look for the absense of /system/etc/g.prop

The current conflict checks can be logged as output instead of aborting the installation, indicating whether one is flashing 'stock' style or 'fornexus' style.

But we will have to decide if we allow such 'fornexus' style flashing only with the 'stock' package, or also with the smaller ones?

**Comment by rapperskull** [comment]
I also like the idea. As for as the stock or all question, I think that we should allow this behavior on all packages, since you can now still reduce the fornexus package to smaller ones.

**Comment by mfonville** [comment]
@rapperskull If you could re-test the latest version, with the quotes etc now properly in place, we can merge it.

**Comment by rapperskull** [comment]
I just built and flashed again and there's no visible problem. Now we just have to test on a custom ROM (I'm Stock) and then we can merge the changes.

**Comment by mfonville** [comment]
I will now test on my custom ROM them. If it works, I push it to master before tonights build.

**Comment by mfonville** [comment]
I get an error during flashing :-(

**Comment by mfonville** [comment]
Hmm, I think I got an incomplete merge somehow, and are missing your fixes... let me retry

**Comment by mfonville** [comment]
Ok, seems ok now :-)
I will merge it.

**Comment by mfonville** [comment]
I now updated the website too, to reflect the changes that will take effect tomorrow. Wiki still has to be properly updated though.

**Comment by mfonville** [comment]
@rapperskull I updated the website now. Will you update the links in #3 on your thread and explain to your users what has changed for them?

**Comment by rapperskull** [comment]
All done. I was just thinking that the combined support for custom and Stock ROMs is another plus that only our GApps have.

**Comment by mfonville** [comment]
Yes, it would be another great selling point :-)

Now just convincing the community...
sometimes I google for 'opengapps', if you then see what kind of 'homeopathic' approach people have with GApps on the forums... One would recommend on GApps over the other as if it would solve all their problems, while most are fully interchangeable (especially if it are 'Play Store'-only packages), and objective differences like error-handling, DPI variations support are completely neglected. So I fear Stock ROM support will also be mainly for those who really know what they are looking for :-P
