### ISSUE TITLE
ERROR 10 : Failed to set-up Open GApps' pre-bundled busybox

### ISSUE THREAD

**Issue by anirudh13verma** [opengapps/opengapps#953]
**I was installing lineage os 14.1 on j2xlte**
I had first wiped the system, cache, data, internal storage, then i flashed linage OS without any issue
But when i install Open GApps ARM_x64 for 7.1 pico
i get this error

 
`ERROR 10 : Failed to set-up Open GApps' pre-bundled busybox
Please use TWRP as recovery instead`

I hav tried using the ARM version also but the issue persists
i hav tried different versions of recovery but the error comes again and again
Im using the latest version 3.6 of TWRP

**Comment by anirudh13verma** [comment]
Need help ASAP

**Comment by anirudh13verma** [comment]
I Found the issue with the TWRP version that I installed, it was unofficial.
I Reinstalled an official version and it worked like a charm

**Comment by Crunchy-Llama** [comment]
> I Found the issue with the TWRP version that I installed, it was unofficial. I Reinstalled an official version and it worked like a charm

hey i'm having the same problem can u send me the link to download the recovery too please?
