### ISSUE TITLE
"Hey google"feature is currently unavailable for this language

### ISSUE THREAD

**Issue by Demotion89** [opengapps/opengapps#954]
Hi ,

I installed lineage OS 18.1 and OpenGapps on my s10+, with lineage recovery. I took the Nano package ... everything installs normally but I get this message in the google assistant: "Hey google" feature is currently unavailable for this language .

apart from this I was able to assign the menu button to the google assistant and it works normally...
There's just the hey google option, which is greyed out.

Thanks for your help .

**Comment by Demotion89** [comment]
[My Reddit Post](https://www.reddit.com/r/LineageOS/comments/srjnz5/hey_googlefeature_is_currently_unavailable_for/)

**Comment by CollinChaffin** [comment]
That makes two of us. I'm running lineage 18.1 on a OnePlusOne and also get "Hey Google" is unavailable for this device, yet prior OS' it worked fine.

**Comment by osm0sis** [comment]
Sounds like no GApps have this working from browsing that Reddit thread.
