### ISSUE TITLE
Process completed with exit code 1.

### ISSUE THREAD

**Issue by premiumlion** [opengapps/opengapps#958]
I keep getting this error:

requests.exceptions.SSLError: HTTPSConnectionPool(host='store.rg-adguard.net', port=443): Max retries exceeded with url: /api/GetFiles (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

Process completed with exit code 1.

**Comment by osm0sis** [comment]
adguard and SSL have nothing to do with gapps.
