### ISSUE TITLE
Universal APK not properly added to all sources

### ISSUE THREAD

**Issue by DJAlik** [opengapps/opengapps#96]
So the new maps APK is truly universal but it was only added to arm64 and x86_64 sources.

djalik@djalik-VirtualBox:~/opengapps$ ./add_sourceapp.sh /home/djalik/Downloads/*
Importing Maps
Package com.google.android.apps.maps | VersionName 9.13.0 | VersionCode 913009020 | API level 18
Universal DPI package
Native code for architecture(s): arm64-v8a armeabi-v7a mips x86 x86_64 
SUCCESS: Added /home/djalik/opengapps/sources/arm64/app/com.google.android.apps.maps/18/nodpi/913009020.apk
Existing version /home/djalik/opengapps/sources/x86_64/app/com.google.android.apps.maps/18/nodpi/910100020.apk
Replaced with /home/djalik/opengapps/sources/x86_64/app/com.google.android.apps.maps/18/nodpi/913009020.apk
djalik@djalik-VirtualBox:~/opengapps$ ./upload_sources.sh 
Resetting all to HEAD before staging new commits...
Resetting arm to HEAD before staging new commits...
Resetting arm64 to HEAD before staging new commits...
A  app/com.google.android.apps.maps/18/nodpi/913009020.apk
Do you want to commit these changes as Maps arm64 18 9.13.0 (nodpi)? [y/N]
y
Committed app/com.google.android.apps.maps/18/nodpi/913009020.apk
djalik (1):
      Maps arm64 18 9.13.0 (nodpi)
Do you want to push these commits to the arm64 repository? [y/N]
y
Counting objects: 7, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (7/7), 17.34 MiB | 712.00 KiB/s, done.
Total 7 (delta 2), reused 0 (delta 0)
To git@github.com:opengapps/arm64.git
   e497f6f..f4bdcde  HEAD -> master
Resetting x86 to HEAD before staging new commits...
Resetting x86_64 to HEAD before staging new commits...
R  app/com.google.android.apps.maps/18/nodpi/910100020.apk -> app/com.google.android.apps.maps/18/nodpi/913009020.apk
Do you want to commit these changes as Maps x86_64 18 9.13.0 (nodpi)? [y/N]
y
Committed app/com.google.android.apps.maps/18/nodpi/913009020.apk
djalik (1):
      Maps x86_64 18 9.13.0 (nodpi)
Do you want to push these commits to the x86_64 repository? [y/N]
y
Counting objects: 7, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (7/7), 17.34 MiB | 725.00 KiB/s, done.
Total 7 (delta 1), reused 0 (delta 0)
To git@github.com:opengapps/x86_64.git
   fd4c071..aabdb83  HEAD -> master

**Comment by mfonville** [comment]
I know about this. But we have no reliable way of distinguishing these universal apks from the 64bit ones. Therefore this is currently unfixable, and in general I would advise also to only add universal APKs if there is really no 'normal' apk.

**Comment by DJAlik** [comment]
I don't see the non universal APK. Is there a way to manually add this to arm and x86? I looked in the apk and the lib files are included for all architechtures

**Comment by mfonville** [comment]
Just copy-paste of the apk from arm64 to arm. Make sure to delete the old apk from arm.

**Comment by DJAlik** [comment]
I thought you do something different with the libs extraction

On Thu, Aug 20, 2015 at 1:03 AM, mfonville <notifications@github.com> wrote:

> Just copy-paste of the apk from arm64 to arm. Make sure to delete the old
> apk from arm.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opengapps/opengapps/issues/96#issuecomment-132902587>.
>



-- 
<http://www.facebook.com/djalik>  <http://twitter.com/#!/DJAlik>
<http://www.linkedin.com/in/alexrusinov>
<http://plus.google.com/114580313768137070684>
<http://www.mixcloud.com/djalik/>
<http://psnprofiles.com/DJAlik>

**Comment by mfonville** [comment]
The libs extraction is done at build time, not when adding the APKs to the sources.
Since this is a technical issue that cannot be resolved, I will close the bug.
