### ISSUE TITLE
Lineage OS 19.1 support

### ISSUE THREAD

**Issue by alfredonodo** [opengapps/opengapps#964]
Hi,
is there any ETA for Lineage OS 19.1 support? I saw two development threads on xdadevelopers.
Thanks

**Comment by hurzl** [comment]
And if not, which other gapps can I replace opengapps with?

**Comment by hurzl** [comment]
It would have been quite easy to link to 
https://forum.xda-developers.com/t/gapps-daily-open-gapps-for-android-all-android-versions-devices.3098071/post-86595145

**Comment by dav447** [comment]
you can use BitGApps that is all i know

**Comment by osm0sis** [comment]
It is technically supported currently, there just aren't any automated builds out yet. Some unofficial ones can be found or self-built in the meantime.
