### ISSUE TITLE
Google-Contacts do not work with OpenGApps Pico with LineageOS 18

### ISSUE THREAD

**Issue by RichardBeisser** [opengapps/opengapps#965]
I have installed this LineageOS 18 on my sm-T550:
https://forum.xda-developers.com/t/unofficial-rom-beta-lineageos-18-1-for-galaxy-tab-a-sm-t550-july-8-2022.4305889/
with TWRP

After that, I installed open GApps with TWRP:
ARM, Android 11.0, pico

I have done this in this order:
- install Rom, wipe cache Dalvik.
- reboot Recovery
- install Open Gapps , wipe Cache und Dalvik

The Problem:

Any contact app which could normally sync with google-contact, cannot sync with google-contacts.
The Apps do not recognise the Google-Account

Google Contacts App:
When I install the app from Playstore, the App want's to add the account.
When I add the credentials of an account which is already added, the according message is shown.
When I add another Google-Account, the account is added to the system, but Contact apps do not recognise the account.

When you go in Android-Settings --> Accounts --> Google, the contact app is not set for sync.

All other Google-Apps (Drive, play, maps, etc) work with the account correctely

**Comment by osm0sis** [comment]
Still an issue with the last published builds?

**Comment by RichardBeisser** [comment]
> Still an issue with the last published builds?
No, just had a look in google-contact app and all contacts of account are shown.
I dont know what solved the problem.
The only thing I made manually was to update LOS monthly.
