### ISSUE TITLE
Gapps Crash after installation reboot

### ISSUE THREAD

**Issue by Samuelgamingyt7** [opengapps/opengapps#969]
My Gapps crashes each after reboot

**Issue description:**

[After installing Open gapps, I rebooted the device and When it came on, It shows Errors, all the google apps will be crashing. Something like (wizard partion has stopped working)]

**Reproduction Steps:**

1. [I installed Slim OS android 7.1]
2. [Installed Open Gapps 7.1 Pico]
3. [Then I wiped Davik cache and then rebooted the device]

**Expected behavior:**

[I expected that I will be able to use gapps on the device,]

**Comment by osm0sis** [comment]
Not seeing any log, and you deleted the issue template checklist.
