### ISSUE TITLE
"Ok Google" not working

### ISSUE THREAD

**Issue by hoanglongutc** [opengapps/opengapps#971]
Issue description:
I have installed Gapps arm64 11 micro,  but I can't use the hotword "ok google". Can only hold the home key to activate google assistant. I appreciate any help. thank you very much

Reproduction Steps:

I have completed the steps to install voice recognition.
Can hold the home button to activate google assistant
However when I say "ok google" or "hey google" I get no response

Expected behavior:
I want when I say "ok google" to be able to activate google assistant

Observed behavior:
no response from the system
Note: 
I'm using combos as follows:
device: raspberry pi 4 - 8GB
speaker and mic: Jabra Speak 510 (connected via USB)
OS: https://konstakang.com/devices/rpi4/LineageOS18/

**Comment by osm0sis** [comment]
Not a normal system, so not sure how you intend us to debug it.

**Comment by osm0sis** [comment]
Also there are several Ok Google issues already open
