### ISSUE TITLE
How to prebuilt  OpenGapps in AOSP 11 build without registering GSF ID 

### ISSUE THREAD

**Issue by amlan007** [opengapps/opengapps#976]
With Above steps i am able to prebuild all GAPPS, but it is showing "Device is not Play Protect certified." so few of the google apps does not work.

So, after registering the GSF ID at https://www.google.com/android/uncertified/, all started to work. and play protect pop up is no longer seen.

**So, my question is: is there any way to bypass the play protect error without registering the GSF ID.**

**Comment by osm0sis** [comment]
You intentionally deleted and didn't follow the issue template.

Play Integrity/SafetyNet has nothing to do with GApps. Check XDA.
