### ISSUE TITLE
inc.compatibility.sh: Syntax error: redirection unexpected

### ISSUE THREAD

**Issue by Stokolyas** [opengapps/opengapps#977]
I try build opengapps for redroid. I clone repo opengapps with git-lfs, but when I run make, I get error ./scripts/build_gapps.sh: 788: /home/user/opengapps/opengapps/scripts/inc.compatibility.sh: Syntax error: redirection unexpected

**Comment by Stokolyas** [comment]
error in string `    gappscore_go=$(sed -e "s/\bdefaultetc\b/defaultetcgo/" <<< $gappscore_go)
` in file opengapps/scripts/inc.compatibility.sh

**Comment by oklaM** [comment]
I come the same error, how to resolve it ?

**Comment by Haoxiqiang** [comment]
maybe the system shell caused it.
try to change build_gapps.sh first line:
` #!/bin/sh -> #!/bin/bash`
or others which your system shell.
