### ISSUE TITLE
[Website] Allow Google Contributor for Ads

### ISSUE THREAD

**Issue by bgiesing** [opengapps/opengapps#98]
Most people don't like ads and I know a few people will use [Google Contributor](http://www.google.com/contributor/welcome/) in which users pay a small amount and will (basically) bid on the Ad spots.

This means that the visitors get to remove ads and the website gets paid the same or better than before. An actual win-win! I was trying to find how to enable it, but I can't find it. It says though that it's a part of AdSense which we use. If you need an example on a site that uses it, look no farther than APK Mirror itself (and Android Police).

@mfonville @raulx222

**Comment by mfonville** [comment]
It should already work by default on AdSense sites, like ours.
Contributor is only available for visitors from the states though.
I will close it, since we can't do anything with it.
