### ISSUE TITLE
previous Google Play versions

### ISSUE THREAD

**Issue by 1268** [opengapps/opengapps#982]
**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

**Issue description:**

currently Open GApps is offered for different Android versions, but the Google Play app itself seems to always be a somewhat current version. I would be interested in older versions of the Google Play app itself for testing.

**Comment by osm0sis** [comment]
Feel free to make your own Open GApps builds with older Play Store APK from APKmirror or wherever.
