### ISSUE TITLE
com.google.android.gsf source

### ISSUE THREAD

**Issue by 1268** [opengapps/opengapps#983]
**Checklist**

- [x] The issue is not answered by reading the [FAQ](https://github.com/opengapps/opengapps/wiki/FAQ)
- [x] The issue is part of The Open GApps Project scope *(and not of the pre-built OpenGApps.org packages scope, for support on those see [XDA Forum](http://forum.xda-developers.com/android/software/Open-GApps-t3098071))*

**Issue description:**

my understanding is the Google Services Framework app (com.google.android.gsf) is not downloadable, even using the internal Google APIs. so my question is, where are you getting this app from?

**Comment by osm0sis** [comment]
Pixel system images, like all core files. That's how all GApps do it.

**Comment by 1268** [comment]
do you have a link or information about the process? I found this:

https://developers.google.com/android/images

but I think those are all ARM. where did you get x86?

**Comment by 1268** [comment]
> There are definitely x86 AVD images

OK where though? I am interested in `x86` or `x86_64` phone images and/or apps

**Comment by osm0sis** [comment]
x86 uploads are pretty sparse nowadays. https://gitlab.opengapps.org/opengapps

**Comment by 1268** [comment]
so where are you guys getting Google Services Framework app from? sorry but its not clear to me from your comments

**Comment by osm0sis** [comment]
https://gitlab.opengapps.org/opengapps/all/-/tree/master/app/com.google.android.gsf.notouch/14/nodpi?ref_type=heads

Looks like gsf is a common APK to all packages, since it's in the all branch. That means it must be multi-arch, and was likely sourced from Pixel factory image.

**Comment by 1268** [comment]
OK cool that is helpful. do you know the process used to extract from the factory image? I tried it myself but ran into an issue:

https://forum.xda-developers.com/t/extract-google-services-framework.4624097/
