### ISSUE TITLE
Not working on yureka.

### ISSUE THREAD

**Issue by inder4u** [opengapps/opengapps#99]
Not working on yureka. Error while flashing zip.

**Comment by mfonville** [comment]
You need to provide debug logs and the exact error you receive.
Also I would like to point out that the xda thread is the primary point of support requested, if there is established that something is wrong with the opengapps package itself, and not with e.g. the ROM, we open a bugreport.

**Comment by rapperskull** [comment]
@mfonville  Should we mark this issue as invalid and close it?

**Comment by mfonville** [comment]
@rapperskull if he does not respond we will. I give him a few more days.

**Comment by mfonville** [comment]
Since lack of response and further information I close this bug

**Comment by inder4u** [comment]
Sorry for delay, I am getting .
--------------------
Recovery does not support transparent compression.

Your ROM uses transparent compression, but your recovery does not support this feature,resulting in corrupt files.

BEFORE INSTALLING ANYTHING ANYMORE YOU SHOULD UPDATE YOUR RECOVERY AS SOON AS POSSIBLE, TO PREVENT FILE CORRUPTION.

error code: 30
-------------------------
DEVICE:  YUREKA
ROM:  cm-12.1-20151005-NIGHTLY-tomato.zip from https://download.cyanogenmod.org/?device=tomato&type=nightly
Recovery : TWRP 2.8.6.0

Further to this opengapps is working  on same device with SNAPSHOT built..

**Comment by mfonville** [comment]
It clearly states what you should update, you should *update* your recovery (that is: TWRP).

**Comment by inder4u** [comment]
But that is the latest release. 2.8.6.0. But in latest snapshot built ROM (i.e. today's release) no problem with TWRP 2.8.6.0, open gapps working flawless. I am getting this error on the nightly release only.

**Comment by rapperskull** [comment]
A little bit of googling reveled that there's also TWRP 2.8.7.0 (unofficial?). Maybe you can try it.

**Comment by inder4u** [comment]
Ya, but not for tomato build.

**Comment by rapperskull** [comment]
I don't know your device, but I read "tomato" [here] (http://forum.xda-developers.com/yureka/orig-development/recovery-twrp-2-8-4-0-touch-recovery-t3004699). Maybe you can give it a try.

**Comment by mfonville** [comment]
It is behind registration (and I don't have an account), but you might find it here: https://www.reddit.com/r/Android/comments/3fwhdb/twrp_2870_for_yu_yureka_tomato/

**Comment by mfonville** [comment]
Ok, login 'bugmenot' 'bugmenot' did wonders, check this out: https://s.basketbuild.com/devs/vishal_android_freak/yu/yureka/

**Comment by mfonville** [comment]
(and maybe good idea to back it up, for other users or future use?)

**Comment by inder4u** [comment]
Hey, Today i have updated to TWRP 2.8.7.0, and found its working with TWRP 2.8.7.0. in both nightly and snapshot release... :) .. Thanks.

**Comment by mfonville** [comment]
Super!
Maybe you can mirror that TWRP somewhere and write something somewhere to point other users to the solution, because it will become for sure a more frequent problem over time (people often don't update their recoveries) and it not only impacts Open GApps, but everything they do from their recovery.

**Comment by dheerajbhaskar** [comment]
:+1: this works

Remember to click on [images...] button at the bottom right to view `.img` files. I was about to think this is a fail, then saw the images button.

**Comment by inder4u** [comment]
Sry, i am updating a invalid closed issue. Yesterday there was a update posted on the above mentioned nightly release and after updating my phone, when i tried to flash Ogapp pico amr64 (today) it not getting flashed with error 40. Its not recognize the new nightly release of tomoto.

**Comment by mfonville** [comment]
@inder4u could you upload your debug logs?
Normally Error 40 indicates that other GApps were already installed.

**Comment by inder4u** [comment]
Never mind, i guess it invalid again. I just flash new tomato built with today Ogapps-AMR64-pico and it worked with TWRP 3.0.0
